### ISSUE TITLE
how should RelayContainer handle `shouldComponentUpdate`

### ISSUE THREAD

**Issue by filod** [facebook/relay#1002]
say i made a `RelayCotainer(ListView)` which accept a `connection` as prop: 

``` javascript
class MyList extends Component {
 render() {
    let {connection} = this.props
    return <ListView
     {...this.props}
    />
  }
}
export default Relay.createContainer(MyList, ...)
```

then i use it like:

``` javascript
class MyComponent extends Component {
  renderHeader() {
    let {topic} = this.props
    return <View>
      <Text>{this.props.viewer.username}</Text>
      <Button onPress={this.ChangeUserNameMutation}
    </View>
  }
  render() {
    let {connection} = this.props.viewer
    return <MyList
      connection={connection}
      renderHeader={this.renderHeader} />
  }
}
```

sadly, when i click button, username will not change, because `RelayContainer` think that nothing has changed, `shouldComponentUpdate` will return `false` in this case, so `MyList.render` will never be called.

the only solution is to pass the connection's parent (which actually changed) to `MyList` like 

``` javascript
  render() {
    let {connection} = this.props.viewer
    return <MyList
      connection={connection}
      anyPropName={this.props.viewer}
      renderHeader={this.renderHeader} />
  }
```

Any ways to solve this more graceful ? or `RelayContainer` is designed to act like this in the first place ?

**Comment by josephsavona** [comment]
`RelayContainer` implements `shouldComponentUpdate` to avoid re-rendering if none of the data changed. It will rerender if any of its fragment data changes, including when items are added or removed from a connection. 

I suspect that the issue here is related to how the components and their fragments are configured. To help debug we'll need more information: what are the container fragments, and what does the mutation change?

**Comment by filod** [comment]
@josephsavona 
in the example above, `RelayContainer(MyList)` only have one fragment named `connection `, the `ChangeUserNameMutation ` will change `viewer.username` (`viewer.connection` actually won't change)

**Comment by josephsavona** [comment]
@filod Is it possible to provide the full container fragment and mutation fat query?

**Comment by filod** [comment]
in my real case (remove some code):

```javascript
// Activities.js => MyList.js
export default Relay.createContainer(Activities, {
  initialVariables: {
    count: 10,
  },
  fragments: {
    viewer: () => Relay.QL`
      fragment on User {
        id,
        authed,
        ${PostActivityListItem.getFragment('viewer')}
        ${LikePostActivityListItem.getFragment('viewer')}
      }
    `,
    // connection fragment
    activities: () => Relay.QL`
      fragment on ActivityConnection {
        edges {
          node {
            __typename,
            ... on LikeActivity {
              id,
              createdAt,
              user {
                avatar
              },
              answer {
                id,
                owner {
                  nickname
                },
                question {
                  id,
                  title
                }
                ${AnswerContent.getFragment('answer')}
              }
            },
            ...
          }
        },
        pageInfo {
          hasNextPage,
        }
      }
    `
  }
})


// Topic.js => MyConponent

const TopicContainer =  Relay.createContainer(Topic, {
  initialVariables: {
    count: 10,
  },
  fragments: {
    viewer: () => Relay.QL`
      fragment on User {
        id,
        authed,
        ${TopicFollowButton.getFragment('viewer')}
        ${Activities.getFragment('viewer')}
      }
    `,
    topic: () => Relay.QL`
      fragment on Topic {
        id
        name
        image
        description
        subscriberCount
        viewerDoesSubscribe
        activities (first: $count) {
          ${Activities.getFragment('activities')}
        }
        ${TopicFollowButton.getFragment('topic')}
      }
    `
  }
})

// SubscribeTopicMutation
...
  getFatQuery() {
    return this.props.topic.viewerDoesSubscribe
      ? Relay.QL`
        fragment on SubscribeTopicMutationPayload {
          unsubscribeTopicId,
          topic {
            id
            subscriberCount
            viewerDoesSubscribe
          }
          viewer {
            subscribedTopics
          }
        }
      `
      : Relay.QL`
        fragment on SubscribeTopicMutationPayload {
          topicEdge,
          topic {
            id
            subscriberCount
            viewerDoesSubscribe
          }
          viewer {
            subscribedTopics
          }
        }
      `
  }
...

```

**Comment by josephsavona** [comment]
I see. In this example, we would expect that the Topic/MyComponent container would re-render after the mutation because `viewerDoesSubscribe` has changed. If that isn't happening it likely indicates that the mutation isn't configured correctly, and the data for the `topic` field of the mutation isn't being requested and/or applied to the store correctly. What is the mutation query that is sent to the server and the corresponding response? Does it contain the data you'd expect?

**Comment by filod** [comment]
yes, mutation applies well. 
the only problem is `Topic/MyComponent ` uses `Activities `'s `renderHeader` to render `topic.subscriberCount`

**Comment by josephsavona** [comment]
I see - the parent component *is* re-rendering, but the data for the child hasn't changed so it doesn't re-render. This causes the child not to re-invoke `this.props.renderHeader` passed from the parent and therefore not see the new data. One simple workaround here is to pass a new `renderHeader` prop every time so that RelayContainer will return false in shouldComponentUpdate and re-render the child:

```javascript
// Use an arrow function to create a new function prop on every parent render:
   <MyList
      connection={connection}
      renderHeader={() => this.renderHeader} />
```

**Comment by josephsavona** [comment]
@filod did you find a workaround for this?

**Comment by filod** [comment]
the code you provide is working for my case.
but i keep another way to make code understandable for our team: pass a connection `parent` prop to `MyList` (which means connection parent is a new object when receive props from relay store)

```javascript
  render() {
    let {connection} = this.props.viewer
    return <MyList
      connection={connection}
      parent={this.props.viewer}
      renderHeader={this.renderHeader} />
  }
```

**Comment by nodkz** [comment]
@filod my recommendation is to use `viewer` for propname instead of `parent`.
Who knows will your team use `viewer` in `MyList` or its subcomponents in future. If so, you already will have proper name, with proper relay data.

In my team we have rule: All announced relay-fragment-names became reserved words for the prop-names and can not be renamed.

**Comment by filod** [comment]
the reason i use `parent` is that i can force `MyList` to receive a `parent` prop.

**Comment by wincent** [comment]
(Spring cleaning.) Cleaning out some old issues and this one looks quite stale at this point, and additionally has some working recommendations in it, so I'm going to close it out. Thanks everybody for contributing to the discussion!
