### ISSUE TITLE
Navigation example for react-native 'TodoMVC'.

### ISSUE THREAD

**Issue by joonhocho** [facebook/relay#1010]
I am trying to find an example of integration between Relay and react-native's [NavigationExperimental](https://github.com/facebook/react-native/tree/master/Libraries/NavigationExperimental).

Has it been done by someone else? If not, any advices on how to get started?
Thank you.

**Comment by josephsavona** [comment]
Thanks for your question! We use these APIs together at Facebook so this is definitely possible. That said, we want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

Would you like to post this question to Stack Overflow with the tag #relayjs? We'll be happy to answer there. Post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs

**Comment by joonhocho** [comment]
Just asked a question on stackoverflow: https://stackoverflow.com/questions/36423727/how-to-use-react-natives-navigationexperimental-with-relay

**Comment by Lenin7** [comment]
Any updates on the question?

**Comment by josephsavona** [comment]
@Lenin7 Answered on Stack Overflow. tl;dr `NavigationExperimental` is still experimental, so just give it a try!

**Comment by joonhocho** [comment]
Check out [react-native-router-relay-todo](https://github.com/joonhocho/react-native-router-relay-todo).
I created the example that uses [react-router-native](https://github.com/jmurzy/react-router-native) which uses NavigationExperimental.
It works, though there are some issues.
