### ISSUE TITLE
Roadmap update? last update was Feb 2016

### ISSUE THREAD

**Issue by idibidiart** [facebook/relay#1018]
Hi there,

Is this still in the Roadmap[1]?

<<
Support client/local state
API for resolving fields locally: #431.
Support querying & compiling client-only fields by extending the server schema, and a means for writing data for these fields into the cache: #114.
>>

1. https://github.com/facebook/relay/wiki/Roadmap

**Comment by wincent** [comment]
Yes, there is still a roadmap, but it's something we'll only update periodically.

More frequently updated are our meeting notes which you can find at: https://github.com/facebook/relay/wiki/Meeting-notes

We're going to move those off the wiki, though, and into the repo itself via PRs, so that people can get notifications when we publish new notes. I believe @josephsavona has a couple of week's worth of meeting notes that he said he was going to publish, but if he doesn't get to it shortly I'll do it.

**Comment by idibidiart** [comment]
Hi @wincent 

Thanks for the update and looking forward to latest meeting notes.

We're making an attempt at a major adoption of GraphQL/Relay across our products, web and mobile, and I'm trying to find out if the ideas listed below regarding support of local/client state are still part of the plan? Are they still justified in your view? @wincent @josephsavona

API for resolving fields locally: #431.
Support querying & compiling client-only fields by extending the server schema, and a means for writing data for these fields into the cache: #114.

?

**Comment by josephsavona** [comment]
@idibidiart We think that those are valid use-cases that Relay may be able to support, hence our creating issues to allow discussion and exploration of the ideas. However, we aren't actively working on those issues directly and don't have a timetable for when they may be completed. 

The [most recent meeting notes](https://github.com/facebook/relay/wiki/2016-03-14-Relay-Team-Sync-Notes#h1-plans) have more information about the core team's current area of focus. In particular, we're focusing on performance and on providing low-level APIs (described in#559) that may allow features such as client-only fields to be implemented in user-space.

**Comment by josephsavona** [comment]
I'm going to close this since this issue is non-actionable - please feel free to ask follow-up questions here.

**Comment by wincent** [comment]
New notes added via 57fb2b1567f.
