### ISSUE TITLE
Docs for star-wars update

### ISSUE THREAD

**Issue by pennyandsean** [facebook/relay#1027]
https://facebook.github.io/relay/docs/graphql-object-identification.html#content
query for 

```
query RebelsQuery {
  rebels {
    id
    name
  }
}
```

should now be 

```
query RebelsQuery {
  factions(names:["rebels"]) {
    id
    name
  }
}
```

Same for empire further down.

**Comment by sibelius** [comment]
@pennyandsean could u send a PR to improve the docs?

**Comment by wincent** [comment]
Thanks for bringing this up, @pennyandsean.

Note that [the documentation here](https://github.com/facebook/relay/tree/571dad28915ff475ee7728eb136adc42c6f3febd/docs) doesn't necessarily need to keep in sync with [the Star Wars schema defined here](https://github.com/graphql/swapi-graphql/tree/484c65c2c0a858e8e7e6bd69dd37917caf355248/src/schema), because the latter is a separate project and the important thing for the Relay docs is that they remain internally consistent.

They do seem to be internally consistent at this point. See [the schema definition](https://github.com/facebook/relay/blob/571dad28915ff475ee7728eb136adc42c6f3febd/docs/GraphQL-RelaySpecification.md), and note that there are multiple pages that assume it (like [this one](https://github.com/facebook/relay/blob/571dad28915ff475ee7728eb136adc42c6f3febd/docs/GraphQL-Connections.md)).

So, I'm going to close this for now. If you feel strongly that we should update the docs to match the schema in [the swapi-graphql project](https://github.com/graphql/swapi-graphql), please feel free to submit a PR, but note that we'd want to make sure that *all* the references that depend on the shape of the schema get updated throughout the documentation, so it might be a pretty big change for a not necessarily very clear gain. I'll leave that judgment up to you though. In the meantime, thanks for filing the issue!

**Comment by wincent** [comment]
And note, if I am wrong about the docs being internally consistent, that's a documentation bug, so please let us know.
