### ISSUE TITLE
Improve on error message when reserved query keyword is used

### ISSUE THREAD

**Issue by bitbrain** [facebook/relay#1031]
I defined a route to fetch all nodes of a graph model. The `nodes` field has been specified manually in a schema. However the field is already reserved by `GraphQL` to do nodes/edges compositions. I created a sample route as follows:

``` jsx
class GraphRoute extends Relay.Route {
  static routeName = 'Graph';
  static queries = {
    graph: (Component) => Relay.QL`
      query GraphQuery {
          nodes {
            id
          }
      }
    `
  };
}
```

The following error is produced on runtime:

```
invariant.js:38 Uncaught Invariant Violation: RelayRecordStore.getDataID(): Argument to `nodes()` cannot be null or undefined.
```

It is very confusing to a user to read this error because it does not indicate that a reserved keyword has been used. (in this case: nodes).

No error is thrown when I change it to (and changing the respective schema as well):

``` jsx
class GraphRoute extends Relay.Route {
  static routeName = 'Graph';
  static queries = {
    graph: (Component) => Relay.QL`
      query GraphQuery {
          customNodesField {
            id
          }
      }
    `
  };
}
```

**Comment by wincent** [comment]
(Spring cleaning.) This issue is nearly a year old now and is likely stale — it's possible that code changes have occurred which modify the error message — so I am going to close it. But thank you for the report. If you think this is still an issue with current Relay, please consider submitting a PR to improve the error message; we are always happy to see contributions that improve the developer experience of people using the framework.
