### ISSUE TITLE
Inspect the cache in more readable way

### ISSUE THREAD

**Issue by Globegitter** [facebook/relay#1053]
The store/cache seems to me one of the least documented features and it is imo hard to tell how exactly relay caches its data, which is propagated to containers and updated from mutations (i.e. what is the relation between `fieldIDs` in a mutation and how the data is stored in the cache). I love that the cache handled automatically but I think Relay would benefit a lot if it had more debugging features around this part.

Looking in the react dev tools or logging `Relay.Store.getStoreData()` just gives you an object with a lot of keys, where it is not quite clear which actually hold the data. There is e.g. a `_cachedStore`, a `_recordStore` and a `_records` all seeming to have overlapping data which has been requested by queries.

In my opinion the nicest solution would probably be to see the current store in the React Devtools in the `Relay` tab.

I might be able to look into that myself at some point but wanted to raise this already to see what other people think/say to this.

**Comment by josephsavona** [comment]
@Globegitter We agree. One of our ideas here was to have a Relay "debugger" - something that optionally prints information about what Relay is doing in order to make it more obvious what's happening (diffing a query, writing data into the store, constructing a mutation query, etc). The aim would be to both help people debug when issues do occur as well as to help people learn about all the things Relay is doing behind the scenes. 

@yuzhi has been focused on this lately, but I'd encourage you to send a PR with changes that you think would be helpful and we can discuss from there.

**Comment by xuorig** [comment]
Probably quite related to #1045 which @yuzhi was also taking a look at too :)

**Comment by yuzhi** [comment]
@Globegitter I agree that we definitely need something like that. As far as making it easier to debug, we can use a lot of help from the community. I haven't started working on making it easier to inspect the data Relay has cached yet. If you have time and ideas, we would love to see an PR!

**Comment by Globegitter** [comment]
I had a bit of a play with the Relay plugin in the dev tools (https://github.com/facebook/react-devtools/tree/master/plugins/Relay) and I think two different views on the store would be nice.

One view that corresponds directly to the queries you constructed or maybe even the components where it is being displayed (in my mind a call the more the 'intuitive' view, i.e. it would be more easy to read etc.

The second view would just be how it is stored in Relay, so maybe just `getNodeData()` on storeData and possibly the `_rootCallMap` to show, this is how it is actually stored in relay, flat.

In my opinion the first one would be more important to kind of get an understand of how your queries/components relate to the existing data and would probably also make debugging easier. The second one would more be to get some under the hood understanding and maybe also a nice fallback so one can immediately see all the data that is in the cache.

I will do some more testing around and hopefully can hopefully get something nice and basic out.

**Comment by Globegitter** [comment]
Having worked a bit now with https://github.com/facebook/react-devtools the developer experience is currently not that great as there is no simple relay app that can just run in the iframe that they provide. And if you don't use the iframe setup you can not inspect the inspector.

So I thought as a first step I would make another todo app using https://github.com/relay-tools/relay-local-schema to add here as an example which can then be used for easier react devtools development.

**Comment by wincent** [comment]
I'm going to close this due to inactivity. Note that we're still interested in making debuggability better in Relay (and probably always will be; when can an app/framework become "too debuggable"?). Suitable next steps for anybody interested in this: submitting a PR to provide better visibility into the store, and/or watching the master branch, where we have been shipping code for the new Relay core (more of this is coming, and obviously the low-level storage implementation details have changed, so any debugging solution would ideally be built on top of the new APIs and implementation rather than the legacy ones).

Thanks for the discussion!
