### ISSUE TITLE
Idea: __dataID__  might not necessary to appear in a component

### ISSUE THREAD

**Issue by lvarayut** [facebook/relay#1057]
When I fetched data from a database, all the objects and arrays contain `__dataID__` properties. Normally, if I needed to mutate some properties in the objects, I would send `this.props` as following:

```js
  getVariables() {
    return this.props; 
  }
```

Which obviously returned an error because it also sent  the `__dataID__` that hasn't been defined in a Type.  I could manually loop through all the objects and arrays in order to remove the `__dataID__`. However, that's quite tedious. 

`__dataID__` helps Relay gain performance; refetching, mutating and etc. Relay could use `__dataID__` behind the scene without binding it to `this.props` in containers. As a developer, we will never ever want to manually access the `__dataID__`, won't we? Should it be included in the `this.props`?

**Comment by josephsavona** [comment]
Thanks for asking about this. Relay uses underscore prefixed keys on props to store metadata. This includes `__dataID__` (global id or a generated one), `__status__`, and some others for deferred query tracking. These are necessary in order to allow records from props to be passed into methods like `props.relay.hasOptimisticUpdate()`. 

In the future we may consider using Symbols in order to make the metadata accessible only to Relay: for now the simplest approach is to use "private" keys. 

Can you explain your use case a bit more? Why pass all of the existing records into a mutation as-is? In general products would explicitly pass changed properties.

**Comment by lvarayut** [comment]
Thanks for your great response. I'm trying to write a reusable mutation for updating data, called `TripPlannerMutation`. So, if any data changed, it could use to the same mutation. Let's say, I have Trip, Country, and City types as following:

```
{
  "data": {
    "viewer": {
      "trips": {
        "id": "VHJpcDpWSEpwY0RwV1NFcHdZMFJ2UFE9PQ==",
        "travelCompany": "A company",
        "countries": [
          {
            "id": "1",
            "countryName": "Thailand",
            "cities": [
              {
                "id": "11",
                "cityName": "Bangkok",
                "durationNights": 2,
                ...
               }
             ]
             ...
            }
         ]
         ...
      }
   }
}
```

If I added a new city/country or even changed some properties, I would like to be able to reuse the same `TripPlannerMutation` to mutate the data. So, I'm currently using `react-addons-update` to update the object, then, I send the updated object to the back-end using `Relay.Store.commitUpdate(new TripPlannerMutation(updatedTrip));` which unintentionally contains `__dataID__` and returns an error.

**Comment by josephsavona** [comment]
I see, thanks for clarifying. In this case, I'd recommend explicitly extracting the properties of the props object to pass into the mutation. You could hand write this (list out all the specific properties), or just write a function that recursively maps the props object to a new object, minus the metadata keys. 

We're definitely open to concrete ideas about other ways to store this result metadata. for now though I'm going to close this since there is an easy workaround. Please feel free to continue the discussion here or to reopen with suggestions for alternatives!

**Comment by lvarayut** [comment]
Thanks @josephsavona. I currently do as your suggestion. But this introduces another problem about Data masking. Actually, City and Country contain their own fragments. Trip is currently using `City.getFragment('city')` and `Country.getFragment('country') to combine all the fragments and send them for retrieving data. Since, Trip can't directly access the returned data of City/Country, I have no way to send the entire structure to the back-end. The returned object is shown as following:

```
{
  "data": {
    "viewer": {
      "trip": {
        "id": "VHJpcDpWSEpwY0RwV1NFcHdZMFJ2UFE9PQ==",
        "travelCompany": "A company",
        "countries": [
          {
            __dataId__: "1"
            __fragments__: { 2:: client: "1"}
          }
         ]
         ...
      }
   }
}
```

If I added a new country, I would like to update the countries array and send the updated one back to the database. However, I couldn't do that since the Trip can't access the countries array. What I can do is to send just the `id` of the trip and the new country name and let the back-end retrieve the Trip object by using the id, add the new country to the array, and persist it to the database. I have to write another mutation for adding a city, and also another one for updating other properties.

I feel like I'm doing something in the wrong way. Your advice would be really appreciated.

**Comment by janicduplessis** [comment]
I've hit a similar issue too, where I'm using relay data when updating an object in a mutation. Would it be possible to make the __dataID__ field not enumerable? This way it would be possible to clone the relay data before sending it to the mutation and the copy would not include any meta data. This would achieve a similar result as using a Symbol.

**Comment by josephsavona** [comment]
@lvarayut For this case, you can use a [mutation fragment](https://facebook.github.io/relay/docs/api-reference-relay-mutation.html#fragments-static-property) to allow the mutation to specify all the fields on an object that it needs to have fetched in order to execute. Rather than have the views fetch all the fields and pass them to the mutation, you can do `${YourMutation.getFragment('...')}` in the component query, and then pass this to the mutation as a prop.

@janicduplessis We understand that having to filter out these properties is slightly inconvenient. Ultimately, it comes down to performance and which operations are more common. Reading data for fragments is a very common operation that we would prefer to keep as fast as possible, which means using plain properties instead of `defineProperty`. Mutations are less common and not on the critical path, so the extra cost of skipping metadata properties is less of a concern. 

We'll definitely keep this use case in mind though. It still feels that there should be an alternative to copying so many fields in order to construct the mutation, though.

**Comment by janicduplessis** [comment]
@josephsavona I guess another alternative could be to have relay mutations do the filtering out of it's metadata before sending the result. For simple mutations this isn't really an issue but for mutations with deep nested objects it becomes annoying. For now I ended up writing a clone function that removes `__dataID__` but I feel like it could be handled by relay as some more people might hit this problem.

**Comment by sibelius** [comment]
this could help

```jsx
const isObject = obj => obj !== null && typeof obj === 'object';

const removeDataID = relayObj => {
  return Object.keys(relayObj).filter(key => key !== '__dataID__').reduce((obj, key) => {
    const value = relayObj[key];
    const simpleValue = isObject(value) ? removeDataID(value) : value;

    return {
      ...obj,
      [key]: simpleValue,
    };
  }, {});
};
```
