### ISSUE TITLE
Missing child when only the id field is defined

### ISSUE THREAD

**Issue by jsdir** [facebook/relay#1102]
When I use the following fragment in a Relay container:

``` js
Relay.createContainer(Component, {
  fragments: {
    parent: Relay.QL`
      fragment on Parent {
        foo
        child { id }
      }
    `
  }
})
```

`props.parent` does not include a `null` `child`.

``` js
{
  foo: "bar"
}
```

However, when I add another field to `child`:

``` js
Relay.createContainer(Component, {
  fragments: {
    parent: Relay.QL`
      fragment on Parent {
        foo
        child { id, __typename }
      }
    `
  }
})
```

`props.parent` then includes `child`:

``` js
{
  foo: "bar",
  child: {
    id: "baz",
    __typename: "Child"
  }
} 
```

Why doesn't the `child` show up in the first example? Is this behavior caused by Relay's internal caching system?

**Comment by wincent** [comment]
This looks like a bug to me.

Relay will avoiding passing generated data to components because it wants to be sure they only get the data they explicitly asked for. `id` fields are often generated, but not in the case of your example, where the `id` field is explicit, so you should get it if you're asking for it.

Interested in coming up with a failing test case and making sure that it still fails on the current master branch @jsdir?

**Comment by ianstormtaylor** [comment]
Oh man I wish I had looked here earlier, took forever to realize it wasn't my fault! (Hopefully.) Running into this as well, except with:

```
fragment on Team {
  tokens {
    id
  }
}
```

Without adding another field to `tokens` the `team.tokens` in the response will be undefined, instead of an empty array. As soon as I add:

```
tokens {
  id
  created_at
}
```

The empty array `team.tokens` is there as expected.

**Comment by anttimo** [comment]
Updating from Relay 0.8.1 to 0.9.1 seem to have fixed this issue for us or then just hided it somehow since it was bit hard to reproduce it. @jsdir @ianstormtaylor would be nice to know if you have tested with newer Relay and if it fixed this issue for you too?

**Comment by jsdir** [comment]
I'm closing this issue since this bug apparently got fixed when `subtractRelayQuery` was removed in `relay@0.9.1`

**Comment by wincent** [comment]
Indeed, R.I.P., `subtractRelayQuery`. Thanks very much for reporting the issue, and to others who chimed in as well.
