### ISSUE TITLE
Not able to get Relay work with React Native

### ISSUE THREAD

**Issue by BilalBudhani** [facebook/relay#1147]
I'm trying to setup a basic React Native Relay project. I'm creating this issue after spending ample of time trying debug the problem without any luck. I'm getting this warning on console and my react native app is not able to make calls to GraphQL server. 

```
Warning: RelayNetworkLayer: Call received to injectImplementation(), but a layer was already injected.

Running application "ExampleApp" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF

fetchWithRetries(): Still no successful response after 1 retries, giving up.
```

Here is my code 

index.ios.js

```javascript
import React, { Component } from 'react';
import Relay from 'react-relay';

import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';
import App from './app';
import AppRoute from './route/appRoute';

Relay.injectNetworkLayer(
  new Relay.DefaultNetworkLayer("http://localhost:1337/graphy")
);

class ExampleApp extends Component {
  render() {
    return (
      <Relay.RootContainer
        Component={App}
        route={new AppRoute()}
      />
    );
  }
}

AppRegistry.registerComponent('ExampleApp', () => ExampleApp);
```

appRoute.js
```javascript
'use strict';

import Relay from 'react-relay';

export default class extends Relay.Route {
  static queries = {
    page: (Component) => Relay.QL`
      query {
        posts(offset: 0) { ${Component.getFragment('page')} }
      }
    `,
  };

  static routeName = 'AppRoute';
}

```

app.js
```javascript
'use strict';

import React, {Component} from 'react';
import Relay from 'react-relay';

import {
  View,
  Text,
} from 'react-native';

class App extends Component {

  render() {
    console.log('props', this.props);
    return(
     <View>
      <Text>Testing</Text>
     </View>
    );
  }
}


export default Relay.createContainer(App, {
  fragments: {
    page: () => Relay.QL`
      fragment on Viewer {
        posts { id, title }
      }
    `,
  }
});
```

package.json
```json
{
  "name": "ExampleApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "babel": "^6.5.2",
    "babel-preset-react-native": "^1.8.0",
    "babel-relay-plugin": "^0.8.1",
    "react": "^0.14.8",
    "react-native": "^0.25.1",
    "react-relay": "^0.8.1"
  }
}
```

babelRelayPlugin.js
```javascript
const getBabelRelayPlugin = require('babel-relay-plugin');
const schema = require('../schema.json');

module.exports = { plugins: [getBabelRelayPlugin(schema.data)] };
```

Here is the full repo link: https://github.com/popstand/react-native-relay-graphql-example

Similar code built with ReactJS and Relay works well on webpage. I'm not able to make it work on React Native. What is possibly going wrong here which is causing this issue?

**Comment by wincent** [comment]
I think the warning can be safely ignored (and will go away in the next release; it's already mitigated on the master branch, as of commit d1abc54d5ab60fc).

The `fetchWithRetries` failure I am not sure about. Are you able to connect to that *same* GraphQL endpoint outside of React Native? (Sounds like you are, but I just want to clarify.)

**Comment by BilalBudhani** [comment]
@wincent Yes, I'm able to connect and load data from GraphQL with web version of my code. But, I'm not sure what's wrong with React Native code.

**Comment by Longsight** [comment]
Wherever you're running the RN code, is **it** able to reach the GraphQL server? If you're running in iOS Simulator then localhost should be fine, but if you're running on an actual device then you'll need to change that to a more meaningful network address.

I had similarly cryptic problems with `DefaultNetworkLayer` for a while, but debugging within `DefaultNetworkLayer` and `fetchWithRetries` themselves got to the bottom of it. I'm damned if I can remember what the issue was, but I suspect it's unrelated here.

**Comment by steveluscher** [comment]
Thanks for your question! It sounds like you're having reachability problems from your device/simulator to your GraphQL server. Let's get some more eyes on this!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

Questions like yours deserve a purpose-built Q&A forum. Would you like to post this question to Stack Overflow with the tag #relayjs? We'll be happy to answer there. Post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs
