### ISSUE TITLE
Relay Docs is one of the hardest docs I ever tried to understand

### ISSUE THREAD

**Issue by ashah888** [facebook/relay#1148]
Relay Docs are ridiculous hard to understand.

It lacks examples.
It lacks clear explanations.
Unclear, scattered variables in examples.

**Comment by BilalBudhani** [comment]
As someone who is trying to understand how to implement Relay, I can relate to this and second the OP.

**Comment by nodkz** [comment]
I agree with you. But after several months I found doc very condenced. I totaly reread it about 5 times ;)

**Comment by KyleAMathews** [comment]
Errr... what the hell?

There are real people behind Relay who've put an enormous amount of effort into documenting Relay. At least try to respect that.

Relay is an ambitious new project. And despite the OP's comment is abundantly documented with 3-4 working examples, extensive API docs, numerous conference talks, blog posts, etc. I would love it if all Open Source code I use was documented and supported this well.

If you have constructive, detailed, *respectful* feedback about what you've found difficult to understand while learning Relay, I'm sure people here would love to hear that. But your comments so far are not the least bit helpful and are frankly pretty offensive.

**Comment by KyleAMathews** [comment]
And I apologize if that came across as too harsh. Your perspective is valuable and needed for Relay to be successful. It really would be valuable to hear your stories of what and where you struggled.

I'm not a Relay maintainer but I know what it's like to be receive these sorts of comments and it's not fun.

**Comment by wincent** [comment]
Thanks to everybody for chiming in on this thread. We'd definitely like to improve the documentation, and do what we can to make Relay easier to understand. Like @KyleAMathews said, however, in order to be most useful, we need the feedback to be a little more concrete, focused and actionable. I'm going to close this one for now, and I encourage you to open narrower issues for specific problems that you find with the documentation or the concepts in the framework. The more detail, the better, and best of all is if you can incorporate a concrete suggestion for how something could be changed into a format that would be more understandable and useful to you.

(Also feel free to comment on this issue, even though I am going to close it. I'm just closing it because it is not specific enough to be actionable, not because I want to silence the discussion.)

**Comment by nodkz** [comment]
@KyleAMathews nobody say that doc is terrible. Just say that it is "hard to understand". And it really such is. Because Relay has huge amount of abstractions/logic/relations and especially in conjunction with graphQL, so brains should hard strained to catch all aspects and principles how Relay works. So I can not imagine examples, which can give easy dive to Relay. 

I found doc very condensed (absent vacuity). So need read every topic attentively, cause every paragraph contain concentrated (high amount) information. And I spent seconds to find needed information. So for me at now doc is very good, for me at past doc was how @ashah888 wrote above.

Framework is too fresh, and of course is written low amount tutorials for newbies. Just need wait a critical mass of audience and success projects outside facebook.

PS. I am spent 7 months to study from scratch NodeJS + ES6 + Webpack + React + Relay + GraphQL + and tons of other modules (after Dan's talk at React Europe 2015 about hot-reload). So beautiful and simplicity have hight price. BTW I'm very glad that I ran away from RoR. Glad that choose Relay, not Redux. Glad how FB invested resources to open source and what amazing peoples maintains it. Especially inspired by eminence grises - Sebastian Markbage and Lee Byron.

**Comment by BerndWessels** [comment]
There are plenty of Relay Git Issues here about the fundamentals and understanding of the nitty gritty of Relay that got shut down with the comment that they are noise and better placed at StackOverflow. Unfortunately often they are then not answered on StackOverflow. And from my personal experience there are many areas in Relay that are either not documented or very poorly explained.

The risk here is that people get all excited about GraphQL and they should! But then when it comes to Relay they get disillusioned about the complexity and how hard it is to use GraphQL on the client.

So Relay can drag down GraphQL's success. I experienced it myself. I convinced my company to use GraphQL. Everybody loved it until people got extremely frustrated with Relay. It almost killed GraphQL in our company. I could only save it by dropping Relay and build a much simpler and easier to use and understand client site GraphQL connector.

Obviously we all appreciate the huge effort of all the people working on Relay - but maybe there should be a warning on the Git Readme saying "Work in progress, not ready for production yet".

**Comment by brad-decker** [comment]
Our company has successfully implemented a fully working Relay website using the documents provided and a little sleuthing inside the source code. It's my opinion that more documentation and better documentation is ALWAYS possible but that doesn't meant that it is not usable to produce a working product.

@Aweary @dwightbe :+1: :+1:

**Comment by KyleAMathews** [comment]
Relay seems like an excellent example of a *simple* tool not necessarily an *easy* one (using [Rich Hickey's framework](https://www.infoq.com/presentations/Simple-Made-Easy)).

It's certainly not easy to get going with compared to using existing, familiar tools e.g. REST but is incredibly *simple* to use once you get it and things are setup. For my product, Relay is the most carefree part of the stack and just works. Creating new components is a breeze.

Or to use economic terminology. Relay has a high fixed cost but very low marginal costs.

My assumption is over time the fixed cost will drop but as far as I'm concerned, Relay has by far the lowest marginal costs in the data-fetching industry.

**Comment by tar-aldev** [comment]
1. What about any examples with react-router integration? (It looks like an overhead to create own routing solution just to be able to loadQueries ahead of component mounting)
2. In your step by step guide you use `loadQuery` directly
https://relay.dev/docs/getting-started/step-by-step-guide/#step-5-fetching-a-query-with-relay
But there is also a hook `useQueryLoader` which returns `loadQuery`. It is not clear at all when to use which.
A lot of examples have it like
```
const preloadedQuery = loadQuery(RelayEnvironment, RepositoryNameQuery, {
  /* query variables */
});
```
That is, of course, nice, but it has no help in case you have variables coming from e.g. router params or as prop. (because loadQuery is outside of component)
3. In some examples like this one https://relay.dev/docs/guided-tour/rendering/queries/#rendering-queries
```
const data = usePreloadedQuery<HomeTabQuery>(
    graphql`
      query HomeTabQuery($id: ID!) {
        user(id: $id) {
          name
        }
      }
    `,
    props.queryRef,
  );
```
props.queryRef is coming from nowhere and there is no explanation about how to configure it up the tree or pass it down properly.
4. Errors handling.
It looks like the only way of handling errors is by using error boundaries. It is kind of a ridiculous thing because when you have hooks and use function components everywhere, creating `class ErrorBoundary extends Component` seems to be very out of place... Also, what should I do in case I need more granular error handling? Something more accurate than just wrapping components with error boundary? What if I want to show a popup notification like `notistack`?
5. Examples
I agree, that there are some examples and docs, but they are not complete. **Step by step guide** gives a very basic understanding, while a **Guided tour** has not complete code sample, but just pieces of code here and there.
I do not want to abuse anyone or put a link to other libraries, but there are some of them which have guided tour, where an entire application is created. Needless to say, that such guides give you great understaning of features, while in your docs. there are only basic things that are explained.
Finally, as a new guy who wants to look at examples, I surely took a look at all three of them posted on your site.
1. https://github.com/relayjs/relay-examples/tree/51b8fbf17d2067cbc927aa38975862c81552e157/todo - 
seems to be quite okay, but again, it has only one root query `appQuery`, and it uses QueryRenderer. What if I have multiple pages?
There are parts like 
```
TodoListFooter_user on User
```
And it is not clear where this User type comes from. Is it defined somewhere in the backend schema? Is it generated somewhere? Not clear at all.
Then in the render part, there is a code like this
```
<TodoListFooter user={user} />}
...
// then in TodoListFooter
const TodoListFooter = ({
  relay,
  user,
  user: {todos, completedCount, totalCount},
}: Props) => {
...
```
What the heck? Where did the relay prop come from? Was it passed magically (automatically)?
2. https://github.com/adeira/relay-example 
Seems okay and uses next.js, but still, it uses QueryRenderer which seems to be passing away according to this
https://relay.dev/docs/migration-and-compatibility/relay-hooks-and-legacy-container-apis/
3.  https://github.com/juffalow/react-relay-example/tree/8ab693477b996a9dd2f74175e4f6ab60d1fb5746
Seems to be the only clear and understandable example. Uses typescript which is great. However, it uses `useLazyLoadQuery ` which you do not recommend. Here is a link https://relay.dev/docs/api-reference/use-lazy-load-query/#uselazyloadquery
4. https://github.com/relayjs/relay-examples/tree/51b8fbf17d2067cbc927aa38975862c81552e157/issue-tracker
Seems like an overcomplication... I personally abandoned the ope when saw that there is a custom routing implementation which seems insane when there is a `react-router`- battle-tested routing library.

Let alone the fact that a lot of examples still use flow while today literary all use typescript. At least the ability to switch between flow and typescript would be really appreciated.

Sorry, for a long and angry comment. I am not sure whether this issue is tracked at all. However, if anyone can give some advice it will be extremely appreciated. (at least about how to deal with useLazyLoadQuery which seems to have no alternatives, but is not recommended to use)

**Comment by karlmarxlopez** [comment]
We are using relay on a recent React Native project, which we are having a good experience on the performance, but not on the documentation.

1. I agree with the previous comments that the documentation is condensed, the hooks example on the repo is incomplete.
2. They should create an example app with screens that implement the hooks version and the older version.
3. There is no actively maintained official React Native debugger. IIRC, the last published version was 4 years ago. It is painful to debug using only log middleware.
4. No VSCode extension support, the current one using Apollo extension is flaky.
5. There should be more examples per hooks, explaining the best practices.

A good inspiration for the documentation would be Redux, Redux Toolkit, and React Navigation, just to name a few.
