### ISSUE TITLE
How to limit/skip inside connection queries?

### ISSUE THREAD

**Issue by ashah888** [facebook/relay#1151]
I'm trying to do a pagination query.

But the connection query's args.after = "ABCDEFG123" _only_ seem to work within the ranges of the first  query result.

For example, if I do a query and if it returned 10 items, and then if I perform another query with a cursor passed to it, my query is incapable of displaying anything after the first 10.

This seems very inefficient if I have to query my entire database in order for the cursor pagination to work.

What is the proper use case for the relay connection queries?

**Comment by wincent** [comment]
Hi @ashah888. I'm not sure I exactly get the question. Can you provide a concrete example of a query and also show the code you're trying to use to do the pagination?

**Comment by steveluscher** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

Questions like yours deserve a purpose-built Q&A forum. Would you like to post this question to Stack Overflow with the tag #relayjs? We'll be happy to answer there. Post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs
