### ISSUE TITLE
Rename npm package to relay

### ISSUE THREAD

**Issue by taion** [facebook/relay#1159]
Now that `react-relay` has passed @davidaurelio's `relay` in version, would it be possible to use the `relay` package name on npm?

It would save me feeling dumb every time I accidentally type

``` js
import Relay from 'relay';
```

**Comment by wincent** [comment]
Funny you should ask. @cpojer brought up the same idea only an hour ago.

**Comment by cpojer** [comment]
(@taion and I talked about this today ;) ).

**Comment by taion** [comment]
I was looking at https://www.npmjs.com/package/relay after messing up that import again, and thought that the name of the package owner looked sorta familiar.

**Comment by KyleAMathews** [comment]
Or relay core could be in "relay" and the react relay bindings stay at
"react-relay"? Is Relay core still a thing?

**Comment by josephsavona** [comment]
> Is Relay core still a thing?

Yes. We'll publish more info soon, but we're working on this.

**Comment by josephsavona** [comment]
The experimental new core that we've previously called Relay "2" (see #1369) is split into a view-agnostic core and React binding layer. We're likely to keep using a single repository, but we'll keep in mind the idea of releasing the core as a separate package. I'm going to close this since it isn't actionable near-term (we're still incrementally working toward the new core). Thanks for starting the discussion about this! Feel free to reopen or comment if you think think this needs to be addressed sooner.
