### ISSUE TITLE
Changed npm preinstall behavior breaks Relay examples for Node 5 & 6

### ISSUE THREAD

**Issue by CoericK** [facebook/relay#1177]

**Comment by steveluscher** [comment]
Thanks for reporting. Help us find out why:

* What git hash you're on: `git show`
* What `npm -v`
* What `node -v`
* Paste the output of the broken step into a gist.github.com

**Comment by steveluscher** [comment]
I've added new build tests for the examples. Every example builds, it would seem (https://travis-ci.org/facebook/relay/builds/133505982) so you must be having trouble executing them?

**Comment by steveluscher** [comment]
Oh, interesting. Even though it looks like those TravisCI builds passed, they actually failed for Node 5 and Node 6. Looking…

**Comment by CoericK** [comment]
@steveluscher After i knew Relay 0.9 was released i made a fresh clone, then i made npm install on the root of the relay repo, and then moved to the todo example and didnt work.
node: v6.2.0
npm: 3.8.9

I made a pull request https://github.com/facebook/relay/pull/1178

**Comment by steveluscher** [comment]
Oh, wow. This entire problem is because the behavior of `npm preinstall` changed in npm 3.x (see https://github.com/npm/npm/issues/10379). We relied on this behavior to fully install & build the local version of `react-relay` and `babel-relay-plugin` before _starting_ to build the example code.

**Comment by steveluscher** [comment]
OK. A while ago, we decided to use `file:` relative version specs in our examples. The idea was that you might want to develop the examples in tandem with Relay or the Babel plugin. Or that you might want to make a backward incompatible change to one of the examples.

In practice, this has kept a lot of people from being able to use the examples because of issues like https://github.com/npm/npm/issues/10379. I'm going to change the dynamic today.

Now, we're going to lock the examples to the _release_ version of `react-relay` and `babel-relay-plugin`. This will make the examples run reliably for most of us, and will fix all of the Node 5/6 issues I've just discovered as part of this bug report.

If you want to develop on the examples and Relay in tandem, then you can do a little bit of extra work to `npm link` your local copy of `react-relay` and the `babel-relay-plugin`. A guide on how to set all of that up can be found here: http://justjs.com/posts/npm-link-developing-your-own-npm-modules-without-tears

**Comment by CoericK** [comment]
Oh glad that my report helped to make that improvement @steveluscher, let me know if there is anything else that I can test and give feedback.

**Comment by steveluscher** [comment]
Still one thing to do. Need to upgrade fbjs-scripts in react-native to get Babel 5 out of the picture for npm 3. I have a PR out for that.

**Comment by steveluscher** [comment]
Merging into #1188.
