### ISSUE TITLE
Relay And SEO

### ISSUE THREAD

**Issue by nikhildaga** [facebook/relay#1191]
First of all thank you for Relay. Its a very useful and powerful framework. I have developed a fairly big web application using Relay but Google bot is unable to crawl the pages. All the pages appear blank to Google bot.

Please advise me what to do to make Relay components crawlable by search engines.

Thanks.

**Comment by josephsavona** [comment]
Hi! Thanks for your question. We have an ongoing discussion about this in #136, but the short version is: use https://github.com/denvned/isomorphic-relay/ to do server rendering. I'm going to close this since there's already an open issue on this topic, please feel free to ask more questions at #136.
