### ISSUE TITLE
React Native Relay and State Management

### ISSUE THREAD

**Issue by CoericK** [facebook/relay#1210]
I'm exploring Relay but using it with React Native, I saw some implementations that are using react-native-router-flux to handle the routes, but a reduce its also being created:
```js
const reducerCreate = params=>
{
  const defaultReducer = Reducer(params)
  return ( state, action ) => defaultReducer( state, action )
}
...
 <Router createReducer={reducerCreate} ...>
...
</Router>
```
Does this mean that we can create as many store, actions, reducers as we need and make our components work with Relay as Containers??? Isn't Relay a replacement for Redux in terms of Glabal State Management?

Lets say that I got an initial Launcher Component, with redux, on componentDidMount I would call an  action to check if there is any local session, then according to the response I can call `Actions.sign()` or `Actions.home()` 

With Relay how can I can handle this? Can both work together?

**Comment by NevilleS** [comment]
I'm not quite sure what the issue here is (Stack Overflow might be a better place for a high level question like this), but the quick answer is that Relay is *not* a replacement for Redux, and in fact co-operates quite nicely with Redux. Relay provides it's own store that manages all the GraphQL data you fetch and mutate in your application; Redux provides a store that manages anything else you want to model. On RN, the Redux store might be somewhere you manage navigation state, for example.

**Comment by wincent** [comment]
Yeah, I think there are probably two appropriate forums for this kind of question:

1. Stack Overflow for concrete technical questions about *how* to make architect an app using Relay and Redux (or any other local state management solution, Flux-like or otherwise).
2. [relay-future](https://github.com/relayjs/relay-future) For forward-looking discussion of possible directions for integrated local state management in Relay.

On that latter subject, we're not actively working on it right now — we're currently focused on getting the core abstractions solid and performant on potentially low-power, network-poor mobile devices — but we thin that problems like tackling local state will be good goals to focus on next.

In the meantime going to mark this one as closed. Thanks for your quesion @CoericK, and for your input @NevilleS.
