### ISSUE TITLE
Relay strips fragments that query only the id

### ISSUE THREAD

**Issue by blaiprat** [facebook/relay#1220]
I've just came to this issue, I'm trying to get from GraphQL an array of GraphQLObjects but the only information I need is the Id. Here's the query: 

```js
viewer: () => Relay.QL`
    fragment on User {
        arrayOfObjects {
            id
        }
        email
    }
`,
```

Once everything is loaded, `this.props.viewer` has only the email. After checking I've seen that the query sent to graphQL doesn't have `arrayOfObjects` in it. So adding an extra element to the query like:

```js
viewer: () => Relay.QL`
    fragment on User {
        arrayOfObjects {
            id
            name
        }
        email
    }
`,
```
It works as usual, I get both the ids and name in `arrayOfObjects`. I might be wrong, but I'd say this is a bug, the component that writes this query doesn't need to fetch any other information, so bloating the query doesn't seem appropriate.

**Comment by wincent** [comment]
I think what you're running afoul of here is code that we had in `subtractRelayQuery` until very recently (569a0e57f22058f9c1d266). [Example](https://github.com/facebook/relay/commit/569a0e57f22058f9c1d2669b487b0225c501308a#diff-3185b2e83986afb0b91017c77031c27cL97):

```
// this would subtract to node(4){id,hometown{id}}, which is "empty"		
// because it contains no non-requisite, non-id scalar fields
```

We explicitly considered fields that implemented the `Node` interface to be "empty" if they didn't contain any non-requisite, non-id scalar fields, and I gather your `arrayOfObjects` items all implement `Node`. Generally, but not always, you don't need to ask for the `id` because in order to get the `id` you would have needed the `id`, except when you don't... The workaround to indicate that you really wanted to fetch the `id` anyway was to [assign an alias](https://github.com/facebook/relay/commit/569a0e57f22058f9c1d2669b487b0225c501308a#diff-3185b2e83986afb0b91017c77031c27cL125).

So, I think this may be a non-issue after 569a0e57f22058f9c1d266, but in the meantime you can work around this by using an alias. I'll close this for now, but feel free to comment again if you have any further thoughts, or think I'm wrong about my diagnosis.
