### ISSUE TITLE
API Simplification

### ISSUE THREAD

**Issue by jehoshua02** [facebook/relay#124]
I'm reading through the documentation for relay. Great work on this. I understand this is a "technical preview" so I wanted to offer some advice.

I find React's api is so dead simple that I felt confident I could use it correctly.

I was expecting similar simplicity with Relay. The api is too complex for me to feel confident in using it. Are there any plans to simplify Relay's API?

To give you an idea, when I imagined Relay before it was released, I was expecting a lot less wiring up of things. I would simply define a graphql query in the container component which Relay would magically merge with queries from other components, make a query off to the server, shell the data back out to components when available. Route and RootContainer feel cumbersome to me. The Mutations api also feels disjointed. I find it hard to understand in what order things happen (lifecycle) and the naming of the methods and everything feels a little off/confusing.

Perhaps I just need to keep reading the docs and it will all become clear. But maybe Relay needs to be crafted with a little more empathy?

**Comment by jehoshua02** [comment]
Oh yeah, and I was wondering if components really need to be aware of Relay at all (`this.props.relay`) and if Relay could be refined to instead pass down callbacks for mutations and data as props.

**Comment by phated** [comment]
I also appreciate all the work that's gone into this.  However, I've spent a good amount of time with the docs and examples so far and I agree with the points made.  I don't like "magic" things, but the API feels very disjoint for Mutations (graphql for most of it but objects with custom types for getConfigs).  The babel-relay-plugin is very frustrating to use since you have to pass it an introspected JSON file.  Also, all of the sub-classing is very awkward, especially where some of it is just to define new static properties.

I walked our local node user group through Relay this week and everyone seemed to agree.

**Comment by josephsavona** [comment]
Thanks for you honest feedback. We're always interested in finding ways to make things more approachable and understandable. In general, the most actionable type feedback is example application code that uses your "ideal" or desired API. Please feel free to post code or a link to a gist here so we have concrete examples to discuss. 

@jehoshua02, can you provide some example code for your proposed Container API? Note that routes provide a fixed starting point in the graph (query), and containers are reusable (fragment). 

@phated a couple points:
- `babel-relay-plugin`: The dependency on the instrospection JSON is definitely a limitation. Fortunately, it's a temporary one! Once the `graphql` API stabilizes we'll enable the creation of plugins from JS schema files. 
- As for the mutation API, we agree that less configuration would be good. We plan to improve this API, and would welcome suggestions!

**Comment by jehoshua02** [comment]
@josephsavona I'm very glad my plea for empathy was heard. I wasn't sure which way it would go. I'd like to take a whack at proposing ways the api can be simplified after I read the docs more and have some time to play with Relay.

However, in my experience, when I have written some code, especially documentation, I find that following the documentation, pretending I am completely unfamiliar with the library helps me identify how the documentation and especially the code can be polished and refined further. I also wouldn't expect someone else to know how code I've written could be improved better than myself.

That said, I'd still be happy to point out things I struggle to understand, or things that feel awkward, and provide "dream code" as long as it is understood that my feedback may be incomplete and feeble at this point.

**Comment by gyzerok** [comment]
@josephsavona 
Please check [my repo](https://github.com/gyzerok/redux-graphql) where I started to create custom implementation of Relay in July before official release.
The motivation was: 
1) bored to wait official release 
2) In Relay you need to provide custom implementation for only-client stores, so you need to use one other framework for it which is bad in my opinion
3) Redux is really awesome
So I've ended up with some Redux-tools implementation which current provides data fetching mechanism. 
I've found [react-redux](https://github.com/rackt/react-redux) idea about Smart and Dumb components quite cool. Generally you create Smart components for your root view tree nodes (which correspondes to routes) and dumb component for other views. You can read more about it in the react-redux docs. So my implementation is kind of react-redux fork.
Readme is currently out of date. Please check ```examples``` directory to see my ideal api for this.

@jehoshua02 If you interested in more simple API, I would be happy if you can help me in my project. Together we may challenge better API which later on we can provide to Relay team.

**Comment by drojas** [comment]
I like the current API and initially felt the same awkwardness, but the pillow told me that may be that's just because the framework aims to be ultra flexible and targets different levels of abstractions at once, and they are not trying to build something that works only for React, or the web. For me, that's a possible explanation for the changes to the API, so far.

May be one can trade that flexibility for some simplicity by wrapping the parts that don't need to be so flexible. For instance a wrapper could provide simplicity by managing Route and RootContainer under the hood, and a redux-like pattern (or may be redux) could provide further extensibility in a simper way via middleware. For instance, some people may want to put middleware in their mutations and network layers. I think all that can be done today in user land though some wrapping (probably without any  monkey patching).

I love this project, thanks a lot!

**Comment by josephsavona** [comment]
Thanks again for the feedback. It's important to remember that Relay is a younger framework than React, and also that the problem it solves is more complex. We'll continue to improve the documentation and streamline the API going forward. I'm going to close this issue, but we encourage you to continue the discussion by filing separate issues with either questions about unclear aspects of the API, or with sample code demonstrating API proposals.
