### ISSUE TITLE
[new mutation api] List of desirable features

### ISSUE THREAD

**Issue by nodkz** [facebook/relay#1241]
List of desirable features:
- [x] 1. Pass several variables on the top level (not only input). It needed for getting fine grained payload which required some additional variables. [Implementation founded here](https://github.com/facebook/relay/blob/829450ab74aa5c6b0cdb453cb76b1fbc45f16687/src/mutation/RelayGraphQLMutation.js#L374)
- [ ] 2. Move on top level clientMutationId. It is to annoying extract it from inputs and passes to output. Downside we get visibility of this fieldname for every mutation in graphiql doc.
- [ ] 3. Nested mutations in graphql. For example, I have seven methods for mutating user model. It will be nice if I hide them all under `user: UserMutations` field/type.
- [ ] 4. Allowing `path`s in `getConfigs()` for `parentName`, `fieldIDs[key]`, `deletedIDFieldName` in deeply nested GraphQL elements would be nice. So I could have something like `pathToConnection` rather than `connectionName`, as in some environments it can be quite unnatural to enforce the immediate parent of a list to be a relay node. (@Globegitter [last paragraph in comment](https://github.com/facebook/relay/issues/1241#issuecomment-235308799)) 

Fill free to leave your desirable features in comments. I'll add them to this list with a serial number for referencing in the further discussions.

Will be cool if @wincent write about newly implemented features, what planned and of course what think about our desirable features.

**Comment by Globegitter** [comment]
This might of course already be covered by the relay team for the new mutation API, or become irrelevant entirely, but I just noticed an inconsistency, which I don't understand:

`NODE_DELETE` needs a `parentName` in the config where-as `RANGE_ADD` does not. I don't quite understand why the `parentID` itself is not sufficient.

It would also be nice if I could also return an object for `NODE_DELETE` which consists of the `parentID`/`sourceID` (so the server can supply it and I can simplify the config on the frontend) and the id(s) to be deleted.

Also allowing (especially list) mutations of deeply nested elements would be nice. So I could have something like `pathToConnection` rather than `connectionName`, as in some environments it can be quite unnatural to enforce the immediate parent of a list to be a relay node.

**Comment by nodkz** [comment]
@Globegitter `RANGE_ADD` has `parentName` https://facebook.github.io/relay/docs/guides-mutations.html#range-add

`parentName` - is the fieldname in your mutation payload (response)
`parentId` - is `id` in Relay's flat objects cache (store)
So these two fields need for making a relation between your graphql response and relay store. So this relation makes possible to merge data from a typed object in response with an object in relay's store. 

This article will be quite useful for understanding internal implementation of Relay's store http://hueypetersen.com/posts/2015/09/30/quick-look-at-the-relay-store/

Your suggestion in the last paragraph is awesome! Added under number **#4** in the list of desirable features.

**Comment by Globegitter** [comment]
@nodkz yes I know that RANGE_ADD has parentName but it is an optional config field there where it is required for NODE_DELETE, do I just don't understand that difference.

 Thank you for posting that article, will have a read.

**Comment by nodkz** [comment]
Due Greg talk about Relay 2: https://www.youtube.com/watch?v=OEfUBN9dAI8&feature=youtu.be
This issue became irrelevant. Mutations will become imperative.
