### ISSUE TITLE
allow formatRequestErrors to override

### ISSUE THREAD

**Issue by bsr203** [facebook/relay#1245]
Hi,

I like to format the error message sent by the server, and currently it is not possible to just change that method `formatRequestErrors`.
`RelayDefaultNetworkLayer` makes it allow override `sendMutation` and `sendQueries`, and I could achieve the same by overriding them, but like to do the minimal changes and not to have a stale implementation of above methods. 
Can you make `formatRequestErrors` overridable.

thanks.

**Comment by steveluscher** [comment]
That seems reasonable!

Would you be interested in sending a PR? Simply move the implementation of `formatRequestErrors` into the `RelayDefaultNetworkLayer` class just above `_sendQuery` as the ‘protected’ method `__formatRequestErrors` (prefixed with two underscores) so that subclasses of `RelayDefaultNetworkLayer` can override it.

**Comment by bsr203** [comment]
thanks.. will give a shot :-)

**Comment by josephsavona** [comment]
@bsr203 Feel free to submit a PR for this, I'll go ahead and close the issue.

**Comment by bsr203** [comment]
sorry for the delay. In my case, I had to use a custom network layer and didn't get around it. Will contribute back when experiment with it again. thank you.

**Comment by jwb** [comment]
We're looking at making a PR for this, but wonder if it's likely to be relevant if the new Relay core is imminent. Are you still merging PRs for changes relative to 0.10.0, @steveluscher?
