### ISSUE TITLE
getFatQuery – necessary? Too knowledgable?

### ISSUE THREAD

**Issue by mhart** [facebook/relay#125]
Probably stemming from a lack of understanding, but is there a reason that `getFatQuery` needs to be so fine-grained and nested and not just rely on the server to send back the fields that have changed (possibly with a little help from the client by just specifying a query root or similar)?

(I'm thinking of things like https://github.com/facebook/relay/blob/master/examples/todo/js/mutations/MarkAllTodosMutation.js#L26-L37 )

It feels like the client needs to have a lot of knowledge of what fields the server will actually change, which makes it harder to change behaviour on the server without also updating the clients – I get this is generally true for traditional REST APIs, but I kinda feel like GraphQL could be smarter than that?

Possibly the same is true for `getConfigs` – is there no way for the server to signal to the client what it did?

**Comment by taion** [comment]
I think it would make a lot of sense for `getFatQuery` and `getConfigs` to live on the server rather than on the client, because they're not properties of the client at all.

I don't think it's possible for the server to know in the general case what fields have changed, and what updates should be made. Imagine my GraphQL server is just calling out to a bunch of REST servers; there's no way in general for it to know a priori what fields are going to change - at best it'd have to receive the response from the REST server and do a deep diff operation, which seems potentially quite tricky and fragile in practice.

**Comment by josephsavona** [comment]
> I don't think it's possible for the server to know in the general case what fields have changed, and what updates should be made.

Yup! That's exactly the reason for `getFatQuery` and `getConfigs`; it's impractical for GraphQL to understand how a given mutation may directly or indirectly affect the data model. That said, we are exploring the possibility of moving some of the configuration to the server.

**Comment by mhart** [comment]
> it's impractical for GraphQL to understand how a given mutation may directly or indirectly affect the data model

I mean, I get this, but how can the same thing not be said about the client? Even more so because it's not actually the one modifying the data – the server is.

Whether the server can figure it out automatically or whether you just specify it explicitly as part of a mutation (in your schema), it definitely feels more like a server responsibility.

> we are exploring the possibility of moving some of the configuration to the server

Cool! Any discussion of what this might look like anywhere?

**Comment by yuzhi** [comment]
Just to elaborate on what Joe mentioned:
Currently we are using `FatQuery` to intersect with queries we’ve fetched so far to figure out the exact set of data want to update with the server response (to avoid over-fetching and under-fetching). It’s unlikely for the server to keep track of what fields each client has fetched. This is especially important when there is a relationship change. One example, is let’s say there is a view with a user's profile picture. Once the user does a UpdateProfilePicture Mutation, the server might know that `user.profilePicture` now points to this new `profilePicture`’s id, but it might not know what the client also need the `profilePicture`’s new `url` for a specific size. While the server can send data for all the fields under the `profilePicture`, it can be pretty inefficient and cause cycles. Doing the query intersection on the client side ensures that the new `url` is fetched without including unneeded fields. 

The configs are needed on the client side in order for Relay to know what to do with both optimistic mutations and how to handle the server mutation. It tells Relay whether it need to merged in a field or add a new edge in the beginning of a connection. 

These two things definitely don’t have to be client specific and can live somewhere on the server. However, since it is not part of the GraphQL and we need to access to them within Relay, having them in the client seemed like the easiest place for most people to get started.

**Comment by taion** [comment]
One more thought here - there's also quite a lot of potential overlap between `getOptimisticResponse` and `getFatQuery` + `getConfigs`. For example, at http://facebook.github.io/relay/docs/guides-mutations.html#optimistic-updates, if you wrote e.g.

```js
  getOptimisticResponse() {
    return {
      story: {
        id: this.props.story.id,
        likers: {
          count: this.props.story.likers.count + 1,
        },
        likeSentence: null,
        viewerDoesLike: !this.props.story.viewerDoesLike,
      },
    };
  }
```

This would actually contain all the information in `getFatQuery`.

**Comment by mhart** [comment]
How about `fragments`? Is there some duplicated info there too or is it just me?

**Comment by yuzhi** [comment]
@taion They may look similar in that example because the optimistic payload is very thorough, but keep in mind that optimistic responses are completely optional. Mutations can have simpler optimistic response or no optimistic updates at all. The optimistic response also doesn't tell Relay store where to add edges or what to do with fields that are just a list of ids that are meant to be deleted. One potential thing we might not need from the optimistic payload is the `story.id` since that can be inferred from the `getConfigs`, but I'm not sure how the rest are being overlapped.

@mhart Fragments in mutations are mainly a way to declare what the mutation might need to generate the optimistic payload, which might also include fields that don't need to be in the `fatQuery` or be part of the `getConfigs`. It's similar to how components has fragments to declare what it needs to generate the view. What do you think it is duplicating or does it just look similar to the other ones in the examples?

**Comment by taion** [comment]
Understood - I brought that up because it seems like in cases where I do want to specify a very thorough optimistic response, I end up duplicating a lot of work. Maybe this is better handled by some "mutation helper" utility that lets me specify both parts in one shot.

**Comment by yuzhi** [comment]
Thanks for the feedback. I understand there are a number of pieces going into a single mutation that can seem very daunting to get started. This is definitely one of the more complex problem that Relay is trying to support. Going forward, we'll continue to find ways to improve and simplify the mutation API to make it easier to use without sacrificing features. Hopefully, we've answered why we have `fatQueries` and `getConfigs` in the current version of the mutation API. I'm going to close this issue for now, but we want to encourage more discussions on this. Please continue to open issues if you have more questions about why different parts of the API is needed or have ideas on simplifying them.

**Comment by taion** [comment]
:+1: I definitely need to get more experience using mutations in anger before I have a sense for what the actual API pain points are, rather than just hypothetical ones.

**Comment by josephsavona** [comment]
I've created a new meta-task at #538 to track this and several other issues about the mutations API. Let's continue the discussion there!
