### ISSUE TITLE
Get rid of changedTodos in the outputFields of the MarkAllTodos mutation

### ISSUE THREAD

**Issue by mhart** [facebook/relay#126]
Specifically talking about this field:

https://github.com/facebook/relay/blob/2a86be3e71cdc6511fa994e3de539f72070da1b4/examples/todo/data/schema.js#L173

I can't find a reference to it in the client code at all.

Is it just unused? If so, maybe it could have a comment (or be removed?)

**Comment by steveluscher** [comment]
Thanks for pointing this out! It is unused in the current implementation, but the current implementation also refetches the todos, whether or not their `complete` flag has been flipped. This would also work:

```javascript
  getFatQuery() {
    return Relay.QL`
      fragment on MarkAllTodosPayload {
        changedTodos {
          complete,
        },
        viewer {
          todos {
            completedCount,
          },
        },
      }
    `;
  }
  getConfigs() {
    return [{
      type: 'FIELDS_CHANGE',
      fieldIDs: {
        changedTodos: this.props.todos.edges[0].node.id,
        viewer: this.props.viewer.id,
      },
    }];
  }
```

…but having to specify at least one `id` for `changedTodos` in `fieldIDs` is awkward, especially because this mutation is designed to make supplying the actual todos optional.

Maybe there's something else that we could do here, like:

```javascript
  /* ... */
  getConfigs() {
    return [{
      type: 'FIELDS_CHANGE',
      fieldIDs: {
        changedTodos: 'any',
        viewer: this.props.viewer.id,
      },
    }];
  }
```

… to signal that we want to intersect the fat query with the union of all the tracked queries for this type, and send the resultant query up with the mutation.

Thoughts, @yuzhi @joesavona, @yungsters?

**Comment by yungsters** [comment]
I think the correct way to deal with this is to fetch `completedCount` on `viewer { todos }` as in your snippet. I think we can get rid of `changedTodos` because it never makes sense for a field on the client to be updated by it.

**Comment by steveluscher** [comment]
> …it never makes sense for a field on the client to be updated by it.

But we do need to update the `complete` field on each changed todo.

This has been implemented in https://github.com/relayjs/relay-examples/pull/2

**Comment by mhart** [comment]
@steveluscher that repo doesn't seem to exist (or is private?)

**Comment by mhart** [comment]
@zpao is https://github.com/relayjs/relay-examples private?

**Comment by steveluscher** [comment]
It's private, for a few moments longer. Stay tuned!

**Comment by mhart** [comment]
Cool, I can see it now, thanks!
