### ISSUE TITLE
RelayContainer's `shouldComponentUpdate` doesn't support non-query props that are objects

### ISSUE THREAD

**Issue by nthtran** [facebook/relay#1261]
Is there a reason why `RelayContainer` only handles non-query props that are scalar but not objects?

Due to `isScalarAndEqual` here in [RelayContainerComparators.js](https://github.com/facebook/relay/blob/master/src/container/RelayContainerComparators.js#L82), the `===` check only applies for scalar props. If any non-query prop is an object `shouldComponentUpdate` will always return true even if the object's reference hasn't changed.

**Comment by nthtran** [comment]
This makes `RelayContainer`inefficiently renders if it receives a prop that's an object. Given this example:

```js
class Item extends React.Component {
  render() {
    const { store, item } = this.props;
    return store.showItems ? <li>{item.name}</li> : null;
  }
}

Item = Relay.createContainer(Item, {
  fragments: {
    item: () => Relay.QL`
      fragment on Item {
        name
      }
    `,
  },
});

const store = {
  showItems: true,
};

class ItemList extends React.Component {
  const { items } = this.props.itemList;
  return <ul>
    {
      items.map(
        item => <Item
          key={item.id}
          item={item}
          store={store}
        />
      )
    }
  </ul>;
}

ItemList = Relay.createContainer(ItemList, {
  fragments: {
    itemList: () => Relay.QL`
      fragment on ItemList {
        items {
          id
          ${Item.getFragment('item')},
        },
      }
    `,
  },
});
```

In this case `store` is an object and its reference would never change. However `Item` will always rerender just because `store` is non-scalar, even if the current and next props satisfy `shallowEqual`.

The comment [here](https://github.com/facebook/relay/blob/master/src/container/RelayContainerComparators.js#L81) says a non-query prop must be scalar and ===. Just trying to understand why it must be scalar because this makes it impossible to pass immutable objects as props to `RelayContainer` and still have efficient re-rendering.

**Comment by jardakotesovec** [comment]
I have also ran into this issue and vote for '===' comparing for objects, so efficient comparison can be achieved at least with immutable approach as @nthtran  suggests.

**Comment by josephsavona** [comment]
This is by design. Relay is designed to work with arbitrary JavaScript code, which means that an object prop may be `===` to the previous prop yet have been modified since the previous render. The only safe thing to do in the HOC `shouldComponentUpdate` in this case is to return true if an object is encountered - otherwise it could skip a necessary update. 

However, you can achieve the desired affect! If you know that your prop objects are (or are treated as) immutable, you can still implement `shouldComponentUpdate` in the component itself to return false on triple equality. Note that the Relay provided props - fragment props plus `relay` - will be `===` unless the value has changed.

**Comment by josephsavona** [comment]
@nthtran As a concrete example, if you know that the `store` prop is immutable then the `Item` component can implement `shouldComponentUpdate` to return false if all props are `===`.

**Comment by nthtran** [comment]
Yep that's what I've been doing. Was just under the impression that `RelayContainer` was supposed to support immutable data to make it a bit less manual in optimising components for efficient re-rendering. Thanks for your reply @josephsavona.

**Comment by jardakotesovec** [comment]
@josephsavona Lets say that it would do === comparison on all props including objects, not just scalar - what would be the down side?  Currently its not useful for mutable nor immutable object props.  Using === for all props would make it at least useful for immutable use case. And docs would just say it does '===' comparison instead of comparison for scalar values, suggesting you either treat structures immutably or do your own shouldComponentUpdate.

I actually think it would be more intuitive than current behavior..  I know that it can be found in docs.. but in practice I also end up reading the code to find out what 'breaks' shouldComponentUpdate in relay container as I expected shallow compare by default. Majority devs seems [to also aim](https://twitter.com/reactjs/status/736412808372314114) for shallow compares in shouldComponentUpdate in react

**Comment by jardakotesovec** [comment]
@josephsavona Down side is that someone with mutable data would be prevented from re-renders, right? So probably until react would decide to go with this default shallow compare it makes sense to let optimization (via shouldComponentUpdate) on user same way as react does. Ok :-).

**Comment by josephsavona** [comment]
> Was just under the impression that RelayContainer was supposed to support immutable data

@nthtran I see. Yeah, Relay can't assume that props you give it are immutable, but it does guarantee that the props it provides to you can be treated as such. `RelayContainer` reuses any portion of the previous results that are deep equal to the new results [via a helper](https://github.com/facebook/relay/blob/master/src/legacy/store/GraphQLStoreQueryResolver.js#L269). The [tests](https://github.com/facebook/relay/blob/master/src/legacy/store/__tests__/recycleNodesInto-test.js#L89-L96) help to clarify the behavior a bit more.

> Down side is that someone with mutable data would be prevented from re-renders, right?

@jardakotesovec Right. Mutability is the default in JS, so the current behavior was chosen as being the least surprising overall while still allowing developers to use the standard approach to React optimization if necessary.
