### ISSUE TITLE
getConfigs() with both RANGE_ADD and FIELDS_CHANGE overfetching

### ISSUE THREAD

**Issue by BlooJeans** [facebook/relay#1305]
When I have both a RANGE_ADD and a FIELDS_CHANGE config, the FIELDS_CHANGE config overrides the RANGE_ADD and causes a refetch of the connection field that the RANGE_ADD should've optimized for

In the following example, the RANGE_ADD should add the newGroup to `viewer.groups`.  I need to also do a FIELDS_CHANGE on the same viewer because the `viewer.contacts` might change.

```js
getFatQuery() {
  return Relay.QL`
    fragment on AddGroupPayload @relay(pattern: true) {
      viewer {
        groups
        contacts
      }
      newGroupEdge
    }
  `;
}

getConfigs() {
  return [{
    type: 'RANGE_ADD',
    parentName: 'viewer',
    parentID: this.props.viewer.id,
    connectionName: 'groups',
    edgeName: 'newGroupEdge',
    rangeBehaviors: (connectionArgs) => {
      return 'prepend';
    },
  }, {
    type: 'FIELDS_CHANGE',
    fieldIDs: {
      viewer: this.props.viewer.id,
    },
  }];
}
```

If I remove the FIELDS_CHANGE config, then the mutation responds very efficiently, with only the added group:
```js
{
  "response": {
    "addGroup": {
      "newGroupEdge": {
        "__typename": "GroupEdge",
        "cursor": "updatedAt1469734335274",
        "node": {
          // ...group node here...
        },
      },
      "viewer": {
        "id": "viewerIdHere",
      },
  },
}
```

But with both configs, the RANGE_ADD is ignored/overridden, and the mutation responds with something like:
```js
{
  "response": {
    "addGroup": {
      "newGroupEdge": {
        "__typename": "GroupEdge",
        "cursor": "updatedAt1469734335274",
        "node": {
          // ...group node here...
        },
      },
      "viewer": {
        "id": "viewerIdHere",
        "_groupsrgC8": {
          "edges": Array[24], // array of many group objects
        },
      },
  },
}
```

One idea I tried was to use field aliases to get around the "shared" viewer between the two configs, but aliases don't seem to be supported in fat queries.  Might this be a good way to support my use case?
```js
getFatQuery() {
  return Relay.QL`
    fragment on AddGroupPayload @relay(pattern: true) {
      viewerGroups: viewer {
        groups
      }
      viewerContacts: viewer {
        contacts
      }
      newGroupEdge
    }
  `;
}

getConfigs() {
  return [{
    type: 'RANGE_ADD',
    parentName: 'viewerGroups',
    parentID: this.props.viewer.id,
    connectionName: 'groups',
    edgeName: 'newGroupEdge',
    rangeBehaviors: (connectionArgs) => {
      return 'prepend';
    },
  }, {
    type: 'FIELDS_CHANGE',
    fieldIDs: {
      viewerContacts: this.props.viewer.id,
    },
  }];
}
```

**Comment by wincent** [comment]
Thanks for the very detailed issue report, @BlooJeans. The behavior as you describe it is as expected, given how fat queries work. You are running up against one of the limitations of the declarative mutations API; it makes it possible to succinctly express *some* (common) intentions, but it is not sufficiently expressive to express everything in the universe of possible, nuanced intentions. Your aliases idea sounds reasonable on the surface, although I expect it could be non-trivial to implement support for it.

I'm going to close this for now because right now our focus is on shipping [Relay 2](https://speakerdeck.com/wincent/relay-2-simpler-faster-more-predictable), and in Relay 2 the declarative mutations API will be no more, but if someone wants to take a crack at implementing it for Relay 1 I'll be happy to re-open it. With our current focus, however, this isn't something we are likely to work on.

In the meantime, one option available to you is to consider using the low-level `RelayGraphQLMutation` API that exists on the master branch but is not documented. Using this API you can roll your own (static) query, with no magical tracked query synthesis. Because this is a manual process, it has far fewer restrictions in terms of expressivity, but it also requires you to do a bit of manual work. You can see some examples of its use [in the test suite](https://github.com/facebook/relay/blob/81b456e1738fc838ab9293f4caa4f28e6744664c/src/mutation/__tests__/RelayGraphQLMutation-test.js). For context, the reason this API remains undocumented and not officially supported is that it only goes part-way towards the fully static model that we are switching to in Relay 2; it still rests on legacy underpinnings in Relay 1 (the transaction abstraction, queue, collision key, some configuration etc).
