### ISSUE TITLE
Is there any ways to do Relay.refresh?

### ISSUE THREAD

**Issue by ErrorPro** [facebook/relay#1311]
Hello. We have a problem with refreshing full store. We have a notification system in our app and when new notification comes we want to refresh some data in relay store. Now we're using RelayStore.forceFetch with custom query inside. But sometimes we want to refresh connections. Actually we can use forceFetch but in this case we have to provide exact the same list of arguments for a query(because relay keeps uniq ids for each data in its store). So friends(first: 10) and friends(first:10, id: null) ids will be different. Now we found a way how we can do it we use a mutation. We just return viewer from a server mutation and we customize fatQuery in a client mutation. It works but it looks like a hack. Is there any way to do it correct?

**Comment by wincent** [comment]
I'm not aware of a canonical "official" way to do this. The mutation approach is a novel approach and like you say, a bit of a hack, as it sounds like you're not actually intending to really mutate anything at all.

Another way you could consider, depending on the complexity of the arguments that you are dealing with, is manually tracking the `first` and other arguments in state, and then using that to do your `forceFetch`, although it sounds like you have already tried this approach in some form.

When Relay 2 comes out, you will have more options here. Connection management is going to be more manual/explicit, so you will necessarily have more control over and awareness of what variables are being used. We also will have a low level handler API that will allow you to observe (and rewrite) incoming data related to a connection (any field really), and you could use that to do some tracking of your own.

In the meantime, you could consider asking on Stack Overflow too. We want to keep the GitHub issue tracker for bugs and PRs, and have questions on a dedicated forum that is purpose built fo questions and answers. If you do, post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs

Closing this in the meantime to keep the queue clear. But feel free to comment if you have further thoughts.
