### ISSUE TITLE
Question: Best places to learn more Relay

### ISSUE THREAD

**Issue by rterysen-openroad** [facebook/relay#1315]
Can you list some good place's for Relay examples and learning? Pluralsight had a good course but it was minimal.  I would like to learn best practices in handling slightly more challenging things.  Did Facebook put out any projects that show relay/graphql best practices in action that we can reference or books? I would like to see other approaches to problems and designs.

**Comment by wincent** [comment]
Thanks for your question!

I'm not sure if Stack Overflow is the best place for this kind of question (perhaps another Stack Exchange site is), but in general we want to keep the GitHub tracker for tracking bugs/fixes and feature development, and encourage people to post questions elsewhere.

In the meantime, here are some basic starting points:

- The [relay-examples](https://github.com/relayjs/relay-examples) repo provides a number of small apps showing how to get started.
- You can see the kinds of questions people are asking about Relay under [the relayjs tag](http://stackoverflow.com/questions/tagged/relayjs) on Stack Overflow.
- The Relay docs contain [a tutorial](https://facebook.github.io/relay/docs/tutorial.html) and some follow-up material, "[Thinking in GraphQL](https://facebook.github.io/relay/docs/thinking-in-graphql.html)" and "[Thinking in Relay](https://facebook.github.io/relay/docs/thinking-in-relay.html#content)", as well as some [video presentations](https://facebook.github.io/relay/docs/videos.html).
- [The awesome-graphql repo](https://github.com/chentsulin/awesome-graphql) has a bunch or Relay-related resources (as well as stuff related to the broader GraphQL ecosystem, obviously).

> Facebook put out any projects that show relay/graphql best practices in action that we can reference or books?

We haven't put out any projects as far as I know, but I've heard rumors of a book being published soon (not by us). I'm going to close this for now because it is not directly actionable, but if you do find anything useful please do comment here so that others might benefit from your discovery. Thanks once again for your question!
