### ISSUE TITLE
Issues with masking data and Forms

### ISSUE THREAD

**Issue by jquense** [facebook/relay#1326]
I just want to note a constant struggle I have with the way Relay masks/scopes data. It is very very frustrating to construct forms from smaller relay container input components. consider this example:

``` jsx
class UserForm extends React.Component {
  state = { user: null };

  onChange = (user) => {
    this.setState({ user })
  };

  render() {
    let currentUser = this.state.user;
    return (
      <div>
       {currentUser && currentUser.userName}
       <UserDropdown 
         users={this.props.users} 
         onChange={this.onChange} 
       />
    </div>)
  }
}

export default Relay.createContainer(UserForm, {
  fragments: {
    users: (variables) => Relay.QL`
      fragment on User @relay(plural: true) {
        userName
        ${UserDropdown.getFragment('users')}
      }
    `,
  },
});
```

 and **UserDropdown** 

``` jsx
function  UserDropdown({ users, ...props }) {
  return (
    <Dropdown 
      {...props} 
      items={users} 
      valueField="userId" 
      textField="name" 
    />
  )
}

export default Relay.createContainer(UserDropdown, {
  fragments: {
    users: (variables) => Relay.QL`
      fragment on User @relay(plural: true) {
        userId
        name
      }
    `,
  },
});
```

The crux of the example being that the parent `UserForm` requests a different field then it's child, hover the selected user being passed back up is scoped to `UserDropdown` for obvious reasons. This makes constructing a new object to be saved later _really_ frustrating. The above is only a simple case it gets much hairier as you add complexity or need/want to isolate form sections into their own components. I could manually "rescope" the user to the correct one by finding it in the `users` array in UserForm, but that can be costly and adds a ton of silly complexity. 

In these cases we've taken to awkwardly avoiding `createContainer` entirely and exporting fragments only, but that makes it hard to interop with actual relay containers, who constantly complain about the record they are given. The only other option is to jsut give up co-locating the queries with these components, which sounds ok in the above case but not in actual situations where the form is large, multi-stage, and made up of many layers of components.

cc @taion

**Comment by jardakotesovec** [comment]
I generally aim for keeping minimal state and everything else is derived in render method. Thats likely why I have not run into this issue..

So in this particular situation I would just pass `user.id` to `UserForm onChanged` method.

And in `UserForm render` method I would go for

```
const  currentUser = this.props.users.find(u => u.id === this.state.userId)
```

**Comment by jquense** [comment]
@jardakotesovec ya, I think falls into the "manually rescoping" which only sometimes is feasible, it also requires that parents query enough of the object to be able to do that. It's also not super helpful when you are trying to validate record creation,often just saving the id of an object is not enough.

**Comment by jardakotesovec** [comment]
@jquense I don't think about this as re-scoping but as keeping/passing minimal state and getting rest from relay store using relays collocated queries. Just following logic that component can display/work with data it asks for in fragment.

 So if UserForm needs more data fields about selected user than `id` I think it makes sense to describe it in fragment and get the user from users array. I don't expect that simple look ups using `find` would be noticeable in performance..  I use them all the time.. and never showed up during profiling nor felt as complex statements...

Just sharing my view on this. Its definitely interesting topic.

**Comment by josephsavona** [comment]
@jquense Thanks for filing this issue, this is an interesting use case. We'll keep it in mind and would appreciate your feedback about the API.

In the short-term, I agree with @jardakotesovec's suggestion. The parent component should be responsible for fetching the fields it needs to access on an object, and it can pass a callback to the child to allow the child to interact with the parent object. Something like:

```javascript
// Parent
render() {
  return <Child onSelect={() => this.updateItem(this.props.item)} />;
}
```

This way the child doesn't what fields the parent fetched and vice-versa.

**Comment by jquense** [comment]
I think generally callbacks work fine except in the cases of lists or more heavily nested records.

Its a good bit more work to have the Parent component take a record `id` and find the item in it's `users` lists when the child is already passing up the exact record you are looking for.

It may not be feasible but it seems like a better option would be for relay containers to expose a way to re-scope records. 
```
// Parent
render() {
  const { relay } = this.props;
  return <Child onSelect={(record) => this.updateItem(relay.scope(record))} />;
}
```

Tho that may require too much bookkeeping, (and some sense in which `item` knows it's own type)

**Comment by wincent** [comment]
Thanks for this discussion. As it refers to the old Relay APIs and we've just released Relay Modern I am going to close it out so that we can focus the issue tracker on current work. Please file any issues/questions that you may have related to the new APIs as new issues. Thanks once again!

**Comment by sorenhoyer** [comment]
I think this question is still very relevant in 2022. 

Ideally you'd want to use fragments all the way down to, and including, the form input components. However, I guess people generally stop passing down fragments to child components of a form to avoid the hassle of having to manually make a local copy each record (and linked records and modify the __id and refs ("rescoping") to avoid making unwanted changes to records outside the scope of the current form? I recently ran into an issue where I had to do this, not only for connections but connections inside nodes of a parent connections. That is when I gave up on trying to solve this with Relay since the commitLocalUpdate got way to complicated and long. 

It would be really useful to see an example or a snippet indicating how to deal with forms in Relay, other than "ejecting" from Relay by stop using masked fragments at that time. The idea is to use them all the way down, if I'm not mistaken?

@josephsavona - now 5 years later, with all the work that has been going on since 2017, how is Relay intended to be used for forms? Because some applications are very form-heavy and also forms can be rather complex, so it would be a shame to stop using fragments and masking when you have form input child components.

Even if your answer still hasn't changed it would still be nice to hear an official advice on this from the relay team, since it can be really time consuming and frustrating trying to handle this with Relay - especially if Relay was never intended for this use case :-)

**Comment by sibelius** [comment]
useFragment data as initialValues of Formik

let Formik control form fields, then submit the new values to a mutation

or try this one https://github.com/morrys/relay-forms

**Comment by sorenhoyer** [comment]
@sibelius I know you can easily do that. That is also how I've done it so far.

What I really would like to, however, is to use Relay to co-locate data dependencies down to the deepest nested form field child components instead of stop using fragments when you hit the parent form component.

I wouldn't recommend relay-forms.

**Comment by sibelius** [comment]
Can you useFragment in any form field? And pass the ref as props?
