### ISSUE TITLE
Relay+GraphQL vs Flux+Alt+Store+Action

### ISSUE THREAD

**Issue by spyalert01** [facebook/relay#133]
Hi, 
When we learn about store and action. We understand that we can make component listen to store. And one component can listen to multiple store. 
When one component is updated, the component that listen to the same store will be updated autoamatically because it subscribed to the same store.

I am wondering, how can we do the same for this in Relay?

**Comment by josephsavona** [comment]
Relay automatically sets up subscriptions so that [Container](http://facebook.github.io/relay/docs/guides-containers.html#content)s update whenever the data they are rendering changes - either due to a refetch or a mutation. Containers also implement an efficient `shouldComponentUpdate` that prevents re-rendering when data hasn't changed.

**Comment by spyalert01** [comment]
thanks. will take a look
