### ISSUE TITLE
Hot change `RelayQLTransformer` in `getBabelRelayPlugin`

### ISSUE THREAD

**Issue by nodkz** [facebook/relay#1345]
For proper server side hot reload needed ability to change graphql schema in the [transformer](https://github.com/facebook/relay/blob/master/scripts/babel-relay-plugin/src/getBabelRelayPlugin.js#L51).

I'm adding new fields to schema, json file automatically was regenerated by homemade webpack plugin. And now I can not found a proper way how to patch on fly `BabelRelayPlugin` with new schema  without restarting webpack.

**Comment by nodkz** [comment]
Right now I'm watching @wincent [talk about Relay 2](https://www.youtube.com/watch?v=OEfUBN9dAI8&feature=youtu.be) and think that `making all static` should have a flag. Wants developer make all static, or computable at runtime according to Hot Reload when modules updated. 

Maybe I'm something missing. But I'm worried about losing HMR, cause it's the best feature, that developers have now.

**Comment by josephsavona** [comment]
I have to think a bit more about the OP. But to your comment: HMR and static/dynamic queries are orthogonal. In either case if a child component's data requirements change (eg its fragment changes), then the nearest parent renderer that fetched data for it must refetch using the new query containing the new fragment. Otherwise you can reload the component, but it will likely be missing data. 

In a dynamic query architecture the query would be rebuilt at runtime, in a static architecture the query would be regenerated by the build step and then refetched at runtime. In *either* case, *something* must tell the runtime that the parent module must reload given that the child changed. 1:1 module reloads (file A changed, therefore reload only that module in the browser) are simply insufficient in general for this use case. 

So this isn't about dynamic can static, but rather about teaching HMR systems generally about interdependencies.

**Comment by nodkz** [comment]
> ...reload the component, but it will likely be missing data.

Crazy rabbit-hole for HMR.

@gaearon did you think about adding some hook for devs, that allows to fetch some data and put it to store before call `hot.module.accept()` in [RHL3](https://github.com/gaearon/react-hot-loader/tree/next)

**Comment by PawkaHub** [comment]
@nodkz Did you ever get anywhere with this? I'm running into the same issues as well myself and would love to be able to hot patch the schema stored in BabelRelayPlugin without restarting webpack, as that's the only thing holding me back from getting at least some basic semblance of automatic schema generation working.

**Comment by josephsavona** [comment]
@PawkaHub I would try composing the plugin: create a wrapper plugin that delegates to an instance of the Relay plugin, creating a new instance whenever the schema changes.

**Comment by PawkaHub** [comment]
That worked great @josephsavona! Thanks for the suggestion. I'm gonna do a bit more testing with it just to make sure there's no hidden kinks in usage and then I'll look into releasing it as an NPM module for people to make use of.

**Comment by josephsavona** [comment]
@PawkaHub Awesome! That's great to hear, looking forward to seeing that npm package :-)

**Comment by wincent** [comment]
(Spring cleaning.) Not sure if there is anything immediately actionable here, but I'm going through and cleaning out issues that haven't had any activity for a while, lack clear next steps and/or don't have anybody actively working on them.

Thanks to everybody who participated in the discussion.
