### ISSUE TITLE
Returning strange alias for connections via REQUIRED_CHILDREN after mutation

### ISSUE THREAD

**Issue by Rohit-cheddr** [facebook/relay#1354]
For some reason when I do a mutation and get a return value with REQUIRED_CHILDREN in getConfigs, connections are being returned with a strange alias: `_tierItems2EmfF3` where it should be `tierItems`.

When I make the same mutation through GraphiQL, the connection is returned properly.

I am not sure if this is some kind of configuration issue, but I have no idea what could be causing this.

**Comment by toxsick** [comment]
I have the same problem. I think it is related to the fact that relay adds connection parameters when the query is created (e.g. first:100). But how can we access the data properly when the mutation returns?

Help?!

**Comment by rodrigopr** [comment]
Also having the same problem.
Relay don't seem to handle field alias on REQUIRED_CHILDREN callback.
As a workaround, I'm using relay `generateRQLFieldAlias` internal method to get actual field name.

**Comment by davidstoker** [comment]
I've run into this as well. I'm executing a mutation directly using `Relay.GraphQLMutation` with a connection in the response. I'd like to use the response data in my `onSuccess` callback though the connection is coming back aliased in the response: `_pendingSessionst2Pdh` in my case instead of `pendingSessions`. 

In my instance, the connection parameters are fixed (first: 100) so I can use the known alias directly though this feels hacky. How are aliases really supposed to be handled?

**Comment by dpehrson** [comment]
I just hit this as well, for certain fields when I include them in a `REQUIRED_CHILDREN` fragment the fields are sent to the `onSuccess` handler with their aliased name.

**Comment by wincent** [comment]
Relay Modern is now out and no longer does auto-aliasing so further changes in respect to this issue are now unlikely. Closing this as such, but thanks for participating in the discussion!
