### ISSUE TITLE
NODE_DELETE mutation accepts only string for deletedIDFieldName, not an array (path) of strings

### ISSUE THREAD

**Issue by vangavroche** [facebook/relay#1361]
Looks like it doesn't work when the deletedIDFieldName is an array.

Given this config:

```
  getConfigs() {
    return [{
      type: 'NODE_DELETE',
      parentName: 'viewer',
      parentID: this.props.viewer.id,
      connectionName: 'todos',
      deletedIDFieldName: ['deletedTodo'],
    }];
  }
```

the ultimate query may be like:

```
mutation RemoveTodoMutation($input_0:RemoveTodoInput!) {
  removeTodo(input:$input_0) {
    clientMutationId,
    /// parent:
    viewer {
      ... // something defined by tracked children and fat query
    }
    /// node to delete
    deletedTodo {
       id
    }
  }
}
```

where the `deletedTodo { id }` is generated by [buildFragmentForDeletedConnectionNodeID  function of the RelayMutationQuery](https://github.com/facebook/relay/blob/master/src/mutation/RelayMutationQuery.js#L571)

When the response payload is returned, [writeRelayUpdatePayload](https://github.com/facebook/relay/blob/master/src/traversal/writeRelayUpdatePayload.js#L119) will try to delete the node, according to the deletedIDFieldName.

But the issues is, if the deletedIDFieldName is an array, these lines of code will not work correctly:

```
  const recordIDs = payload[config.deletedIDFieldName];
  if (!recordIDs) {
    // for some mutations, deletions don't always occur so if there's no field
    // in the payload, carry on
    return;
  }

  if (Array.isArray(recordIDs)) {
    recordIDs.forEach(id => {
      deleteRecord(writer, id);
    });
  } else {
    deleteRecord(writer, recordIDs);
  }
```

because the recordIDs here will be a JSON.

**Comment by wincent** [comment]
At the moment we expect a field name here, not an array path, by design.

Having said that, we added support for array paths for `RANGE_DELETE` mutations a while back. On the surface of it, I am not aware of any reason why we couldn't do the same for `NODE_DELETE` as well. Any interest in submitting a PR?

**Comment by vangavroche** [comment]
Yes, I think supporting an array path will be much more flexible.  PR is created.

**Comment by wincent** [comment]
The old mutations API is no longer being actively worked on or supported, and Relay Modern is now out, so I'm going to close this one in order to keep the issue tracker focused on the stuff that is currently being worked on. On the related PR, looks like the import failed, and it is now hopelessly stale. :-(
