### ISSUE TITLE
Possible optimization related to setVariables and Node

### ISSUE THREAD

**Issue by AndrewIngram** [facebook/relay#1370]
Let's say I'm building an app with users who can sell products. A simplified version of my GraphQL schema looks like this:

```
type Product implements Node {
  id: ID!
  // fields
}

// Connection definitions for ProductConnection

type User implements Node {
  id: ID!
  username: String!
  products: ProductConnection
}

type Viewer implements Node {
  id: ID!
  user(id: Int!): User
}
```

I'm rendering a page that displays a user and their products, so naturally I end up with a query like this:

```
{
  viewer {
    user(id: $userId) {
      username
      products(first: $count) {
        edges {
          node {
            id
          }
        }
      }
    }
  }
}
```

Let's assume that viewer, user and product pages are all relatively expensive to resolve (i.e. require backend service calls and take 10s or 100s of milliseconds). In reality, viewer is free, but i'm trying to avoid creating a more complex example just to illustrate the problem.

Now, if I use `setVariables` to change `$count` to something larger, Relay helpfully uses its knowledge of connections to only fetch the missing results rather than everything, this is great.

The problem is that the query for each new page is starts from viewer, which means to get an additional page of products, I have to re-resolve both viewers and users before I can even start loading the next page of products.

Given that User implements Node, it should be possible to generate a more optimal query that starts from the User node. Or more generally, for the part of the tree with variables that have changed, find the closest ancestor that implements Node.

This would also allow me to change the schema slightly (naughty) to get even better optimizations:

```
type Product implements Node {
  id: ID!
  // fields
}

// Connection definitions for ProductConnection

type UserRelationships implements Node {
  id: ID!
  products: ProductConnection
}

type User implements Node {
  id: ID!
  username: String!
  relationships: UserRelationships
}

type Viewer implements Node {
  id: ID!
  user(id: Int!): User
}
```

In this version, i've added an additional relationships type between User and Products, which implements Node but is essentially free to resolve (it's unmasked GlobalID would be the same as the User's, just a different type). This means i'd be able to get the next page of products without any unnecessary data-loading whatsoever.

Does this optimisation already exist (i.e have I somehow missed it?), or is there a reason it doesn't? And would implementing it still be possible given Relay 2's move to static queries?

**Comment by josephsavona** [comment]
> The problem is that the query for each new page is starts from viewer, which means to get an additional page of products, I have to re-resolve both viewers and users before I can even start loading the next page of products.

Can you clarify what you are describing here? Is this behavior that you are seeing in raw GraphQL? Or in Relay? 

Note that Relay already implements the optimization you described. When `serVariables` is called, Relay will attempt to refetch it using the nearest object with an id, rather than go all the way back to the query root. 

So in your example if User implements Node, then a `setVariables` call to increase the count would result in a query such as:

```
query Foo($id: ID) {
  node(id: $id) {
    products(after: <cursor>, first: <count>) { ... }
  }
}
```

More generally, 

```
viewer {
  field(id: $id) {
    ...
  }
}
```

Is an anti-pattern: the viewer field is unnecessary, since the object being requested can be identified by its id. Viewer makes sense only for data that is non-identifiable (no id) and that is contextual based on the person viewing the app.

**Comment by AndrewIngram** [comment]
I mean specifically with Relay (I'm asking it here for a reason). The optimisation I've described (and what you've confirmed) is what I expected to happen, but isn't what is actually happening.

Is the fact that I'm doing your anti-pattern related or is it an aside remark? Because my example is simplified and excludes other arguments, but the User type definitely implements Node. But I'm doing this way because Viewer is required for so many other things, that it didn't make sense to special case types with an arity of 1 or 0.

**Comment by AndrewIngram** [comment]
Okay, i've found the issue. Which is that I didn't have a separate component representing the entire connection, just one representing the array of edges. It seems that the described optimisation only works when the ancestor node is also at the root of the fragment.

To clarify, before I had something like this:

```
export default Relay.createContainer(UserPage, {
  initialVariables: {
    id: null,
    count: 32,
  },
  fragments: {
    viewer: () => Relay.QL`
      fragment on Viewer {
        user(id: $id) {
          products(first: $count) {
            edges {
              node {
                ${ProductList.getFragment('products')}
              }
            }
            pageInfo {
              hasNextPage
            }
          }
       }
      }
    `,
  },
});
```

Whilst moving to this fixed the issue:

```
export default Relay.createContainer(UserPage, {
  initialVariables: {
    id: null,
  },
  fragments: {
    viewer: () => Relay.QL`
      fragment on Viewer {
        user(id: $id) {
          ${UsersProducts.getFragment('user')}
        }
       }
      }
    `,
  },
});
```

(where `UserProducts` contains the full connection and `ProductList`)

**Comment by josephsavona** [comment]
Ah, yes that would explain it. Thanks for following up! `setVariables` starts from the fragments on the container where it was called, wraps that fragment in a query (just `node` If the object has an ID, otherwise with the path up to the nearest identifiable object), then does diffing/etc. So you have control over how much is refetched by choosing where to break the fragment boundary. 

About the viewer pattern: this was an aside, but it's relevant to the final solution. We've found that it's generally best to let the route/query specify what the "root" object to fetch is, and then have containers be agnostic about the root. If you put `viewer { user(id: $id) }` in the fragment, you can no longer use that container anywhere in a query that you have a User, you can only use it at the root. The component becomes far less reusable. If instead you do `node(id: $id)` in the route query, and then `fragment on User { userField}` in the container, then it's completely reusable - and you avoid this issue about refetching ;-)

**Comment by josephsavona** [comment]
@AndrewIngram Thanks again for investigating and following up here. I'm going to close this issue since you've resolved it, but we're happy to continue the discussion either here (comment and we can reopen) or on a new issue. 

Also note that one of the side-effects of static queries in Relay 2 is that it becomes much more obvious what query is being used to refetch data - since the developer writes the query! This should help to avoid issues such as this one.
