### ISSUE TITLE
How to connect Relay to a GraphQL server running on different machine?

### ISSUE THREAD

**Issue by hhashmi** [facebook/relay#1391]
I have a GraphQL server (express + mongodb). I want to connect react relay to my existing GraphQL server which is running on a different machine.

I tried to search for it but no luck. Can any one guide me though ?

**Comment by wincent** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

Questions like yours deserve a purpose-built Q&A forum. Would you like to post this question to Stack Overflow with the tag #relayjs? We'll be happy to answer there. Post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs
