### ISSUE TITLE
How to populate an AutoComplete with data from Relay?

### ISSUE THREAD

**Issue by tranduchieu** [facebook/relay#1398]
Im getting the problem related to `setVariables`like this case http://stackoverflow.com/questions/39292391/populating-an-autocomplete-with-data-from-relay-fails. It causes pagination, search, autocomplete failed. Many people is getting this bug & still don not have the answer.
I think it is really a **big problem** for Relay users with the recent version.
I hope that the whole community will join to give idea & solution for this problem.
Tks.

```
import React, { Component, PropTypes } from 'react';
import Relay from 'react-relay';

class Users extends Component {
  /* ... */

  handleSearchName = (text) => {
    console.log('handleSearchName');
    this.props.relay.setVarliables({
      name: text,
    }, (res) => {
      console.log(res);
    });
  }

  /* ... */
}


export default Relay.createContainer(Users, {
  initialVariables: {
    first: 5,
    name: null,
  },
  fragments: {
    viewer: () => Relay.QL`
      fragment on Viewer {
        id
        users(first: $first, name: $name) {
          edges {
            node {
              id
              name
            }
          }
        }
      }
    `,
  },
});
```

![screen shot 2016-09-28 at 10 21 54 am](https://cloud.githubusercontent.com/assets/1744522/18900370/dc8996d0-856a-11e6-8519-be7599c3773e.png)
![screen shot 2016-09-28 at 10 07 45 am](https://cloud.githubusercontent.com/assets/1744522/18900377/e60bad24-856a-11e6-8a1d-1b9214e12bd2.png)

**Comment by andyfenelon** [comment]
try it like this.
```
handleSearchName = (text) => {
  this.props.relay.setVariables({
    name: text
  });
}
```

**Comment by josephsavona** [comment]
Does @andyfen's suggestion help?

**Comment by wincent** [comment]
Thanks for the question, @tranduchieu. I'm going to optimistically close this on the assumption that @andyfen's suggestion was enough to get you unblocked.

For future reference, we'd encourage you to post questions like this to a purpose-built Q&A forum, such as Stack Overflow, where you are more likely to get a timely response (and where others are likely to benefit from the answer). You can use the tag #relayjs, and if you do post a question there related to this, please share the link here so that others can find it.

Thanks once again for bringing this up!
