### ISSUE TITLE
RelayQuerySubtractor on fragment references

### ISSUE THREAD

**Issue by devknoll** [facebook/relay#140]
While looking into #132, I realized that theoretically the batching behavior that I'm looking for _should_ already exist. Specifically, `RelayPendingQueryTracker` should prevent us from making another request for data that's already in-flight, i.e. it should subtract new queries from all existing queries.

However, I'm seeing the following being sent over the RelayNetworkLayer:

```
query DashboardQueries{viewer{id,..._0NaN}} fragment _0NaN on Viewer{name,id}
```

```
query DashboardQueries{viewer{id,..._0NaN}} fragment _0NaN on Viewer{name,id}
```

In this example, I am rendering two RootContainers that have the same Relay.Route on them. `_subtractPending` is definitely calling `subtractRelayQuery` on the pair of queries, but the result is strictly equal.

Is this intended behavior?

**Comment by josephsavona** [comment]
Subtraction is primarily focused on avoiding duplicate queries in the case that the query processing happens on the server (part of our internal server/preload modes that we are working to open-source). In this case, the fact that the identical queries aren't being subtracted is probably a bug.

We're continuing to work on supporting query batching in the OSS release, but subtraction is only part of this (and will probably be removed at some point b/c there are now simpler ways to achieve the same effect).

**Comment by devknoll** [comment]
Thanks Joseph.

> and will probably be removed at some point b/c there are now simpler ways to achieve the same effect

Can you expand on this when you get a chance?

**Comment by josephsavona** [comment]
Relay (internally) supports a "preload" mode in which the server begins processing queries while the client is downloading and initializing the application code. The idea is that by the time the client is ready to execute the app, the query results are already available (rather than having to wait until this point to even initiate a query). Subtraction allows Relay to detect when a query that the client would execute is the same as one for which the server has already fetched data - preventing the client from duplicating a request. Going forward, we'll likely replace subtraction with a simpler way of correlating the client queries & server responses.

Note that outside of this use case, we've found that most queries don't actually subtract out. The marginal benefit doesn't justify the complexity of an extra step.

**Comment by devknoll** [comment]
Interesting, thank you for the comments. It sounds like in the long term, just not issuing duplicate queries on the user side is the way to go :wink: 

> In this case, the fact that the identical queries aren't being subtracted is probably a bug

Do we want to label this a bug? Otherwise it can probably be closed.

**Comment by josephsavona** [comment]
@devknoll do you have a good repro case that you could share?

**Comment by devknoll** [comment]
@josephsavona Dead simple repro case here: https://github.com/devknoll/relay-starter-kit/tree/duplicate-queries

You can imagine a more sophisticated scenario where e.g. a Header queries for a Viewer's user for name, profile picture, and then some other component (e.g. a Newsfeed comment box) also needs the viewer profile picture. In such a case, the data would be requested twice.

**Comment by josephsavona** [comment]
That was easy ;-) - thanks!

**Comment by devknoll** [comment]
I'm going to close this out for now.

> we've found that most queries don't actually subtract out

This seems true and I only ran into this issue because I was doing something weird. Happy to reopen if necessary, but doesn't seem like a huge issue right now.
