### ISSUE TITLE
Recommiting a failed transaction throws error

### ISSUE THREAD

**Issue by mikberg** [facebook/relay#1402]
I'm trying to let users "retry" a mutation if it failed, e.g. if there was network issues. I'm following [this guide](http://mgiroux.me/2016/relays-apply-update-function/) to accomplish this.

However, when I call `transaction.recommit()`, an error is thrown from `RelayMutationQueue._get`: `RelayMutationQueue: '0' is not a valid pending transaction ID.`.

Is this expected? Is there another, documented, way of achieving this?

I'm creating the transaction in a component method:

``` js
const mutation = new CreateGroupMutation(input);
const transaction = Relay.Store.commitUpdate(
  mutation, { onFailure, onSuccess }
);

this.setState({ transaction });
```

Then I'm trying to recommit using this method:

``` js
  retry = () => {
    const { transaction } = this.state;
    if (transaction) {
      transaction.recommit();
    }
  }
```

**Comment by leebyron** [comment]
I'm sorry this issue has sat here for so long. In an attempt to clean up our issue queue we're closing some aging or unclear-action issues. Also, while this issue applies to Relay Classic, our team is trying to focus on Relay Modern going forward.

If this issue is still important to you, please feel free to reopen it with an update.
