### ISSUE TITLE
Nested create Mutation

### ISSUE THREAD

**Issue by timsuchanek** [facebook/relay#1407]
Hi, I have this nested create mutation with my graphql backend:

``` graphql
mutation {
  createPost(input: {
    imageUrl: "http://lorempixel.com/400/400"
    description: "hello"
    clientMutationId: "asd"
    extra: {
      text: "extra text"
    }
  }) {
    edge {
      node {
        id
        description
        imageUrl
        extra {
          text
        }
      }
    }
  }
}
```

Each post has one `Extra` model, that just contains a `text`.
Now my question:
Does relay update the local representation of model `B` properly if I create `B` nested in `A` in one create mutation?

Thanks!

**Comment by wincent** [comment]
Thanks for the question, @timsuchanek!

This seems like the sort of thing that you could confirm by testing. Without running it myself, I believe the answer is "probably"; it may depend on whether the object at `extra` has an `id` and whether it is already in the store. If not, it's possible that you could use [`REQUIRED_CHILDREN`](https://facebook.github.io/relay/docs/guides-mutations.html#required-children) to force an arbitrary set of fields to be fetched, although you would be responsible for doing something with the data in the mutation callback.

However, one thing to bear in mind is that the former Relay mutation API is now considered "legacy". We have a new, static mutation API (`Relay.GraphQLMutation`) that you can use to force fetching of exactly the data you require for a given mutation without any of the magic and inference of fat and tracked queries. Additionally, we're rolling out an even newer API built on top of a new core (see recent work on the `master` branch, and further pieces that we'll be merging in over the coming weeks/months); all of this is static too, so moving to `Relay.GraphQLMutation` right now is a worthwhile incremental step.

Going to close this for now. Please comment again if you have anything further to add. For questions, we'd also encourage you to use a purpose-built Q&A forum like Stack Overflow, and use the tag #relayjs? You're morel likely to get a timely response, and others are more likely to find it there too. If you do, post a link to your Stack Overflow question here, so that others can benefit from it if they stumble across this.
