### ISSUE TITLE
Bulk actions

### ISSUE THREAD

**Issue by birge** [facebook/relay#1413]
Is there a way to apply ranged add to array of nodes coming from the server?

An example would be a todo app with a few filters: Mine, Unassigned, Done. I want to allow the user to select multiple conversations and assign them or mark them as done or some other bulk action. With a mutation I can send the array of ids and the action and do the proper task there but I have no idea how to deal with the return nodes. Ideally the server would return an array of nodes and I could run the getConfigs on each individual node. Is there something already in place to deal with bulk actions? I know you can RANGE_DELETE/NODE_DELETE with multiple IDs but I need to remove them from one list and add them to another so I would need to use RANGE_ADD and apply it to each node. I would greatly appreciate any help.

**Comment by wincent** [comment]
Thanks for your question, and sorry that it took us a while to respond to it! I think your best bet here may be just to refetch the entire range in response to a bulk operation like this. You can use `'refetch'` as a `rangeBehavior`, although this isn't explicitly called out [in the docs](https://facebook.github.io/relay/docs/guides-mutations.html) (the full list of possible mutator constants can be found [here](https://github.com/facebook/relay/blob/81f8cf92d240cb1cd6fd7cc2263a51c58b2b5a19/src/legacy/mutation/GraphQLMutatorConstants.js#L15-L19)). [This article](http://mgiroux.me/2016/the-mysterious-relay-range-behaviours/) may also prove helpful if you need more flexibility in handling range mutations.

For future reference, I'd encourage you to use a purpose-built Q&A forum like Stack Overflow for questions like this (as we want to keep the GitHub tracker a high-signal place for tracking bugs and features). Use the tag #relayjs and post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs
