### ISSUE TITLE
Add ability to track upload progress of mutations

### ISSUE THREAD

**Issue by gucki** [facebook/relay#1417]
Afaik it's not possible to track the "upload progress" of mutations. This is a show stopper for using mutations for file uploads and support should be added. I also posted a question on stackoverflow: http://stackoverflow.com/questions/40103779/how-to-subscribe-to-progress-event-of-relay-graphql-mutation

**Comment by sjchmiela** [comment]
It's fairly easy to implement a `sendMutation` method of a network layer with `XMLHttpRequest` that would report back the progress, but I can't find a way to forward the progress back to the observer, it seems that `RelayMutationRequest` abstracts the mutation away and you don't have access to the original mutation object (into which observer could inject custom methods).

Any ideas? 💡

**Comment by wincent** [comment]
The old mutations API is no longer being actively worked on or supported, and Relay Modern is now out, so I'm going to close this one in order to keep the issue tracker focused on the stuff that is currently being worked on. If you'd like to explore this question in the context of Relay Modern, please file a new issue for that. Thanks!
