### ISSUE TITLE
Add ability to silence warnings displayed when re-injecting network layer

### ISSUE THREAD

**Issue by sedubois** [facebook/relay#1429]
As discussed [here](https://github.com/facebook/relay/issues/1122#issuecomment-256062288), I believe there is a valid use case for being able to update the network layer (with `Relay.injectNetworkLayer`) without displaying a confusing warning in the console. For example, during a user sign-in flow.

Besides, the warning is actually displayed as an error, not a warning, in the Javascript console.

**Comment by hadfieldn** [comment]
As workaround, I call this prior to calling injectNetworkLayer(): 
```js
clearNetworkLayer() {
    Relay.Store._storeData.getNetworkLayer()._implementation = null;
  }
```

I haven't noticed any issues with it so far, but all I'm doing with the new layer is changing the header and token used for authentication.

**Comment by leebyron** [comment]
I'm sorry this issue has sat here for so long. In an attempt to clean up our issue queue we're closing some aging or unclear-action issues. Also, while this issue applies to Relay Classic, our team is trying to focus on Relay Modern going forward.

If this issue is still important to you, please feel free to reopen it with an update.
