### ISSUE TITLE
Networklayer issues

### ISSUE THREAD

**Issue by proProbe** [facebook/relay#1437]
Hello everyone.

Im currently using relay with react-native and have come to see some weird problems with the networklayer. It usually happens when the app is in the background and then started again. Im not quite sure where the problem originates from but seems to indicate that the networklayer doesnt exist even though it has been injected and used. Should also notice that this only happens on `ANDROID`.

The error is shown as following (Sorry for the wall of text): 
`Fatal Exception: com.facebook.react.common.JavascriptException: RelayNetworkLayer: Use `RelayEnvironment.injectNetworkLayer` to configure a network layer., stack:
_getImplementation@869:1960
supports@869:1809
a@874:185
<unknown>@874:1133
<unknown>@886:599
<unknown>@886:634
_invokeWithinScopedQueue@886:1052
<unknown>@886:920
_scheduleIfNecessary@886:1312
enqueue@886:686
E@874:925
run@874:4470
primeCache@695:1167
_runQueries@926:1341
componentDidMount@926:800
notifyAll@132:486
close@222:281
closeAll@138:1167
perform@138:615
perform@138:528
perform@131:1858
B@131:2030
closeAll@138:1167
perform@138:615
batchedUpdates@216:481
s@131:1064
u@223:69
enqueueSetState@223:1050
setState@28:347
value@601:1674
callback@629:3081
<unknown>@585:3881
<unknown>@630:696
<unknown>@65:562
callTimer@60:785
callTimers@60:1203
value@58:2827
<unknown>@58:1062
d@58:130
value@58:1034`

Some possible causes could be that we use `code-push` to push some updates to the user. The codepush replaces the js-files on the app itself and might perhaps cause errors with the networklayer. This is just a speculation and might not at all be the root of the problem. Anyways, is it possible to see where the problem stems from and solve this?

**Comment by proProbe** [comment]
After more discussions will fellow coders, it might be something with that the app somehow gets destroyed when laying in the background. Firing it up again has sometimes lead to this crash that you see above. Im still not sure how to solve this though and would happily discuss this with someone

**Comment by wincent** [comment]
Thanks for your question! Sorry for taking so long to respond. I think your hunch that code-pushing may be involved is worth following up on, but I'm basing that on intuition alone.

This isn't something we've seen here in our React Native apps. I don't think there's anything clear and actionable for us to do here, so I would suggest posting on a purpose-built Q&A forum like Stack Overflow. Would you like to post this question there with the tags #relayjs and/or #react-native? Feel free to link back here so that we don't lose track of it. In the meantime I am going to close this one out.
