### ISSUE TITLE
pendingVariables always null after calling setVariables

### ISSUE THREAD

**Issue by ssbeefeater** [facebook/relay#1450]
When i try to set a variable, the component updates only after fetch is complete. Here is a sample code.

    class RelayExample extends React.Component {
      setVars() {
        this.props.relay.setVariables({id: '2'});
      };
      render() {
        console.log(this.props.relay.pendingVariables);
        return (
          <div>
            <button onClick={this.setVars.bind(this)}>set variable</button>
          </div>
        );
      }
    }
    
    RelayExample = Relay.createContainer(RelayExample, {
      initialVariables: {
        id: '1'
      },
      fragments: {
        userStore: ()=> {
          return Relay.QL`
          fragment on userStore {
             user(id:$id){
              email
             }
          }
          `;
        }
      }
    });
    
    ReactDOM.render(
      <Relay.RootContainer Component={RelayExample} route={new TestQuery()}/>,
        document.getElementById('app')
    );
When i press the button i get this result in console:
[![enter image description here][1]][1]

Even if i use forceUpdate right after the setVariables function, i get similar result.

    setVars() {
            this.props.relay.setVariables({id: '2'});
            this.forceUpdate();
    };

[![enter image description here][2]][2]

See also in [StackOverflow](http://stackoverflow.com/questions/40717117/react-relay-pendingvariables-always-null-after-setvariables)

  [1]: https://i.stack.imgur.com/2xJJl.png
  [2]: https://i.stack.imgur.com/3Ml4T.png

**Comment by unirey** [comment]
> When i try to set a variable, the component updates only after fetch is complete.

This is because of RootContainer's [default behavior](https://github.com/facebook/relay/blob/master/src/container/RelayRootContainer.js#L80-L83). However, Im not entirely sure about [`pendingVariables`](https://github.com/facebook/relay/blob/master/src/container/RelayContainer.js#L290-L320). 

This is probably because `render` is only called when component updates but thanks to RootContainer's default behavior it only updates when you have the new data but `pendingVariables` is null by that time.


For example, this works:

```jsx
this.props.relay.setVariables({
    id: '2'
}, ({ ready, done, error, aborted, events }) => {

    // {id: "2"}
    console.log(this.props.relay.pendingVariables)
})
```

**Comment by unirey** [comment]
> When i try to set a variable, the component updates only after fetch is complete.

This is because of RootContainer's [default behavior](https://github.com/facebook/relay/blob/master/src/container/RelayRootContainer.js#L80-L83). However, Im not entirely sure about [`pendingVariables`](https://github.com/facebook/relay/blob/master/src/container/RelayContainer.js#L290-L320). 

Hypothesis: RootContainer's default behavior prevents React component `render()` until it has the new data but `pendingVariables` is null by that time. You have to change the default behavior to make this work.


For example, this works:

```jsx
this.props.relay.setVariables({
    id: '2'
}, ({ ready, done, error, aborted, events }) => {

    // {id: "2"}
    console.log(this.props.relay.pendingVariables)
})
```

**Comment by unirey** [comment]
> When i try to set a variable, the component updates only after fetch is complete.

This is because of RootContainer's [default behavior](https://github.com/facebook/relay/blob/master/src/container/RelayRootContainer.js#L80-L83). However, Im not entirely sure about [`pendingVariables`](https://github.com/facebook/relay/blob/master/src/container/RelayContainer.js#L290-L320). 

My theory: RootContainer's default behavior prevents React component `render()` until it has the new data but `pendingVariables` is null by that time because fetch is complete. Change the default behavior to make this work.


For example, this works:

```jsx
this.props.relay.setVariables({
    id: '2'
}, ({ ready, done, error, aborted, events }) => {

    // {id: "2"}
    console.log(this.props.relay.pendingVariables)
})
```

**Comment by ssbeefeater** [comment]
@unirey  As i can understand, according to [this](https://facebook.github.io/relay/docs/api-reference-relay-container.html#pendingvariables) example after a new variable is set, the component must update and the pendingVariables must be fulfilled so you can set a loading state or something. By the way, your example still gives me null.

**Comment by unirey** [comment]
@ssbeefeater Interesting.. I used to have the same problem with `null` but it works now and I have no idea why. However, it worked as shown in my example. I presume request payload and response are correct?

**Comment by ssbeefeater** [comment]
@unirey Yes everything is fine except that. I cant understand what is wrong

**Comment by josephsavona** [comment]
Thanks for reporting this. I suspect that this has to do with the readyState callback being called in a way that isn't perfectly in sync with React, such that props hasn't updated yet. 

Can you work around this? The pendingVariables should be correct whenever render is called. Similarly, within the readyState callback the pending variables are known (theyre whatever you passed to setVariables).

**Comment by yachaka** [comment]
@josephsavona I have the same problem here. `pendingVariables` are never set for me. I'm using relay 0.9.3 and developing on react-native 0.37.

**Comment by mathewsp79** [comment]
Same here for me..its always null

**Comment by mathewsp79** [comment]
i tried various places to console.log..its never populated. i use ver 0.9.2

**Comment by yachaka** [comment]
For some reason, it is now working as expected for me, and I don't remember making changes to this part of the code.

**Comment by kostasmanionis** [comment]
Having the same issue, using `react-relay@0.10.0` & `react@15.4.1` 😿

**Comment by wincent** [comment]
`setVariables` is part of the Relay Classic API, and no further work is being targeted for that now that Relay Modern is out. As such, closing this to keep the issue tracker clean and focused on current work. Thanks for the discussion though!
