### ISSUE TITLE
Listening to any change on the Store

### ISSUE THREAD

**Issue by yachaka** [facebook/relay#1458]
Hi there,

I'm currently building an app on React-Native using Relay. Everything works really great, Relay is a fantastic framework.
I want now to serialize and save the Store data any time it changes, so if the user quits the application and comes back, I can restore the data already fetched and provide a nice offline mode experience.

Where can I listen for any data change on the Store ? I've been looking at `this._changeEmitter` inside `RelayEnvironment`, but it seems like you can only listen to specific records IDs, whereas I want to be notified when any part of the Store changes.

**Comment by leebyron** [comment]
I'm sorry this issue has sat here for so long. In an attempt to clean up our issue queue we're closing some aging or unclear-action issues.

If this is something you'd like to see happen, then we'd be happy to review a pull request.

If this issue is still important to you, please feel free to reopen it with an update.
