### ISSUE TITLE
Fragment isn't used to fetch fields if list is empty initially and then It is populated via mutation

### ISSUE THREAD

**Issue by oguzbilgic** [facebook/relay#1475]
**Edited**

`User` component's fragment is similar to this:

```js
user: () => Relay.QL`
  fragment on User {
    name
    items {
      id
      ${Item.getFragment('item')
    }
    ${AddItemMutation.getFragment('user')}
  }
`
```

`User` component's render function is similar to this:

```js
<div>
  {this.props.user.name}

  {this.props.user.items.map(item =>
    <Item key={item.id} item={item} />
  )}
</div>

```

And `Item` component has a fragment such as this
```js
item: () => Relay.QL`
  fragment on Item {
      id
      name
      createdAt
    }
  }
`
```

`AddItemMutation` similar to this:

```js
  getFatQuery() {
    return Relay.QL`
      fragment on AddItemPayload {
        user { items }
      }
    `;
  }

  getConfigs() {
    return [{
      type: 'FIELDS_CHANGE',
      fieldIDs: {
        user: this.props.user.id
      }
    }];
  }
}

AddItemMutation.fragments = {
  user: () => Relay.QL`
    fragment on User {
      id
    }
  `
};
```

Problem exists when user initially has no items. When the first item is added through this mutation, relay doesn't request the additional fields required by the `Item`. However if user already has items, and when another item is added through the mutation, relay successfully fetches the aditional fields required by the `Item`

**Comment by leebyron** [comment]
I'm sorry this issue has sat here for so long. In an attempt to clean up our issue queue we're closing some aging or unclear-action issues. Also, while this issue applies to Relay Classic, our team is trying to focus on Relay Modern going forward.

I believe this issue is much improved with Relay Modern.

If this issue is still important to you, please feel free to reopen it with an update.
