### ISSUE TITLE
Schedule a Query differently if it can be resolved from cache or not

### ISSUE THREAD

**Issue by yachaka** [facebook/relay#1479]
Hello,

For context, I'm currently developing  an application on React-Native using Relay.
I've been taking care of not disrupting user active animations to give a smooth feeling across the application ; and I've been naturally looking at `Relay.injectTaskScheduler`, as it's mentioned in the documentation.

However, I've been disabling it because its behavior would not match what I've been looking for.
I'm trying to have this behavior :
1. Push transition to page
2. If data is available in the cache, then render the view with cache data - because it's fast and that way user won't see a loader.
Else, display the loading placeholder and display data when available but only after animation finished - to prevent dropping frame.

The problem is : if you inject react-native `InteractionManager.runAfterInteractions` task scheduler, the behavior will be that it **always** displays a loader ; because it waits for the interaction to finish before checking the cache.

If you don't inject it, then you will have a nice user experience - when the data is available in the cache (second visit of the screen for example, or offline mode), it will resolve fast and synchronously, allowing the user to view the page with data animating. But if the data isn't available, it will display a loading placeholder, and sometimes if the data batch resolves mid-transition, then the animation will drop frame - because it is trying to render the view with the newly received data.

Here is 2 mp4s illustrating what I've been describing : 
First, the behavior with the injected task scheduler :
[With task scheduler](http://dc621.4shared.com/img/IcpjxdY-ba/821afb20/dlink__2Fdownload_2FIcpjxdY-ba_3Fsbsr_3D3401b472898f614a26effbe7fb87babd991_26lgfp_3D1000_26dsid_3Dhljsk0.62d4cb7349a4a579e2805a6f4ae15e41/preview.mp4)
As you can see, it is very annoying as on every page load, the loading placeholder is displayed even when the data is cached.

[Without task scheduler](http://dc621.4shared.com/img/MCHD_l3iba/96f22372/dlink__2Fdownload_2FMCHD_5Fl3iba_3Fsbsr_3D8e1bb88ba8d33976c2be6ef6115b7626991_26lgfp_3D1000_26dsid_3Dhljsk0.3db6d58e4c93da48ddaeddc484b94ed1/preview.mp4)
This is much better. However, sometimes on the first load, the data is resolved mid-transition and the transition stutters and drop frames.

It could be nice that we decide whether a task is resolved or not depending on what is it. If it is to read from cache, I can do it right now because it might end in an improved user experience, if it is to merge data received over the network into store, I can wait until end of transition.

IDEA: Maybe we could receive in the task scheduler, on top of the `task` argument, a `priority` argument which would give the priority of the task ? This could even match the [ReactPriorityLevels](https://github.com/facebook/react/blob/master/src/renderers/shared/fiber/ReactPriorityLevel.js) done for `react-fiber`. The goal of `react-fiber` pretty much join this issue, so it does make sense.

**Comment by josephsavona** [comment]
@yachaka Thanks for asking about this. The current behavior is intentional, though its certainly something we can reconsider in the future if the constraints of the system change. In current Relay answering the question "can query X be fulfilled from cache" can be an expensive enough operation that it may interrupt animations itself (depending on the complexity of the query and how many cache objects have to be looked at). Further, simultaneously rendering a complex view and animating isn't always ideal. This led us to implement the current behavior where the render is always managed by the injected scheduler (`InteractionManager.runAfterInteractions` was added in part to serve this use-case). 

In future versions of Relay core we may be able to relax this constraint so this is something we should keep discussing. As a workaround, you might try injecting a custom scheduler that only waits for interactions to complete in certain cases (terrible idea but might work: if a task resolves early enough within an animation run it immediately).

**Comment by leebyron** [comment]
I'm sorry this issue has sat here for so long. In an attempt to clean up our issue queue we're closing some aging or unclear-action issues. Also, while this issue applies to Relay Classic, our team is trying to focus on Relay Modern going forward.

I believe in Relay Modern the situation is much improved as we support Network implementations that return synchronously, in the case of being fulfilled from cache.

If this is something you'd like to see happen, then we'd be happy to review a pull request.

If this issue is still important to you, please feel free to reopen it with an update.
