### ISSUE TITLE
[Question] Using defaultProps w/ react-relay

### ISSUE THREAD

**Issue by brandonmp** [facebook/relay#1492]
In React, Is there a way to use `defaultProps` to guard against `null` values passed down from `Relay.createContainer()` (ie, `nulls` originating from the `gql` query)?

AFAIK `defaultProps` only fires when an `undefined` is passed, so I was thinking of somehow trying to shortstop props b/t the `container` and the `component`, but it isn't immediately obvious to me if that's the right path here.

**Comment by wincent** [comment]
Thanks for your question! We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track bugs and feature requests, so I am going to suggest that you post this on a purpose-built Q&A forum like Stack Overflow. You could use the tag #relayjs and/or #reactjs? If you do that, please post a link to your Stack Overflow question here, to so that we don't lose track of it.

Briefly, however, I don't  think there's any non-hacky way to do this. In the new Relay core and APIs which are rolling out to `master`, we have schema-directed Flow type generation that you'll be able to use to ensure your components are adequately dealing with potentially `null` properties in a type-safe manner, but it will still be up to you to write the code — or come up with an abstraction — that allows you to set up default values conveniently. Another option to consider is making the types non-nullable and having the server be responsible for returning defaults, but whether or not that makes sense probably depends on your application domain.
