### ISSUE TITLE
How to reset all variables calling `setVariables`

### ISSUE THREAD

**Issue by alfonsoperez** [facebook/relay#1493]
This may very well be an userland issue, but in any case it's not clear to me as per the documentation how to reset all currently set variables to their `initialVariables`, for example I have in a form submit handler something like this:

```
onSubmit = (values) => {
  props.relay.setVariables(nullifyValues(values));
}
```

And when `values` is `{}`, `props.relay.variables` don't seem to change. Is there an easy way to reset all variables?.

Thanks

**Comment by amkoehler** [comment]
`setVariables` expects only the variables you want to be changed, so in this case you will need to pass it an object containing all of your existing variables in `this.props.relay.variables` set to what their initial state should be (e.g. null or undefined for a string, false for boolean, `{}` for objects and `[]` for arrays). 

To avoid this, I would suggest refactoring to put all of these variables that need resetting inside of its own object. That way you can reset it as one variable instead of several, and you have more flexibility when adding variables later.

**Comment by alfonsoperez** [comment]
Thanks for the clarification.
