### ISSUE TITLE
Documenting best practice for (multi-)selection

### ISSUE THREAD

**Issue by jamiehodge** [facebook/relay#1496]
I am interested in documenting best practice around the fetching of single objects in a typical search -> select scenario.

Assuming a query: `{ viewer { account { users(name: "...") } } }`

The (browser) user searches and selects a user, adding it to the URL. This is repeated multiple times. Now we have a URL with n user UIDs.

`/path/to/app?userId=abc123&userId=456def...`

The UIDs are merged into the relay params, using react-router-relay's prepareParams function, making them available to further down the component chain.

`{userId=['abc123', '456def']}`

The UIDs are mapped over, producing n queries or fragments using the node interface or a field to fetch the specific user.

```js
user: () => Relay.QL`query user { node(id: $userId) }`
```
or
```js
user: () => Relay.QL`fragment on Account { user(id:$userId) } }`
```

There are number of open questions in this scenario: 

1. Does one use the node field or the, in this case, Account field to fetch the individual selected users? 
2. If it is the node field, does one need a separate query or can one somehow use fragments? 
3. If a separate query is necessary, how does one avoid query name collisions? 
4. Is using a separate Renderer, deferring the query, a best practice?
5. Are there specific caching tradeoffs to be aware of?

Since this is such a common pattern, it would be great to have it clarified and documented.

**Comment by josephsavona** [comment]
# Case 1: List -> Detail View (simplified version of the above)

The use-case is an app with a list view, and clicking an item in the list navigates to a detail view for that item. A common approach is for the list view to fetch its items via a connection field, where each edge has a `node` whose type implements the `Node` interface (i.e. each node has a globally unique `id` and can be refetched with `query { node(id: $id) }`). The detail view would then use a `node(id: ...)` query to fetch more information about the selected node.

# Case 2: List -> Multi-item Detail View (OP)

This is similar to the above, except that the user selects multiple items such that there are a list of ids to fetch on the detail view. The canonical approach is to use a `nodes(ids: [id1, id2, ...idn])` query for the detail view to fetch all the information for all of the items in a single query. 

The `nodes` field should accept a single argument `ids: [ID!]!`. It should return one result per input id, in an order matching the input arguments. For ids that do not exist or cannot be fetched, it should return null in order to ensure the ordering requirement.

--

@jamiehodge I think this use-case is probably best addressed via a `nodes` query on the second screen, since it avoid needing multiple renderers.

**Comment by jamiehodge** [comment]
This is very helpful. Thank you.

Given Case 2. If the view is a combo box, where the multi-item detail view is a sibling of the list view, what does the fragment look like and does one need a new Renderer to "break out" of the Account type and query the top-level nodes field?

**Comment by jamiehodge** [comment]
Is relay's cache aware of the overlaps between the node(s) in the account users connection and nodes being fetched via `nodes`? i.e. does it look at the individual items with plural queries?

**Comment by jamiehodge** [comment]
More generally, I think it would be a large win for Relay if these and other common patterns were included as code examples in the documentation.

**Comment by hkjorgensen** [comment]
Thanks for the question and answers.

@josephsavona where does the `nodes` interface come from? I can't find it in the docs: https://facebook.github.io/relay/docs/graphql-relay-specification.html

**Comment by josephsavona** [comment]
@hkjorgensen The `nodes` field isn't documented (yet), we should add it.

**Comment by josephsavona** [comment]
@hkjorgensen here's an example of a `nodes` query and the expected server response: https://github.com/facebook/relay/blob/e524c7e91339ba49ef1c528b58d6353388423872/src/interface/__tests__/RelayOSSNodeInterface-test.js#L172-L188

**Comment by jsdnxx** [comment]
> The nodes field isn't documented (yet) but is stable

@josephsavona will current relay try to use this? I.e., if I have a graphql server that supports `node` but not `nodes`, will this potentially break a relay client?

**Comment by josephsavona** [comment]
Relay never creates `nodes` queries, but it supports them if you use them.

**Comment by jamiehodge** [comment]
I think good next steps would be to:
- Add a nodesField to the node helper in graphql-relay-js
- Add a page or two of documentation outlining these two solutions

I'll see if I can take the former.

**Comment by wincent** [comment]
Closing this one due to inactivity, and because we want to clean out the old stuff from the issue tracker now that Relay Modern is out, so that we can keep it focused on current work.
