### ISSUE TITLE
Does relay update containers automatically on change in data in store?

### ISSUE THREAD

**Issue by nikhildaga** [facebook/relay#1497]
If I update relay store using
```
const query = Relay.createQuery(Relay.QL`query Foo { ... }`, {var: 'value'})
RelayStore.getStoreData().handleQueryPayload(query, payload)

```
will it update the relevant relay containers (where the data has changed) automatically?

Thank you!

**Comment by josephsavona** [comment]
Yes. Note that the shape of the response is expected to match what the server would have returned for that query - including having fields be aliased using the aliases Relay generates. 

What is your use case?

**Comment by nikhildaga** [comment]
Thank you Joseph!

The use case is Subscriptions. 

The current recommended library for subscriptions removes subscriptions on component unmount and therefore, requires forceFetch to be true, which is very inefficient.
https://github.com/edvinerikson/relay-subscriptions/pull/19/files

If we can subscribe to different types of updates and update store from a single place and be assured that the containers will automatically update, it will a big thing!

**Comment by josephsavona** [comment]
> If we can subscribe to different types of updates and update store from a single place and be assured that the containers will automatically update, it will a big thing!

Yup, that's how Relay works. Queries, mutations, and subscriptions all publish new data into the store. Whenever a publish happens, all observers of the store are notified. Containers conceptually observe the results of their fragments, so they are re-rendered whenever data changes in the store that affects their result (regardless of the source of that data). 

> The current recommended library for subscriptions removes subscriptions on component unmount and therefore, requires forceFetch to be true, which is very inefficient.

This seems tangential to the above question. How to combine diffing, force-fetching, and subscriptions is application specific. Ideally any subscriptions API would allow a product to choose between several options. An initial forceFetch followed by holding a subscription until unmount seems like a reasonable approach, since it keeps the number of subscriptions proportional to the data being actively viewed. On the other hand, if the maximum number of subscriptions is known to not grow too large, it maybe be desirable to just subscribe to all updates you may ever care about, and then not use forceFetch. @edvinerikson, @taion - does `relay-subscriptions` support both approaches?

**Comment by josephsavona** [comment]
Closing since the initial question is answered, but feel free to continue the discussion!

**Comment by edvinerikson** [comment]
It is definitely possible to skip the React API and use the `subscribe` method directly in relay-subscriptions. It's basically `relayEnvironment.subscribe(new Subscription())`.

Another approach which probably is better is to use the React API and mount a component that never unmounts which holds all the subscriptions.

The example app in the repo is built like @josephsavona mentioned, it only listen on data that is currently visible on the page however it doesn't have to be like that. it's up to the developer to make that decision.

**Comment by nikhildaga** [comment]
Thanks @edvinerikson for the awesome relay-subscriptions library.   I am using both the subscribe api and containers api.

I have forked and made some modifications to relay-subscriptions createContainer :  https://github.com/reachifyio/relay-subscriptions/blob/master/src/createContainer.js#L53-L97
It isn't perfect but works for our use case.


```mount a component that never unmounts which holds all the subscriptions.```

I thought about it too but the problem is that all the data which should be subscribed too isn't known at one place. Its scattered among different relay containers.

**Comment by edvinerikson** [comment]
> I thought about it too but the problem is that all the data which should be subscribed too isn't known at one place. Its scattered among different relay containers.

is it variables that isn't know or is it the fragments? You can share the fragments in the subscription.

Looking at your changes it seems they introduce a memory-leak since every time you mount the component it will create a new subscription but you will never remove it once the component unmounts. If you don't have a smart network layer which can de-dupe them you will probably face memory issues after a while.

I still think you can solve this with the current container provided by relay-subscriptions without the need of forking. You just have to be smart about where you render the component. e.g. in the example we initiate the subscription in each `TodoItem` but instead you could move the subscription to the parent component. Doing that in the example app will remove the need for `forceFetch`

**Comment by nikhildaga** [comment]
@edvinerikson :  Its the variables that aren't known.. Yes, we are removing duplicate requests in network layer. 

But, I agree with you, that ultimately there should be a single place from where we subscribe only once and update the store.  As Joseph mentioned, its possible, will give it a try.
