### ISSUE TITLE
How to update relay store with data which can change later?

### ISSUE THREAD

**Issue by jinxac** [facebook/relay#1532]
I was working on an e-commerce relay+react-native application. But there are few products for which order status is confirmed after confirmation with the sellers. 

So the first time i load the app, the order history contains past orders. Now if I place the order with relay mutation, the order status for this is processing. Now once the seller confirms this item I change the order status to confirmed in the backend, but since it is cached in the relay it keeps on showing order status as processing only.

Now, my question here is how do I update the local relay store with the new order status? Can I updated this as soon as the status is changed in backend? I could not find anything related to this in relay docs.

**P.S:**

1.  If i close app and start again it works fine as relay query is called again, but I minimise the app and launch the app it shows cached data as expected.
2. The platform is **IOS**
3. Backend is based on graphene and I run background jobs to update the order status by calling the APIS provided by seller.

**Comment by wincent** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

Questions like yours deserve a purpose-built Q&A forum. Would you like to post this question to Stack Overflow with the tag #relayjs? Post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs

In brief, however, the best tool for this situation is likely to use `forceFetch` ([top SO answer for "force fetch" search](https://stackoverflow.com/questions/37464509/react-relay-always-force-fetch-route-or-relaycontainer)).
