### ISSUE TITLE
Can we get an explanation and examples of GraphQLMutation's optimistic queries and responses?

### ISSUE THREAD

**Issue by lukecwilliams** [facebook/relay#1533]
The documentation on GraphQLMutation has just one example of an optimistic query and response, which is for FIELDS_CHANGE.  

I'm totally stuck and noticed others are too - I don't know the theory on how the optimistic query is supposed to be crafted, why it even exists when Relay already knows what I'm trying to query, how to craft it and the response for the other update types.

I think adoption of GraphQLMutation will be very limited without this info.  Can someone help out with some explanation and examples?  I don't think it'll take too long and it will be very high impact for those of us trying to be early adopters!

**Comment by AWDGroup** [comment]
@lukecwilliams I agree that the whole mutation with Relay is very difficult to adopt.
I'm not an expert in Relay and I might be wrong about some of the stuffs, but here is my understanding from the Optimistic response:

Since Relay is caching everything on the client side to minimize the server calls, the optimistic queries is used to provide a better user experience to deliver the change to the user immediately without getting the response from the server. It means that you can provide what kind of info would user expects if the mutation was successful.  lets say you have a todo list and you want to modify the title, description or the status of the todo. Therefore you can specify the queryResponse to have these cached and showed to the user immediately:

```
getOptimisticResponse() {
        return {
            todo: {
                id: this.props.id,
                title: this.props.title,
                description: this.props.description,
                completed: this.props.completed,
            }
        };
    }
```

You can also use relay.hasOptimisticUpdate to check if an update is in progress. for example you can have something like this to make the title red when the update is in progress and the response has not been checked with the server:

```
class TodoItem extends Component {
    render() {

        //highlight fields that are getting updated
        let optimisticUpdateStyle = {};
        if (this.props.relay.hasOptimisticUpdate(this.props.node)) {
            optimisticUpdateStyle = {
                color: 'red',
            };
        }

       return (
           <Text style={optimisticUpdateStyle}>{this.props.node.title}</Text>
       );
}

```


Lets say you want to add an item to your TODO list using RANGE_ADD:


```
  getConfigs() {
    return [{
      type: 'RANGE_ADD',
      parentName: 'viewer',
      parentID: this.props.viewer.id,
      connectionName: 'todoConnection',
      edgeName: 'todoEdge',
      rangeBehaviors: () => 'append',
    }];
  }

  getOptimisticResponse() {
    return {
      todoEdge: {
        node: {
            description: this.props.description,
            title: this.props.title,
            completed: false //Since we just created this TODO it cannot be completed
        },
      }
    };
```

Still same scenario, the user will see this item got added to the list (in Relay Cache) but it does not mean that it actually got added on the server side till the server side confirms it.

I hope these examples help you understand it better

**Comment by wincent** [comment]
Thanks very much for bringing this up @lukecwilliams, and sorry for any frustration that coming to grips with the mutation APIs has caused.

> I'm totally stuck and noticed others are too - I don't know the theory on how the optimistic query is supposed to be crafted, why it even exists when Relay already knows what I'm trying to query, how to craft it and the response for the other update types.

Relay knows the query but not the result because mutations are largely a black box: even a relatively structured mutation like a `RANGE_ADD`, for example, is a black box; we know that something is going to be appended but we don't know what. Only the server has the definitive answer, and the developer may be able to construct a description of it too, in the from of an optimistic payload.

> I think adoption of GraphQLMutation will be very limited without this info. Can someone help out with some explanation and examples? I don't think it'll take too long and it will be very high impact for those of us trying to be early adopters!

A the moment we are aggressively prioritizing documenting the new Relay core and APIs. If you're curious about this, feel free to check out our work on the `experimental` branch. We're not going to actively pursue documenting the existing APIs right now because we want to ruthlessly prioritize getting the new code out into people's hands as soon as possible (we would, however, welcome any PRs that seek to improve the existing docs). In the meantime, the [`RelayGraphQLMutation` tests](https://github.com/facebook/relay/blob/master/src/mutation/__tests__/RelayGraphQLMutation-test.js) include a number of useful examples, and they may be of some help.

Thanks once again for raising this issue, and we hope to deliver relief soon now with a higher standard of documentation rolling out with the new APIs in the near future.

**Comment by lukecwilliams** [comment]
Follow-up: Modern docs so far have been very good, and the team is actively engaged with the early adopters.  Much appreciated.
