### ISSUE TITLE
Relay Query affecting Mutation Query

### ISSUE THREAD

**Issue by joshdavey** [facebook/relay#1536]
I have a form for creating ads. The form's mutation returns an Ad and an object the ad is connected to. I use a REQUIRED_CHILDREN config to get the ad back along with any errors that may have occurred. I also use a RANGE_ADD to add that ad to the object it has a connection to.

Here is the strange thing... If I load this form on it's own (like a page refresh) it works just fine. However... let's say I navigate to another page (using react-relay-router) and then come back to the form and try to use it I will get an error on my RANGE_ADD config telling me that it expected the "ads" field to be a connection. This same config works no problem otherwise.

Here is the error...
```
Uncaught Error: RelayMutationQuery: Expected field `ads` on `flow` to be a connection.
```

Here is the AdSave mutation for reference...

```javascript
export default class AdSave extends Relay.Mutation {
  getMutation() {
    return Relay.QL`mutation { adSave }`;
  }

  getFatQuery() {
    return Relay.QL`
      fragment on AdSavePayload {
        ad {
          id
          name
        }
        account {
          id
        }
        flow {
          ads
        }
        errors {
          key
          message
        }
      }
    `;
  }

  getConfigs() {
      return [{
        type: 'REQUIRED_CHILDREN',
        children: [Relay.QL`
          fragment on AdSavePayload {
            ad {
              id
              name
            }
            errors {
              key
              message
            }
          }
        `]
      }, {
        type: 'RANGE_ADD',
        parentName: 'flow',
        parentID: this.props.flowId,
        connectionName: 'ads',
        edgeName: 'adEdge',
        rangeBehaviors: {
         '': 'append',
        },
      }];
  }
```

**Comment by joshdavey** [comment]
Update: both my Account node and Flow node have an "ads" connection. I re-named one of the connections to "advertisements" and it worked...  Can someone explain what's going on here? I'd like to keep my names consistent :)

Thanks!

**Comment by wincent** [comment]
Thanks for posting @joshdavey.

Glad to hear that you sorted it out, but I think you may have found a bug.

My quick analysis suggests that `validateConnection` ([defined here](https://github.com/facebook/relay/blob/a1337903578e5b982d51f06fd0d57e5d25ce9b0c/src/mutation/RelayMutationQuery.js#L684)) is failing an `invariant` because its caller `getConnectionAndValidate` ([defined here](https://github.com/facebook/relay/blob/a1337903578e5b982d51f06fd0d57e5d25ce9b0c/src/mutation/RelayMutationQuery.js#L703) is getting hold of the wrong `ads` field (the one under `account`) because it is using `findDescendantFields` ([defined here](https://github.com/facebook/relay/blob/a1337903578e5b982d51f06fd0d57e5d25ce9b0c/src/mutation/RelayMutationQuery.js#L719)) to locate it, and that function returns the first found field, which is not necessarily the right one.

Right now we are aggressively focusing on shipping the new Relay core and APIs to the public (see our recent activity on the `experimental` branch), and that is basically a ground-up rewrite which is unlikely to manifest this bug, so we're unlikely to get to this ourselves. But if this issue is directly impacting you, perhaps the breadcrumbs I've shared above are enough to get you started on a PR with a regression test and fix?

**Comment by wincent** [comment]
On the other hand, the fix may be as simple as:

```diff
diff --git a/src/mutation/RelayMutationQuery.js b/src/mutation/RelayMutationQuery.js
index 20caa06d..70ea4e14 100644
--- a/src/mutation/RelayMutationQuery.js
+++ b/src/mutation/RelayMutationQuery.js
@@ -705,7 +705,8 @@ function getConnectionAndValidate(
   parentName: string,
   connectionName: string,
 ): void {
-  const connections = findDescendantFields(parentField, connectionName);
+  const connections = findDescendantFields(parentField, connectionName)
+    .filter(maybeConnection => mabyeConnection.isConnection());
   if (connections.length) {
     // If the first instance of the connection passes validation, all will.
     validateConnection(parentName, connectionName, connections[0]);
```

So I might just send a PR for that anyway.
