### ISSUE TITLE
IDEs cannot understand the default relay import.

### ISSUE THREAD

**Issue by hailwood** [facebook/relay#1537]
If we have at the top of our file the default import then the IDEs are unable to resolve anything off it other than `DefaultNetworkLayer`

```javascript
import Relay from 'react-relay';
```

However if we explicitly import the `RelayPublic.js` file then it can understand it fine although obviously this isn't what we want to be doing.

```javascript
import Relay from 'react-relay/lib/RelayPublic'
```

Are we able to clean up the export code at all or is this an issue for the IDEs?

**Comment by wincent** [comment]
Thanks for posting, @hailwood. Here's my understanding of what's happening here.

I think the reason they failing to resolve is because they are two different modules, and `Relay` spreads `RelayPublic`'s properties in using a spread operator (`...`).

In the compiled build, the spread gets transpiled into something that's likely opaque to them:

```
module.exports = (0, _extends3['default'])({}, require('./RelayPublic'), {
  // Expose the default network layer to allow convenient re-configuration.
  DefaultNetworkLayer: require('./RelayDefaultNetworkLayer')
});
```

That `_extends3['default']` is effectively an `Object.assign` polyfill, and it's not surprising that the IDE doesn't have enough intelligence to see through it.

> Are we able to clean up the export code at all or is this an issue for the IDEs?

At this time, we're aggressively prioritizing shipping the new Relay core and APIs rather than working on the previous implementation (see code recently landed to the `experimental` branch), so it is doubtful that we'd take any action here. If we did, it would probably be a crude spelling out of imports like this:

```
module.exports = {
  Environment: RelayPublic.RelayEnvironment,
  GraphQLMutation: RelayPublic.RelayGraphQLMutation,
  // etc...
};
```

Which would have the downside that it could fall out of date when `RelayPublic` updates.

I'm going to close this for now and suggest that we revisit it — if it is still a problem — only after the result of our work on the `experimental` branch has been shipped to `master`.

In the meantime, thanks for the question!
