### ISSUE TITLE
Viewer ID and node interface implementation

### ISSUE THREAD

**Issue by jamiehodge** [facebook/relay#1542]
Yet another question regarding the root viewer:

I've been reading tests on master (https://github.com/facebook/relay/blob/73c100b27fe295efd62e352344d29c118b66f2bc/scripts/jest/testschema.graphql) and the new experimental branch. I've noticed that the experimental branch introduces a special `client:viewer` ID for the root viewer: https://github.com/facebook/relay/blob/experimental/src/experimental/runtime/handlers/viewer/RelayViewerHandler.js#L24

I've spent some time trying to glean some best practice regarding the viewer and know that the team is reluctant to clarify the concept/implementation.

Based upon the test queries and the changes in the experimental branch, it appears as though the FB approach is to have the following structure:

```
{
  viewer {
    actor {
      ... on User {
         userField
      }
   }
}
```

Ignoring the indirection of the actor Interface, it seems as though the idea is that the viewer encapsulates the session and queries on the user fields are optional. This makes a lot of sense for my use case, as there is often no point in spending cycles querying for the user, as I have the essential properties in the session (in the context).

```
{
  viewer {
    account {
      ...
    }
    user {
      ...
    }
}
```

My confusion/question is how the viewer implements the node interface. It appears as though I can either use `Viewer:<SessionUserId>` or have some special values, like the experimental branch uses.

Am I on the right track? Any help would be very much appreciated.

**Comment by wincent** [comment]
`Viewer` at Facebook doesn't implement the `Node` interface. Legacy relay has a bunch of unpleasant hacks in it to make it behave as though it does, because we need it to for the purposes of refetchability, and to ensure that all the user data related to the viewer is correctly normalized.

The `viewer` field is really just a historical artifact. We could easily have designed the schema with a bunch more independent root fields than it has, but we didn't. It's possible to contextualize field resolution within the notion of a "session" with or without the `viewer` field, passing that down via context during query execution.

The new Relay core has a much cleaner and more generalized "hack" in place for this allowing us to deal with the "specialness" of `Viewer`. Users of Relay in the community aren't expected to implement a schema that uses the `viewer` pattern, although they may want to. (We neither recommend nor discourage it: like many design questions, it is a trade-off.)

> Ignoring the indirection of the actor Interface, it seems as though the idea is that the viewer encapsulates the session and queries on the user fields are optional.

The indirection abstracts the fact that a logged-in person could be a human `User`, or someone acting on behalf of a `Page` etc. I wasn't around when `viewer` first came into being (before Relay), but I seem to recall that there might have been technical limitations that made it more convenient to nest a bunch of related fields under subfields of a single root field, rather than as separate root fields; it's certainly true that the early Relay code base had limitations like this.

`client:viewer` is an implementation detail on which you shouldn't dwell or rely.

I'm going to close this now as I doubt there's anything actionable for us to do here. In the meantime, I'd worry you to ignore what you see in the test suite and design your schema based on your business needs; the new Relay core is flexible enough that it will adapt just fine to a schema with or without it.
