### ISSUE TITLE
Dealing with 'Id' name clash

### ISSUE THREAD

**Issue by benjaminhon** [facebook/relay#1555]
I have a backend redis database that also uses 'id' as a field parameter.

I have managed to get around the problem of specifiying a globalId by using resolvers to remap the localid to a globalid.

thus, all my writes to the database uses the local id, however all the queries map it to a globalid using the resolvers.

however, i am a bit confused about the mutation getConfigs(), since my props to the mutation will be a localid, i am guessing that i need to convert this to globalid in the fieldsId right?

for example,
```
getConfigs: ->
  [{
    type: 'FIELDS_CHANGE'
    fieldIDs:
      anchor: toGlobalId('Anchor', @props.anchor.id)
  }]
```

thanks

**Comment by leebyron** [comment]
I'm sorry this issue has sat here for so long. In an attempt to clean up our issue queue we're closing some aging or unclear-action issues.

I hope you were able to find a solution to your question. In the future I recommend asking general questions on stack overflow, since this forum tends to focus on bugs and requests.
