### ISSUE TITLE
why does relay overwrite my clientMutationId on the client side before sending?

### ISSUE THREAD

**Issue by benjaminhon** [facebook/relay#1556]
in my mutation
```
getVariables: ->
    { device, anchor, beacon, gatt } = @props.input
    return {
      clientMutationId: "CreateDevice#{device.id}"
      device
      anchor
      beacon
      gatt
    }
```

however when debugging it uses the default value in the input variable.
```
clientMutationId: "0"
```

i am able to get it working in graphiql by specifying the clientmutationid, but not from the client, as it overwrites with the default value.

**Comment by amkoehler** [comment]
[This comment](https://github.com/facebook/relay/pull/1083#issuecomment-231930313) suggests that `clientMutationId` is added automatically by babel-relay-plugin. It gets added automatically somewhere, because I've never had to manually set it in the mutation. 

It makes sense why you don't have issues in GraphiQL, because that doesn't know about Relay or babel-relay-plugin. If you need the value  `CreateDevice#{device.id}` to be sent to the server, I'd suggest you leave `clientMutationId` alone and send that value with a different key.

**Comment by benjaminhon** [comment]
ok noted

**Comment by kassens** [comment]
Closing this as it refers to classic where we don't expect to do any major updates.

Relay Modern shouldn't do anything special about `clientMutationId` anymore.
