### ISSUE TITLE
[Modern] RelayStaticNetwork generates wrong query

### ISSUE THREAD

**Issue by sibelius** [facebook/relay#1666]
`RelayClassic.Store`:

Query:
```graphql
query UserListQuery($first_0: Int!) {
  viewer {
    id
    ...F0
  }
}

fragment F0 on Viewer {
  _users2ZRkdS: users(first: $first_0) {
    pageInfo {
      hasNextPage
      endCursor
      hasPreviousPage
    }
    edges {
      node {
        id
        name
      }
      cursor
    }
  }
  id
}
```
variables: `{ first_0: 1 }`

`RelayStaticNetwork`
Query:
```graphql
query UserListQuery($count: Int!, $cursor: String) {
  viewer {
    ...UserList_viewer
    id
  }
}

fragment UserList_viewer on Viewer {
  users(first: $count, after: $cursor) {
    pageInfo {
      hasNextPage
      endCursor
      hasPreviousPage
      startCursor
    }
    edges {
      node {
        id
        name
        __typename
      }
      cursor
    }
  }
}
```
variables: `{ count: 1, cursor: null }`

example of code to reproduce: https://github.com/sibelius/ReactNavigationRelay/pull/5

**Comment by mjmahone** [comment]
What exactly is wrong with the generated query? There are more edges encoded in it, and things are named differently, but that's because we can build this query statically, without needing to make-up aliases. The added edges are a result of applying certain transforms (like the [RelayConnectionTransform](https://github.com/facebook/relay/blob/master/packages/relay-compiler/handlers/connection/RelayConnectionTransform.js).

There may be an issue specifically with how the transform works, but the behavior you're pointing out is, from what I can tell, intentional.

**Comment by josephsavona** [comment]
As @mjmahone mentioned, the Relay Modern query appears completely valid and effectively identical to the classic one. Differences:
- fields are not auto-aliased - the `_users2ZRkdS: users(...)` is now just `users(...)`. Note that auto-aliases weren't exposed to the developer in Relay Classic so this shouldn't be a breaking change.
- there's no duplicate `id` field in the `UserList_viewer` fragment, since that field is already requested in the parent query
- `users.edges.node.__typename` is added, presumably because the field has an abstract type
- `pageInfo` has some extra fields added for completeness

**Comment by sibelius** [comment]
I'm using graphql-relay-js to generate my connections

it makes `cursor` a required String field, take a look here: https://github.com/graphql/graphql-relay-js/blob/master/src/connection/connection.js#L103

@mjmahone should the RelayConnectionTransform, strip cursor when cursor is null?

or should we modify `graphql-relay-js` to accept `null` cursor values?

**Comment by sibelius** [comment]
in fact it does accept a null string on `after` and `before`, fixed in my server, tks
