### ISSUE TITLE
[Modern] freezing snapshot variables

### ISSUE THREAD

**Issue by seanchas** [facebook/relay#1669]
In development mode RelayEnvironment.lookup freezes snapshot data, seenRecords and variables.
But if variables contain mutable objects from, say, history of react-router, they also become frozen, which lead to exceptions with updating said history.

**Comment by josephsavona** [comment]
Thanks for asking. This is intentional: it's unfortunately common practice in the JS ecosystem to mutate values in unpredictable ways. In this case, the ideal option would be to fix the router to stop mutating history. A simple workaround is to copy the variables - e.g. `{...vars}` - before passing them tinto Relay.
