### ISSUE TITLE
Consider making RelayStaticRecord configurable for use with custom records

### ISSUE THREAD

**Issue by r0man** [facebook/relay#1672]
Hello,

I would like to use Relay with ClojureScript's persistent data structures. After reading [1] I got the impression that the new Relay design may support this use case (as well as ImmutableJS or JS maps) by creating and modifying records through the RelayStaticRecord class. However, since RelayStaticRecord is used directly in the codebase, I couldn't find a way to swap in my custom implementation. Is this something you would consider? You probably have already a plan for something like this, so if you are interested in supporting those use cases I would be happy to try to send a PR and would appreciated any hints on how this should be done.

Thanks, for the new Relay!

Roman

[1] https://github.com/facebook/relay/blob/master/packages/relay-runtime/ARCHITECTURE.md#data-types

**Comment by josephsavona** [comment]
Thanks for asking. Using closurescript data structures would likely be quite involved - we didn't design the system to support this use case.

For context, the main goal of abstracting the record format was to support things like using JS `Map`, perhaps `Object.create(null)`, or possibly a native data structure. Another goal was to make it easier to make changes to the system: if we need to change a key name for records, we can do it in one place. 

The runtime is also built around th idea of mutable data, immutable architecture. Records are mutable for performance, then copied on write when two versions of a record need to be merged and then frozen (in DEV only) once they're added to the Store in order to prevent additional updates. This means that for records that aren't ever updated we don't pay the cost of immutability. Also note that the fragment results that are vended to components are plain JS objects/values.

**Comment by leebyron** [comment]
@r0man we would be open to this kind of change as long as it could be done in a way that was not too invasive and didn't result in performance degradation. Since we don't have a plan for this, we would lean on you for that investigation

**Comment by yuzhi** [comment]
Seems like Joe and Lee has provided some solid answers above. I'm going to close this for now, fee;=l free to reopen if you have more questions about this in the future.
