### ISSUE TITLE
Node and Nodes - when does modern relay is supposed to use these ?

### ISSUE THREAD

**Issue by decebal** [facebook/relay#1727]
I am struggling to gather information on how to make best use of these graphql entries.

Modified my TypeSystem to allow for these 2, but the app does not seem to use them at all, I guess my colleagues supposed classic relay will "automagically" use them. How is relay supposed to make use of these entries? 

p.s. I encountered the relay directive for plurals, but not sure how it comes into picture here as it looks like modern relay is passing the directive in the query and my implementation of the TypeSystem does not allow for that at the moment, should it be supported on the Schema as well ?

**Comment by chollier** [comment]
Relay Modern doesn't need `node` or `nodes`. Classic used them to "refetch" fields when it already had a node in the store but some fields where missing given the current query (query tracking / diffing)

**Comment by ohjames** [comment]
@chollier Does Relay Modern not do any query diffing at all? I have a bunch of stuff nested under my `account` data structure and requesting certain fields on that data structure is very expensive. I'd like to avoid having to re-request those fields when possible (they are always requested first thing when the app loads).

**Comment by wincent** [comment]
@ohjames: Correct, no query diffing at all. We're trading off magic for explicit control because it leads to a simpler (and usually much faster) result. If you want to manage an expensive subset of a query explicitly you would use an abstraction like a refetch container to fetch only the subset, at a specific time that is appropriate to your UX.
