### ISSUE TITLE
[Modern] connections with dynamic args

### ISSUE THREAD

**Issue by stoffern** [facebook/relay#1764]
Sorry if i am misunderstanding the full thing but i seem to have big issues when getting feeds with dynamic variables.
Example of the store is:
`client:root:viewer:__Feeds_feedClosest_connection{"latitude":45.00,"longitude":46.00}`
`client:root:viewer:__Feeds_feedClosest_connection{"latitude":45.01,"longitude":46.02}`

As i can see the store will fill up as the GPS change.

Is searching for records with "wildcard" with store.getLinkedRecord() is it possible?
What is good practice here?

cc @leebyron @JenniferWang

**Comment by stoffern** [comment]
Should they be moved into `filter` would that fix it?

**Comment by JenniferWang** [comment]
I'm not a huge fan of looking up the store by regrex/wild card except for debugging purpose. Since the query variables are provided by client side, it should be possible to supply that value when looking up the store.

**Comment by stoffern** [comment]
@JenniferWang quite hard when queries are of dynamic GPS values.
I solved it now by refetching the feed. But the store will increment as the user is "on the move".

**Comment by JenniferWang** [comment]
@stoffern Aha, got it. In that case, since this is a connection field, you could have `@connection(key: 'Foo', filters: [])` to overwrite the result.

**Comment by stoffern** [comment]
Nice! Its just not documented yet. Sorry for the issue, hope this will help others tho 😉

**Comment by JenniferWang** [comment]
Ah, we missed that in the doc!
This is a backdoor for connection field; I'm still thinking if we should provide this general directive to allow having a `key` and `filter` in a regular field that supports this behavior. This is not on our schedule yet since it might involve a non-trivial change. (We don't want to sacrifice performance)

Please re-open the issue if anybody is running into this issue on a regular field.
