### ISSUE TITLE
[Modern] relay-compiler add basic docs on how to add custom transformers/handlers

### ISSUE THREAD

**Issue by JCMais** [facebook/relay#1788]
Like just changing all values of a field of given type to something else.

**Comment by wincent** [comment]
Thanks for the input here. We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 3 months) because the volume of material in the issue tracker is becoming hard to manage. If this is still important to you please comment and we'll re-open this.

Thanks once again!

**Comment by JCMais** [comment]
This is still important I think.

**Comment by mike-marcacci** [comment]
I would like to second this. I have a strong use case for a custom handler, but navigating the process of implementing it by reading source code is a challenging.

**Comment by sibelius** [comment]
Maybe you can take a look on how was done to add typescript support to relay Modern
