### ISSUE TITLE
[Modern] QueryRenderer reruns same query everytime on the server 

### ISSUE THREAD

**Issue by canaydogan** [facebook/relay#1819]
Hi,

I have been started migration of classic to modern relay. My app is using react router and have many routes. If the url changes, query renderer reruns. 

In the classic relay, the relay fetches the data just once, but in the modern, every running of query renderer fetch data from the server, whereas the same query has been fetched before. Is there anything that I missed.

Thank you.

**Comment by eugene1g** [comment]
This is the new normal - today Relay Modern does not do any caching (of data or queries) out of the box. I'm not sure if this will change in the future, but for now this responsibility is delegated to the app. The easiest way to do this is to add caching on the network layer e.g. with  [RelayQueryResponseCache](https://github.com/facebook/relay/blob/master/packages/relay-runtime/network/RelayQueryResponseCache.js)

**Comment by unirey** [comment]
It's not very tricky to add Relay Classic -style cache, there's even a [npm package](https://www.npmjs.com/package/relay-query-lookup-renderer) published by @robrichard.

However, it will still not be the same as Classic. Mainly (for my data needs at least) because Relay Modern follows GraphQL spec closely and `node` implementation is not in the spec. 

Im still trying to figure Relay caching out but it seems that Relay Modern caching is almost like (root) query scoped. Items have `__ids`, why not look them up by id (e.g `node` query)? Not flat cache anymore?
@josephsavona Any comments?

**Comment by josephsavona** [comment]
@unirey Relay Modern does have an in-memory cache that is flat (map of global ids to records, records link to others by reference - check out the architecture.md file in relay-runtime for more details). A query is effectively a fragment that is rooted at a special "root" record in the cache, and a root field is just a plain field on that record. There's nothing special about node. 

The key is that the behavior of the `node` root field in Relay Classic was a relay-specific behavior. It's possible that schemas exist that use that name but don't follow the Relay Classic spec. We wanted to prioritize compatibility with the GraphQL spec first, then work to address these types of use cases in collaboration with the community and, if possible, at the spec level so that all clients can benefit from a standard for identifying objects in the cache.

**Comment by josephsavona** [comment]
One idea we've explored is allowing applications to inject handling for specific types/fields that would be invoked *if* data for a field was missing. This would allow optionally injecting behavior that replicated the behavior of `node` in Relay Classic, without hard-coding that logic into the core.

**Comment by hisapy** [comment]
Hey guys, I just experienced the same problem. First I was using a `QueryRenderer` to get cities based on a selected province and noticed that the cities already fetched were fetched again and again when picking a province selected previously. Then I thought that maybe a refetchContainer would do the same as the old Relay where cities already fetched were loaded from store, but I got the same results, every time I pick a province the query is POSTed back to the server again.

So based on what's discussed here, is there a probability that `node` root field get's _deprecated_?

 🤔

**Comment by robrichard** [comment]
@hisapy the Relay Modern `QueryRenderer` will always fetch new data, it does not check the store to see if data is already available in the store. I published [relay-query-lookup-renderer](https://www.npmjs.com/package/relay-query-lookup-renderer) which will check the the store to see if it already has the data to render. I think you would be able to use it in your case avoid re-fetching already fetched data.

**Comment by hisapy** [comment]
Thanks @robrichard, I'll take a look at it. 

PS: Anyways, I'm concerned about the `node` behavior in Relay Modern.

**Comment by unirey** [comment]
@robrichard Just wondering: what routing library do you use and how do you handle routing w/ your package (or `QueryRenderer` which is almost the same)? Relay keeps re-fetching data for same queries, even with `lookup`. I think routing messed something up, because it only happens if I leave the route and come back.

@hisapy Nothing about `node` seems to be sure for now but I think that either `node` or something similar will eventually land to Relay Modern because having a single `by-id` query makes a lot more sense than having 10 different `single<Type>(id: !ID)` queries. I for one keep the query for now. As Joseph has said: first goal was to make Relay to follow GraphQL spec very closely and we'll solve these "edge cases" later.

**Comment by robrichard** [comment]
@unirey I think your data is refetched when you switch routes because when `QueryRenderer` is [unmounted it disposes of it's hold on the data](https://github.com/facebook/relay/blob/master/packages/react-relay/modern/ReactRelayQueryRenderer.js#L194) and the [store schedules garbage collection](https://github.com/facebook/relay/blob/master/packages/relay-runtime/store/RelayMarkSweepStore.js#L100). I think you could either have your router call `retain` on the same data so it is never garbage collected, or maybe build a custom store with a no-op for dispose so garbage collection never happens. Or the easiest solution might be to use [RelayQueryResponseCache](https://github.com/facebook/relay/blob/master/packages/relay-runtime/network/RelayQueryResponseCache.js) so the data is cached at the network layer.

@hisapy I think the relay classic behavior was to find the nearest node and fetch it when `setVariables` was called. In Relay modern, this behavior isn't there at all and you can write your own query to fetch the object by the top level node interface with a refetch query. I don't think the node field is necessarily deprecated, you just have to write the static queries yourself to use it instead of Relay building them automatically.

**Comment by wincent** [comment]
Thanks for the input here. We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 3 months) because the volume of material in the issue tracker is becoming hard to manage. If this is still important to you please comment and we'll re-open this.

Thanks once again!

**Comment by shahankit** [comment]
@robrichard I'm using react-router and each page is normally rendered using `<QueryRenderer />`. Can you please explain how do I cache using either `retain` or `RelayQueryResponseCache` method.

**Comment by damassi** [comment]
@shahankit - Not sure if you figured this out but this library will help: https://github.com/robrichard/relay-query-lookup-renderer
