### ISSUE TITLE
Document that mutations still require routes

### ISSUE THREAD

**Issue by boosh** [facebook/relay#192]
The mutations "complete example" on http://facebook.github.io/relay/docs/guides-mutations.html doesn't mention routes. Please update the docs to include sample routes and how to render the `LikeButton` component, or at the very least document that a route is still required.

**Comment by boosh** [comment]
As additional feedback I'm really struggling with getting any mutations working. More thorough, complete examples of mutations in the docs would be very helpful.

**Comment by josephsavona** [comment]
@boosh Did you look at the guides for Routes and Containers? Note that there are complete working examples of mutations in the [TodoMVC Example App](https://github.com/facebook/relay/tree/master/examples/todo/js/mutations).

**Comment by boosh** [comment]
Yes I read the guide but it wasn't obvious to me that the Routes and Containers also related to Mutations. I read the mutation docs only when I needed it. A link to the todomvc app would be helpful too.

**Comment by yungsters** [comment]
@boosh Can you elaborate on what kind of documentation you think would be helpful? I'm not sure what we need to call out regarding routes when explaining mutations.

**Comment by boosh** [comment]
I guess it's more to restructure the docs a little bit to make each page more standalone. I.e. the mutations docs shouldn't assume that people have previously read the container and route docs in that session or can remember everything about it. 

There's potentially a lot of new tech here - relay, react, relay server, graphql, etc, etc.

I've been developing my app by getting reads working (so I built a relay server and read the docs on relay containers & routes). I set up a couple of pages using mocked data. Then when I went back to add in support for mutations I was a bit confused as to how the pieces fitted together. I knew that containers needed routes, but I didn't realise mutations did since I had this slightly disjointed dev process. 

So just a short summary on the the mutations page saying that mutations also require routes would have helped, as would a complete example of say, creating a component that can trigger a mutation, and code to render it (i.e. so it's obvious it needs a route). That way, the docs would be a bit more standalone as people dip in and out while they develop.

**Comment by josephsavona** [comment]
@boosh The sequence you describe makes sense - get reads working, then try mutations. I'm curious how you got reads working without routes though?

**Comment by boosh** [comment]
I did use routes for reads, but then I just didn't realise that I also needed them for mutations. As I say, I think the way to make that clearer is for the pages to be a bit more standalone - i.e. extend the example mutations to include routes and render calls. That would also help to show how to pass parameters to the routes/mutations, etc. 

Probably what made me think I didn't need routes was the heading on the mutations page "A complete example". It's not complete since it doesn't include routing and a render call. These are just the misinterpretations you make when you're in a hurry I guess, so it'd be handy to make the examples more explicitly complete.

**Comment by yungsters** [comment]
@boosh Thanks for explaining your workflow. What you're suggesting makes a lot of sense. At the bare minimum, we could link back to previous guides with a short contextual blurb connecting the two guides.

But one part I am still unclear about (and maybe I'm missing something) is what you need to know about routes in order to build and send a mutation. It is necessary to construct the mutation fragments (and optionally if you're using `prepareVariables`), but otherwise the fact that routes are necessary should be pretty transparent. Have you found somewhere we are unexpectedly leaking routing concepts into mutations?

**Comment by boosh** [comment]
OK so I've had 2 problems with this:

1. The first is that using a `viewer` as an outer object is a very common pattern, but the docs don't show how to use this. The docs all pass parameters to the outermost route, but in fact, for my queries it's my subqueries I need to parameterise since the `viewer` is just a container to work around #112.
2. In the example at https://facebook.github.io/relay/docs/guides-mutations.html, the mutation has a 'story' fragment that returns the ID. It took me ages to realise that I still needed to call `MyMutation.getFragment('story')` even if the component I was calling it from already required all of the same data (e.g. `story.id` in this case). It seemed like that was unnecessary, but because of how things should be standalone components it is necessary. This was just my misunderstanding from being new to react & relay.

**Comment by steveluscher** [comment]
If I understand correctly, the biggest problem that you encountered was that Relay offered no warning for failing to compose a mutation's fragment(s) all the way down to the root of your application. We have no sensible way of presenting a warning, right now, since all fragments are optional.

We do, however, have an idea to add the notion of required or optional fragments. If we introduce this system, and eventually make all fragments required-by-default, we'll be able to warn when there's a missing link in the chain. This might look something like this:

```
story: () =>  Relay.QL`
  fragment on Story @relay(optional: true) { id }
`,
```

This should offer a more rigorous solution than documentation alone, so we should head for that. Tracked in #333.
