### ISSUE TITLE
[relay-compiler] Generated flow types not working for lists

### ISSUE THREAD

**Issue by danielbuechele** [facebook/relay#1959]
The flow types generated by relay-compiler do not work correctly for lists of scalar types.

The `schema.graphql` that is used for relay-compiler looks like this:
```
input ArticlePatch {
  rowId: String
  tags: [String]
  links: [LinkInput]
}
```

The generated flow-type looks like this
```
export type UpdateArticleByRowIdInput_articlePatch = {
  rowId?: ?string;
  tags?: ?string;
  links?: ?Array<?UpdateArticleByRowIdInput_articlePatch_links>;
}
```
Note, `tags` is of type `?string` but should rather be `?Array<?string>`. However flowtypes for non-scalar-type lists seem to be typed correctly.

**Comment by kassens** [comment]
Interested in trying to create a PR for this? 

The generator code is here:
https://github.com/facebook/relay/blob/master/packages/relay-compiler/relay/core/RelayFlowGenerator.js

And test cases that should be added to are here: https://github.com/facebook/relay/tree/master/packages/relay-compiler/core/__tests__/fixtures/flow-generator

**Comment by danielbuechele** [comment]
The is already a test case covering this, which passes: https://github.com/facebook/relay/blob/master/packages/relay-compiler/relay/codegen/flowtype/__tests__/printFlowTypes-test.js#L69
I'll need to look more into why this is not working in my case. Anyone else who can reproduce this?

**Comment by JenniferWang** [comment]
@danielbuechele  the test case you found is for the old flow type generator.

**Comment by leebyron** [comment]
I'm sorry this issue has sat here for so long. In an attempt to clean up our issue queue we're closing some aging or unclear-action issues.

I know the flowtypes have undergone improvements in recent months, so please check to see if your issue was resolved by a later version.

However if there are still problems, we'd be happy to review a pull request.

If this issue is still important to you, please feel free to reopen it with an update.
