### ISSUE TITLE
Allow overriding `shouldComponentUpdate` in Relay Modern

### ISSUE THREAD

**Issue by macalinao** [facebook/relay#1974]
https://github.com/facebook/relay/blob/master/packages/react-relay/modern/ReactRelayFragmentContainer.js#L129

One should be allowed to pass in a `shouldComponentUpdate` function here. I am using Relay with React-Router and it's causing problems.

**Comment by wincent** [comment]
For context, here is some related discussion in the context (no pun intended) of Relay Classic: https://github.com/facebook/relay/pull/897

@macalinao: what's your use case here exactly?

**Comment by zth** [comment]
This is a problem I've encountered as well. My use case is I have fragments fetching the same data regardless of the URL, but the UI renders differently depending on params in the URL. Since nothing but the URL changes (and everything that changes with React Router is inside non-scalar context which Relay then does not look at), my fragment containers block the entire sub tree render on URL change.

My current workaround is a HOC that adds the pathname + stringified params/query to the fragment container as a regular string prop, which allows Relay to detect the string changing and update accordingly. However, to me this feels a little brittle and it's easy to forget decorating all fragment containers.

**Comment by macalinao** [comment]
Same as @zth, though my workaround is to wrap every `createFragmentContainer` with `withRouter` recursively.

**Comment by leebyron** [comment]
I'm sorry this issue has sat here for so long. In an attempt to clean up our issue queue we're closing some aging or unclear-action issues.

If this is something you'd like to see happen, then we'd be happy to review a pull request.

If this issue is still important to you, please feel free to reopen it with an update.
