### ISSUE TITLE
Relay Modern Store/Record Source/Cache-management Documentation

### ISSUE THREAD

**Issue by mssodhi** [facebook/relay#2043]
Hi I was wondering if there was any documentation or resources for Record Source? This is for React-Native. I specifically want to give my relay environment a persistent storage, so that I don't have to query even on app reload. Helps with offline if the data is already in the persistent storage. I'm not worried about syncing data as of yet, just need a read only store. Any guidance to docs, or resources would be appreciated. Thanks!
@kassens 
@josephsavona 
@wincent 
@leebyron

**Comment by kassens** [comment]
This is certainly something we need to document more and publish some examples!

**Comment by leebyron** [comment]
I recommend looking at https://github.com/facebook/relay/blob/master/packages/relay-runtime/ARCHITECTURE.md for the most written description of this part of Relay.

Unfortunately there's less in depth documentation on this part of Relay since this isn't a typical surface people interact with. If you find yourself down this hole and would like to contribute back your learnings, please create a pull request!
