### ISSUE TITLE
[Modern] RefetchContainer: refetch gets disposed on object ID change

### ISSUE THREAD

**Issue by musawirali** [facebook/relay#2102]
If I have a logged in user represented as:

`viewer {
 user {
   id
 }
}`

When no one is logged in, the `user` is null. When is a user IS logged in, and I call refetch on my RefetchContainer, which grabs the user again, one of two things happen:
1) If the user is still logged in, everything works fine.
2) If the user's session on the server has expired, and the server now sends user = null, the refetch() call apparently gets disposed.

This (2) is the problem. Is this expected behavior? I have a loading screen that I show in this manner:

`
this.setState({ loading: true }, () => this.props.relay.refetch(null, null, () => this.setState({ loading: false }));
`

So when the refetch gets disposed, the callback is never called and my loading screen stays forever.

Am I doing something wrong (or against relay convention) or is this a bug?

**Comment by leebyron** [comment]
This doesn't sound like a bug. Since you have a RefetchContainer fetching data about a user, if that user object goes away, then the related UI is removed, since the UI is removed, then the associated refetch would also be cancelled upon unmount.

If the user has logged out, then it seems to make sense that your UI would reflect that state. If you want to automatically renew user sessions before the UI has a chance to react to the updated values, I suggest handling that as part of your network layer (similar to if you wanted to retry requests after network timeouts).
