### ISSUE TITLE
[Modern] [Feature request] Type coercion on hydration (for dates)

### ISSUE THREAD

**Issue by mattkrick** [facebook/relay#2132]
On my GraphQL backend, I created a `GraphQLISO8601Type`. It's just great because I don't have to bog down my application logic with coercing a string to a date.

Similarly, I'd like it if I didn't have to bog down my view-layer logic with type coercion. If a `GraphQLISO8601Type` comes down, I'd like Relay to automatically convert it to a JS date.

My dream would be a `coerceType` object on the `Environment` constructor:

```
const env = new Environment({
  ...otherStuff,
  coerceType: {
    GraphQLISO8601Type: (str) => new Date(str)
  }
})
```

Happy to PR if this is something worthwhile.

**Comment by kassens** [comment]
I thought about this before, I think it's pretty interesting and could be useful if it works well in all cases.
One thing we have to be extremely careful about is performance of a potential implementation. The simple implementation would do this during "normalization" (converting from the hierarchical JSON response into a key-value store) by just looking at at the `__typename` and checking if there's a key for that type in `coerceType`. Unfortunatly, this would mean a lot of extra lookups in really hot code that we want to keep as fast as possible.

The way this could potentially be achieved is by plugging into the compiler.
1. The compiler would look for fields of type `ISO8601Date` and add a `@__clientField(handle: "date")` directive. _NOTE: this could also be written by hand, but would just be tedious and ugly_
2. You pass in a custom `handlerProvider` that has a provider for `date` to update the field: https://facebook.github.io/relay/docs/relay-environment.html#adding-a-handlerprovider Unfortunately, we don't have docs for handlers yet since it's a really advanced feature.

This would probably be it for _reading_ data, not where this would best happen when sending to the server, but that's not as perf-sensitive.

Not sure if there's a good way to make this generic, but might be a fun way to add some features to the compiler.

**Comment by mattkrick** [comment]
`@__clientField(handle: "date")` that's a _really_ fun pattern, a compiler extension to do this sounds right, albeit daunting for an outsider!

> This would probably be it for reading data, not where this would best happen when sending to the server, but that's not as perf-sensitive.

It doesn't matter how this is _sent_ to the sever since the server will coerce it with a custom scalar's `parseValue` or `parseLiteral`, right? I could be missing your point here.

**Comment by mattkrick** [comment]
Ah shoot, just noticed this is a dupe of #91, I'll close in favor to keep the conversation all together.
