### ISSUE TITLE
[Modern] Set update to optionally merge, not replace

### ISSUE THREAD

**Issue by mattkrick** [facebook/relay#2133]
Let's say i query a todo item: `{id: 1, text: 'test', completed: false}`
now i turn it to true, but my server only provides the changed fields: `{id: 1, completed: true}`.
Currently, Relay creates a new object and replaces the old reference with the new in `updateTargetFromSource`. Instead, I'd like to merge the 2 objects & get `{id: 1, text: 'test', completed: true}`. 

The use case is subscriptions: a single `todoChanged` subscription could replace `textChanged` and `todoCompleted` by listening to all fields, but stripping nulls. 

To implement this today I could either send a bogus ID down from the server so Relay doesn't work it's update magic, or maybe I could do `@__clientField(handle: "merge")` on every subscription & iterate over the sources, but neither feel great.

**Comment by amkoehler** [comment]
Any luck with this? I ran into a similar problem updating a list in a mutation. Each item in the list had single new property being updated, so I had to use [setLinkedRecords](https://facebook.github.io/relay/docs/mutations.html#setlinkedrecords-records-array-recordproxy-name-string-args-variables-recordproxy) in the mutation's `updater` to update the whole set. I was fortunate enough that I could query for all the fields within each list item to make sure I'm not updating with nulls, but would be nice to do a merge instead of querying for a lot of the same data.

**Comment by mattkrick** [comment]
i wrote a merge handler that does the trick.

basically, my server follows a protocol kinda like Meteor's DDP, so each object has a `type` like 'ADD', 'UPDATE', 'DELETE', etc.

Then, for every query/mutation/subscription that follows this pattern, you just do like I wrote above: `@__clientField(handle: "merge")`.

The handler looks like this:
```
const MergeHandler = {
  update(store, payload) {
    const record = store.get(payload.dataID);
    if (!record) return;

    const type = record.getLinkedRecordID('type');
    if (type !== UPDATE) return;

    const serverField = record.getLinkedRecord(payload.fieldKey);
    if (!serverField) return;

    const updatedId = serverField.getDataID();
    const clientRecord = store.__mutator._base.get(updatedId);
    const serverDiff = store.__mutator._getSinkRecord(updatedId);
    const keys = Object.keys(serverDiff);
    for (let ii = 0; ii < keys.length; ii++) {
      const key = keys[ii];
      if (serverDiff[key] === null) {
        store.__mutator.setValue(updatedId, key, clientRecord[key]);
      }
    }
  }
};
```

**Comment by bdei** [comment]
what is the solution for 2021 ?
