### ISSUE TITLE
[modern] FIELDS_CHANGE equivalent

### ISSUE THREAD

**Issue by sibelius** [facebook/relay#2139]
What does look like a FIELDS_CHANGE config using `updater` from commitMutation?

**Comment by dminkovsky** [comment]
It looks like mutation responses (optimistic and then server) are normalized into the store automatically, so you don't need `FIELDS_CHANGE` because Relay does this anyway. You see this in mutation doc:

> optimisticResponse: an object conforming to the mutation's response type definition. If provided, the optimistic response will be normalized to the proxy store

and the Relay Runtime [ARCHITECTURE.md](https://github.com/facebook/relay/blob/v1.4.1/packages/relay-runtime/ARCHITECTURE.md) where it describes how normalized records are published to the store ("Store Operations"), which happens to mutation responses.

**Comment by kassens** [comment]
That's correct. As long as the Relay understands that they're the same object (best by having an `id` field) it should just update the fields.

**Comment by sibelius** [comment]
what if Relay does not understand they are the same?

is there a way to force the update?

can I also update a whole connection? or append some items to a existing connection?
