### ISSUE TITLE
[Modern] collisionKey for mutation is deprecated?

### ISSUE THREAD

**Issue by nodkz** [facebook/relay#2144]
How I understood Relay Modern does not have `collisionKey` for mutations anymore. Or I'm something missing and Modern provides some alternatives?

Relay Classic allows sending mutations in serial mode if they have same collision key. It very useful functionality when you sending chat messages, some events or other data which should be sent to the server in strict order.

How can it be solved with Relay Modern? Can anybody share the proper solution?

**Comment by kassens** [comment]
You are right, this is one of the feature that is no longer part of the core. Relay was doing too many things and this was unfortunately one of the features we removed in the rewrite.

There's a bunch of things to consider, like do you endlessly queue updates or should they expire/replace/collapse in some way? Chat messages you might all want to send in a queue per chat channel. "Like, unlike, like" of an item might be collapsed into a single like mutation. Multiple "Add 1 to cart" mutations might be collapsed into a single "Add n to cart" mutation.

Since there's some flexibility in what you might want, we think it's best if people add a queue system on top of the core APIs and keep the core building blocks leaner in terms or learning curve, file size, and complexity.

It shouldn't be too difficult to build a simple queue or Relay Classic style key based queue on top of the existing API. This could even be shared as an npm module if it would be generic and useful to other people!

**Comment by nodkz** [comment]
Good. @kassens thanks for the answer and clarifying Relay team position about this feature. I completely agree with your decision.

As usual, I make some things in my internal app. And if find, that it is good customizable, I'll publish npm package.

Thanks!
