### ISSUE TITLE
[Classic] Components rerenders all time

### ISSUE THREAD

**Issue by valeryq** [facebook/relay#2148]
I upgraded my Relay from v0.10.0 to latest version, but encountered with a trouble, my components become rerenders after upgrade, because prop from relay container returns non immutable as was early (on 0.10.0).

My components all time re-renders, when receive new props (for example navigation), because object with data from relay container non immutable all time.

Have you encountered such a problem?

```
<Relay.Renderer
  environment={Environment.getStore()}
  queryConfig={new Route(preparedParams)}
  Container={DecoratedComponent}
  render={({ error, props, retry }) => {
    if (error) {
      if (error.response && error.response.status === 403) {
        return this.context.store.dispatch(actions.ensureAuthenticated());
      } 

      return <ConnectionErrorScreen onPress={() => this.onRetryPress(retry)} reloading={this.state.reloading} />;
    } else if (props) {
      // *** HERE: props from callback all time is new, even if they have not changed ***
      return <DecoratedComponent {...this.props} {...props} />;
    }

    return this.renderLoading();
  }}
....
```

**Comment by quazzie** [comment]
I have the same problem.
Same query and same parameters - same result but not ===.
If josephsavona is to believed here https://github.com/facebook/relay/issues/1261#issuecomment-234475633 it should pass immutable/=== objects.

**Comment by quazzie** [comment]
It seems to be because queryConfig is changing, so RelayReadyStateRenderer.prototype.componentWillReceiveProps updates its internal "_relay" variable and that makes the context change so then RelayContainer.prototype.componentWillReceiveProps will receive the new context with a different relay property. Which promptly does a cleanup then reinitializes itself. Then it reruns the query i presume and returns a !== result.

So if you pass memoize the queryConfig it should work.

**Comment by kassens** [comment]
Closing this as we no longer support Relay Classic to help us focus on the Modern issues!
