### ISSUE TITLE
Mutations for types belonging to many of another type 

### ISSUE THREAD

**Issue by sgwilym** [facebook/relay#220]
I have a model where a child object can belong to `n` parent objects. If I delete a child object belonging to many parents, it doesn’t seem like there’s any way for Relay to update all the stored parent objects with this information:

- `FIELDS_CHANGE` only returns a single object’s information, which doesn't work for situations where parent objects have different edges in their child connections.
- `NODE_DELETE`, `RANGE_ADD`, and `RANGE_DELETE` only take a single `parentID` in their mutator configuration, meaning only one parent object will have the deleted object removed from its connections.

I suppose the same problems apply if you wanted to add an edge between a new object and many parents.

Haven’t tried this, but would something like this work?

```js
/* ... */

getFatQuery() {
  return Relay.QL`
    fragment on CreateChildPayload {
      ${ this.props.parents.map((parent, i) => {
        return `parent_${i} { children }`
      })},
      newChildEdge
    }
  `
}

getConfigs() {
  return this.props.parents.map((parent, i) => {
    return {
      {
        type: 'RANGE_ADD',
        parentName: `parent_${i}`,
        parentID: parent.id,
        connectionName: 'children',
        edgeName: 'newChildEdge',
        rangeBehaviors: {
          '': 'append'
        }
      }
    }
  })
}

/* ... */
```

But then again, you’d need to dynamically change the return fields of the payload, and changing the schema on the fly doesn’t sound like a very good idea 😅

**Comment by devknoll** [comment]
A little follow-up from a discussion in the #ruby channel on GraphQL Slack:

It seems like there's some mixing of tree and graph going on here. If `NODE_DELETE` means that a node is being deleted from a graph, then shouldn't *all* edges be deleted (and thus a `parentName`/`parentID` need not be specified)?

Would this be better named `EDGE_DELETE` for its current behavior?

**Comment by yungsters** [comment]
Ideally, `NODE_DELETE` *would* allow updating many parents. I think we do not have this capability because there has not been a good way to declare the fat query without making the mutation payload include the entire schema.

What we *do* do currently is delete all edges and update all connections when a node is deleted. It happens here:

https://github.com/facebook/relay/blob/2a86be3e71cdc6511fa994e3de539f72070da1b4/src/traversal/writeRelayUpdatePayload.js#L145-L156

**Comment by devknoll** [comment]
Doh, thanks for the clarification @yungsters 

Two random, most likely bad ideas:
  1. We could automatically issue `node` queries on any known parents after the mutation (possibly just a single plural selection?) Bad because there's an async gap between the mutation finishing and the result coming in.

  2. Relay mutation spec could be updated to include a `parent(parentIDs: [ID!]` field on mutation payloads. This could be added automatically by Relay and would include a list of all local nodes with a connection containing an edge to the node in question. Bad because... not entirely sure what fields we would select while preventing overfetching?

**Comment by devknoll** [comment]
Actually, that _might_ just work. That's what the fat query is for. Imagine:

```
getFatQuery() {
  return Relay.QL`
    fragment on MutationPayload {
      connections {
        ... on TypeA {
          # Fat query for TypeA
        }
        
        ... on TypeB {
          # Fat query for TypeB
        }
      }
    }
  `
}
```

(where `connections` is what I was previously calling `parent`)

Then Relay would automatically add the aforementioned `[ID!]` argument to the `connections` field, containing the ID of every local node with a connection containing the edge being mutated.

Maybe I'm missing something though.

**Comment by devknoll** [comment]
To make this less magical and not require any spec changes, you could define a `parentField` in the config, so Relay could automatically change:

```
fragment on MutationPayload {
  purple {
    ... on TypeA {

    }
    ... on TypeB {

    }
  }
}
```

into:

```
fragment on MutationPayload {
  fieldForNode1: purple(id: 1) {
  }

  fieldForNode2: purple(id: 2) {
  }
}
```

without worrying about possible field name collisions.

**Comment by wincent** [comment]
With the [Relay 2](https://speakerdeck.com/wincent/relay-2-simpler-faster-more-predictable) release approaching, we'll have an entirely new mutation API that is more expressive/imperative. Significant further work on Relay 1 mutation API is unlikely, at least from Facebook, as we are turning our efforts towards getting Relay 2 out the door. So I am going to close this one and label it as "relay 1". Thank you to everybody who participated in the thread!
