### ISSUE TITLE
Refetch Container doesn't update props

### ISSUE THREAD

**Issue by MartinDawson** [facebook/relay#2244]
Refetching works fine with pagintationContainer but with refetchContainer the new props never get updated even though the response comes back from the server correctly as shown in the network tab. I can't figure this out.

https://stackoverflow.com/questions/45245653/relay-modern-refetchcontainer-props-arent-passed-to-component

**Comment by AndreiCalazans** [comment]
Can you put up some code which we could try to help you debug.

It seems very strange, since everything in that stackoverflow issue looks fine.

**Comment by MartinDawson** [comment]
I'm using [found-relay](https://github.com/4Catalyzer/found-relay) for routing instead of QueryRenderer but it shouldn't affect anything.

```
const query = graphql`
  query primaryLayoutContainerQuery(
    $songId: Int
  ) {
    song(id: $songId) {
      ...editSongModalContainer_song
    }
  }
`;

export const routeConfig = {
  Component: PrimaryLayout,
  query,
  prepareVariables: (variables) => ({
    ...variables,
    songId: 104,
  }),
};
```
```
const PrimaryLayout = ({ song }) => (
    <div>
      <EditSongModal song={song} />
    </div>
);
```

const fragments = graphql`
  fragment editSongModalContainer_song on Song {
    name
    coverImageUrl
    artist
  }
`;

const refetchQuery = graphql`
  query editSongModalContainerRefetchQuery(
    $songId: Int
  ) {
    user {
      id
    }
    song(id: $songId) {
      ...editSongModalContainer_song
    }
  }
`;
```
const enhance = compose(
  refetchContainer(fragments, refetchQuery),
  lifecycle({
    componentWillMount() {
         const refetchVariables = () => ({ songId: 105 });
         this.props.relay.refetch(refetchVariables, null);
    }
  }),
  branch(
    props => !props.song,
    renderNothing,
  ),
);

export default createRefetchContainer(enhance(EditSongModal), 
  graphql`
    fragment editSongModalContainer_song on Song {
      name
      coverImageUrl
      artist
    }
  `,
graphql`
  query editSongModalContainerRefetchQuery(
    $songId: Int
  ) {
    song(id: $songId) {
      ...editSongModalContainer_song
    }
  }
`);
```

```
  const EditSongModal = ({ song,}) => (
    <div>{song.name}></div>
  );
```

I see the new result in the network tab but `song` is always the value of song 104 instead of the new re-fetched 105.

**Comment by MartinDawson** [comment]
@AndreiCalazans I copied the exact way the example does it and it still doesn't update with the new props. This needs looking at.

```
ReactDOM.render((
  <QueryRenderer
    environment={environment}
    query={graphql`
      query appQuery($songId: Int) {
        song(id: $songId) {
          ...editSongModalContainer_song
        }
      }
    `}
    variables={{
      songId: 104,
    }}
    render={({error, props}) => {
      if (error) {
        return <div>{error.message}</div>;
      } else if (props) {
        return <EditSongModal song={props.song} />;
      }
      return <div>Loading</div>;
    }}
  />
), document.getElementById('app'));
```

```
class TodoItem extends React.Component {
  render() {debugger
    const item = this.props.song;
    return (
      <div>
        {item.name}
        <button onClick={this._refetch} title="Refresh">refresh</button>
      </div>
    );
  }

  _refetch = () => {debugger
    this.props.relay.refetch(
      {songId: 105},  // Our refetchQuery needs to know the `itemID`
      null,  // We can use the refetchVariables as renderVariables
      () => { console.log('Refetch done') },
      {force: true},  // Assuming we've configured a network layer cache, we want to ensure we fetch the latest data.
    );
  }
}

export default createRefetchContainer(
  TodoItem,
  graphql`
    fragment editSongModalContainer_song on Song {
      name
      coverImageUrl
      artist
    }
  `,
  graphql`
    query editSongModalContainerRefetchQuery(
      $songId: Int
    ) {
      song(id: $songId) {
        ...editSongModalContainer_song
      }
    }
  `
);
```

**Comment by MartinDawson** [comment]
https://stackoverflow.com/questions/45245653/relay-modern-refetchcontainer-props-arent-passed-to-component

> Oh I think I got through a similar problem too. If I remember correctly I believe the "id" Relay is using to identify the component is including the variables for the initial query so try unwrapping your container fragment in the QueryRenderer by moving the searchUsers(..) to the fragment and then in the query just ...Search_user. You'll have to define Search_user as a fragment of your root, i.e.: in my case it'd something like fragment Search_user on RootQueryType. My last suggestion is turning your debugger on and see whats going on when you get the data.

This seems to be a bug. Moving the query to the fragment works...

**Comment by jstejada** [comment]
Hey @MartinDawson, sorry for the delay in getting back to you on this issue!

This is actually expected behavior, and I'll try to expand on the answer from stack overflow. When `refetch` is called and the `refetchQuery` is executed, Relay doesn't actually use the result of the query to re-render the component. All it does is normalize the payload into the store and fire any relevant subscriptions. This means that if the fetched data is unrelated to the data that the mounted container is subscribed to (e.g. using a totally different node id that doesn't have any data overlaps), then the component won't re-render.

In this specific scenario, the reason why the container doesn't re-render, i.e. why it isn't subscribed to the changes fired by the `refetchQuery`, is due to how subscriptions are set up. A subscription is basically a subscription to a `snapshot`, which basically represents a concrete fragment and the data and records associated with at a given point in time -- when the records associated with a snapshot change, the subscription for that snapshot will be notified of changes.

In this case, given that the fragment for the container has no variables, the snapshot that it will subscribe to will **only** be associated with the initial node record; after refetch happens and the the store is updated, the records for the new node will have been updated, but the record associated with that original snapshot hasn't changed, so the container subscribed to it won't be notified.

This means that Refetch containers are only really meant to be used when you are changing variables in the component fragment. The solution you provided here is valid, or if you don't want or need to include variables in the fragment, you could go one level up and set new variables directly in the QueryRenderer (using props or state).

This could definitely be made more clear in the docs, so I'll update them to reflect this. Thanks for your patience! I hope this helps!

**Comment by sibelius** [comment]
Your fragment needs to ask for name as well, it is only asking for id

**Comment by juhaelee** [comment]
@sibelius  this is my `createRefetchContainer` now:

```
createRefetchContainer(
  MountComponent,
  graphql`
    fragment MountedRenderer_viewer on User
    @argumentDefinitions(show: { type: "Boolean", defaultValue: false }) {
      id
      name @include(if: $show)
    }
  `,
  graphql`
    query OwnershipsRenderer_Query($show: Boolean!) {
      viewer {
        ...MountedRenderer_viewer @arguments(show: $show)
      }
    }
  `,
);
```

still the same problem though, the store is being updated but the `MountComponent` is not rerendered / the callback does not executed

**Comment by sibelius** [comment]
you need to also use renderVariables in this case

renderVariables = {
   show,
}

https://facebook.github.io/relay/docs/en/refetch-container.html#arguments

**Comment by CoericK** [comment]
@juhaelee I see that you had the same problem I had and @sibelius  tried to help you as well did you solve your problem? I facing the same problema here https://github.com/facebook/relay/issues/2421

**Comment by juhaelee** [comment]
@CoericK my problem was that I was actually calling refetch with the wrong parameters. Had nothing to do with the graphql tag

**Comment by dehypnosis** [comment]
Anyone still got problem?

**Comment by dehypnosis** [comment]
I just refreshed fragmented component's key for workaround

**Comment by n-sikka** [comment]
@dehypnosis can you explain exactly what you did?

**Comment by dehypnosis** [comment]
```<component key={dynamicKey} />```

i just changes component's key dynamically

**Comment by strindhaug** [comment]
Another possible reason, that confused me for some time today: you have a `shouldComponentUpdate` in the component that does not return true even if the data is updated.
