### ISSUE TITLE
Can I preload data into the store when the app start? 

### ISSUE THREAD

**Issue by irrigator** [facebook/relay#2313]
I noticed that [instagram.com](https://www.instagram.com/) loads pretty fast although **it's a React single page application** and **it doesn't do server side rendering**. After checking the network responses, I found their trick is to send back the initial query result with the html document (through a global variable ```window._sharedData``` in a script tag). When the js bundle is downloaded and the app starts, they somehow **preload** the initial data into the client store (don't know if they are using Relay or not), thus saving an extra request to fetch the data.

Can I do the same thing in Relay Modern? I'm sorry not to ask this question on Stackoverflow. But after reading through the documentation I am still not sure whether this is possible with Relay Modern.

**Comment by zth** [comment]
Yeah, have a look at this related comment in another issue: https://github.com/facebook/relay/issues/676#issuecomment-325214249

I guess the tricky part in the non-SSR scenario is to extract what queries you can actually pre-render where, especially if you have queries using variables and so on.

**Comment by irrigator** [comment]
@zth Thanks for pointing out! The "tricky part" does involves some work. My plan is to extract the query at build time (Relay Compiler already support this) and build a map between top-level routes and query. Then in the server code you can use this map and the request info to get the query, run it and inject it into the placeholder html file.

**Comment by irrigator** [comment]
Just found #1760, which is what I am looking for, which means this issue can be closed.

**Comment by alloy** [comment]
@irrigator I _think_ you should be able to close it yourself, mind doing so?

**Comment by sibelius** [comment]
`usePreloadedQuery` https://relay.dev/docs/en/experimental/step-by-step

**Comment by tony** [comment]
@sibelius @irrigator Hi, I came from a google search, I don't believe this answer is addressed

Thank you for the project! I apologize if this is in any way distracting. I believe the case I'm encountering is common, though. Correct me if I'm wrong, and let me know if I can provide any more context!

Some context, I'm trying to get faster initial render (just making google lighthouse happy :)). Technically, this initial render could work cold without relay and just pure props, but in reality due to hooks and routing, relay ends up becoming enmeshed, it's hard to just use pure props and not avoid relay becoming part of the webpack chunks. Want to see how much I can trim things down without requiring an SSR refactor.

Assume a raw graphql response:

```
{"series":{"edges":[{"node":{"id":"U2VyaWVzOjE=","nameShort":"HSK","nameLong":"Hànyǔ Shuǐpíng Kǎoshì","cardCount":8828,"deckCount":4}},{"node":{"id":"U2VyaWVzOjI=","nameShort":"PCR","nameLong":"Practical Chinese Reader","cardCount":2319,"deckCount":65}},{"node":{"id":"U2VyaWVzOjM=","nameShort":"NPCR","nameLong":"New Practical Chinese Reader","cardCount":3845,"deckCount":60}},{"node":{"id":"U2VyaWVzOjQ=","nameShort":"IC2","nameLong":"Integrated Chinese (2nd edition)","cardCount":1054,"deckCount":23}},{"node":{"id":"U2VyaWVzOjU=","nameShort":"IC3","nameLong":"Integrated Chinese (3rd edition)","cardCount":942,"deckCount":20}},{"node":{"id":"U2VyaWVzOjY=","nameShort":"HSK_2010","nameLong":"Hànyǔ Shuǐpíng Kǎoshì 2010 (beta)","cardCount":5002,"deckCount":6}}]}}
```

This is loaded from the server side and made available in a `window` variable so the network request can be avoided.

How does someone make it so that query response is already in the store?

Aside: The other thing is, since `usePreloadedQuery` is recommended, that has to be run inside a react component (I think, right?).  Even if the server provides the graphql data, this approach means relay has to be part of the initial load, and for any component loaded that uses the hooks.

If I may be so bold - if data in `window.ourInitialData` is ready to go, most likely, we're likely okay to fishline stuff down with props. No relay is necessarily required.

If relay has to get pulled in anyway due to hooks being in our component structure - How easy is it to preload data, e.g. like in a redux-style? 2. How many pieces of relay end up getting pulled into use just the store (since at this point, all we/i need is the data we already have to be accessible to render the component, no fetching required, yet).

Is there a pattern to avoid pulling in bigger relay pieces until later?   (Maybe this is more of a webpack configuration issue on my part! Not sure!)

**Comment by sibelius** [comment]
Check how I solved SSR in this post https://dev.to/sibelius/adding-server-side-rendering-to-a-relay-production-app-30oc

If this is not enough, open a new issue with more info about your use case
