### ISSUE TITLE
Validate the shape of mutation configs

### ISSUE THREAD

**Issue by sgwilym** [facebook/relay#232]
This has happened to me a couple times now — a mutation will silently fail if a key in a config is spelled incorrectly.

This works: 
```
  getConfigs() {
    return [{
      type: 'FIELDS_CHANGE',
      fieldIDs: { updatedThing: this.props.thing.id }
    }]
  }
```

But this will just silently cause half of the mutation query to go missing:
```
  getConfigs() {
    return [{
      type: 'FIELDS_CHANGE',
      fieldIDS: { updatedThing: this.props.thing.id }
    }]
  }
```

Same thing goes for the very British mistake of specifying `rangeBehaviours` instead of `rangeBehaviors` — a truly insidious problem!

**Comment by wincent** [comment]
Thanks for the report, @sgwilym. I think we could probably add some (`__DEV__`-only) runtime config shape validation, likely in `RelayMutationQuery.buildQuery` it we had to. But we do have Flow types for those shapes there already though. When your code has an error in it, does it pass Flow typecheck?

**Comment by sgwilym** [comment]
I'm not using Flow, so I wouldn’t have any idea 😁

Is it assumed that users of Relay are all using Flow typechecking…?

**Comment by wincent** [comment]
> Is it assumed that users of Relay are all using Flow typechecking…?

No. Relay itself uses Flow extensively, but the type annotations get stripped at build time, of course, and how you transform/preprocess/check your userland code is up to you.

Looking in `[RelayTypes](https://github.com/facebook/relay/blob/master/src/tools/RelayTypes.js)`, which is the list of types that we've exposed because we consider them useful to external users who may want to typecheck their code with Flow (and in addition to usefulness, these are the minimal set that we consider less likely to need to change over time), I see we're not exporting the config shapes anyway.

So on the balance, a runtime check is probably in order.

**Comment by angelf** [comment]
I also got hurt by fieldIDs vs fieldIds. Checking that a FIELDS_CHANGE config requires a fieldIDs would be nice.

**Comment by jkettmann** [comment]
Me too. Spent hours today finding that I once wrote fieldIds and once fieldsIDs. Luckily the relay playground throws an error

**Comment by josephsavona** [comment]
@jkettmann I'm glad that Relay playground helped here. Note that the latest version of Relay validates mutation configs - @wincent even added hints that suggest the correct keyword if its misspelled ;-)

**Comment by jkettmann** [comment]
@josephsavona Thanks, great news. Good reason to update my dependencies ;-)

**Comment by wincent** [comment]
Closing this thread as it is pretty stale. We added a bunch of validation for mutation configs in [v0.8.0](https://github.com/facebook/relay/releases/tag/v0.8.0), and mutation configs as such are going away entirely in [Relay 2](https://speakerdeck.com/wincent/relay-2-simpler-faster-more-predictable), being replaced by a new API.

Thanks to @sgwilym and @jkettmann for chiming in.
