### ISSUE TITLE
Flow types for 1.5

### ISSUE THREAD

**Issue by steida** [facebook/relay#2331]
I am confused. Is this libdefs official and ready for Relay 1.5 or not?

https://github.com/flowtype/flow-typed/tree/master/definitions/npm/react-relay_v1.x.x/flow_v0.47.x-

As for "Relay Containers are now properly Flow typed."

What does it mean? It's related to internal code or some Flow types should be used with createFragmentContainer etc.

Thank you for all your work!

**Comment by orta** [comment]
It does look like this is just for internal code (otherwise I would have expected `x.js.flow` files in the [pkg](https://unpkg.com/relay-runtime@1.5.0/) like how [graphql-js does it](https://unpkg.com/graphql@0.13.1/) ) 

Perhaps someone could try using the same technique as they used: https://github.com/graphql/graphql-js/pull/412

**Comment by jstejada** [comment]
sorry for the confusion @steida. I'm going to merge this into #2284 and clarify in the release notes
