### ISSUE TITLE
Cursor for create mutation

### ISSUE THREAD

**Issue by steida** [facebook/relay#2337]
So I have this server api:

```js
async createWeb(parent, { input }, ctx, info) {
    // Only an authorized user can create a web.
    const userId = getUserId(ctx);

    // The same logic as on clients.
    const validationErrors = validation.validateNewWeb(input);
    if (validationErrors) throwError(validationErrors);

    const domainName = input.name
      .toLowerCase()
      .split('')
      .map(char => diacriticsMap[char] || char)
      .join('')
      .replace(/[^a-z0-9]/g, '');
    const timestamp = Date.now().toString(36);
    const domain = `${domainName}-${timestamp}`;

    const web = await ctx.db.mutation.createWeb({
      data: {
        name: input.name,
        domain,
        owner: { connect: { id: userId } },
      },
    });

    return {
      edge: {
        node: web,
        cursor: '', // WTF I should return here?
      },
    };
  },
```

And this mutation:

```js
const mutation = graphql`
  mutation CreateWebMutation($input: CreateWebInput!) {
    createWeb(input: $input) {
      edge {
        node {
          ...WebsItem
        }
      }
    }
  }
`;
```

What cursor should be? Thank you.

**Comment by jstejada** [comment]
Hey @steida, this issue is really not pertaining to Relay as it depends on your server implementation, which is independent of Relay. I would need to be familiar with your web app to tell you what the cursor should be.

In general, a cursor is an identifier that serves as a marker that allows you to paginate over a set of records, e.g. `items(after: <cursor>, first: 10)`. You can find a good explanation here: https://dev-blog.apollodata.com/understanding-pagination-rest-graphql-and-relay-b10f835549e7#c0da

**Comment by dclarke-modus** [comment]
I also have the same problem. I dont think this is server implementation specific but, more on the side of the architecture of Relay-GraphQL. Say for example I"m doing 2 steps:

1. Fetch a list of records for my Paginated Container with a filter {name: 'blah'}. This essentially would be a sub-list of the bigger list depending on the filter. So say the total record in the DB is 100 but, with the filter, you only return 20 records, the cursor would be based on 20 records. 

2. Subsequently I send a create record mutation and I want to get the cursor (so I can add the record to my Paginated Connection on the client). My mutation payload would need the cursor in this case and if I had to generate it with say `offsetToCursor`, I do not know what the original filter (from step #1 is). So essentially I'd have to do offsetToCursor(collection.find({}).length), which would be wrong because, this would return 101 and not 21.
