### ISSUE TITLE
How to handle the "%future added value" in flow types generated enums

### ISSUE THREAD

**Issue by HichamELBSI** [facebook/relay#2351]
Hi everyone,

How to use a flow type generated enum with the for a known enum (see the use case below)

```javascript
// ./src/events/__generated__/my_generated.graphql.js
...
export type EVENT_TYPES = ('activity' | 'formation' | '%future added value');
export type Event = {
     type: EVENT_TYPES
}
...
```

```javascript
// ./src/components/icon.js
type IconProps = {
    type: 'menu' | 'arrow' | 'activity' | 'formation',
};

const Icon: React.ComponentType<IconProps> = ...

export default Icon;
```

```javascript
// ./src/events/index.js

import type {Event} from './__generated__/my_generated.graphql.js';

type EventPageProps = {
     myEvent: Event
}

const EventPage = ({myEvent}: EventProps) => (
     <div>
               /* Flow error : 
                         Cannot create Icon element because string literal 
                         %future added value [1] is incompatible with string enum [2] in property type.     
              */
               <Icon type={myEvent.type} /> 
     </div>
)
```

**Comment by leebyron** [comment]
These are generated as a reminder that GraphQL services often expand in capabilities and may return new enum values. To be future-proof, clients should account for this possibility and do something reasonable to avoid a broken product. Flow types help us catch cases where that hasn't yet occurred.

**Comment by AugustinLF** [comment]
Hmmm, but couldn't you say that about any relay generated type? That we rely on the schema to be correct? If tomorrow the `type` property of `Event` becomes nullable, our code will fail where it shouldn't, right?

**Comment by leebyron** [comment]
That is also true! I think this area of GraphQL is the least well defined at the moment however historically we've seen changes of what type a field returns (including becoming nullable) being considered as server breaking changes and thus avoided, while we've seen additions to enums not being considered server breaking changes and occurring (we now have a tool in graphql.js that detects this as a "dangerous" change). Another related example is a Union type adding a new possible type which can be returned - this hasn't historically been considered breaking but is dangerous for the same reason.

To bring the example closer to your code - if in the future you introduce a new kind of event and ship it, then your client may crash because it got `undefined` where it expected an icon. Relay's generated flow types are trying to help you out by pointing out this possible future scenario.

Right now this is always how this works, but I think if you really thought this wasn't useful then we would definitely entertain a PR which allows for configuration to exclude this "future added value" entry

**Comment by AugustinLF** [comment]
Thanks for your insight! It does indeed make sense to make such an option interesting, since in our case, we do have a total control on the server (so we would have to handle the new type of `Event` before the API is allowed to be updated), but it might not be the case for everybody.

I'll see if I can give a PR a try :)

**Comment by anfedorov** [comment]
> if you really thought this wasn't useful then we would definitely entertain a PR which allows for configuration to exclude this "future added value" entry

It seems actively harmful if it breaks working code where other solutions exist. A type system enforcing defensive coding against "arbitrary future values" seems the opposite of what type systems usually do — enforce that there are no arbitrary values, but only those that are defined in the type system. That's the whole point of the

        default:
          throw ((impossible: empty) => {})(val)

construct, is it not?

**Comment by nurbolnygmanov** [comment]
if I am using relay with autogenerated TS types, do i still need this option turned on?
