### ISSUE TITLE
optimisticResponse has some undocumented requirements

### ISSUE THREAD

**Issue by irrigator** [facebook/relay#2365]
I tested the optimisticResponse feature using Github's GraphQL API, and found some undocumented behaviors that might be confusing to users. The mutation code is below:
```javascript
import { graphql, commitMutation } from 'react-relay'

const mutation = graphql`
  mutation AddStarMutation($input: AddStarInput!) {
    addStar(input: $input) {
      starrable {
        ... on Repository {
          viewerHasStarred
        }
      }
    }
  }
`
function commit(environment, id) {
  return commitMutation(environment, {
    mutation,
    variables: {
      input: {
        starrableId: id,
      },
    },
    optimisticResponse: {
      addStar: {
        starrable: {
          id: id, // even though the mutation doesn't ask for this field, we still need to provide id for optimisitic update to work
          viewerHasStarred: true,
          __typename: 'can be any string', // ought to be 'Repository'
        },
      },
    },
  })
}
export default { commit }
```  
Here `starrable` is of type `Starrable`, which is an interface implemented by both `Repository` and `Gist` type. The start quide states that for optimistic update to  work:

>In the simplest case above, we just need to pass an optimisticResponse option, which should refer to an object having the same shape as the mutation response payload. 

But here, the requirements seems to be:

1. When the type of a field is an interface or an union, even if you use inline fragment to query the concrete type, you still need to provide a __typename for that field. Weirdly, the __typename need not to be accurate. Any string will do.

2. As you can see in the above example, the shape of optimisticResponse and the mutation need not to be same. What's important is that optimisticResponse must have an id, whether the mutation has id or not.

Are these bugs or technical limitations? If someone can clarify on this or point me to the related source code, I'd love to help with either code or documentation.

**Comment by alloy** [comment]
With regards to the shape of the optimistic response in relation to the mutation response payload, I think the confusing bit here is that your mutation payload probably _does_ have an `id` and a `__typename` field, even when you’re not requesting it. If you inspect the query that’s made and the resulting response, you’ll probably see these show up.

This is because Relay will automatically:
* select an `id` field, if it exists on the type, for cache denormalization purposes: https://github.com/facebook/relay/blob/3b4bb40448f72779d69d576f35752e1e1408f5bb/packages/relay-compiler/transforms/RelayGenerateIDFieldTransform.js#L87-L118
* select a `__typename` field in the case of a union or interface: https://github.com/facebook/relay/blob/3b4bb40448f72779d69d576f35752e1e1408f5bb/packages/relay-compiler/transforms/RelayGenerateTypeNameTransform.js#L33-L36

Alas I don’t see a good solution to this _other_ than documenting this behaviour.

----

I’m not actually sure _why_ `__typename` is automatically selected. If it’s only really meant to assist in using the type information (such as Flow) in the compiled artefacts (by conditionally executing code at runtime based on the type), then I guess that explains why it doesn’t matter what value you’re passing in. @jstejada do you know?

**Comment by alloy** [comment]
I’m not actually sure _why_ `__typename` is automatically selected. If it’s only really meant to assist in using the type information (such as Flow) in the compiled artefacts (by conditionally executing code at runtime based on the type), then I guess that explains why it doesn’t matter what value you’re passing in. @jstejada do you know?

**Comment by irrigator** [comment]
Seems like the doc is accurate. I created a pull request to explain this behavior: #2366.
