### ISSUE TITLE
Why `QueryRenderer` not to rerender when variables Change?

### ISSUE THREAD

**Issue by xyy94813** [facebook/relay#2447]
https://github.com/facebook/relay/blob/ac6e381e1287e2e9636511421922963db580deec/packages/react-relay/modern/ReactRelayQueryRenderer.js#L195-L200

Component `QueryRenderer` only need to render once?
Even variables changed?

**Comment by jstejada** [comment]
hey @xyy94813 the QueryRenderer itself wont re-render, but when you pass new variables we will re-fetch the query with the new variable and call your render prop again; does that make sense?

**Comment by xyy94813** [comment]
thx. 
But it didn't re-fetch after i upgrade relay to v1.6.0 in my project.

**Comment by ankit5174** [comment]
I have the Base Component which will have a QueryRenderer to fetch data for header, food items, filtering options. In the render method, i would like to display the <Header/>, <FoodList/> and a sidebar <FilterSidebar>. Now when on click of a item in <FilterSidebar>, i am changing the state in redux , which in turn is used as variables for the QueryRender. The QueryRender refetches the data again withe the new filters. The problem is since <Header/> and <Filtersidebar/> is also inside renderer method of queryrender, All the components get refreshed. Is there any way to handle this situation where only the listing changes based on new variables.

**Comment by sibelius** [comment]
@ankit5174 you need to use a refetch container in this case, instead of a QR

**Comment by ankit5174** [comment]
@sibelius I assume FoodList will be the refetch Container. If that is so then this.props.relay.refetch of FoodList will be available in the same component. But i need to make the refetch call from <FilterSidebar//> component. Any way we can expose the functions from one component to its sibling?
