### ISSUE TITLE
Different refs to React component in production and development

### ISSUE THREAD

**Issue by ntelkedzhiev** [facebook/relay#2486]
I'm trying to access the React component. In development the component can be access by: `reactComponent.refs.__INTERNAL__component` while in production (as described in #154) the ref is: `reactComponent.refs.component`.

Is this on purpose? Is there a better ways of accessing the original react component?

**Comment by kassens** [comment]
String refs have been deprecated for a long time with React and this was during a couple versions providing warnings.

You should be using the `ref` property and pass a callback function or `React.createRef()` to it which we in the latest version handle using `React.forwardRef` to give you a reference to the internal component instead of the higher order relay container component.
