### ISSUE TITLE
uv_os_get_passwd returned ENOENT in docker

### ISSUE THREAD

**Issue by alexesDev** [facebook/relay#2699]
I build my application in docker, pass current uid via `-u` and get an error becouse `/etc/passwd` don't have any info about `uid`. This error can be repeated like this.
```bash
docker run --rm -it -u 200 \ # any uid
  node:10.13-alpine \
  sh -c 'echo "require(\"os\").userInfo()" | node'

SystemError [ERR_SYSTEM_ERROR]: A system error occurred:
uv_os_get_passwd returned ENOENT (no such file or directory
```

I can mount `/etc/passwd` from host, but this is bad
```bash
docker run --rm -it -u 200 \
  -v /etc/passwd:/etc/passwd \
  node:10.13-alpine \
  sh -c 'echo "require(\"os\").userInfo()" | node'
```
If use `process.geteuid()` instead of `os.userInfo().username`, then there will be no problem.
https://github.com/facebook/relay/blob/d7c66caeb397fb68f42a7368e5fea2ae06d063aa/packages/relay-compiler/util/RelayCompilerCache.js#L43

**Comment by Hypnosphi** [comment]
@alexesDev how did you solve this issue?

**Comment by MoSattler** [comment]
I got the same issue as well. Though only in Docker in github actions.

**Comment by MoSattler** [comment]
Possibly related to this: https://github.com/nodejs/node/issues/25714

**Comment by toxsick** [comment]
Had the same thing with openshift. The problem was that my user present in `/etc/passwd`. This can be checked easily with `whoami`, because it failes in this case. When I add the current user like this, it works:

```
echo "${USER_NAME:-default}:x:$(id -u):0:${USER_NAME:-default} user:${HOME}:/sbin/nologin" >> /etc/passwd
```
In my case this is a [openshift topic](https://docs.openshift.com/container-platform/3.3/creating_images/guidelines.html#openshift-container-platform-specific-guidelines) that drives me nuts on a regular basis. I had to build a custom node image that adds `RUN chmod g=u /etc/passwd` to be able to do this.

Hope it helps someone.
