### ISSUE TITLE
TypeScript definitions are stale

### ISSUE THREAD

**Issue by jedmao** [facebook/relay#2765]
- The TypeScript definitions for Relay are now quite stale.
- **Related:** #2073 was back in 2017, so I'm not sure how invested Facebook is in 2019 to continue Flow support going forward.
- The golden path would be to generate type definitions with the TypeScript compiler.
- I don't know of any graceful project setup that would allow Flow and TypeScript to co-exist. As such, would the FB team be at all open to a community rewrite into TS? (a shot  in the dark)

**Comment by ckknight** [comment]
I manually converted the flow type definitions to TypeScript for 3.0, which mostly hold up for 4.0

I'll see about getting that into DefinitelyTyped next week, but I'm not fond of the strategy I took, as there are imperfections especially around the different ways that `?`, `null`, `undefined`, and `void` are handled within Flow as opposed to TypeScript.

**Comment by sibelius** [comment]
check this https://github.com/facebook/relay/issues/2073#issuecomment-338292538

can't you update the types on https://github.com/DefinitelyTyped/DefinitelyTyped?

to emit typescript for fragments you can use this plugin https://github.com/relay-tools/relay-compiler-language-typescript

**Comment by ckknight** [comment]
@sibelius yep, @alloy is great. My plan is to update his existing types which are currently out of date.

And yes, the `relay-compiler-language-typescript` plugin is fantastic.

**Comment by sibelius** [comment]
can we close this?

**Comment by ckknight** [comment]
As soon as I update those definitions, yes.

**Comment by jedmao** [comment]
This will continue to be a pain point as Relay code is updated and the TS definitions are always chasing its tail. The best solution would really be to have the source code written in TS, but I'm guessing that might be too much to ask.

**Comment by sibelius** [comment]
it won't happen soon I guess

**Comment by ckknight** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36212

**Comment by alloy** [comment]
While projects like Jest have made the move, I suspect that Relay is going to be a harder sell to FB. However, if by any chance the team _is_ interested but short on manpower, then I would gladly offer some of my time to help out.

**Comment by josephsavona** [comment]
> The best solution would really be to have the source code written in TS, but I'm guessing that might be too much to ask.

> While projects like Jest have made the move, I suspect that Relay is going to be a harder sell to FB. 

A few quick notes on this:

* For the most part we don’t have mandates about what technologies can and can’t be used, so our team does have the flexibility to choose to use/not use Flow or to use something else. That choice boils down to whether we (Relay core team) want to use another language, and think that changing languages is a worthwhile project relative to other things we could spend our time on. We’re fortunate to have a supportive manager in @yuzhiz and if there was a reasonable case to be made to change I’m confident she’d support us.   
* TypeScript is by all accounts great. If it’s the right fit for your team by all means use it. We’re happy to support folks who use Relay from TypeScript, though we depend more on OSS contributions here.
* As far as switching languages for Relay core: I can’t reasonably justify (even to myself) an effort to change language unless the alternative choice would enable us to build features or achieve performance that we couldn’t otherwise. The obvious elephant in the room is WASM. Using a lower-level language and compiling to WASM could *potentially* allow us to achieve things that we can’t in JS (and that matter for Relay use-cases). 

So: we’re probably not changing languages, if we do it probably won’t be a different gradually-typed JavaScript (or really any language w GC).

**Comment by alloy** [comment]
Alright, @ckknight’s type updates for Relay v4 are merged and an automated release should go out soon, so combined with @josephsavona’s comment I’m considering this issue resolved.
