### ISSUE TITLE
Sample code, docs in ES5.

### ISSUE THREAD

**Issue by AntouanK** [facebook/relay#278]
I admire the OSS we get from the Facebook team these days. Top quality stuff.
I don't get though why you enforce everyone to use every single ES6 feature when it's not really practical yet.

I'm trying to get a sample project with GraphQL and Relay, and although I like the concept a lot, I have to go through code that it's entirely written with every ES6 feat you can think of. Classes, destructuring, modules, you name it.
I love ES6, but not everyone is used to it yet, we are far from that.
And 99% of real production projects cannot actually ship those things. 
Actually no single browser supports all of those ES6 features.

Yes, I know we can use Babel, but by writing all the code in ES6, you practically make usage of babel a dependency. And for better or for worse, some people might not want to use babel ( it is a huge dependancy on many levels ).
At least you should give people an option.

So is there any way to get some ES5 examples?

Thanks.

**Comment by wincent** [comment]
Thanks for posting!

How fast to migrate towards new language features is something we've discussed internally.

One issue is the one you raise about engine support (which obviously will always lag behind the cutting edge), but there's also the question of readability: being very early adopters of new features may make the code less readable to people for whom things like destructuring and so on are new (or even unknown) concepts.

But it's complicated, as always. Here are a few reasons why we've consciously chosen to bias towards new features:

- Relay is (and will be) dependent on a transpilation/build step because of our heavy use of static analysis, our build time validation of queries (which is one of the big "fail fast" value-adds of GraphQL), and the necessity of turning those query fragments into the underlying concrete representation. Once you've got the build step, making use of additional build-enabled features comes at a negligible cost.
- People like playing with shiny new things (evidence of this is the pace of evolution of JavaScript, which is driven by people and not by technological change), so we think embracing the future will on the balance attract more users/contributors to the community than otherwise would be the case. My personal sense is that this is true internally at Facebook as well, where people are subjectively happier and objectively more effective when writing "modern" JavaScript.
- We see ourselves as not merely wanting to follow where the community is (and certainly not synchronizing with the "lowest common denominator" from among what is widely used and supported) but to actually help define what the future is. Some new features may feel a bit "out there", but we explicitly want to drive adoption so that they *don't* feel "out there" like that in the future. This is why we participate actively on TC39 and adopt what we consider to be beneficial new features early on.
- We feel that some of these new features (many of which we've originated at Facebook, such as JSX, Flow annotations, object spread notation etc) deliver substantial (not merely incremental) improvements to the developer experience and the ability of developers to produce reliable, robust, readable code. Some of these are highly experimental (stage 0 ES proposals, or not even slated to be baked into the language), but we push them because we think the upside is so large.
- With the explosion in the transpilation, linting, tooling ecosystem in recent years, the change to the yearly "train" model for ES specification, and future developments such as Web Assembly, we think the way people build JavaScript applications has fundamentally changed. All major browser vendors participate in the standards process and have baked-in autoupdaters on their platforms; they have effectively signed off on the idea that JavaScript is a fluid, moving target, and that polyfills and transpilers are (or are becoming) both the standard delivery mechanisms for JavaScript code and also the means with which the future shape of the language should be elaborated, vetted and tested.

So hopefully that gives you some insight into the reasons for our approach. We honestly think that the future may feel a little strange now, but before you know it it will seem the most natural thing in the world.

I'm going to close this for now, but feel free to comment further if you have additional thoughts on the topic.

**Comment by AntouanK** [comment]
@wincent  Thanks for the detailed response.
I respect your reasons, and most of them do sound valid. 
I believe you'll find that while some developers like "playing with shiny things", myself included, most are not comfortable with doing that on production, and companies/managers certainly don't want or allow that.

I do agree that you should push for evolving the language, but all I said is, give at least some option for the rest of the audience.
Like in React, there was a notion that "JSX is optional" and "here's how you do it with ES5 or without JSX". Although most devs used JSX. 
But, there was a choice.

Relay feels it went all in. ES6 and Babel or forget it.

In any case, thanks for sharing all of those libraries with everyone.
