### ISSUE TITLE
Q: Multiple entry points (routes) as single request with multiple queries?

### ISSUE THREAD

**Issue by jzalucki** [facebook/relay#279]
I want to start using Relay in my application but it can be done only part by part. This means that I will end up with several applications embedded inside page each with its own entry point. This way every entry point will be creating its own graphql query and will send it as separate request which obviously is not what I want to achieve.

Is there any possibility to have multiple entry points that will be collected and send to server as one request with multiple root queries? If not maybe there is a workaround that can be applied? Any suggestions are welcome.

**Comment by wincent** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

Questions like yours deserve a purpose-built Q&A forum. Would you like to post this question to Stack Overflow with the tag #relayjs? We'll be happy to answer there. Post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs

**Comment by jzalucki** [comment]
http://stackoverflow.com/questions/32517450/multiple-entry-points-routes-as-single-request-with-multiple-queries
