### ISSUE TITLE
Let server tell client where new item should be inserted in range

### ISSUE THREAD

**Issue by KyleAMathews** [facebook/relay#293]
Currently when a mutation returns a new item, in `getConfig` you can tell Relay to `append` or `prepend` the item to a list. This covers most cases as most lists are sorted by the created or updated date but there are times when using custom sorts that a new item would end up somewhere in the middle of a range. In these cases, it'd be nice if we could instruct the server to tell the client where a new item should be inserted.

**Comment by devknoll** [comment]
Some ideas...

### Server Side

The "best" way to achieve this would probably be to somehow query the server with the different sets of field args being used locally on a connection call, with a result being e.g. before/after cursors to help place it.

The problem is that you'll need to implement some sorting/filtering logic on the client regardless if you want to support optimistic updates.

### Client Side

Another solution would be to allow `rangeBehaviors` to be set to a function. It would receive the newEdge, currentEdges, and any field arguments, and return a new index for the edge:

```js
rangeBehaviors: (newEdge, currentEdges, args) => {
  // Filtering
  if (args.startsWith && !newEdge.name.startsWith(args.startsWith))
    return null;

  // Sorting
  if (args.orderBy) {
    return findIndexForOrderBy(newEdge, currentEdges, args.orderBy);
  }

  // Append/prepend
  return currentEdges.length;
},
```

**Comment by josephsavona** [comment]
Another option is to provide a way for the schema to define how field arguments correlate to sorting logic. For example, in the query `friends(first: 10, orderBy: "name")` the schema might indicate that edges should be sorted by the `name` field. Relay could use this metadata to automatically insert new edges at the correct location (and ensure that the `name` field was always fetched when this sort criteria was applied, so that every edge can be sorted correctly).

There are some cases where this may not be possible - in particular, algorithmically sorted connections such as the Facebook News Feed. In these cases, the schema could simply not define "order by" semantics for any arguments, and the client would have to specify append/prepend logic when adding edges.

These type of semantic schema annotations could apply more generally around connections, for example allowing for arbitrary names for `edges` and `node` fields and `first`/`after` arguments.

cc @dschafer @leebyron

**Comment by devknoll** [comment]
But one of the features of GraphQL that I really like is that it _doesn't_ have notion or semantics for sorting built in, and I'd love for it to stay that way :wink: 

Couldn't renaming connection args just be Relay specific configuration? 

My original client side proposal also had an option for `rangeBehaviors ` that looked like:

```js
rangeBehaviors: {
  'orderBy:$field': (newEdge, oldEdge, {field}) => newEdge[field].localeCompare(oldEdge[field]
}
```

It seems like these would cover the same use cases while remaining flexible and not having to add anything specific to the spec...

Thoughts? :+1:

**Comment by taion** [comment]
Caveat here that my understanding of `RANGE_ADD` is mediocre, but I believe that as a stopgap, it would be nice if one of the potential range behaviors were to "refresh" the connection from the server (perhaps it could even be the default).

Unless I'm misunderstanding something, right now I can't really express the case where I might want to prepend or append in default-ish cases, but re-pull the entire connection when using more complex arguments on the connection.

**Comment by josephsavona** [comment]
@taion The default is to refetch from the server, otherwise `append` or `prepend` behavior is used if specified. 

cc @yuzhi @steveluscher

**Comment by taion** [comment]
:+1: to that, then.

I feel like the cases where I care the most about not refetching the entire connection are usually the ones where operations look like simple appends or prepends.

I think @devknoll's server-side proposal is the most generic and broadly applicable solution, assuming the difficulties with identifying the edge for insert are manageable. I feel like putting even more of this sort of logic in the client is a messier direction API-wise, since I really want my server to own these aspects of the data.

I don't think it's very important that this makes optimistic updates more difficult - rather, I think optimistic updates in these cases in general look more like nice-to-haves, and specifically figuring out where the edge goes optimistically on the client side may not be necessary in many cases, or could be special-cased for important cases.

**Comment by leebyron** [comment]
> Another option is to provide a way for the schema to define how field arguments correlate to sorting logic. For example, in the query friends(first: 10, orderBy: "name") the schema might indicate that edges should be sorted by the name field.

I think this is really interesting. I think semantic knowledge of sort/filters could allow cache stores like Relay's to fulfill more cases. However I don't have much knowledge on what would actually need to be encoded in type definitions and schema introspection to provide relay with relevant data. As you point out, it can only do so much though, it can't tackle anything where information isn't provided in a field like an "edge rank" mechanism or where the sort order is a derivation of multiple fields. I'm happy to entertain more specific proposals on this front. 

> I think @devknoll's server-side proposal is the most generic and broadly applicable solution

I concur! It seems to me that there are two problems to solve here:

**1) Send a mutation to a server that results in a modified list then query a minimal set of information to update the list on the client. (The OP's question)**

This problem is broader than Relay and is about best practices when designing GraphQL mutations. 90% of cases can be solved by making an assumption that append/prepend will be the right behavior. Otherwise, I really like the idea of a server responding with a sort of "placement context". Just spitballing ideas here, for example:

```
{
  data {
    previousEdge { cursor }
    edge { cursor, node { id, ...AllYourData } }
}
```

If `previousEdge` is null, then this is a "prepend", otherwise this is an "insert after". This example could be extended to include `nextEdge` as well to quickly determine "append". Caveat this approach with the mutation would need to know things like sort/filters to determine these prev/next edges, and it may not be possible for the server to do this efficiently at all.

**2) Optimistic mutations by Relay**

Here, in order to support more variable behaviors like this one discussed in this issue, I think @devknoll's "client side" approach is in directionally correct. In my eyes an ideal "gloves off" approach would be to allow optimistic mutations to be specified by the app developer as "this is what I think the GraphQL response will be" - effectively mocking the server. That's a heavy API, but would allow for support of broader behavior.

**Comment by devknoll** [comment]
@dschafer posted an answer [here](http://stackoverflow.com/questions/32613879/should-the-opaque-cursors-in-connections-be-stable-across-different-field-args/32615799#32615799) that I thought was related, since it recommends embedding field arguments into edge creation.

With that in mind, maybe we could write a spec for the field types `newFriendsEdge `, that possibly also includes as an argument the list of cursors that Relay already has locally (half-jokingly suggested as a bloom filter for bandwidth savings) so the server could return an index, or a set of cursors to insert the edge between.

**Comment by taion** [comment]
@josephsavona Can you clarify what you mean by

>The default is to refetch from the server

Per my comment on #340, I can't seem to trigger this behavior at all.

**Comment by taion** [comment]
Okay, I think I understand that now.

For the refetch behavior, I need to actually specify the connection as an unterminated field in the fat query. Then if every call to the connection is mapped to either a valid range behavior (or a falsy value), then the unterminated field gets filtered out when intersecting the fat query and the subscribed set. Otherwise the full re-fetch happens, but it won't do what we want unless the unterminated field is specified in the fat query.

I'm sure I'm missing a half-dozen important things here - is there a chance of getting an update to the docs there, including to reflect the actual form of the calls (`field(value)` instead of `field:value`)? It's quite difficult to figure out how to even use the current implementation of range behaviors right now, even using the docs plus the source code plus stepping through the logic in a debugger.

**Comment by taion** [comment]
Regarding the server side thing, I just realized something in conjunction with working on my cursor-based pagination. There's a very standard "position plus offset" cursor-building strategy often used e.g. when sorting on timestamps that aren't guaranteed to be unique: http://cramer.io/2011/03/08/building-cursors-for-the-disqus-api/. In this case, if inserting a new edge in the middle of a connection leads to a new collision in timestamp, then this can potentially lead to cursors for other edges with the same timestamp changing.

Another thought here, though, is that general arbitrary sorting by field of connections doesn't really go well with cursor-based pagination. In the general case, for tables with lots of columns you might want to sort by, many of those columns may well not be particularly suited for cursor-based pagination anyway, so maybe the whole "understand arbitrary `orderBy` statements for connections in Relay" part is a bit moot, since often cursor pagination would not be appropriate for those types of collections anyway.

**Comment by taion** [comment]
One more complication here - there's no guarantee that the cursors are going to be the same for different server-side sorting behaviors. In fact most cursor-building strategies lead to different cursors based on the server-side sorting behavior. In other words, I don't think it's even possible to solve this with the current API for returning the created edge at all.

**Comment by josephsavona** [comment]
This is a great discussion, and we'd very much like to improve the mutations API. I've created a new meta-task at #538 to track this and several other related issues. Let's continue the discussion there!

**Comment by maxaggedon** [comment]
@leebyron would you have any recent resources on the `previousEdge` suggestion ? I am looking for best practices on that matter.

My problem is that the default cursor implementation is to represent the edge's index in an array, and therefore subsequent mutations fail to insert new edges at the right place. Would it be a better practice to set the node id as the edge cursor ?
