### ISSUE TITLE
Union types support in Relay.

### ISSUE THREAD

**Issue by jzalucki** [facebook/relay#296]
When you have defined field as an union of two types (in example machines contains Ships and Droid) then in Relay you can do something like that:
```
fragment on Faction@ relay(plural: true) {
  name,
  machines {
    ... on Ship {
      name
    }
    ... on Droid {
      name,
      primaryFunction
    }
  }
}
```
so under machines prop your objects are correctly evaluated, but if you want to do that using fragments from external components:
```
fragment on Faction@ relay(plural: true) {
  name,
  machines {
    ${StarWarsShip.getFragment('ship')}
    ${StarWarsDroid.getFragment('droid')}
  }
}
```
then you end up with fragment definitions under machines. It looks like you are trapped and can't check which object is which type in machines array so you can't decide which component should be used.

**Comment by steveluscher** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

Questions like yours deserve a purpose-built Q&A forum. Would you like to post this question to Stack Overflow with the tag #relayjs? We'll be happy to answer there. Post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs

**Comment by steveluscher** [comment]
Ping! I'm really dying to answer that you can include a `__typename` field in your query, but I'd like you to post the question on Stack Overflow where people can continue to benefit from the answer long after this GitHub issue is closed.

**Comment by jzalucki** [comment]
Posted here:
http://stackoverflow.com/questions/32558861/union-types-support-in-relay
