### ISSUE TITLE
why diffrent behaviors when execute quey with and without composing fragment?

### ISSUE THREAD

**Issue by videni** [facebook/relay#2982]
This is quite confusing,  please check this [unable to get correct data using `useLazyLoadQuery` when compose fragment into query](https://github.com/facebook/relay/issues/2979),  the `useLazyLoadQuery` sometime returns  json data obstained from http server, sometims it retusn a generated graphql request definition defined in  'src/__generated' directory.

**Comment by sibelius** [comment]
When using fragments we have data masking

Data masking will only show data to the component that declared the data

Example, if a component only asks for User name, it won’t be able to access User email, even if the query has if because of another component

Reread the docs to understand better, also run and modify relay-examples to play with data masking

**Comment by videni** [comment]
@sibelius, I see , thanks
