### ISSUE TITLE
Cryptic runtime error in relay 8.0.0 "Warning: RelayGraphQLTag: node ... unexpectedly wrapped in a function."

### ISSUE THREAD

**Issue by agdt3** [facebook/relay#2990]
We've recently updated to `relay 8.0.0` from `7.1.0` and are now starting to see the following error in console and while running unit tests:
`
console.error node_modules/relay-runtime/node_modules/fbjs/lib/warning.js:30
Warning: RelayGraphQLTag: node [Query] unexpectedly wrapped in a function.
`

package.json (partial)
`
"react-relay": "^8.0.0",
"relay-runtime": "^8.0.0",
"relay-test-utils": "^8.0.0",
"react-relay-network-modern": "^4.4.0",
"babel-plugin-relay": "^6.0.0",
"relay-compiler": "^8.0.0",
`

Any help is appreciated!

**Comment by sibelius** [comment]
upgrade babel-plugin-relay to v8

**Comment by agdt3** [comment]
Thank you very much!

**Comment by agdt3** [comment]
FYI: Just tested this with `"babel-plugin-relay": "^8.0.0"`, still getting the same error.

**Comment by sibelius** [comment]
flow or typescript?

try to remove all __generated__ and regenerate them

**Comment by agdt3** [comment]
Neither. Nuked the `__generated__` folder and re-ran relay compiler. Same issue.

**Comment by sibelius** [comment]
make sure all relay version are the same

```jsx
yarn why react-relay
yarn why relay-runtime
```

is this web ou app?

**Comment by sibelius** [comment]
can you great a repro?

check this https://github.com/relayjs/relay-examples/pull/131

**Comment by agdt3** [comment]
`=> Found "react-relay@8.0.0"`
`=> Found "relay-runtime@8.0.0"`
`=> Found "babel-plugin-relay@8.0.0"`

This is a react webapp.

OK, so I've deleted and re-created everything. No longer see errors in console, but do see these as errors when running jest tests, so might be related to `jest (24.9)` and/or `relay-test-utils (8.0.0)`.

**Comment by sibelius** [comment]
try to remove jest cache

it looks like it is not transpiling correct

**Comment by agdt3** [comment]
Looks like that worked. Thank you again!

**Comment by apuntovanini** [comment]
We're facing the same issue, tried 
- removing node_modules and yarn install again
- check versions
- regenerated queries

but cant' get it to work.

In addition to this, when trying to print the error, can't find the node and raises an error. We did not change anything in our queries and/or component since v7 (that works).

```
Uncaught TypeError: Cannot read property 'name' of undefined
    at getNode (GraphQLTag.js:32)
```

We use typescript, may it be an issue with relay-compiler-language-typescript?

**Comment by kejistan** [comment]
I also encountered this issue and the root cause ended up being `babel-loader`'s cache. Clearing the cache directory resolved this.

**Comment by apuntovanini** [comment]
@kejistan indeed, got it working! Thank you very much!

**Comment by AlicanC** [comment]
This worked for our CRA-based setup:
```bash
rm -rm node_modules/.cache/
rm src/**/__generated__/*.graphql.js
```

**Comment by wasd171** [comment]
We are also experiencing issues with the generated TS files, even after removing the `node_modules` and `__generated__` the result of running the `relay-compiler` is the same

**Comment by earksiinni** [comment]
We're also having the exact same problem as @apuntovanini (`Uncaught TypeError: Cannot read property 'name' of undefined at getNode (GraphQLTag.js:32)`) and we're also using TypeScript. However, not all of our team members are encountering the issue. Clearing babel cache and compiled fragments didn't help.

cc: @perryazevedo

**Comment by sibelius** [comment]
Clear all the caches

Babel
Watchman
Metro-bundler
Webpack
Jest
__generated__
typescript

**Comment by earksiinni** [comment]
@sibelius, I admit that it feels like a caching issue due to the fact that it's inconsistently broken, but I'm not sure what else to try. We ran the following:

```
# Clear __generated__
find . -name __generated__ -type d -print0|xargs -0 rm -r --
# Clear node_modules cache
rm -rf node_modules/.cache
```

We're not using Jest (or any other kind of testing), Watchman, or Metro bundler. TS to my knowledge doesn't cache anything.

Any other places we should be looking for caches/commands we should try running?

**Comment by sibelius** [comment]
Try to create a repro

**Comment by earksiinni** [comment]
I've isolated the immediate cause for our issue, but I'm not sure why it's happening.

[In a recent change](https://github.com/facebook/relay/commit/0439857775005d33b81b185f2f26d8bb04d3795b#diff-48a2a9393036e1af24710e0151a63fc1) to GraphQLTag.js, [these lines were added](https://github.com/facebook/relay/blob/v8.0.0/packages/relay-runtime/query/GraphQLTag.js#L55-L65):

```
if (typeof node === 'function') {
  node = (node(): ReaderFragment | ConcreteRequest);
  warning(
    false,
    'RelayGraphQLTag: node `%s` unexpectedly wrapped in a function.',
    node.kind === 'Fragment' ? node.name : node.operation.name,
  );
} else if (node.default) {
  // Support for languages that work (best) with ES6 modules, such as TypeScript.
  node = node.default;
}
```

The problem in our case is that `node` is a function that, instead of returning a node, returns an object that has a single `default` field that contains the node, so `node.operation.name` fails. Seems like the `else if (node.default)` is intended to catch this case, but it doesn't account for default exports returned by functions-wrapped nodes...?

Our workaround is to patch the code above by inserting `if (node["default"]) node = node.default;` after `node = (node(): ReaderFragment | ConcreteRequest);`. Then we're able to see the warnings.

I don't know enough about `relay-runtime` to create a repro, but I do know that this is happening for one developer on our team even after we've cleared his caches, nuked the repo and started from scratch, etc. Doesn't happen for the other devs.

**Comment by earksiinni** [comment]
This seems relevant: https://github.com/facebook/react/issues/12453#issue-308403033

I traced `node` back to https://github.com/facebook/relay/blob/v8.0.0/packages/react-relay/buildReactRelayContainer.js#L73. I'm guessing that for our dev and possibly others, `forwardRef` is returning a function. If that's the case, React needs to be upgraded and a more helpful message should be displayed. Will confirm.

**Comment by wasd171** [comment]
We are using `relay-compiler-language-typescript`, but the solution proposed by @earksiinni has also fixed the `Uncaught TypeError: Cannot read property 'name' of undefined at getNode` issue

**Comment by saltycrane** [comment]
I upgraded Relay from `v7.1.0` to `v9.0.0` in a Next.js project. The error was caused by a caching issue. The solution for me was to delete the `.next/cache/next-babel-loader` directory.

A side note: at first I thought [@earksiinni's solution](https://github.com/facebook/relay/issues/2990#issuecomment-590632687) to set `eagerESModules` to `true` was the fix. But I realized that changing my babel config must have busted the next-babel-loader cache to make the error go away, but it wasn't the true solution.

**Comment by nirvdrum** [comment]
I was having the same problem as @earksiinni, upgrading from 7.1.0 to 9.0.0. Before finding this issue, I modified `relay-runtime` to dig into `node["default"]`, which fixed the problem, but I ended up with the warning @agdt3 reported (which is how I found this issue). I'm happy to say the fix was the same: clear jest's cache. With that, I was able to back out my modification to `relay-runtime`. I don't think any change is needed in Babel.

I didn't even know jest had a cache, so this issue was illuminating in a couple ways. If jest doesn't invalidate the cache when it should, I can see that being an ongoing problem. But, at least I have a new thing to add to the checklist when tests go haywire.
