### ISSUE TITLE
Make publish process more fool-proof

### ISSUE THREAD

**Issue by wincent** [facebook/relay#303]
So v0.3.0 was a broken build (see #301) that I had to redo and supersede with v0.3.1.

This was the first time I'd done the release, so I inspected the `package.json` to see what would happen on running `npm publish`. Based on that reading, I expected this to happen:

- `prepublish` would run, which would...
- run `build`, which would...
- kick off `gulp`, which would...
- build things such as the files under `dist`, then...
- actually publish to NPM

What actually happened:

- as above, but the `gulp` build threw an error, and ...
- the module got published anyway

I blew away my state, reinstalled and ran `gulp` again to be sure it could run to completion without error, but I didn't realize that the built package itself was faulty until #301 was reported.

So, this is unfortunate and I am sorry it happened, but we should try to make the whole thing more resilient such that this particular failure mode can't happen again.

Open questions:

- did the `gulp` build actually exit with a non-zero exit status on hitting the error?
- if so, does that failure affect the overall return status of the `build` subtask?
- and correspondingly, is a `build` failure enough to make `prepublish` abort?

**Comment by zpao** [comment]
I don't think gulp did exit with non-zero. And yes, I'm pretty sure a non-zero `prepublish` would have aborted `publish`.

There are 2 pieces here.

1. The very dumb module rewriting, which in order to be fast (and simple), doesn't actually resolve modules, just works purely in inputs (though will throw on duplicates). We could make it actually do some resolution (eg, just in map or relative), would just slow it down a little bit.
2. In this case it was the webpack step which "failed" and I would have expected to error with non-zero but perhaps this doesn't do what we want (https://github.com/facebook/relay/blob/master/gulpfile.js#L98).

**Comment by wincent** [comment]
I'll see if I can repro what actually happened so that we're not shooting in the dark here.

**Comment by zpao** [comment]
`npm install fbjs@0.2.0` and then you should see exactly what happened (perhaps with a minor difference of something saying how you got the dependency installed - `fbjs@^0.2.0` vs `fbjs@0.2.0`)

**Comment by wincent** [comment]
I think ab2afb30b7c53bca75638758acc4a3a4f0542309 is mitigation enough for now. Thanks, @zpao.
