### ISSUE TITLE
variable value set via prop is not considered in fetch

### ISSUE THREAD

**Issue by Gregoor** [facebook/relay#309]
Apparently it is currently possible to set variables via identically named props. The subsequent(?) request however does not consider that set value.

I saw that you already have an issue for this in your internal bug tracker (https://github.com/facebook/relay/blob/d2f9ae54ba1a8810a1a43ef199e073687932c2d3/src/container/RelayContainer.js#L832), but I thought this issue might be valuable for other people who run in the same problem.

i just renamed the variable, which worked fine for me.

**Comment by josephsavona** [comment]
For context, `variables` have to passed as as props to child components because of cases like this:

```javascript
// Container
fragments: {
  user: () => Relay.QL`
    fragment on User {
      ${Picture.getFragment('pic', {size: 32})},
      ${Picture.getFragment('pic', {size: 128})},
    }
  `
// Component
render() {
  return <Picture pic={this.props.user} />; // does this use `size: 32` or `size: 128`?
}
```

But rendering `<Picture pic={this.props.user} size={32} />` makes it clear which set of variables apply to the child.


That said, this is an area of the API that we'd like to clean up. One proposal is the following:

```javascript
// Container
fragments: {
  user: () => Relay.QL`
    fragment on User {
      ${Picture.getFragment('pic', {size: 32})} @relay(alias: 'lilPic'), # give an explicit alias...
      ${Picture.getFragment('pic', {size: 128})}, @relay(alias: 'bigPic')
    }
  `
// Component
render() {
  return <Picture pic={this.props.user.lilPic} />; // ...and reference it here (no need to pass variables)
}
```

**Comment by fson** [comment]
@josephsavona Why not use the [GraphQL syntax for aliases](http://facebook.github.io/graphql/#sec-Field-Alias) instead of the special `@relay` directive in this case?
```js
fragments: {
  user: () => Relay.QL`
    fragment on User {
      lilPic: ${Picture.getFragment('pic', {size: 32})},
      bigPic: ${Picture.getFragment('pic', {size: 128})},
    }
  `
```

**Comment by josephsavona** [comment]
@fson That would be awesome - but that syntax is not supported for fragments. The above is equivalent to the following:

```
fragments: {
  user: () => Relay.QL`
    fragment on User {
      # invalid..
      lilPic: ... on Picture { ... },
      bigPic: ... on Picture { ... }
    }
  `
```

**Comment by fson** [comment]
@josephsavona Oh, I see.

In the `@relay(alias: 'bigPic')` example, I assume Relay would convert it to something like this:
```graphql
fragment on User {
  lilPic: profilePic($size1) {
    ... on Picture { ... },
  }
  bigPic: profilePic($size2) {
    ... on Picture { ... }
  }
}
```
Where is the name of the field (`profilePic` in this case) defined?

**Comment by josephsavona** [comment]
cc @schrockn @leebyron

**Comment by josephsavona** [comment]
@fson Relay can't convert to `lilPic: profilePic ...` because that assumes the fragment has one root field, which is rarely the case. 

Per offline discussion with @leebyron and @dschafer we'll probably have to add support for fragment aliases in the language to make this seamless. This would use your earlier proposal, @fson:

```
fragment on User {
  foo: ${Child.getFragment('foo')},
}
```

**Comment by fson** [comment]
Thanks for the clarification @josephsavona.

This seems like the most obvious syntax. However, wouldn't it also assume a fragment with just one field that it can alias? What would happen if you try to apply it to fragment with many fields?

**Comment by josephsavona** [comment]
@fson the response for aliased fragments would be an object:

```javascript
# source fragment
var userFragment = Relay.QL`
  fragment on User {
    id,
    name,
  }
`;
```

Then use it:
```
# query
fragment on Foo {
  user: ${userFragment} # equivalent to `user: ...fragmentName`
}
# response
{
  user: {
    id: "...",
    name: "...",
  }
}
```

**Comment by fson** [comment]
If that's how it would work, how does that differ from this (currently supported) syntax?
```js
fragment on Foo {
  user {
    ${userFragment}
  }
}
```
Maybe there is some more complex use case that I'm not seeing right now...

**Comment by josephsavona** [comment]
@fson the new syntax would create a new object, into which the results of the fragment are spread. The current syntax spreads the result into the *outer* fragment.

Old result:
```
{
  id: "...",
  name: "...",
}
```

New result:
```
{
  user: {  // <-- fragment results are nested inside a new object
    id: "...",
    name: "...",
  }
}
```

**Comment by fson** [comment]
Ah, I got it now :+1: Thanks.

**Comment by saikat** [comment]
Am I right in thinking that this issue is saying that if I have a Relay container with variables set up like this:

```javascript
export default Relay.createContainer(CallViewer, {
  initialVariables: {
    callId: "testId"
  },

  fragments: {
    viewer: () => Relay.QL`
        call(id:$callId) {
          ${Call.getFragment('call')}
        }
      }
    `,
  },
});
```

And then I render it like this:

```
<CallViewer callId="anotherId" />
```

anotherId will override the value of callId but will not actually cause a re-fetch?

**Comment by taion** [comment]
You need to pass through the variable mapping with `getFragments` as well, e.g. `${CallViewer.getFragments('viewer', variables)}`

**Comment by vladar** [comment]
@josephsavona Looks like we have to pass both - variable mapping __and__ prop with same name to make this work as @taion mentions above.

My example:
I need to display different number of items in connection for different scenarios. Child fragment has variable `commentsShown`.

But if I only pass variable mapping (without props) - Relay fetches all items as expected, but truncates them to initial variable value on render.

If I only pass `prop` with same name - Relay won't fetch all items (subject of this issue).

If I pass both - `commentsShown` variable and `commentsShown` prop everything works as expected. But that seems odd for me. 

Am I missing something?

**Comment by josephsavona** [comment]
@vladar yup! This is because you might use the same fragment twice with different variables. See my answer above: https://github.com/facebook/relay/issues/309#issuecomment-140485321

**Comment by netgusto** [comment]
Variables set via props are (silently) breaking the fetch indeed.

Is this supposed to work ?

If not, what's the proper way to fetch data using variables based on props owned by the parent ? I tried setting relay variables in the component constructor, but:

* I suspect this is an anti-pattern
* relay triggers a first fetch with initial values for variables before using the variables set in the component  constructor

**Comment by taion** [comment]
You're doing it wrong - follow the pattern above and inject the variables in via the container as well as via props.

**Comment by netgusto** [comment]
@taion but these prop'd variables are known only in the component context, and not statically in the `fragments` section of the relay container (for instance, a piece of state handled by a component).

Is there something I'm missing ? I mean, fragment variables live in a static context, and I can't see how I would be able to access component runtime data within that static context. Could you explain me, please ?

**Comment by vladar** [comment]
@netgusto 

You should define variable mapping when including nested fragment:

```
viewer: (variables) => Relay.QL`
  someField {
    ${NestedContainer.getFragment('someField', {variable1: 'my-constant', variable2: variables.myProp})}
  }
}
`,
```

Then when your component is rendered with custom `myProp` Relay will assign it to nested container variable (`variable2` in this example). Note, that `myProp` must also be defined in `initialVariables` even if it's `null`.

**Comment by quazzie** [comment]
How to do this for nested structure ?

https://stackoverflow.com/questions/34255662/props-in-relay-preparevariables

I want to set expanded for some of the tree.
I have saved the expanded state and when i navigate i save this in sessionStorage, when i return i want to restore the expanded state of all the branches and leafs.

**Comment by josephsavona** [comment]
@quazzie Thanks for asking. I'm writing an answer to your question on Stack Overflow.

**Comment by netgusto** [comment]
@taion @vladar Thanks for you answers.

Still, the relay variables set in the parent (`Freelance`) are set in the nested component (`FreelanceList`), but not used by relay in the query fragment defined by `FreelanceList`.

```javascript
import React from 'react';
import Relay from 'react-relay';

class FreelanceList extends React.Component {

    static propTypes = {
        job: React.PropTypes.string.isRequired,
        city: React.PropTypes.string.isRequired,
        first: React.PropTypes.number.isRequired,
        viewer: React.PropTypes.object.isRequired,
        relay: React.PropTypes.object.isRequired
    };

    render() {
        return (
            <div>
                <h2>Freelances {this.props.job} à {this.props.city}</h2>
                <ul>
                {!!this.props.viewer.freelances && this.props.viewer.freelances.edges.map(edge => (
                    <li>{edge.node.firstname} {edge.node.job}</li>
                ))}
                </ul>
            </div>
        );
    }
}

FreelanceList = Relay.createContainer(FreelanceList, {
    initialVariables: { job: null, first: null },
    fragments: {
        viewer: () => Relay.QL`
            fragment on Viewer {
                freelances(job: $job, first: $first) {
                    edges {
                        node {
                            id
                            ... on Freelance {
                                firstname
                                lastname
                                job
                            }
                        }
                    }
                }
            }
        `
    }
});

class Freelances extends React.Component {

    static propTypes = {
        params: React.PropTypes.object.isRequired,
        location: React.PropTypes.object.isRequired,
        viewer: React.PropTypes.object.isRequired,
        relay: React.PropTypes.object.isRequired
    };

    render() {
        return (
            <FreelanceList viewer={this.props.viewer} job={this.props.params.job} city={'Paris'} first={10} />
        );
    }
}

Freelances = Relay.createContainer(Freelances, {
    fragments: {
        viewer: (variables) => Relay.QL`
            fragment on Viewer {
                ${FreelanceList.getFragment('viewer', variables)}
            }
        `
    }
});
```

**Comment by netgusto** [comment]
I've set up this playground that reproduces the problem: https://goo.gl/i7uuMt

**Comment by netgusto** [comment]
anyone ?

**Comment by vladar** [comment]
@netgusto Yeah, this variable mapping process is one of the most error-prone and unclear areas in Relay.

It is better to understand it's internals better to avoid pitfalls. You must realize that GraphQL query is prepared in static time - before components are rendered. Relay cannot know value of your `props` at  this point in time. That is why it must be passed in as variable (route param for initial rendering).

But in your example `HelloRoute` doesn't define any variable mappings and is rendered without any params. As a result GraphQL query is constructed with default values!

To make your example work you must 1) change your Route:
```javascript
class HelloRoute extends Relay.Route {
  static routeName = 'Hello';  // A unique name
  static paramDefinitions = {
    message: {required: true}
  };
  static queries = {
    echoz: (Component, variables) => Relay.QL`
      query {
        Viewer {
          ${Component.getFragment('echoz', {message: variables.message})},
        }
      }
    `,
  };
}
```

2) Add your message as route param on render:
```javascript
ReactDOM.render(
  <Relay.RootContainer
    Component={HelloApp}
    route={new HelloRoute({message: "my message from props"})}
  />,
  mountNode
);
```

3) As far as I understand Relay expects explicit mapping, so your `HelloApp` container must be also tweaked:
```javascript
HelloApp = Relay.createContainer(HelloApp, {
  initialVariables: {message: null},
  fragments: {
    echoz: (variables) => Relay.QL`
      fragment on Viewer {
          ${HelloNested.getFragment('echoz', {message: variables.message})}
      }
    `,
  }
});
```

Note: this is how you do it to construct initial query for route. But for subsequent queries, you use `setVariables()` + `props`.

**Comment by netgusto** [comment]
Thank you @vladar for your detailed answer. Applying your advices, I can't get it to work on the React Playground.

It's bugging me how difficult it is to use relay for some simple use cases. Maybe my approach is wrong.

What I've found difficult so far :

* Static query resolution; I understand why it's done that way, and do not complain; but some use cases (using a piece of component state as a variable) are simply not possible (I'd be happy if someone could prove me wrong on the Relay playground above :) )
* Viewer to work around issue #112
* naming is very slippery; especially, everything seems to breaks if a fragment is named the same as one of it's nested fragments; every parent component has to know the name of the fragments its children expect to be fetched
* the flow of data as props between parent / child is unclear to me; also, very difficult to debug when data does not flow correctly (until the Relay dev tools are released maybe ?)
* No integrated paginated connection; some apps still make good use of paged lists, and do not use infinite scroll

This is not a complain, do not get me wrong. I appreciate the effort the community and FB puts in this project.

Thanks !

**Comment by vladar** [comment]
Hey, try https://goo.gl/08PZ7g - working version on playground.

Also note that I am not a member of Relay team, so no comments on your points, although I do share some of them.

**Comment by josephsavona** [comment]
@vladar thanks for answering so many questions here and for the working playground. there's one hand-coded message left though...

@netgusto [here](https://facebook.github.io/relay/prototyping/playground.html#source=%2F%2F%20LINE%2024%20below%3B%20change%20%22the%20static%20message%22%20below%20by%20%24message%20%3A%20boom%20!%0A%0Aclass%20HelloNested%20extends%20React.Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20%2F%2F%20Relay%20will%20materialize%20this%20prop%20based%20on%20the%0A%20%20%20%20%2F%2F%20result%20of%20the%20query%20in%20the%20next%20component.%0A%20%20%20%20var%20%7Bmessageback%7D%20%3D%20this.props.echoz.echo%3B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%3Ch1%3E%7Bmessageback%7D%20!%3C%2Fh1%3E%0A%20%20%20%20%20%20%20%20%3Chr%20%2F%3E%0A%20%20%20%20%20%20%20%20%3Cpre%3E%7BJSON.stringify(this.props%2C%20null%2C%202)%7D%3C%2Fpre%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20)%3B%0A%20%20%7D%0A%7D%0A%0AHelloNested%20%3D%20Relay.createContainer(HelloNested%2C%20%7B%0A%20%20initialVariables%3A%20%7B%20message%3A%20null%20%7D%2C%0A%20%20fragments%3A%20%7B%0A%20%20%20%20%2F%2F%20change%20%22the%20static%20message%22%20below%20by%20%24message%20%3A%20boom%20!%0A%20%20%20%20echoz%3A%20()%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20fragment%20on%20Viewer%20%7B%0A%20%20%20%20%20%20%20%20echo(message%3A%20%24message)%20%7B%0A%20%20%20%20%20%20%20%20%20%20messageback%2C%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%0A%7D)%3B%0A%0A%2F**%0A%20*%20%231%20-%20Your%20React%20components%0A%20*%20This%20will%20look%20familiar%20to%20React%20developers.%0A%20*%0A%20*%20To%20learn%20more%20about%20React%2C%20visit%3A%0A%20*%20%20https%3A%2F%2Ffacebook.github.io%2Freact%0A%20*%2F%0Aclass%20HelloApp%20extends%20React.Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3CHelloNested%20%0A%20%20%20%20%20%20%20%20echoz%3D%7Bthis.props.echoz%7D%20%0A%20%20%20%20%20%20%20%20message%3D%7Bthis.props.relay.variables.message%7D%0A%20%20%20%20%20%20%20%20%2F%3E%0A%20%20%20%20)%3B%0A%20%20%7D%0A%7D%0A%0A%2F**%0A%20*%20%232%20-%20Relay%20containers%0A%20*%20Compose%20your%20React%20components%20with%20a%20declaration%20of%0A%20*%20the%20GraphQL%20query%20fragments%20that%20fetch%20their%20data.%0A%20*%0A%20*%20To%20learn%20more%20about%20Relay%20containers%2C%20visit%3A%0A%20*%20%20%20https%3A%2F%2Ffacebook.github.io%2Frelay%2Fdocs%2Fguides-containers.html%0A%20*%2F%0AHelloApp%20%3D%20Relay.createContainer(HelloApp%2C%20%7B%0A%20%20initialVariables%3A%20%7Bmessage%3A%20null%7D%2C%0A%20%20fragments%3A%20%7B%0A%20%20%20%20echoz%3A%20(variables)%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20fragment%20on%20Viewer%20%7B%0A%20%20%20%20%20%20%20%20%20%20%24%7BHelloNested.getFragment('echoz'%2C%20%7Bmessage%3A%20variables.message%7D)%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%0A%7D)%3B%0A%0A%2F**%0A%20*%20%233%20-%20Relay%20routes%0A%20*%20Define%20a%20root%20GraphQL%20query%20into%20which%20your%0A%20*%20containers'%20query%20fragments%20will%20be%20composed.%0A%20*%0A%20*%20To%20learn%20more%20about%20Relay%20routes%2C%20visit%3A%0A%20*%20%20%20https%3A%2F%2Ffacebook.github.io%2Frelay%2Fdocs%2Fguides-routes.html%0A%20*%2F%0Aclass%20HelloRoute%20extends%20Relay.Route%20%7B%0A%20%20static%20routeName%20%3D%20'Hello'%3B%20%20%2F%2F%20A%20unique%20name%0A%20%20static%20paramDefinitions%20%3D%20%7B%0A%20%20%20%20message%3A%20%7Brequired%3A%20true%7D%0A%20%20%7D%3B%0A%20%20static%20queries%20%3D%20%7B%0A%20%20%20%20echoz%3A%20(Component%2C%20variables)%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20query%20%7B%0A%20%20%20%20%20%20%20%20Viewer%20%7B%0A%20%20%20%20%20%20%20%20%20%20%24%7BComponent.getFragment('echoz'%2C%20%7Bmessage%3A%20variables.message%7D)%7D%2C%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%3B%0A%7D%0A%0A%2F**%0A%20*%20%234%20-%20Relay%20root%20containers%0A%20*%20Compose%20a%20Relay%20container%20with%20a%20Relay%20route.%0A%20*%20This%20enables%20Relay%20to%20synthesize%20a%20complete%20query%0A%20*%20to%20fetch%20the%20data%20necessary%20to%20render%20your%20app.%0A%20*%0A%20*%20To%20learn%20more%20about%20Relay%20root%20containers%2C%20visit%3A%0A%20*%20%20%20https%3A%2F%2Ffacebook.github.io%2Frelay%2Fdocs%2Fguides-root-container.html%0A%20*%2F%0AReactDOM.render(%0A%20%20%3CRelay.RootContainer%0A%20%20%20%20Component%3D%7BHelloApp%7D%0A%20%20%20%20route%3D%7Bnew%20HelloRoute(%7Bmessage%3A%20%22my%20message%20from%20props%22%7D)%7D%0A%20%20%2F%3E%2C%0A%20%20mountNode%0A)%3B%0A&schema=%2F**%0A%20*%20Copyright%202013-2015%2C%20Facebook%2C%20Inc.%0A%20*%20All%20rights%20reserved.%0A%20*%0A%20*%20This%20source%20code%20is%20licensed%20under%20the%20BSD-style%20license%20found%20in%20the%0A%20*%20LICENSE%20file%20in%20the%20root%20directory%20of%20this%20source%20tree.%20An%20additional%20grant%0A%20*%20of%20patent%20rights%20can%20be%20found%20in%20the%20PATENTS%20file%20in%20the%20same%20directory.%0A%20*%2F%0A%0Aimport%20%7B%0A%20%20GraphQLObjectType%2C%0A%20%20GraphQLSchema%2C%0A%20%20GraphQLString%2C%0A%7D%20from%20'graphql'%3B%0A%0A%20%20var%20EchoType%20%3D%20new%20GraphQLObjectType(%7B%0A%20%20name%3A%20'Echo'%2C%0A%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20%20%20messageback%3A%20%7B%0A%20%20%20%20%20%20%20%20type%3A%20GraphQLString%0A%20%20%20%20%20%20%7D%0A%20%20%7D)%2C%0A%7D)%3B%0A%0Avar%20ViewerType%20%3D%20new%20GraphQLObjectType(%7B%0A%20%20name%3A%20'Viewer'%2C%0A%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20echo%3A%20%7B%0A%20%20%20%20%20%20%20%20type%3A%20EchoType%2C%0A%20%20%20%20%20%20%20%20args%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20message%3A%20%7B%20type%3A%20GraphQLString%20%7D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20resolve%3A%20(root%2C%20args)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20console.log('ARGS%20IN%20GRAPHQL'%2C%20args)%3B%0A%20%0A%20%20%20%20%20%20%20%20%20%20return%20%7B%20messageback%3A%20'YOU%20SAID%20%3A%20'%20%2B%20args.message%20%7D%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%7D)%2C%0A%7D)%3B%0A%0A%0A%2F**%0A%20*%20The%20schema.%0A%20*%20Here%20we%20export%20a%20schema%20that%20offers%20one%20root%0A%20*%20field%20named%20'greetings'%2C%20and%20a%20method%20to%0A%20*%20resolve%20its%20data.%0A%20*%0A%20*%20To%20learn%20more%20about%20writing%20GraphQL%20schemas%20for%20Relay%2C%20visit%3A%0A%20*%20%20%20https%3A%2F%2Fgithub.com%2Fgraphql%2Fgraphql-relay-js%0A%20*%2F%0Aexport%20default%20new%20GraphQLSchema(%7B%0A%20%20query%3A%20new%20GraphQLObjectType(%7B%0A%20%20%20%20name%3A%20'RootQueryType'%2C%0A%20%20%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20%20%20Viewer%3A%20%7B%0A%20%20%20%20%20%20%20%20type%3A%20ViewerType%2C%0A%20%20%20%20%20%20%20%20resolve%3A%20()%20%3D%3E%20(%7B%20%7D)%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D)%2C%0A%20%20%7D)%2C%0A%7D)%3B%0A) is an edited version of the playground with variables passing though from the route through to the bottom component.

Thanks for the great questions and observations. I'll try to provide a bit more context:

> Static query resolution; I understand why it's done that way, and do not complain; but some use cases (using a piece of component state as a variable) are simply not possible (I'd be happy if someone could prove me wrong on the Relay playground above :) )

We agree that passing variables in both the static query and as props is not ideal, but it's currently necessary to distinguish between the same container being referenced multiple times with different variables - see my [earlier comment](https://github.com/facebook/relay/issues/309#issuecomment-140485321). Also note that it's absolutely possible to use component state as a variable - if you're willing to make multiple round trips for data. Relay optimizes for a single round-trip by default using static variables, but for complex use-cases you can use `setVariables` after the component mounts to fetch additional data (based on the previously fetched data or local state).

> naming is very slippery; especially, everything seems to breaks if a fragment is named the same as one of it's nested fragments; every parent component has to know the name of the fragments its children expect to be fetched
> the flow of data as props between parent / child is unclear to me; also, very difficult to debug when data does not flow correctly (until the Relay dev tools are released maybe ?)

Fragments can be named the same as children fragments without issue, but I can see how it might have appeared that this wasn't the case while you were debugging other issues. We agree with your second point here that Relay could (should) be more debuggable. Now that the core functionality is stable, this is something we'd like to work with the community on. Ideas and contributions welcome!

> No integrated paginated connection; some apps still make good use of paged lists, and do not use infinite scroll

Agreed: we've focused on making infinite scroll easy (since we use it heavily internally), while other forms of pagination are less obvious to implement. Again, this is an area where community contributions would be especially welcome.

**Comment by jeromecovington** [comment]
I'm pretty well on track with how to do this via @josephsavona's example. But while working with similar code, I am getting the following error:
```
Error: Error: You supplied a GraphQL document named `InfiniteScroll` that uses template substitution for an argument value, but variable substitution has not been enabled.
```

**Comment by josephsavona** [comment]
@jeromecovington To reference a variable, just use `$var`:

```javascript
initialVariables: {
  first: ...,
  termSlug: ...,
  taxSlug: ..., // <-- be sure to define a default for each variable (or set them to `null`)
},
fragments: {
    root: (variables) => Relay.QL`
    fragment on Root {
      allContent(first: $first, termSlug: $termSlug, taxSlug: $taxSlug) {
        edges {
          node {
            id,
            ${FeedCard.getFragment('content')}
          }
        }
        pageInfo {
          endCursor
        }
      }
    `
  }
```

**Comment by jeromecovington** [comment]
@josephsavona  - But here I am trying to set the values of `termSlug` and `taxSlug` to those passed in via the route. Ex.
```
class InfiniteRoute extends Relay.Route {
  static routeName = 'InfiniteRoute';
  static paramDefinitions = {
    termSlug: {required: true},
    taxSlug: {required: true}
  };
  static queries = {
    root: (Component, variables) => Relay.QL`
      query {
        root {
          ${Component.getFragment('root', {
            termSlug: variables.termSlug,
            taxSlug: variables.taxSlug
          })}
        }
      }
    `
  };
}
```

**Comment by jeromecovington** [comment]
Ah! I see that works...I thought I needed to explicitly reference `variables` in the query template string. Thanks!

**Comment by guzart** [comment]
@josephsavona Is there a place to track if the fragment alias will be added to the language? Thank you.

```
fragment on User {
  foo: ${Child.getFragment('foo')}
}
```

**Comment by josephsavona** [comment]
@guzart see https://github.com/facebook/graphql/issues/137

This is something that makes sense for Relay because of the way we do fragment composition with effectively local variables. It isn't so clear if this makes sense for GraphQL clients generally, though, so we may pursue alternatives (for example, a relay directive for providing an alias).

**Comment by mjhlybmwq** [comment]
why not use something else instead of `props` to set variables?

**Comment by steveluscher** [comment]
Thanks for all of the interesting discussion, everyone. This GitHub issue is going a bit off the rails though; I'm going to close it now that we understand how and when variables get overwritten with props. If anyone would like to raise a follow-on issue, please feel free to open a new one!
