### ISSUE TITLE
npm install fails with older npm versions

### ISSUE THREAD

**Issue by RichardForrester** [facebook/relay#319]
System: Laravel Homestead VM (http://laravel.com/docs/5.1/homestead)

Issue:

Upon `cd ~/repos/relay/examples/todo && npm install`, install fails with the following output: 

576 error notarget No compatible version found: babel-relay-plugin@'file:../../scripts/babel-relay-plugin/
576 error notarget Valid install targets:
576 error notarget ["0.1.0","0.1.1","0.1.2","0.1.3","0.2.0","0.2.1","0.2.2","0.2.3"]
576 error notarget
576 error notarget This is most likely not a problem with npm itself.
576 error notarget In most cases you or one of your dependencies are requesting
576 error notarget a package version that doesn't exist.
577 error System Linux 3.13.0-24-generic
578 error command "/usr/bin/node" "/usr/bin/npm" "install"
579 error cwd /home/vagrant/repos/relay/examples/todo
580 error node -v v0.10.37
581 error npm -v 1.4.28
582 error code ETARGET
583 verbose exit [ 1, true ]`

**Comment by zpao** [comment]
You need a newer version of npm (2.0+) which supports file references.

`npm i -g npm@latest`

**Comment by steveluscher** [comment]
Let us know if that fixes your problem, @RichardForrester, or simply close this issue.

**Comment by RichardForrester** [comment]
@zpao Thanks!

**Comment by kassens** [comment]
I think we can warn for older versions of `npm`.

**Comment by zpao** [comment]
Not well. I was going to say you could use the `devEngines` thing I wrote (in `fbjs-scripts`) as a `preinstall` hook, but you need to install `fbjs-scripts` first…

If you really wanted you could just make `npm install ../../scripts/babel-relay-plugin` a `postinstall` step.

**Comment by kassens** [comment]
Ugh, I misunderstood the `"engines"` field in `package.json`. It's only used when the package is installed somewhere else, not when `npm install` is run inside the package.

**Comment by steveluscher** [comment]
I was talking to @josephsavona about this the other day. One of the reasons that these are file references is so that if there's a breaking change in the framework, and we update the examples, any given clone of master will still work.

The file references are also here for the convenience of people who want to change framework code and see the effect on the examples. I think the canonical approach to this is to use `npm link` to link the example and the local copy of the npm module you're hacking on (we used to recommend this) but it doesn't get us the above-mentioned feature for free.

Programming is hard.
