### ISSUE TITLE
Relay to TypeScript

### ISSUE THREAD

**Issue by maraisr** [facebook/relay#3226]
Another sibling Facebook project (https://github.com/facebook/jest) has already been partially if not completely been re-written to TypeScript.

What is the appetite for Relay (react, runtime) to also house its source code in typescript? I'd be more than happy to lead the charge on that.

**Comment by kassens** [comment]
Due to FB internal integrations that sometimes go a bit more into the internals then the public API exposes, I don't think this a viable idea at the moment.

What might be more realistic is to somehow ship TS types for the public APIs with the project, but I'm not well informed how that could work? Separate ts interface files in the repo that get bundled to the production bundles?

**Comment by maraisr** [comment]
Yeah i think that would be the optimal. I've done a fair bit of the TS types to get that DX nice and slick—so could defs help get that happening. The main point then from your perspective then would be to not let that api slide when the flow stuff happens. So would need to be generated or at least dts tested against the api. But even then, like with the types ive created. Sometimes, and especially with EntryPoints the flow types didnt have the right DX. So yeah not sure, maybe the DT types are good for now, just gotta get someone like me to almost become the maintainer of the DT types, and ensure they're on point either by release or shortly after.. (not a year later).

I know the React types lag by about a week or so.
