### ISSUE TITLE
Fragement props

### ISSUE THREAD

**Issue by mutasemhidmi** [facebook/relay#3313]
When using relay fragment why i need to pass props to the child fragments and if I'm doing that why I need the fragment then since I can just get the data from the props, what I mean in the below example TodoList is a parent component, and let's say it's rendered under QueryRenderer and TodoItem is child component so if I'm passing the item as props why I need fragment in todoitem. I was expecting that if I wrap my component with fragment I should get this information directly the same way it's done in redux 

```javascript
class TodoList extends React.Component {
  render() {
    // Expects a `list` with a string `title`, as well as the information
    // for the `<TodoItem>`s (we'll get that next).
    const list = this.props.list;
    return (
      <View>
        {/* It works just like a React component, because it is one! */}
        <Text>{list.title}</Text>
        {list.todoItems.map(item => <TodoItem item={item} />)}
      </View>
    );
  }
}


// TodoItem.js
class TodoItem extends React.Component {
  render() {
    // Expects the `item` prop to have the following shape:
    // {
    //   item: {
    //     text,
    //     isComplete
    //   }
    // }
    const item = this.props.item;
    return (
      <View>
        <Checkbox checked={item.isComplete} />
        <Text>{item.text}</Text>
      </View>
    );
  }
}
```

**Comment by mutasemhidmi** [comment]
i would really appreciate an answer for this question

**Comment by josephsavona** [comment]
This is discussed in the docs, for example in [Composing Fragments](https://relay.dev/docs/en/experimental/a-guided-tour-of-relay#composing-fragments). The tl;dr is that each component declares its data dependencies using a fragment and parents compose dependencies of their children. At render time, each component needs to know _which_ object it's rendering - in the example, `TodoItem` needs to know which todo item it is rendering! - which is passed as a prop. The `item` prop in this case tells Relay _which_ item is being rendered, and Relay combines that w the corresponding fragment to go and read (and subscribe to) the necessary data about that item.

It's different from Redux because Relay is doing much more work for you.

**Comment by mutasemhidmi** [comment]
@josephsavona thanks for the explanation
