### ISSUE TITLE
Compiler errors at schema description

### ISSUE THREAD

**Issue by marcotoniut** [facebook/relay#3376]
While using another tool to generate the schema, I found out that the relay compiler errors whenever there's a string description above the topmost schema declaration.

```graphql
"Description of the schema"
schema {
  query: RootQueryType
  mutation: RootMutationType
}
```

yields

```
ERROR:
Syntax Error: Expected "schema", found String "Description of the schema"
error Command failed with exit code 100.
```

After digging around for a bit, I found out that there has been a spec update to graphql which incorporates the ability to add descriptions at this level. Am I right to assume that relay is still catching up to it?
https://github.com/graphql/graphql-spec/pull/466/files

**Comment by captbaritone** [comment]
From what I can tell, this was [added to `graphql-js`](https://github.com/graphql/graphql-js/pull/2419) Feb 2nd and they have not yet [cut a release](https://github.com/graphql/graphql-js/releases) that includes it. I have confirmed that this parses without error in the new Rust compiler.

If `graphql-js` cuts a new release with this change, and it's within the v15 range, you should be able to resolve this by upgrading your version of `graphql-js` since Relay expects it as a peer dependency.
