### ISSUE TITLE
Question: Can I change the GraphQL endpoint?

### ISSUE THREAD

**Issue by stevewillard** [facebook/relay#339]
If I serve up a relay app on say, port 3000, is it possible to configure Relay to make GraphQL requests to another port, or an entirely different domain?

Thanks!

**Comment by wincent** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

Questions like yours deserve a purpose-built Q&A forum. Would you like to post this question to Stack Overflow with the tag #relayjs? We'll be happy to answer there. Post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs

(Note that there are already some questions there related to configuring the network layer, such as [this one](http://stackoverflow.com/questions/32494136/injecting-custom-network-url-not-working-relayjs), which may already answer your question for you.)

**Comment by stevewillard** [comment]
Thanks a bunch! That post actually answered my question. I didn't realize  you could do:
```
Relay.injectNetworkLayer(
  new Relay.DefaultNetworkLayer('http://localhost:8080/graphql')
);
```
