### ISSUE TITLE
globalIdField vs String

### ISSUE THREAD

**Issue by u9520107** [facebook/relay#356]
I am bit confused as to when to use globalIdField.
Suppose I have a data like this:
```
type User {
  id: globalIdField('User'),
  name: String,
  folders: [ Folder ]
}
type Folder {
  id: ???,
  ...
}
```

In terms of actual data structure, the folders are stored within the User object in a document based storage. Folders do have ids so that some other entities may reference it under the context of the user.
So if I give it a global id, does that mean I have to be able to fetch the specific folder from nodeDefinitions. That would mean cycling through all the users in the data base to hunt the folder down.
Is it ok for the id field to be treated as a simple string in this case? If so, what happens if I try to update fields of the folder object?

I guess another way to ask this question is, does every object type that contains an id field counts has a node, and have to implement the node interface?

**Comment by steveluscher** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

Questions like yours deserve a purpose-built Q&A forum. Would you like to post this question to Stack Overflow with the tag #relayjs? We'll be happy to answer there. Post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs

**Comment by u9520107** [comment]
As requested:
http://stackoverflow.com/questions/32686133/when-to-use-globalidfield
