### ISSUE TITLE
Invalid use of @defer on an inline fragment

### ISSUE THREAD

**Issue by artola** [facebook/relay#3607]
Compilation throws an error when the fragment spread contains `@defer` and `@relay(mask: false)`, otherwise containing just one of them it works.

```txt
ERROR:
- Invalid use of @defer on an inline fragment, @defer is only supported on fragment spreads.
  
  Source (derived): root/dummy.tsx (7:9)
  6:         title
  7:         ...dummySessionDeferred @defer @relay(mask: false)
             ^
  8:       }
```

Expected: it should work as with other directives (e.g., @defer together @include).

Using:
 - "graphql": "15.4.0-experimental-stream-defer.1"
 - "relay-compiler": "^12.0.0"
 
```js
const query = graphql`
  query dummyQuery {
    sessions {
      nodes {
        id
        title
        ...dummySessionDeferred @defer @relay(mask: false)
      }
    }
  }
`;

graphql`
  fragment dummySessionDeferred on Session {
    abstract
    speakers {
      name
      bio
    }
  }
`;
```

**Comment by kassens** [comment]
@relay(mask: false) basically just copies the whole data inline. @defer cannot "suspend" correctly at that place. You should have the same effect by adding the @defer directive on the parent fragment. (Here in the example you just have a query, so you cannot really use @defer because there would not be anything to partially render )
