### ISSUE TITLE
startCursor and endCursor

### ISSUE THREAD

**Issue by taion** [facebook/relay#372]
@schrockn told me to file this -

Currently it appears that there's some code around `startCursor` and `endCursor` in the connection code and the examples. However, it looks like pagination instead uses the per-edge `cursor`s.

It would make it a lot easier to wrap REST APIs with a GraphQL adapter for use with Relay if there were actual support for pagination based on `startCursor` and `endCursor` in `pageInfo` rather than per-edge `cursor`s.

The motivation is that implementations of cursor-based pagination on REST APIs generally only return start and end cursors rather than a cursor per item, so someone wrapping such a backend (assuming it generates opaque cursors) won't actually have access to the per-element cursors that the Relay connection interface requests.

This isn't a show-stopper for me, since I can just modify my backend to return all the cursors, but I think developers trying to wrap REST APIs that they can't change would have an easier time of using Relay connections if they could just specify start and end cursors for each page.

**Comment by josephsavona** [comment]
Relay uses the `cursor` from the nodes for pagination because there is no guarantee that users will consistently page through a connection with the same offsets. One part of the app might do first 5, 10, 15, another part could should first 2, 4, 6. Therefore Relay needs a cursor at every edge from which it can correctly paginate. Also, note that `startCursor` and `endCursor` should be *identical* to the `cursor` value of the first and last edge, respectively.

**Comment by taion** [comment]
For a simple/common case where I don't specify e.g. `after` in the args to the connection, I don't see why that's the case.

If component 1 asks for `widgets(first: 10)`, then `widgets(first: 20)`, it seems like Relay only needs the end cursor for the first page to retrieve items 11 through 20 in the connection.

If I have another component that asks for `widgets(first: 3)`, then `widgets(first: 6)`, it seems like Relay should in principle be able to satisfy this request without looking at cursors at all. Furthermore, if this component later goes from `widgets(first: 18)` to `widgets(first: 21)`, Relay could in principle still use the end cursor from above to query just for item 21 in the connection.

Am I missing something here? I'm just outlining something that sounds plausible in my head.

This wouldn't support the case where someone tried to explicitly do `widgets(after: $someCursor, first: $whatever)`, but this seems like a somewhat more rare case, and anyway if the connection only returns start and end cursors, there's no easy way to get ahold of the `$someCursor`.

**Comment by taion** [comment]
Actually, I guess you need only `endCursor` when paginating with `first` (or just `startCursor` when paginating with `last`).

I would argue that, on net, the benefit of having an easier way to do pagination that works better when wrapping existing REST APIs can outweigh the extra complexity and potential confusion from having two schemes for cursoring.

**Comment by josephsavona** [comment]
@yuzhi can you provide additional context here? I know we discussed this a while back.

**Comment by yuzhi** [comment]
Sorry for the slow response! I haven't had much internet access in the last couple of days. Just caught up on this and saw that I got mentioned in slack about the same issue.

##### Context on why Relay gets cursors for each edge
When we were building Relay, we tried to gets data so that it can be cached and support as many views as possible with minimal round trips. As @josephsavona mentioned above, different component can paginate with different page sizes. We only ever need the very last and first cursor to paginate correctly, as @taion mentioned. However, getting cursor on every edge means Relay can always generate the correct `pageInfo`, more specifically `startCursor`, `endCursor` fields, without having to do another route trips to get the proper `pageInfo` for a different page size from the server for a different page size.  It didn't make sense to wait for a server round trip for something that's fetching `first:3` when we already have `first:5`. Having cursor on every edge is also handy when mutations can add and remove edges and might make the very last cursor out of date. In those cases, Relay just have to look at the cursor for the last or first not deleted edge.

##### Work around for existing REST endpoints
Provided that you only ever paginate in one direction with this particular connection (Always use `first:<count>` or always use `last:<count>`), you can just generate cursors for edges with something like `<endCursor> + 'i'` where `i` is the number/distance of edges to the last edge. You can optionally hash it, encode it, and etc. to make it seem more opaque. Just make sure your GraphQL wrapper around your REST endpoint knows how to parse it and strip out the `i` portion before sending the request to your REST endpoint.

Things to avoid:
*  `null` cursors
  * if the last edge gets deleted, Relay won't have any cursors to paginate with, and will have to try to refetch the whole connection.
* repeating the same cursor
  * If multiple edges have the same cursor, when a server response for `(first:5, after: <repeatedCursor>)` comes back, Relay won't know which of all the edges with that cursor to the newly fetched edges after.

Let me know if this helps.

**Comment by taion** [comment]
Thank you for taking the time to answer. Apologies if this caused you any inconvenience. This wasn't causing me any direct issues - it just seemed a little more difficult than it should have been.

I think I see what you mean now with `startCursor` and `endCursor`. I guess the use case must be something like, for a paginated view rather than an infinite scrolling view, to enable the developer to do something like:

```js
this.props.relay.setVariables({
  after: this.props.viewer.widgetList.pageInfo.endCursor,
  first: PAGE_SIZE
});
```

Is that right? It wasn't previously clear to me how those two fields could be used since I've only done endless scroll lists that just kept incrementing `first` so far, but I think this makes sense now.

In general it shouldn't be too difficult to modify most backends to generate per-item cursors anyway, and the benefits of Relay minimizing trips to the server even when doing multiple kinds of pagination seem pretty compelling.

**Comment by taion** [comment]
On second thought, the "modifying the backend" point is completely moot, since if the user ever wants to use a `RANGE_ADD` mutation, then the backend needs to return a cursor for the newly created item, and it's pretty unusual for REST APIs to include a cursor on a `201 CREATED` response to a `POST` request.

The rest of the pagination stuff can be worked around, but the benefit just isn't there. This does mean that most REST APIs are going to need some tweaking to work nicely with Relay connections, but that's probably for the best all around.

Thanks!
