### ISSUE TITLE
Error message source locations are incorrect

### ISSUE THREAD

**Issue by tomgasson** [facebook/relay#3735]
Error message from v13 are printed relative to the string.

This error indicates line 23
<img width="937" alt="Screen Shot 2022-01-10 at 11 13 14 am" src="https://user-images.githubusercontent.com/345235/148706975-eac79ad5-2bad-4226-8bd2-195a9010767a.png">

But this is at line 68 in the source code
<img width="795" alt="Screen Shot 2022-01-10 at 11 13 36 am" src="https://user-images.githubusercontent.com/345235/148706979-13faa852-793b-468e-a10e-14ad2b82f07c.png">

These should be offset relative to the source file

**Comment by alunyov** [comment]
Thanks for the report! This looks incorrect.

**Comment by ch1ffa** [comment]
@alunyov I see the same behaviour for v11 and v12.

It can be solved in v13 by removing line 80
https://github.com/facebook/relay/blob/490a77f6589952cd13389301eb7a94bb0a077516/compiler/crates/relay-compiler/src/status_reporter.rs#L77-L84
and by using GraphQLSource instead of String in the diagnostic_printer
https://github.com/facebook/relay/blob/490a77f6589952cd13389301eb7a94bb0a077516/compiler/crates/graphql-cli/src/diagnostic_printer.rs#L91-L93
so you can pass a real line_offset to `to_range` and to some other places
https://github.com/facebook/relay/blob/490a77f6589952cd13389301eb7a94bb0a077516/compiler/crates/graphql-cli/src/diagnostic_printer.rs#L71-L78

I could make a PR, it should work for the diagnostic_printer, but I didn't find an easy way to get a source line for the Validation error output

**Comment by alunyov** [comment]
Thanks for looking into this @ch1ffa!

> I could make a PR
Please, happy to review.

Also I didn't look into this too closely, yet. But I think we have this working correctly in the `relay-lsp`: https://github.com/facebook/relay/blob/main/compiler/crates/relay-lsp/src/diagnostic_reporter.rs
