### ISSUE TITLE
[v13 relay-compiler] Exposing Relay Schema Extensions.

### ISSUE THREAD

**Issue by erictaylor** [facebook/relay#3787]
Pre v13 I know that `relay-compiler` exposed some of the schema extensions that are specific to Relay (ie directives) so that other third party libraries and tools could easily add them (ex: IDE GraphQL hinting/tooling, etc).

I noticed that since v13 that `relay-compiler` has been simplified (obviously) down to just exposing the underlying binary.

Are there any plans re-expose the [schema extensions](https://github.com/facebook/relay/blob/main/compiler/crates/relay-schema/src/relay-extensions.graphql) in some way?

I'm also curious why the underlying `relay-extensions.graphql` file seems to omit `@arguments` and `@argumentDefinitions`?

**Comment by josephsavona** [comment]
It seems reasonable to expose the schema extensions for other tools to pick up, we'd be happy to support a PR to that effect.

As for `@arguments` and `@argumentDefinitons` these cannot be represented as regular directives because they do not have a known set of arguments. Relay Compiler (ab)uses these directives as a stand in for syntax for function arguments and function parameters.

**Comment by erictaylor** [comment]
> It seems reasonable to expose the schema extensions for other tools to pick up, we'd be happy to support a PR to that effect.

I'd be more than happy to make a contribution here. I am curious if you have any recommended/suggested ways on how to expose this? Given this file lives in one of the compiler crates I'm not sure what the preferred approach would be here.

> As for @arguments and @argumentDefinitons these cannot be represented as regular directives because they do not have a known set of arguments. Relay Compiler (ab)uses these directives as a stand in for syntax for function arguments and function parameters.

Understood. Thanks for the explanation.
