### ISSUE TITLE
Dynamic children / Map type

### ISSUE THREAD

**Issue by miracle2k** [facebook/relay#386]
I have an ``Item`` Type. I want it's title to be translated into a variable number of languages. I was imagining a structure like this:

     Item {
        title {
            de,
            fr,
            pa
        }
     }

The admin interface needs to load all of the titles for editing, and optionally add new ones. In other words, I am looking for a "dict".

The only way I can come up with to solve this right now is to use a ``GraphQLString`` and encode the language-strings as a JSON objects.

Is there another one, or should there be?

**Comment by kassens** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

Questions like yours deserve a purpose-built Q&A forum. Would you like to post this question to Stack Overflow with the tag #relayjs? We'll be happy to answer there. Post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs

**Comment by miracle2k** [comment]
I posted it here:

https://stackoverflow.com/questions/32782604/dynamic-children-map-type-in-relay-js
