### ISSUE TITLE
Relay Resolver has module resolution problem in TypeScript

### ISSUE THREAD

**Issue by Beingbook** [facebook/relay#3989]
<img width="542" alt="Screen Shot 2022-06-22 at 15 34 22" src="https://user-images.githubusercontent.com/2682865/174959781-bff75b48-e711-47b9-a14d-8271db429c2e.png">

<img width="865" alt="Screen Shot 2022-06-22 at 15 37 58" src="https://user-images.githubusercontent.com/2682865/174960251-2636af9e-f835-4e04-8ca1-4bfa71f8c683.png">

As above images, generated relay artifacts import relay resolver with extension.
I think using ".js" extension or skipping extension are correct solution at this moment. So we can inference return type of RelayResolver function in TypeScript.

**Comment by captbaritone** [comment]
Thanks for the report @Beingbook. If you're interested in working on a fix, I suspect stripping the extension would be the right approach and the I think the code that derives this path lives here: https://github.com/facebook/relay/blob/main/compiler/crates/relay-config/src/project_config.rs#L360

cc @tbezman

**Comment by Beingbook** [comment]
oops, I'm too late. thanks!

**Comment by chriserickson** [comment]
This was not fixed in 14.1 - the dynamic imports in the AST omit extensions, however the type imports still have the extensions.

It appears that 
https://github.com/facebook/relay/blob/639abe1b23ed2187500514c331bed3aebede2f02/compiler/crates/relay-typegen/src/typescript.rs#L97
and
https://github.com/facebook/relay/blob/639abe1b23ed2187500514c331bed3aebede2f02/compiler/crates/relay-typegen/src/typescript.rs#L101

Both also need to strip extensions, as typescript requires that extensions not be provided.

Is it possible to re-open this? I'm happy to work on a fix.

**Comment by chriserickson** [comment]
I went ahead and created a new issue:

https://github.com/facebook/relay/issues/4056
