### ISSUE TITLE
RANGE_ADD should be skippable if objects have not been fetched.

### ISSUE THREAD

**Issue by miracle2k** [facebook/relay#400]
I am seeing this upon running a migration:

     Warning: writeRelayUpdatePayload(): Expected response payload to include the newly created edge `fooitem` and its `node` field. Did you forget to update the `RANGE_ADD` mutation config?

Here is my setup:

1. I'm using react-router to either route to "ItemsPage" or "AddItemPage". 
2. Every page is a Relay RootContainer.
3. When AddItemPage triggers the location, it doesn't really know if the "viewer.items" connection was already loaded. If the entry point into the app was the AddItemPage component, the items have not been loaded.

Am I not using this right? Arguably, it shouldn't be necessary to load a connection to add items. I prefer not do have to know when I want to run a mutation what objects are already in the Relay store or not.

**Comment by yuzhi** [comment]
You are right. Relay shouldn't try to fetch and store the edge if the connection has not been fetched yet.

Do you know if that error is from the optimistic mutation or the response from the server?
Did you figure out a work around to be unblocked?

**Comment by miracle2k** [comment]
I do not use an optimistic response here.

What happens I believe, is this:

- The AddItem mutation defines a "newItem" field in it's output. This is the newly created edge.
- In getConfigs(), this output field is mapped to the "items" connection via RANGE_ADD.
- Because the "items" connection is not loaded in React, Relay will not ask for this output field when sending the mutation.
- The mutation query responds without the "newItem" output field present.
- Relay now complains the "newItem" field, that it wants to use in RANGE_ADD, is missing.

**Comment by LegNeato** [comment]
Think I might have just hit this as well:

I have user-specific config data that saves choices entered in a setup in a wizard. For each wizard step, I prefill any saved data from the server...but I don't know if the user has loaded the view before or not and there may not be a record on the server. When I write data back, it may or may not have been fetched from the server via Relay depending on if the record exists.

When I do `FIELDS_CHANGE`, it all works as long as there is a record in the database but fails to do the mutation if there is no existing record because it is looking for the `id` in the store. With `RANGE_ADD` (creating a record in the database with the user-specific value the first time the view page is loaded) I get the warning message in this issue but the behavior appears to work fine (record created in the database, future changes update the new record, etc).

:point_right:  Is there a better way to go about this pattern (updating a record if there otherwise add a new one) in Relay?

**Comment by josephsavona** [comment]
merging into #542
