### ISSUE TITLE
Relay resolver always return any type

### ISSUE THREAD

**Issue by eunhyulkim** [facebook/relay#4095]
# Issue
relay resolver in experimental of relay 14 does not return the type correctly. resolver always return any type. Because the artifact file contains 'ts-nocheck' but has a type like ReturnType<type of resolver>, type inference stops.

![Screenshot of Code (2022-10-18 3-35-57 PM)](https://user-images.githubusercontent.com/8200028/196354551-e42928f9-2e67-44b3-9c64-651de1b73609.png)
![Screenshot of Code (2022-10-18 3-40-43 PM)](https://user-images.githubusercontent.com/8200028/196354680-3261dbd9-dfb4-40e1-9c88-fc2ef6b7b52d.png)

# Suggestion
It should be possible to explicitly extract the return type, such as @outputType docblock. Or, when using the @relay_resolver directive for schema, relay should not ignore the type and hold it properly.
![code](https://user-images.githubusercontent.com/8200028/196355405-bdf789b5-105b-4f57-aa81-b43f68add5ce.png)

**Comment by cometkim** [comment]
It might be impossible because Relay compiler doesn't parse JS/TS, it only has a printer.

So we shouldn't emit nocheck directive to use inferences in artifacts now and later.

https://github.com/facebook/relay/blob/908fe115d618ff032e551caf9aaec0d544ec23d5/compiler/crates/relay-compiler/src/artifact_content/content.rs#L775

Not sure it's original intent. @eunhyulkim Is it crashes if we just remove that from the artifacts by hand?

**Comment by cometkim** [comment]
I guess it was added for type-checking performance. if so, it can be selectively re-enabled only for files that require inferences.

**Comment by eunhyulkim** [comment]
@cometkim Even if ts-nocheck is turned off, there is no particular crash. I wish I could control it. However, the import method is different, so it becomes an issue. This point seems to have to be considered.

**Comment by cometkim** [comment]
This duplicates #3989, which seems now to be resolved
