### ISSUE TITLE
Allowing initialVariables to be a function

### ISSUE THREAD

**Issue by emilsjolander** [facebook/relay#419]
Currently i don't see a good way of doing the following as the initialVariables object is created before the props have been set. Correct me if i am mistaken.
```js
Relay.createContainer(Profile, {
  initialVariables: {
    userId: props.user.id,
  },

  fragments: {
    viewer: (variables) => Relay.QL`
      fragment on Viewer {
        node(id: $userId)  { name }
      }
    `,
  },
});
```
Is there a reason for needing the initial variables before props have been set? Otherwise i propose allowing initialVariables to be defined as a function which is invoked with the initial props of the component.
```js
Relay.createContainer(Profile, {
  initialVariables: (props) =>  ({
    userId: props.user.id,
  }),

  fragments: {
    viewer: (variables) => Relay.QL`
      fragment on Viewer {
        node(id: $userId)  { name }
      }
    `,
  },
});
```

**Comment by josephsavona** [comment]
@emilsjolander Relay uses static queries in order to fetch data *before* rendering components. This means that queries don't have access to `props`, because there are none yet!

Containers are designed to be relative - they fetch data for any object of a certain type. Here, that means the `Profile` query should probably be `fragment on User { name }`. Then the **Route** would specify which `User`. The [Routes Guide](http://facebook.github.io/relay/docs/guides-routes.html#queries-vs-fragments) provides an example for exactly this scenario.

**Comment by emilsjolander** [comment]
ok thanks,  i'll have a look!
