### ISSUE TITLE
Mutation: Reference node which will be updated by ID

### ISSUE THREAD

**Issue by Gregoor** [facebook/relay#421]
One of my mutations updates a fragment that is displayed completely somewhere else, though they do have a common ancestor. I could try to get the fragment and pass it through the whole hierarchy and the common ancestor, but I feel like there should be a more direct way.

Given that we already have the node-interface, can't we just update the appropriate node via its ID?

I would imagine something like this:

```javascript
getFatQuery() {
  return Relay.QL`
    fragment on AddNestedTodoPayload {
      todoEdge,
      todoContainer(id: ${this.props.containerID})
    }
  `;
}
```

**Comment by josephsavona** [comment]
cc @yuzhi

**Comment by yuzhi** [comment]
Just to clarify, why do you need to pass the fragment around for the mutation?
Given an terminated fat query field, Relay will automatically include everything that we have about that node so that it gets updated before the next render.

**Comment by Gregoor** [comment]
What is a *terminated* query?

I guess part of my problem is, that the mutation does not necessarily know where this particular todoContainer exists in the graph. In my model todoContainers can be nested inside of each other.

So I think I need a way of updating a field (or rather a node?) without knowing where it is positioned in the data model.

**Comment by yuzhi** [comment]
Sorry, I am not sure I understand the exact question.
https://facebook.github.io/relay/docs/guides-mutations.html#a-complete-example
Fat queries are just a description of what can change in terms of the of mutation fields. In the example above, `story` can be anywhere on the graph as well. Stories can also be nested inside of each other. Relay figures out which story you are talking about by looking at result from 'getConfigs()', which can be a function of set of values you pass into the mutation.
I am not sure what you mean by `updating a field`, since fields are generally belong to a node. Also if the server sends up JUST a field, Relay won't know which node that field belongs to.

If that doesn't answer your question, can you include more information about what you are trying to do? For example: what fragment does your component have? What are types of each of the fields? What fields does your mutation have? which fields are you trying to update?

**Comment by Gregoor** [comment]
Ah, I should be sorry. I got it wrong, I forgot that because of relay's node-interface/object-ID convention  the position in the query is not important, but its ID. Somehow I blocked that out of my mind.

Thanks for taking the time :+1:
