### ISSUE TITLE
Connections on fire - redundant results

### ISSUE THREAD

**Issue by jardakotesovec** [facebook/relay#464]
I am using connections with extra parameters to filter results. And it seems to go wrong on following circumstances. I will try to explain it well enough.. and if not sufficient I will work to reproduce it on some of the examples you have provided.

Lets say I have two independent components using images connection like this
```
  viewer {images (first: 50) {  ... } }
```
and similarly second component:
```
  viewer {images (first: 100) {  ... } }
```

For initial fetch relay asks separately for both, which is redundant (but still acceptable):
```
images(first:50){..}
images(first:100){...}
```

Next step is that I change custom parameter on second one to filter results, so I have
```
  viewer {images (first: 50 customArg="aaa") {  ... } }
  viewer {images (first: 100) {  ... } }
```

Relay generates query, which is also redundant (relay does not have reason to think that more results got available meanwhile since I have not done any mutation) and reason probably is that component 2 is inside component1 tree. I tried it other way round - changing custom arg for component2 and does not generate extra query, just one.
```
images(first:50,customArg:"aaa")
images(after:"YXJyYXljb25uZWN0aW9uOjE=",first:98)
```

And finally I do mutation, which has fatQuery `viewer` and reloads everything and here is what relay reloads

```
images(first:100)
images(first:50)
images(after:"YXJyYXljb25uZWN0aW9uOjE=",first:98)
images(first:50,customArg:"aaa")
```

I understand that its caching results, therefore it still interested in `images(first:50)`, but the `after` variant should not be there I think.

Using relay `0.4.0` and babel plugin `0.3.0`.

**Comment by jardakotesovec** [comment]
One more detail that actually caught my attention at first. If I do following sequence 

start with
```
images(first:50){..}
images(first:100){...}
```
1) change to
```
images(first:50, customArg="aaa"){..}
images(first:100){...}
```
2) change back to
```
images(first:50){..}
images(first:100){...}
```
3) send mutation with viewer in fat query to reload everything, relay requests:
```
images(after:"YXJyYXljb25uZWN0aW9uOjE=",first:48)
images(first:100)
images(first:50)
images(after:"YXJyYXljb25uZWN0aW9uOjE=",first:98)
images(first:50,imageUids:"5")
```

And on client I get
```
GraphQLRange cannot find a segment that has the cursor: YXJyYXljb25uZWN0aW9uOjE=
```

Maybe because the `after` variant get processed first, it will cause this warning, but thats guessing. In my previous example I did not get this warning.

**Comment by yuzhi** [comment]
Thanks you for your questions! I'll try to go through them one by one. 

> For initial fetch relay asks separately for both, which is redundant (but still acceptable):
 ```
> images(first:50){..}
> images(first:100){...}
```

Relay doesn't merge these because each of those connections might ask for very different set of fields and fragments. We also don't want to just put all of the fields and fragments under `image(first:100)` because `image(first:50)` could be asking for a much larger set of fields, where it would be inefficient to fetch them for the `first:100`. Because there are a lot of factors that can go in to whether we should merge those two fields, Relay doesn't try to be smart in combining these fields.

> Relay generates query, which is also redundant (relay does not have reason to think that more results got available meanwhile since I have not done any mutation) and reason probably is that component 2 is inside component1 tree. I tried it other way round - changing custom arg for component2 and does not generate extra query, just one.
```
> images(first:50,customArg:"aaa")
> images(after:"YXJyYXljb25uZWN0aW9uOjE=",first:98)
```
It shouldn't do that if there are no more edges. My best bet is to check your `pageInfo`. It should return "hasNextPage: false" on the first time you queried for `first:100`. When that happens, Relay will know to stop trying to fetch for more data from this connection. If it doesn't return that, Relay can't be sure there aren't any more items and tries to fetch more the next time around. If the `hasNextPage:false` and you are still seeing the second ` images(after:"YXJyYXljb25uZWN0aW9uOjE=",first:98)` query, that would be a bug. Definitely report it to us and we would greatly appreciate repro steps.


> And finally I do mutation, which has fatQuery viewer and reloads everything and here is what relay reloads

We currently fetch based on the fragments that was cached, which means having a lot of ranges can be inefficient. In the future, we might look into dirtying cached data and only fetch data needed for the current view to make this step a but more efficient.

> Maybe because the `after` variant get processed first, it will cause this warning, but thats guessing. 

Yup, you are 100% right. Relay can't handle connection fields with `cursors` we haven't seen before. This shouldn't be a problem anymore if we dirty the data and just fetch for data based on the current view requirements.

Let me know if I missed anything or if any part is confusing.

**Comment by jardakotesovec** [comment]
> It shouldn't do that if there are no more edges. My best bet is to check your pageInfo. It should return "hasNextPage: false" on the first time you queried for first:100. When that happens, Relay will know to stop trying to fetch for more data from this connection. If it doesn't return that, Relay can't be sure there aren't any more items and tries to fetch more the next time around. If the hasNextPage:false and you are still seeing the second images(after:"YXJyYXljb25uZWN0aW9uOjE=",first:98) query, that would be a bug. Definitely report it to us and we would greatly appreciate repro steps.

That was great catch. You were right, it was our bug with `hasNextPage`. So fixing that removed the extra queries with `after`, so also the warning `GraphQLRange cannot find a segment that has the cursor: YXJyYXljb25uZWN0aW9uOjE=`  disappeared.

Now I can only hope that the cache dirtying functionality comes along in foreseeable future :-).  And maybe #233 could be temporary workaround to occasionally reset the cache for us as it might land sooner.

Thanks a lot for detailed answers.
