### ISSUE TITLE
Connection extra arguments

### ISSUE THREAD

**Issue by jardakotesovec** [facebook/relay#465]
Its related to #464   but separate issue to ask question make sense.

If I use extra connection arguments to filter results - it can quickly result in many connections cached with different arguments. Which results in refetching all of them if I set fatQuery for that connection. 

Is there mechanism to control what gets cached? If it refetch all connection argument variants ever used in application lifetime once some mutation that affects this connection get used  -  it will result in huge queries.

And one more question: is possible to use arrays/objects as these extra connection arguments? Its handy for example to list tag ids to filter down images. It works ok.. but not sure how relay handle comparing these arguments - which could result in even more duplicate queries with same arguments.

Thanks a lot for your insights.

**Comment by josephsavona** [comment]
> If I use extra connection arguments to filter results - it can quickly result in many connections cached with different arguments.

As @yuzhi mentioned in #464, Relay currently caches the results for all combinations of connection arguments that have been fetched, which can sometimes grow quite large depending on the product's access patterns. In the future we will likely change this so that only connections that are actively viewed are refetched, and others are marked as stale.

> is [it] possible to use arrays/objects as these extra connection arguments?

Yup! The arguments defined in the connection spec must be as specified (e.g. `first: Int`), but otherwise custom arguments can be of arbitrary types!

**Comment by jardakotesovec** [comment]
@josephsavona Ok, thanks a lot for answer. Should I open issue with feature request for dirtying unused connections? I would like to track it somehow as its very important feature for our use case.
