### ISSUE TITLE
"Could not find a type name for record"

### ISSUE THREAD

**Issue by brenoc** [facebook/relay#474]
I'm experimenting with Relay and Graphql and I've got an error message on the browser console:

> Warning: RelayQueryWriter: Could not find a type name for record `UHJvZHVjdDpwXzE=`.

Here is a runnable example of the issue: https://github.com/brenoc/relay-starter-kit/tree/relay/typenameIssue

This error disappears when I add `__typename` to the query here:
https://github.com/brenoc/relay-starter-kit/blob/relay/typenameIssue/js/components/App.js#L20

What am I doing wrong?

**Comment by BerndWessels** [comment]
I got `RelayQueryWriter: Could not find a type name for record '1'` too in this example:

    var appType = new GraphQLObjectType({
        name: 'App',
        description: 'The application configuration for the current user.',
        fields: () => ({
            id: {
              type: GraphQLID,
              description: 'The identifier'
            },
            email: {
              type: new GraphQLNonNull(GraphQLString),
              description: 'The user\'s email address'
            }
        })
    });

The `1` is the returned id value from the resolve.

@brenoc could you figure it out?

**Comment by josephsavona** [comment]
Are you using the latest version of Relay *and* `babel-relay-plugin`? Older versions of the plugin did not add the necessary `__typename` field, and a version mismatch could cause this issue.

**Comment by BerndWessels** [comment]
@josephsavona  `babel-relay-plugin` `0.3.0`

That is the latest version I guess.

Any ideas what else could be wrong?

Before I used

    id: globalIdField('App'),

but that wasn't really what I wanted - or maybe I just don't understand what that `id` is supposed to be. My assumption is that I can stick the "real" id in there that comes back from my database?

**Comment by josephsavona** [comment]
@BerndWessels - Can you paste the fragment from your container?

**Comment by brenoc** [comment]
@josephsavona Yes, I'm using the lastest version of them, v0.4.0 and v0.3.0 ([my package.json](https://github.com/brenoc/relay-starter-kit/blob/relay/typenameIssue/package.json))

@BerndWessels Unfortunately no, I couldn't :(

**Comment by BerndWessels** [comment]
@josephsavona 

    export default Relay.createContainer(App, {
      fragments: {
        viewer: () => Relay.QL`
          fragment on App {
            id,
            email
          }
        `
      }
    });

As @brenoc pointed out, if I add `__typename` to the requested properties the error goes away - but I expected the system to take care of that?

**Comment by josephsavona** [comment]
I've unable to repro this. First I [recreated this schema](https://facebook.github.io/relay/prototyping/playground.html#schema=import%20%7B%0A%20%20GraphQLID%2C%0A%20%20GraphQLNonNull%2C%0A%20%20GraphQLObjectType%2C%0A%20%20GraphQLSchema%2C%0A%20%20GraphQLString%2C%0A%7D%20from%20'graphql'%3B%0A%0Avar%20APP%20%3D%20%7B%0A%20%20id%3A%20'APP_ID'%2C%0A%20%20email%3A%20'joesavona%40fb.com'%2C%0A%7D%3B%0A%0Avar%20AppType%20%3D%20new%20GraphQLObjectType(%7B%0A%20%20%20%20name%3A%20'App'%2C%0A%20%20%20%20description%3A%20'The%20application%20configuration%20for%20the%20current%20user.'%2C%0A%20%20%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20%20%20%20%20id%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20type%3A%20GraphQLID%2C%0A%20%20%20%20%20%20%20%20%20%20description%3A%20'The%20identifier'%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20email%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20type%3A%20new%20GraphQLNonNull(GraphQLString)%2C%0A%20%20%20%20%20%20%20%20%20%20description%3A%20'The%20user%5C's%20email%20address'%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D)%0A%7D)%3B%0A%0A%2F**%0A%20*%20The%20schema.%0A%20*%20Here%20we%20export%20a%20schema%20that%20offers%20one%20root%0A%20*%20field%20named%20'greetings'%2C%20and%20a%20method%20to%0A%20*%20resolve%20its%20data.%0A%20*%0A%20*%20To%20learn%20more%20about%20writing%20GraphQL%20schemas%20for%20Relay%2C%20visit%3A%0A%20*%20%20%20https%3A%2F%2Fgithub.com%2Fgraphql%2Fgraphql-relay-js%0A%20*%2F%0Aexport%20default%20new%20GraphQLSchema(%7B%0A%20%20query%3A%20new%20GraphQLObjectType(%7B%0A%20%20%20%20name%3A%20'Query'%2C%0A%20%20%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20%20%20app%3A%20%7B%0A%20%20%20%20%20%20%20%20type%3A%20AppType%2C%0A%20%20%20%20%20%20%20%20%2F%2F%20Here%20we%20define%20a%20resolver%20that%20returns%0A%20%20%20%20%20%20%20%20%2F%2F%20the%20data%20defined%20above.%20Were%20this%20schema%0A%20%20%20%20%20%20%20%20%2F%2F%20executing%20on%20the%20server%20side%2C%20you%20could%0A%20%20%20%20%20%20%20%20%2F%2F%20write%20a%20resolve%20method%20that%20fetches%0A%20%20%20%20%20%20%20%20%2F%2F%20live%20data%20from%20a%20database.%0A%20%20%20%20%20%20%20%20resolve%3A%20()%20%3D%3E%20APP%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%0A%20%20%20%20%7D)%2C%0A%20%20%7D)%2C%0A%7D)%3B%0A%0A%0A&source=%2F%2F%20Welcome%20to%20Relay.%0A%2F%2F%20Allow%20us%20to%20introduce%20you%20to%20the%20four%20elements.%0A%0Aclass%20App%20extends%20React.Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20return%20%3Cdiv%3E%7Bthis.props.app.email%7D%3C%2Fdiv%3E%3B%0A%20%20%7D%0A%7D%0A%0A%0AApp%20%3D%20Relay.createContainer(App%2C%20%7B%0A%20%20fragments%3A%20%7B%0A%20%20%20%20app%3A%20()%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20fragment%20on%20App%20%7B%0A%20%20%20%20%20%20%20%20email%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%0A%20%20%7D%0A%7D)%3B%0A%0Aclass%20AppRoute%20extends%20Relay.Route%20%7B%0A%20%20static%20routeName%20%3D%20'App'%3B%20%20%2F%2F%20A%20unique%20name%0A%20%20static%20queries%20%3D%20%7B%0A%20%20%20%20%2F%2F%20Here%2C%20we%20compose%20your%20Relay%20container's%0A%20%20%20%20%2F%2F%20'greetings'%20fragment%20into%20the%20'greetings'%0A%20%20%20%20%2F%2F%20field%20at%20the%20root%20of%20the%20GraphQL%20schema.%0A%20%20%20%20app%3A%20(Component)%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20query%20AppQuery%20%7B%0A%20%20%20%20%20%20%20%20app%20%7B%0A%20%20%20%20%20%20%20%20%20%20%24%7BApp.getFragment('app')%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%3B%0A%7D%0A%0AReactDOM.render(%0A%20%20%3CRelay.RootContainer%0A%20%20%20%20Component%3D%7BApp%7D%0A%20%20%20%20route%3D%7Bnew%20AppRoute()%7D%0A%20%20%2F%3E%2C%0A%20%20mountNode%0A)%3B%0A) in Relay Playground, but the fragment is fetched and written without error.

I also created an extra test for `diffRelayQuery` to make sure that the `id` field wasn't being removed in the diff stage (since the examples above are types that define an `id` field but do not implement the `Node` interface).

@brenoc @BerndWessels - Can you create a repro case in Relay Playground to demonstrate this issue?

**Comment by brenoc** [comment]
@josephsavona I have a repo that you can run and see the issue:
https://github.com/brenoc/relay-starter-kit/tree/relay/typenameIssue

It's just a fork of relay-starter-kit with some minor changes in the code. Is that helpful?

Sorry for not providing a case in Relay Playground as you asked. I think it will take some time for me to port that code into Relay Playground.

**Comment by BerndWessels** [comment]
I think maybe I was just wrong thinking to be able to stick a database id in to object id. It seems that Relay needs type identification within the id to be able to operate. I am still not very comfortable with it, but slowly understand why I can't just put a plain database id into the id property.

Here is a more detailed information about that whole area: http://stackoverflow.com/questions/33399901/in-relay-what-role-do-the-node-interface-and-the-global-id-spec-play

Cheers

**Comment by josephsavona** [comment]
@BerndWessels Yes, see also the [Node Interface Specification](http://facebook.github.io/relay/docs/graphql-object-identification.html#content) - does implementing the `Node` interface for these types solve the problem?

**Comment by rblakeley** [comment]
That same error:
> Warning: RelayQueryWriter: Could not find a type name for record ...

pops up when I bump `react-relay ^0.5.0 -> ^0.6.0` and `babel-relay-plugin ^0.4.1 -> ^0.6.0`

**Comment by josephsavona** [comment]
@rblakeley can you provide more information? What is the unabbreviated error message? How did you query for that record (i.e. what field did you query that returned it), and what is the schema definition for that field?

**Comment by BerndWessels** [comment]
Hello
Not sure if this is still related, but all my problems came from trying to fiddle around with the `id` property of entities.
I tried to use my database ids instead of sticking with the relay generated ids from the `nodeDefinitions` functions.
So just in case you try the same and end up with errors like the one mentioned in this issue - you should really stick to the relay generated `ids` and use the `nodeDefinitions` function to serialize and deserialize.
It took me some time to understand how that all fits together and how to resolve from and to my database objects and ids in relay.
I created a kind of [starter-kit](https://github.com/BerndWessels/react-webpack) that should help to understand how a database like mysql can be plugged in to a react-relay graphql project.
Cheers
Bernd

**Comment by rblakeley** [comment]
@josephsavona the unabbreviated error looks like:
> Warning: RelayQueryWriter: Could not find a type name for record `client:client:6810115162:UmVzb3VyY2U6NA==`.

The app works without issue when I don't bump to `0.6.0`. But when I do bump, a specific mutation is triggering the error. The mutation pattern is to create a new item, `Group`, add the new `groupEdge` to my `User`'s `groups` connection, and to add the `userEdge` to the new `Group`'s `users` connection.

I am using a central [registry](https://github.com/rblakeley/pluck-yourself/blob/master/data/types/registry.js) for my object types which [wraps](https://github.com/rblakeley/pluck-yourself/blob/master/data/types/node.js) `nodeDefinitions`, if that's relevant.

I'm not sure how to answer:
> How did you query for that record (i.e. what field did you query that returned it), and what is the schema definition for that field?

...but the relevant files are:
[js/components/NewGroupPanel.js](https://github.com/rblakeley/pluck-yourself/blob/master/js/components/NewGroupPanel.js)
[js/mutations/NewGroupMutation.js](https://github.com/rblakeley/pluck-yourself/blob/master/js/mutations/NewResourceMutation.js)
[data/mutations/NewGroupMutations.js](https://github.com/rblakeley/pluck-yourself/blob/master/data/mutations/NewGroupMutation.js)
[data/types/GroupType](https://github.com/rblakeley/pluck-yourself/blob/master/data/types/GroupType.js)
[data/types/UserType](https://github.com/rblakeley/pluck-yourself/blob/master/data/types/UserType.js)

**Comment by josephsavona** [comment]
Thanks for filing this - i've identified the missing `__typename`, will send a fix.

**Comment by josephsavona** [comment]
@rblakeley Note that this is just a warning, and Relay will continue to work as-expected when that occurs. At worst, some operations may be *slightly* less efficient due to the missing typename.

**Comment by rblakeley** [comment]
@josephsavona :ok_hand:

**Comment by josephsavona** [comment]
the fix is on master and will go out in the next release. thanks for reporting!

**Comment by laurenskling** [comment]
I'm still getting this warning, at relay 0.7.1 `Warning: RelayQueryWriter: Could not find a type name for record 'VXNlcjox'.` 

this is the request i make:
```
user: () => Relay.QL`
      fragment on User {
        name
        friends(first: $count) {
          edges {
            cursor
            node {
              name
            }
          }
          pageInfo {
            hasNextPage
          }
        }
      }
    `,
```

The `VXNlcjox` id is the id the User is getting from `globalIdField('User')`
When i request more friends, the warning appears, my data is:

```
{
  "data": {
    "node": {
      "_friendsUatc9": {
        "edges": [
          {
            "cursor": "YXJyYXljb25uZWN0aW9uOjI=",
            "node": {
              "__typename": "Friend",
              "name": "resolved heaehraerhaerhaenk",
              "id": "RnJpZW5kOjM="
            }
          },
          {
            "cursor": "YXJyYXljb25uZWN0aW9uOjM=",
            "node": {
              "__typename": "Friend",
              "name": "resolved heaerhaerhnk",
              "id": "RnJpZW5kOjQ="
            }
          }
        ],
        "pageInfo": {
          "hasNextPage": true
        }
      },
      "id": "VXNlcjox"
    }
  }
}
```

if i read `RelayQueryWriter.prototype.getRecordTypeName` correctly, its expecting to get `__typename` next to the `id`, but it's not getting it from the node request, and i don't see how i can add it to my node.

Thanks for any help, i hope my code makes it more clear.

**Comment by josephsavona** [comment]
> When i request more friends, the warning appears

@laurenskling how are you requesting more fields? For example, are you fetching a new query via `RelayRootComponent`, or are you using `setVariables/forceFetch` in a component? If the latter, what is the component's fragment?

**Comment by laurenskling** [comment]
setVariables:
```
    this.props.relay.setVariables({
      count: this.props.relay.variables.count + 2
    });
```
 the fragment i posted above, right? This is my route:
```
user: (Component) => Relay.QL`
      query nameQuery {
        user {
          ${Component.getFragment('user')}
        }
      }
    `,
```

**Comment by gauravtiwari** [comment]
:+1:

**Comment by gauravtiwari** [comment]
#### Infinite scroll feature:
 
Set Variables: 

``` Javascript
if(this.props.root.posts.pageInfo.hasNextPage) {
  this.setState({
    loading: true
  });
  this.props.relay.setVariables({
    count: this.props.relay.variables.count + 20
  }, readyState => {
    if (readyState.done) {
      this.setState({
        loading: false,
      })
    }
  });
} else {
  if (!this.state.done) {
    this.setState({
      done: true,
    });
  }
}
```

Fragment: 
``` javascript
const PostsContainer = Relay.createContainer(Posts, {
  initialVariables: {
    count: 20,
    order: '-id',
    filter: null,
  },
  fragments: {
    root: () => Relay.QL`
      fragment on Viewer {
        id,
        posts(first: $count, order: $order, filter: $filter) {
          edges {
            node {
              id,
              ${PostPreview.getFragment('post')}
            }
          }
          pageInfo {
            hasNextPage
          }
        }
      }
    `,
  },
});
```

**Comment by josephsavona** [comment]
Thanks for the extra info. Reopening to track this.

**Comment by gauravtiwari** [comment]
@josephsavona For some reason, this doesn't throw the warning on Heroku, but only on local development: [https://relay-rails-blog.herokuapp.com/](https://relay-rails-blog.herokuapp.com)

**Comment by josephsavona** [comment]
Thanks again for all the info - I think I see what's happening. In both cases, Relay isn't querying for `__typename` because the type is already known (for @laurenskling the type is `User`, for @gauravtiwari  it's `Viewer`). We can squash this warning by using the existing information about the type in the store, i'll send a PR.

Note that in the meantime this is just a warning and Relay should be working just fine.

**Comment by chirag04** [comment]
#860 fixed the warning for me. :+1:

**Comment by laurenskling** [comment]
Awesome, glad I could have been of help. Thanks for fixing it!

**Comment by josephsavona** [comment]
This should be fixed - feel free to comment if not!

**Comment by albert-the-creator** [comment]
I'm experiencing this in `"babel-relay-plugin": "0.11.0", "react-relay": "0.10.0"` when using the include directive. When $isMounted is initiated at true from the start, it all works, but when initiate it at false, then after the component mounts, set $isMounted to true, I get the query writer error

```
user: () => Relay.QL`
        fragment on User {
            id
            uuid
            first_name
            is_anonymous
            posts(first: $count, 
                  post_type: $post_type, 
                  trade_type: $trade_type, 
                  trade_status: $trade_status) 
                  @include(if: $isMounted) {
                pageInfo {
                    hasNextPage
                }
                edges {
                    cursor
                    node {
                        id
                        ${MediaItem.getFragment('post')}
                    }
                }
            }
            ${CreatePost.getFragment('viewer')}
        }`
```
    
![screen shot 2017-04-28 at 12 30 48 pm](https://cloud.githubusercontent.com/assets/20915233/25544396/29cbdeb2-2c0f-11e7-99c0-a6e1479c53d1.png)
