### ISSUE TITLE
Purging unneeded data

### ISSUE THREAD

**Issue by HurricaneJames** [facebook/relay#479]
Sorry if this is has been discussed somewhere, but I cannot find it. Is there a way to make Relay purge old queries. For example, I want to infinite scroll through a list of items. At some point while scrolling down the list I want to purge the old queries and just re-fetch them when scrolling back up.

**Comment by wincent** [comment]
At the moment, the only way to force a refetch is using a mechanism like [`forceFetch`](http://facebook.github.io/relay/docs/api-reference-relay-container.html#forcefetch), but in the example that you describe that would refetch everything in the connection, which may be an intractably large amount of data.

Note that we already have some code in place ([RelayStoreGarbageCollector](https://github.com/facebook/relay/blob/master/src/store/RelayStoreGarbageCollector.js) and related classes) to do a simple form of garbage collection, but it is based on the notion of subscribed components (ie. which components are mounted; it has no notion of what is visible within a viewport nor how long since a given piece of data was accessed) and it is not active by default.

The use case you describe is one that we've talked about internally, although I don't know if we have a GitHub issue for it yet. If not, this one can be it!

**Comment by wincent** [comment]
Added the "discussion" label as there are a number of ways this problem could be approached.

**Comment by HurricaneJames** [comment]
Even with forceFetch, it does not appear to actually throw out everything and fetch all the data again. I'm working on issue #478 where tracking sub-query fragments (`trackedNodes`) returns those fragments with random ordering causing issues rebuilding connection edges. I will admit that I have not gone too deep into forceFetch, but it appears to still run the `diffRelayQuery` which builds up all those sub-fragments instead of tossing out all trackedNodes and refetching everything. 

As for my example, when I said refetch them, I didn't mean all at once. If I extend my infinite scroll by 20 items when I'm scrolling down, then I would probably do the same when scrolling back up. Though in practice I would try to avoid this type of infinite scroll. I implemented it once and the view position issues were a nightmare.

**Comment by saikat** [comment]
Does `untrackNodesForID` in RelayQueryTracker.js help you?  It's not a documented method and I have not used it.

**Comment by josephsavona** [comment]
@HurricaneJames Currently there is no way to avoid the buildup of multiple distinct tracked queries for e.g. ranges. We typically recommend specifying the result of connection changes via configs such as `RANGE_ADD`, which tell Relay how a connection will change as the result of a modification. This can help to avoid refetching the entire range - have you tried that? 

Note that we're actively working on changing tracked queries in #485.

@saikat `untrackNodesForID` is private API and may (read: almost certainly will) change at any time. Also, using it in this case on the connection would cause Relay not to fetch the connection nodes at all, which doesn't seem to be the desired behavior.

**Comment by josephsavona** [comment]
merging into #537
