### ISSUE TITLE
Optimize shouldComponentUpdate for react-router-relay

### ISSUE THREAD

**Issue by johanobergman** [facebook/relay#496]
`react-router-relay` merges all the queries from `react-router` routes into a top level `relay` route. When `react-router` transitions into a new route, `react-router-relay` merges the new queries into a new top level `relay` route.

This breaks relay's `shouldComponentUpdate`, because of [this](https://github.com/facebook/relay/blob/master/src/container/RelayContainer.js#L769-L771) (returns false when `context.route` has changed). @taion suggested I'd post the issue here since there's no easy way for `react-router-relay` to get around this.

**Comment by taion** [comment]
To clarify a bit on what's happening -

`react-router-relay` supports nested React Router routes with per-route queries.

It generates a Relay route by aggregating together all of those sets of queries together into a single set of queries, and passing that to a top-level Relay `RootContainer`.

As a result, we can have cases where the Relay route changes, but most of the queries do not in fact change (i.e. when only a single deeply nested React Router route gets switched out). However, because the Relay route has changed, the `shouldComponentUpdate` check always returns `true`.

I'm not sure if I'm missing something, or if there's a better way to deal with this on our side.

**Comment by johanobergman** [comment]
Could the route's name be used to check for equality in `shouldComponentUpdate`? That would give `react-router-relay` an option to specify whether the route is a new one or not.

**Comment by taion** [comment]
No - we change the name of the generated route whenever the queries change anyway. It is in fact a different route.

**Comment by johanobergman** [comment]
@josephsavona Do you have any input on this?

**Comment by josephsavona** [comment]
The active route affects both the shape of the container fragments/variables and what the wrapped component renders - any change in route *requires* a re-render. Routes are meant to aggregate all the queries for a single, root container. 

`react-router-relay` is designed to support multiple levels of root containers - one at each level of the route hierarchy - and therefore a single route doesn't seem like the right fit. How about creating a new context at each level of the route hierarchy, each with its own route? When the route changes, only the affected contexts would need to change their route, and components in unaffected portions of the tree would not be affected. This might require a custom alternative to RelayRootContainer/RelayRenderer.

**Comment by taion** [comment]
!

I hadn't thought of just re-implementing RootContainer/Renderer entirely. That makes a ton of sense though.

**Comment by josephsavona** [comment]
@taion Yeah, this seems like the most robust option. Feel free to cc us on pull requests/branches (even on `react-router-relay`) if you'd like feedback on an implementation.

**Comment by taion** [comment]
Actually, do you think it'd be awful to just render a bunch of `RelayRenderer`s into a detached DOM node, then just manage the plumbing of the data myself? Effectively what I'm doing right now, but with one `RelayRenderer` per route, and moving the `RelayRenderer`s off the main component tree entirely (since I need more than one, but don't want to e.g. add a `<div>` or whatever to wrap them all).

**Comment by johanobergman** [comment]
Will that cause a network request for every `RelayRenderer` in a nested route hierarchy?

**Comment by devknoll** [comment]
> Actually, do you think it'd be awful to just render a bunch of RelayRenderers into a detached DOM node

That sounds kinda familiar ;-)

'RelayRenderer'? Man things are changing. I need to catch up with Relay again :-)

**Comment by taion** [comment]
Yeah, the more things change... that said I don't think I'm going to get to this any time soon.

I don't know about the network requests. The default network layer already sends one request per query anyway.

**Comment by josephsavona** [comment]
> do you think it'd be awful to just render a bunch of RelayRenderers into a detached DOM node, then just manage the plumbing of the data myself?

This sounds really inefficient - this really seems like a good use-case for a custom alternative to RelayRenderer. Let's move discussion to relay-tools/react-router-relay#68
