### ISSUE TITLE
Any examples of pagination using cursors?

### ISSUE THREAD

**Issue by luisobo** [facebook/relay#497]
Hi there,

I'm trying to implement pagination, I've got to a point where I can make pagination "work" based on [this example](https://facebook.github.io/react/blog/2015/03/19/building-the-facebook-news-feed-with-relay.html#all-the-news-fit-to-be-relayed). Initially the component loads 5 items, but when asking to load the next five it request the server the `first: 10`, basically, refetching the first 5 again. I'd hope it would only request items 6 to 10 using cursors. 

I failed miserably at finding an example that accomplished that. I couldn't make it work myself either, trying to track a variable for the `after` cursor, because the collection of items gets replaces by the next 5, instead of being appended.

Any pointers on how to properly implement this?

Thank you!

**Comment by wincent** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

Questions like yours deserve a purpose-built Q&A forum. Would you like to post this question to Stack Overflow with the tag #relayjs? We'll be happy to answer there. Post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs

**Comment by soonlive** [comment]
@luisobo have you got any solution?

**Comment by luisobo** [comment]
@soonlive I'm afraid not.

**Comment by josephsavona** [comment]
@luisobo @soonlive Please post on [Stack Overflow](https://stackoverflow.com/questions/ask?tags=relayjs) and provide a link here - we're happy to answer this type of how-to question there.

**Comment by petesaia** [comment]
I know this is old, but figured I'd drop this gist here just incase anyone else is searching for some real world examples of the technique.

https://gist.github.com/petesaia/17bad21c01392dac9162f33dd8cc3ed0
