### ISSUE TITLE
Expected response payload to include the newly created edge

### ISSUE THREAD

**Issue by jwaldrip** [facebook/relay#521]
I am getting this error:

```
Warning: writeRelayUpdatePayload(): Expected response payload to include the newly created edge `listEdge` and its `node` field. Did you forget to update the `RANGE_ADD` mutation config?
```

Can someone explain how to solve the issue of Relay not requesting an Edge object. I have seen numerous posts, but no real clear solution. Here is a gist will all the information:

https://gist.github.com/jwaldrip/a1aa07745151a6ce6add

**Comment by johanobergman** [comment]
My response from discord:
> johanobergman: @jwaldrip I think it might happen if your rangeBehaviors doesn't cover all possible cases of query arguments.
I think relay checks rangeBehaviors twice, once before the request and once after. I had an issue with multiple arguments where it required the order of arguments to be both arg1.arg2 and arg2.arg1
so I specified it twice...

Is this a bug? I've seen a recent commit (4aef0696a2db3422bea1b6c8236dd73a09ac25cc) which should allow arguments in any order. Will that fix the issue?

**Comment by josephsavona** [comment]
Relay will only fetch the newly created edge if some part of the application is actively querying for the range. In the gist the mutation configs include the following:

```javascript
{
  type: 'RANGE_ADD',
  parentName: 'root',
  parentID: this.props.root.id,
  connectionName: 'lists',
  edgeName: 'listEdge',
  rangeBehaviors: {
    ': 'append'
  }
}
```

The new edge (field `listEdge`) will not be fetched unless some part of the application is rendering the `lists` connection -otherwise, Relay doesn't know what fields on `listEdge` are necessary - recursively expanding all possible subfields would fetch too much data.

**Comment by IlyasM** [comment]
@josephsavona, I have  StoriesPage which is a root container. Along with StoriesPage I have AddStoryPage which is also a rootContainer so when I go from StoriesPage to AddStoryPage there I do AddStoryMutation (RangeAdd on StoryConnection) which succeeds (new edge's fields match the stories connection node fields which is queried in StoriesPage) and on success I go back to StoriesPage but there the new edge has not been added unless I do full reload, shouldn't it be updating as it is the only page requesting stories connection? for rangeBehaviors I have {'' : ''}

**Comment by steveluscher** [comment]
Thanks for your question! I have an answer for you, but…

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

Questions like yours deserve a purpose-built Q&A forum. Would you like to copy/paste this question to Stack Overflow with the tag #relayjs? I'll be happy to answer there. Post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs

**Comment by IlyasM** [comment]
Hi thanks, here is the link https://stackoverflow.com/questions/33498099/range-add-mutation-successful-not-updating-the-view

**Comment by steveluscher** [comment]
Oh, I was talking to @jwaldrip, @IlyasM. I have an answer to his question, but not yours yet. Can you supply code samples in your Stack Overflow question?

**Comment by bfwg** [comment]
@steveluscher Hi, I run into the same problem out of nowhere, can you tell me the answer to jwaldrip's problem? 
Thanks
