### ISSUE TITLE
Define fragments based on fetched data

### ISSUE THREAD

**Issue by bgnorlov** [facebook/relay#529]
Hi. Can anyone explain how I can define fragments on Relay container based on data which currently fetched in component? Consider this example:
```javascript
const TreeNodeContainer = Relay.createContainer(TreeNode, {
  fragments: {
    node: (variables) => {
      return Relay.QLfragment on TreeNode {
        id,
        expanded,
        title,
        children(first: 1000) @include(if: $expanded) {
          edges {
            node {
              id,
              ${TreeNodeContainer.getFragment('node').if('how I can get component props or "expanded" value here?')}
            }
          }
        }
      }
    }
  },
});
```
TreeNode component is simple enough - it has mutation which changed 'expanded' field on server. 
```javascript
class TreeNode extends React.Component {

  handleClick() {
    Relay.Store.update(new ExpandNodeMutation({node: this.props.node}));
  }

  render() {
    var node = this.props.node;
    var variables = this.props.relay.variables;
    return (
      <div className="node">
        <div className="title" onClick={this.handleClick.bind(this)}>{node.title}</div>
        <div className="children" style={{paddingLeft: 20}}>
          {node.expanded && node.children && node.children.edges.map((edge)=> {
            return <TreeNodeContainer node={edge.node} key={edge.node.id}/>
          })}
        </div>
      </div>
    )
  }
}
```

**Comment by kassens** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

Questions like yours deserve a purpose-built Q&A forum. Would you like to post this question to Stack Overflow with the tag #relayjs? We'll be happy to answer there. Post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs

**Comment by bgnorlov** [comment]
Sure, https://stackoverflow.com/questions/33452090/define-fragments-based-on-fetched-data.
