### ISSUE TITLE
Is it possible for babel-relay-plugin to get its own repository?

### ISSUE THREAD

**Issue by ryancole** [facebook/relay#548]
Babel's recent release of version 6 changes how plugins are written, slightly. If babel-relay-plugin had its own repository, it could be updated to support Babel 6, with clear tags for Babel 5, etc. Not sure if worth or not, but just wanted to toss the idea out there.

**Comment by josephsavona** [comment]
The plugin has its own npm package, but having it in the same repository simplifies bookkeeping (one place for issues, one repo to sync between FB & OSS) and also simplifies the process of testing plugin changes. The OSS tests use the latest (master) version of the plugin so that we're sure the output of the plugin works in Relay.
