### ISSUE TITLE
graphql-relay-js dependency

### ISSUE THREAD

**Issue by ButuzGOL** [facebook/relay#563]
All the examples use graphql-relay-js on server
Can I handle graphql server without graphql-relay-js and use relay on client ?
Situation if one client use only graphql api and another client use relay to get data how to handle it ?

**Comment by josephsavona** [comment]
Thanks for your question! I have an answer for you, but we want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

Questions like yours deserve a purpose-built Q&A forum. Would you like to post this question to Stack Overflow with the tag #relayjs? We'll be happy to answer there. Post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs

**Comment by ButuzGOL** [comment]
Done https://stackoverflow.com/questions/33617319/graphql-relay-graphql-relay-js-dependency
