### ISSUE TITLE
Document common use cases that aren't yet solvable easily with Relay (with workarounds)

### ISSUE THREAD

**Issue by AndrewIngram** [facebook/relay#595]
Related to discussions about pagination strategies, as well as serious limitations i've found with rangeBehaviors. I think it would be prudent to list any common UI patterns that Relay doesn't support well (if at all) in its current state. Given the amount of effort involved in getting a Relay project up and running, it's disconcerting that 2 months later i'm stumbling upon limitations that are fairly problematic. Relay is no longer a technical preview, so there's an expectation that even if it's not feature-complete, that most limitations can be worked around easily enough.

**Comment by josephsavona** [comment]
Thanks for your feedback. Relay is designed to support common use cases at Facebook first, and there are certainly alternate forms of pagination that other products may need. We're happy to accept pull requests to document the currently supported forms of connections (maybe add a "Pagination" page to the guides section of the docs) or to add support in core for alternate forms of pagination (limit/offset, etc.).

**Comment by AndrewIngram** [comment]
I think you've misunderstood my aim with this issue. I used pagination merely as an example.  The bigger issue is that an important part of any project is to allow potential user to evaluate whether it's fit for purpose. Using myself as an anecdote, i've been working with Relay full-time basically since the day it was open-sourced, and I'm only now reaching the conclusion that it's not really ready for my usage.

There are conversations distributed across various mediums (github issues, chat rooms, stackoverflow mainly) that touch on the limitations, but nothing that says "If you want to X, Relay probably isn't ready for you yet, and won't be until Y". Now, I can go ahead and start a wiki page on this repo (I assume the public can do that), but if it's going to end up being some kind of source of truth, it'd be good to have the blessing of some core contributors.

**Comment by plievone** [comment]
Maybe have a tips section in Relay docs similar to the [React docs](http://facebook.github.io/react/tips/introduction.html) sidebar? It would help in evaluation, as one could see the pain points and possible unwieldy workarounds easier.

**Comment by rblakeley** [comment]
Is the use case for two-way connections at all possible? I've been gritting my teeth trying to make it work for a few days now. I only today found the issue that notes you can't have connectionType at the root. So I wrapped my two connectionTypes, but still can't make it work.
```
users { groups }
groups { users}
```
Is there an example with this kind of data relationship or is it known whether this is possible?

**Comment by josephsavona** [comment]
Thanks for living on the bleeding edge and trying Relay since day one! Relay is still a new framework, and we appreciate your trying it out early, filing issues, and giving us feedback.

Since the initial launch we've worked to document the current and planned features in the form of our [roadmap](https://github.com/facebook/relay/wiki/Roadmap), and we review the issues list to make it easy to see the upcoming fixes and enhancements. We've also flushed out the [guides](http://facebook.github.io/relay/docs/guides-containers.html#content) and [examples](https://github.com/facebook/relay/tree/master/examples) to demonstrate use-cases where Relay excels.

We're happy to accept pull-requests updating the documentation, examples, etc - if the supported features are unclear, we'd like to fix that. Otherwise, it sounds like we need to flush out the guides section of the documentation. For example, it might be worth adding a "Pagination" section (or other areas) to cover various scenarios and how they can be implemented in Relay.

Finally, there's only so much the core team can do at one time, but we're happy to support external contributors in adding features or fixing bugs. If you're interested in contributing but not sure where to start, get in touch! (at mention on [Discord](discordapp.com/channels/102860784329052160/102861057189490688), email us, etc.).
