### ISSUE TITLE
rangeBehaviors should be a function that returns a GraphQLMutatorConstants.RANGE_OPERATION

### ISSUE THREAD

**Issue by steveluscher** [facebook/relay#615]
As mentioned by @johanobergman in #604 and similar to what @AndrewIngram [proposed](https://github.com/facebook/relay/issues/538#issuecomment-156396132) in #538, let's make `rangeBehaviors` a function that receives the connection arguments and returns one of `GraphQLMutatorConstants.RANGE_OPERATIONS`.

```js
getConfigs: [{
  /* ... */
  rangeBehaviors(
    fieldArgs: {[argName: string]: argValue: string}
  ): ?$Enum<typeof GraphQLMutatorConstants.RANGE_OPERATIONS> {
    return isBefore(fieldArgs.startDate, fieldArgs.endDate) ?
      GraphQLMutatorConstants.RANGE_OPERATIONS.APPEND :
      GraphQLMutatorConstants.RANGE_OPERATIONS.PREPEND;
  }
  /* ... */
}]
```

Add an appropriate deprecation warning to `RelayDeprecated`.

Bonus: write a [jscodeshift](https://medium.com/@cpojer/effective-javascript-codemods-5a6686bb46fb#.pe5meqdiz) codemod that will mod this:

```js
rangeBehaviors: {
  'foo(true)': 'prepend',
  'foo(false)': 'append',
}
```

…to this:

```js
rangeBehaviors({foo}) {
  if (foo === true) {
    return 'prepend';
  } else if (foo === false) {
    return 'append';
  }
}
```

**Comment by johanobergman** [comment]
Awesome, this will help a lot since I won't have to track all cached parameter combinations myself.

You could also pass the entire connection to that function and let the developer manually insert the record wherever he wants it. This would be a great deal more flexible than `append`, `prepend` and `remove` are (even though I don't have a use case for it myself right now).

**Comment by devknoll** [comment]
Just wanted to chuck this in here, since it has been discussed a little before: https://github.com/facebook/relay/issues/293#issuecomment-139417086

**Comment by AndrewIngram** [comment]
As mentioned in the related ticket, I'm still not convinced the mutation is the place to handle this. It feels like it could be defined in the actual query on the connection, or in the schema itself (as briefly discussed in the other ticket). If this doesn't make sense, it'd be good to have some insight as to why.

**Comment by xuorig** [comment]
Questions about this issue:

First, since `rangeBehaviors` wont be an object anymore, these lines here wont work as expected. I'm not sure how they can be modified now that we don't have access to what rangeBehaviors will be used? https://github.com/facebook/relay/blob/master/src/mutation/RelayMutationQuery.js#L211-L219

Second question:
To be able to receive argument as an object like this:
```
rangeBehaviors({foo}) {
  if (foo === true) {
    return 'prepend';
  } else if (foo === false) {
    return 'append';
  }
}
```
It means we'll need to transform the RangeFilterCalls from this `[{name: 'orderby', value: 'recent}]` to this `{orderby: 'recent'}` before calling `config.rangeBehaviors`. Just checking I'm understanding this well.

**Comment by josephsavona** [comment]
> It feels like [range configs] could be defined in the actual query on the connection

@AndrewIngram This would force developers to repeat the append/prepend logic everywhere that a connection was used. Furthermore, what would Relay do if two components disagreed? Whether to append/prepend/etc is really something known best by the implementor of the mutation; the logic belongs as close as possible to the mutation definition.

> , or in the schema itself

We're continuing to explore this option. There are lots of possibilities and we'd like to prove out an approach on the client first. The proposal here is a first step in that direction.

**Comment by josephsavona** [comment]
> First, since rangeBehaviors wont be an object anymore, these lines here wont work as expected.

@xuorig Good point. It's possible to list all combinations of fetched connection calls given the parent id of the connection. For example, given `viewer { friends(...) }`, if we know the `viewer` id then we can list out all the combinations of arguments on `friends` that have been fetched. That's available as [`RelayRecordStore#getConnectionIDsForField`](https://github.com/facebook/relay/blob/master/src/store/RelayRecordStore.js#L571-L595). That will give you a list of connection IDs which you can then use to call [`RelayRecordStore#. getRangeFilterCalls `](https://github.com/facebook/relay/blob/master/src/store/RelayRecordStore.js#L611-L620). Together this should give you all the sets of calls needed to replace the check you mentioned in [RelayMutationQuery](https://github.com/facebook/relay/blob/master/src/mutation/RelayMutationQuery.js#L211).


> To be able to receive argument as an object like this: ... It means we'll need to transform the RangeFilterCalls

Yup, we'll have to map the array into an object for convenience.

**Comment by xuorig** [comment]
@josephsavona good to know! 

I'm trying to get the recordStore by requiring `RelayStoreData` and getting the record store like this `RelayStoreData.getDefaultInstance().getRecordStore()`. It works in tests but somehow when I test it with the todo, `RelayStoreData` is an empty object and `getDefaultInstance` is `undefined`... Any idea what's going on ?

**Comment by josephsavona** [comment]
@xuorig are you trying to require `RelayStoreData` from outside of Relay? If so, you'll have to use `require('react-relay/path/to/RelaySoreData')` - individual files from npm packages aren't publicly available via `require('<name>')` so you have to require by path.

**Comment by xuorig** [comment]
@josephsavona Not even, I'm requiring it inside `RelayMutationQuery`, the require throws no errors either, just returns an empty object!

**Comment by josephsavona** [comment]
Ah - it could also be a circular dependency, you may have to require the store somewhere else (`RelayMutationQueue` is passed an instance of `RelayStoreData`, for example).

**Comment by AndrewIngram** [comment]
For me the larger issue is regarding whether append/prepend is enough. For use cases I have right now, it's not. A function to get a sorting key is the obvious solution. But this means you'd also need to apply that function to everything in the connection.

I'm a little uneasy about the solution proposed in this issue, mainly because it feels like changing the rangeBehaviours API in a way that'll have to be changed yet again if we need to support sorting (which obviously I think we do).

Of course, there may already be a way of handling adding nodes to arbitrary positions that i'm not aware of.

**Comment by AndrewIngram** [comment]
Even with the proposed solution, do we not also need access to the edge and node being added? Depending on arguments passed to the mutation, or backend behaviour, we may not know whether to append/prepend/ignore without looking at the node itself.

**Comment by josephsavona** [comment]
@xuorig implemented this in 56e52d3

**Comment by brysgo** [comment]
This doesn't work for arguments that have a non string value, like boolean.

**Comment by josephsavona** [comment]
@brysgo Good catch, @xuorig has put up #1216 to address this.
