### ISSUE TITLE
IE 8 support? Out of space error in Star Wars example

### ISSUE THREAD

**Issue by DylanSale** [facebook/relay#624]
Does Relay support IE 8? I couldn't find a mention of it on the site anywhere, but I know React does (or did?)

In my testing with the Star Wars example, it is getting a stack overflow somewhere in React. It seems to be related to the `route` prop on the `Relay.RootContainer`. It gives `Warning: Failed propType: Function expected`, then the "out of stack space" error at app.js line 11918, character 15 (I'm not sure if this is useful due to webpack, but its in the finally block of the Transaction Mixin's perform method).

Stepping through it shows it is crashing somewhere in the validate prop methods when it is validating the `route` prop. I had trouble getting more details because IE8's developer tools are impossible to use.

EDIT:
Additionally, it seems that there is an infinite recursion where `RelayQueryNode.create` calls `createNode` which calls `RelayQueryNode.create` until it gets a stack overflow. This may be unrelated to the other issue, as it seems to happen when parsing the response from the server. It looks like on Chrome a completely different createNode function gets called. Really weird.

**Comment by shalomvolchok** [comment]
Same question here. Can we get Relay to support IE 8? We have React working with the polyfills, but can't seem to get Relay working... Is it a dead end, or some additional polyfills are needed?

**Comment by josephsavona** [comment]
Thanks for your question. Unfortunately, we are unable to provide support for IE8. It may be possible to get Relay working on IE8 by using polyfills or workarounds, but we can't make guarantees that future changes won't cause a regression.

**Comment by DylanSale** [comment]
Thanks for the reply. What is the lowest version you do support?

**Comment by plievone** [comment]
I was intrigued and got Star Wars example working in IE8 with a couple of changes:
- You can get rid of infinite recursion by renaming `createNode` in [RelayQuery.js](https://github.com/facebook/relay/blob/f7c61d8/src/query/RelayQuery.js#L1274). You can see the problem in built file, where [the other `createNode`](https://github.com/facebook/relay/blob/f7c61d8/src/query/RelayQuery.js#L338) has also a local function name `createNode` (to be displayed in stack traces), confusing IE8 scopes. @josephsavona You may want to rename the outer `createNode` helper to avoid confusion?
- You can use some IE8-compatible fetch polyfill instead of whatwg-fetch, such as `fetch-polyfill`, otherwise the data won't be available and only a blank page renders.

Haven't tested it further, but the example renders fine. There are proptype and contexttype validation warnings due to shims adding extra Symbol-related properties to `RelayPropTypes.QueryConfig`, and React shape validator doesn't check the hasOwnProperty. But they won't kill the page. There may well be other errors yet uncovered, though.

**Comment by josephsavona** [comment]
We're happy to accept PRs and address issues for IE9 and above.
