### ISSUE TITLE
Ability to convert connection to list of nodes

### ISSUE THREAD

**Issue by vladar** [facebook/relay#628]
There is a component `UserListWidget` with following container definition:

```javascript
// UserListWidget:
fragments: {
    users: () => Relay.QL`
        fragment on User @relay(plural: true) {
            id
            displayName
        }
    `
}
```

There is also parent component that needs to render connection of users as plain list. But following won't work:

```
<UserListWidget users={userConnection.edges.map(edge => edge.node)} />
```

It fails with error:
```
Invariant Violation: RelayContainer: Invalid prop `users` supplied to `UserListWidget`, expected element at index 0 to have query data.
```

Changing `UserListWidget` to accept userConnection instead of plain list of users is not an option, because it is a generic component and other parent components will only provide lists of users, not connections.

So I guess there should be a way to treat connection as plain list of nodes somehow?

**Comment by josephsavona** [comment]
Thanks for your question! I have an answer for you, but we want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

Questions like yours deserve a purpose-built Q&A forum. Would you like to post this question to Stack Overflow with the tag #relayjs? We'll be happy to answer there. Post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs

**Comment by vladar** [comment]
Posted at https://stackoverflow.com/questions/33877207/how-to-convert-relayjs-connection-to-plain-array
