### ISSUE TITLE
Offline, caching, service workers

### ISSUE THREAD

**Issue by kevinSuttle** [facebook/relay#631]
Hello Relay team. @leebyron sent me over. https://github.com/facebook/graphql/issues/124

Wondering if you have some perspective on Relay/React/GraphQL intelligent caching, state reconciliation, etc. Was wondering if you had any strategies, or have been testing during [2G Tuesdays](https://code.facebook.com/posts/1556407321275493/building-for-emerging-markets-the-story-behind-2g-tuesdays/).

**Comment by josephsavona** [comment]
We cover Relay's approach to caching in-depth as part of the [Thinking in GraphQL guide](https://facebook.github.io/relay/docs/thinking-in-graphql.html#client-caching). Typical approaches such as HTTP caching don't really apply with overlapping, hierarchical queries (as @leebyron mentioned, this is the same problem with caching the results of SQL queries). 

State reconciliation might refer to several things - what specifically do you mean? Note that Relay allows developers to optionally conform to the [Object Identification specification](https://facebook.github.io/relay/docs/graphql-object-identification.html#content), allowing Relay to automatically de-dupe results from queries and normalize response for you.

We're also working on caching data for offline use as mentioned on the [roadmap](https://github.com/facebook/relay/wiki/Roadmap). 

Re service workers, you could for example inject a [custom network layer](https://facebook.github.io/relay/docs/guides-network-layer.html#content) that was backed by a service worker.

I'm going to close this since there's no issue or bug to track, but feel free to continue the discussion here.

**Comment by josephsavona** [comment]
This is also covered in the [initial blog post](http://facebook.github.io/react/blog/2015/08/11/relay-technical-preview.html#whats-next):

> Finally, it's all too easy as developers to focus on those people with the newest devices and fastest internet connections. We're working to make it easier to build applications that are robust in the face of slow or intermittent connectivity.

**Comment by kevinSuttle** [comment]
Whoa, nice. First item on the wiki, too. Thanks @josephsavona!

**Comment by kevinSuttle** [comment]
@leebyron does DataLoader factor into the strategy here? https://github.com/facebook/dataloader

**Comment by leebyron** [comment]
DataLoader is useful for batching together many frequent requests that can be sent to a database's batch API call. DataLoader's caching is really nothing more than simple memoization, and it has no concept of "offline" since it's intended for a server environment.

Relay's cache model is far more sophisticated and offline support likely requires a different approach than DataLoader.
