### ISSUE TITLE
[graphQLServer] how to map to and from SQL Database ID ?

### ISSUE THREAD

**Issue by BerndWessels** [facebook/relay#640]
Hello

I try to make sense of it but can't figure it out.

In all examples I see that relay types use `id: globalIdField('type')`.

But how do I actually handle objects from a SQL database that have their own database ID?

For example:
I have `users` in a `user` table with `id` as primary key in a SQL database.
I know how to query my SQL database and make updates.
Now I want the relay graphql server to serve and mutate these users.
But I don't know how to deal with the 'id'.

Can anybody please provide a tiny example or code snippets?

Thank you so much
Bernd

**Comment by josephsavona** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

Questions like yours deserve a purpose-built Q&A forum. Would you like to post this question to Stack Overflow with the tag #relayjs? We'll be happy to answer there. Post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs
