### ISSUE TITLE
Add @relay(pattern: true) to the mutations guide / docs

### ISSUE THREAD

**Issue by jardakotesovec** [facebook/relay#647]
I noticed new `@relay(pattern: true)` in change log, but can't figure out from description nor tests what exactly it does and when I should use it when writing *fatQueries*.

Some example would be very helpful.

Thanks.

**Comment by steveluscher** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

Questions like yours deserve a purpose-built Q&A forum. Would you like to post this question to Stack Overflow with the tag #relayjs? We'll be happy to answer there. Post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs

**Comment by jardakotesovec** [comment]
http://stackoverflow.com/questions/34103296/purpose-of-relaypatterntrue

Sure, no problem. I tend to open such issues when I think that it likely will result in updating docs.

**Comment by steveluscher** [comment]
That's a good point! Renaming this issue and reopening.

**Comment by wincent** [comment]
This is important, so I'm going to fold it into #538, which is about overhauling the mutations API. (It will be easier to manage with the various interrelated mutations issues in a single place.)

Thanks once again for filing the report, @jardakotesovec!
