### ISSUE TITLE
[graphQLHTTP] accumulate resolve calls for a single request

### ISSUE THREAD

**Issue by BerndWessels** [facebook/relay#664]
Hi
When a `graphql request` hits my server it jumps into several different `resolve functions` depending on the query.
But I don't want to hit my database with sometimes dozens of small requests (basically a `select` in each `resolve` function). That would not really scale very well.

Is there a way to accumulate all these resolve calls for a single graphql request - so that at the end I can do some magic and build only a single `select` to my database and then resolve all promises?

I can see a few ways of building something myself by accumulating all the promises I return in the resolve functions, but I don't know when all resolve functions for a single request have been called.

Is there a solution to this problem? How does Facebook deal with that scenario?

Cheers
Bernd

**Comment by josephsavona** [comment]
I have an answer for you - but can you post this on [Stack Overflow](stackoverflow.com/questions/tagged/relayjs)? We're trying to keep the GitHub issues high-signal for bugs and enhancements. Please post a link to your SO question here and we'll answer!

**Comment by kassens** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

Questions like yours deserve a purpose-built Q&A forum. Would you like to post this question to Stack Overflow with the tag #graphql and #graphql-js? We'll be happy to answer there. Post a link to your Stack Overflow question here, to so that we don't lose track of it.

**Comment by BerndWessels** [comment]
@josephsavona 
Ok, I posted the question on [Stack Overflow here](http://stackoverflow.com/questions/34145915/how-to-accumulate-resolve-calls-for-a-single-request).
Cheers

**Comment by josephsavona** [comment]
answered!

**Comment by BerndWessels** [comment]
@josephsavona Thanks, added a comment to your answer, please check.
