### ISSUE TITLE
Props passed to container component is not being passed to child component.

### ISSUE THREAD

**Issue by cettox** [facebook/relay#668]
Hello everyone!

I am trying to figure out passing parameters to components that were already encapsulated with relay.createContainer method.

If I encapsulate a container using relay.createContainer method, then It seems I no longer can read props. They are simply not there after encapsulation. 

The only props available after container creation are, this.props.relay and the this.props.viewer prop which I defined as a data dependency.

The only workaround I see is to pass data to child components directly from Store's using Flux. I do not understand the reason why this behavior is implemented?

Thanks.

**Comment by josephsavona** [comment]
@cettox Thanks for posting - this sounds like it might be due to your specific configuration, as RelayContainer does pass props through to components. 

We're trying to keep GitHub issues limited to discussion of bugs and enhancements. Can you post a question at [Stack Overflow](http://stackoverflow.com/questions/ask?tags=relayjs) and paste a link to it here? Thanks!

**Comment by cettox** [comment]
@josephsavona It might be it. However, my configurations is as simple as possible, I just used what relay starter kit offers. I wonder if others experienced this behavior. And if this happens on a slight configuration change, which I am not sure 100%, then since this is a huge behavior that is totally unexpected and and affects developer experience, my guess is that it should better be documented here and after a confirmation, it should be considered as a bug. Lets wait if this incidence really limited to my case. Thanks. I am opening that Stack Overflow thread.
