### ISSUE TITLE
Props in prepareVariables ?

### ISSUE THREAD

**Issue by quazzie** [facebook/relay#673]
Hi can i access props in prepareVariables on a container ?

I have a recursive structure :
```
LocationList = Relay.createContainer(LocationList, {
	fragments: {
		location: () => Relay.QL`
			fragment on LocationPart {
				id, children { id, hasChildren, value, ${LocationListItem.getFragment('location')} }
			}
		`
	}
});
LocationListItem = Relay.createContainer(LocationListItem, {
	initialVariables: {
		expanded: false
	},
	fragments: {
		location: (variables) => Relay.QL`
			fragment on LocationPart {
				id, path, value, description, hasChildren,
				${LocationList.getFragment('location').if(variables.expanded)}
			}
		`
	}
});
```

And on the root i expand the first level by :
```
fragment on LocationPart {
	${LocationListItem.getFragment('location', { expanded: true })}
}
```

But i want to preserve the whole state and restore it when i return.
The preserve state i have covered and i pass down a object-tree with state to all nodes.
So i would like to be able to do this in prepareVariables:
```
prepareVariables() {
	return { expanded: this.props.open[this.location.id] };
}
```

I tried using a contructor:
```
constructor(props) {
	super(props);
	if (props.open[props.location.id]) props.relay.setVariables({ expanded: true });
}
```
but then relay complains about 
```Expected prop `location` supplied to `LocationList` to be data fetch by Relay.```

Is this possible ?

**Comment by kassens** [comment]
Thanks for your question! We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

Questions like yours deserve a purpose-built Q&A forum. Would you like to post this question to Stack Overflow with the tag #relayjs? We'll be happy to answer there. Post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs

**Comment by quazzie** [comment]
https://stackoverflow.com/questions/34255662/props-in-relay-preparevariables
