### ISSUE TITLE
 UNMET PEER DEPENDENCY babel-relay-plugin@0.6.1

### ISSUE THREAD

**Issue by BerndWessels** [facebook/relay#694]
Hi

Looks like you released a new version `0.6.1` of the `babel-relay-plugin` to `npm` without releasing a new matching version of `react-relay`.

Any particular reason for that? Would be good if you could keep these in sync to avoid confusion.

**Comment by josephsavona** [comment]
@BerndWessels Where did you see this warning, and what version of npm and relay are you using?

cc @kassens

**Comment by BerndWessels** [comment]
@josephsavona I maintain the `babel-relay-plugin-loader` module and regularly check for new versions of the `babel-relay-plugin`. This morning I noticed that somebody released `0.6.1` of the `babel-relay-plugin`. So I updated and published a matching version of the `babel-relay-plugin-loader`.

Maybe others want get it yet as long as they target a specific version of the plugin, but if you use `^0.6.0` then you get `0.6.1` automatically with the next fresh `npm install`.
And since `react-relay` has a `babel-relay-plugin` dependency targeting `0.6.0` it shows that warning.

It is not a real problem, I just thought I mentioned it here, since you said that `react-relay` and `babel-relay-plugin` should be in sync.

**Comment by kassens** [comment]
Sorry, this is a problem that rippled through.

- The plugin's version was updated in a4d037fd386f62af9cc4831c409c6e15bac67d88 to make sure internally the transform cache was invalidated, but no new version released.
- This caused `npm install` inside the examples to fail since they had the 0.6.1 version, but expected 0.6.0. As a solution to this, I published the plugin, without doing a full release. This was okay for relay core, as that specifies the exact version.
- Now (this issue) other projects broke that specify a loose version for the plugin.

We have 2 solutions:
- Release 0.7.0 from master
- Release 0.6.1 of core with the same code as 0.6.0 and just the dependency fixed.

**Comment by BerndWessels** [comment]
@kassens It doesn't really break anything, at least for me it only gives a `npm` warning `npm WARN react-relay@0.6.0 requires a peer of babel-relay-plugin@0.6.0 but none was installed.`

But having matching clean releases would be nice anyways ;)

**Comment by josephsavona** [comment]
@kassens thanks for confirming, and @BerndWessels for pointing this out. 

We'll go forward with a `0.7.0` release this week.

**Comment by treeder** [comment]
Did you release this?  I'm getting npm install errors too: 

```
npm ERR! node v5.3.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! babel-relay-plugin@0.6.1 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the babel-relay-plugin@0.6.1 prepublish script 'npm run build'.
```

**Comment by BerndWessels** [comment]
@treeder it looks like 0.7.0 hasn't yet been released - most likely due to Christmas ;)

**Comment by edvinerikson** [comment]
0.7 fixed this so I don't see any reason for this to be open and if it would bubble up again, this issue will still be searchable.

**Comment by josephsavona** [comment]
Thanks @edvinerikson :-)

**Comment by valorize** [comment]
Fyi: Got the same issue with relay version 0.9.4 and babel-relay-plugin (requering also 0.9.4) but babel-relay-plugin is the latest 0.9.2
