### ISSUE TITLE
Uncown bug

### ISSUE THREAD

**Issue by z81** [facebook/relay#702]
Client js
https://gist.github.com/z81/39db6f188087f6ad726f#file-main-js
Server js
https://gist.github.com/z81/47ad0a57ce9c527c2f0a#file-server-js
Generate this graphQL
```
type Query {
  users(limit: Int, order: String, id: Int): [User]
}

type RootMutationType {
  updateUser(id: String!, name: String): User
}

type Task {
  id: Int!
  title: String
}

type User {
  id: Int!
  name: String
  tasks: [Task]
}
```
Zero errors in console and not working.
In network xhr returned valid json result have users.
```
{
  "data": {
    "users": [
      {
        "id": 1,
        "name": "test11133"
      },
      {
        "id": 2,
        "name": "test2222"
      }
    ]
  }
}
```
Sorry for very bad english.

**Comment by josephsavona** [comment]
@z81 Relay doesn't currently support connections as root fields (as you have with `users` on the `Query` type). We're gradually implementing support for a wider variety of root fields, but in the meantime please see the workaround at #112. We suggest creating a "viewer" root field and putting top-level connections under viewer.

I'll close this issue since it's a known limitation with a documented workaround, but please feel free to ask follow-up questions here and we'll try to address.

**Comment by z81** [comment]
I use veawer in # 112, but still get do not get errors, please tell me in what is wrong.
GraphQl
`` `
type query {
   viewer: viewer
}

type Task {
   id: Int!
   title: String
}

type User {
   id: Int!
   name: String
   tasks: [Task]
}

type viewer {
   users: [User]
}
`` `
The server returns the
`` `
{
   "data": {
     "viewer": {
       "users": [
         {
           "id": 1,
           "name": "test11133"
         }
         {
           "id": 2,
           "name": "test2222"
         }
       ]
     }
   }
} `` `
Schema.js
https://gist.github.com/z81/39db6f188087f6ad726f
Client.js
https://gist.github.com/z81/47ad0a57ce9c527c2f0a
Sorry for bad english.
