### ISSUE TITLE
Complex type as a query argument.

### ISSUE THREAD

**Issue by ziflex** [facebook/relay#707]
Hi there,

I've faced with an issue that Relay doesn't support complex types (GraphQLInputObjectType) as argument for query, though GraphQL itself supports it .

Are there any plans to implement this feature? Because one argument for query is not enough.

**Comment by josephsavona** [comment]
Ran you clarify how you're specifying your query or fragment? Relay does support input objects as argument values, but only when they are passed as a variable. 

I.e. This works:

`query { search(query: $inputObject) }`
With variables `{foo: 'value'}`

This isn't supported:

`query { search(query: {foo: ...}) }`

**Comment by ziflex** [comment]
Hi @josephsavona, thanks for response!
On route level I have such query:
```query GetFormContent($params: QueryParams!) { getModel(params: $params)}'```

and on container level:

```fragment on Model {...poperties...}```

The problem is that I'm getting an error: 
> Expected arguments to root field `getModel` to each be strings/numbers, got `{"id":"a670f711","formId":"app-10"}`.

Then I had taken a look at the code which is throwing the error (```forEachRootCallArg.js```) and found that there is no option for objects. It supports only scalar values (and array of them).

**Comment by josephsavona** [comment]
Cc @steveluscher as this related to his work on root calls

**Comment by ziflex** [comment]
@josephsavona any updates?

**Comment by nemanja-stanarevic** [comment]
@josephsavona @steveluscher any chance support for input objects as arguments may land in 0.7? I am happy to help with this if it makes sense at this stage.

Tried using variables as place holders for input object arguments as suggested by @josephsavona above.  However,  running into an issue when two fragments, from two separate components, have the same field with variable placeholder for argument.  When two fragments are pulled together in a parent fragment, GraphQL server throws a conflict "two fields have differing arguments".  Think this is a reasonable behavior for GraphQL server because arguments are set to different variables (even though input object values in variables happen to be the same).

**Comment by sboutzen** [comment]
I am getting the same error, any progress? It can be circumvented by getting your data from `resolve` on a field instead of on the root query, but I think it makes sense to allow input objects on the query.

**Comment by josephsavona** [comment]
We added support for this in https://github.com/facebook/relay/commit/38beb23b2105c4a7eaaca587b9fcc420512f3113 and it will be available in the next release.
