### ISSUE TITLE
setVariables doesn't re-@include fragment

### ISSUE THREAD

**Issue by mrogg** [facebook/relay#710]
If a fragment contains only one field and that field is conditionally @include -ed this may result in no query being sent to the server. I believe this is because of this check: https://github.com/facebook/relay/blob/master/src/query/RelayQuery.js#L221.

This is fine/expected except if the condition checked in the @include is then set via setVariables to some truthy value. In this case the fragment is not then re-included and no query is sent to the server. I've been weaving my way through the code to try and determine where this could be addressed. I can see things fall apart here: https://github.com/facebook/relay/blob/master/src/container/RelayContainer.js#L200. However, I've not yet been able to determine where best to address the issue.

Thanks
Mark

**Comment by josephsavona** [comment]
@yungsters could this have to do with the way we previously de-duped fragments when printing?

**Comment by yungsters** [comment]
@josephsavona I'm not sure, but I don't think so. The memoization that happens in `printRelayQuery` occurs using `getFragmentID()` which takes into account variable values. [There is a test case demonstrates this.](https://github.com/facebook/relay/blob/master/src/traversal/__tests__/printRelayOSSQuery-test.js#L341-L375)

I'll have to create a test case to debug this further.

**Comment by yungsters** [comment]
I can reproduce this using a container with the following fragment:

```
viewer: () => Relay.QL`
  fragment on Viewer {
    actor @include(if: $showActor) {
      name
    }
  }
`
```

When `$showActor` is initialized to `false`, I'm observing that `this.props.viewer` is `null` instead of being an empty object. Also, there is no network request made if this is the only fragment in the entire tree.

It makes sense for there to be no network request — `Viewer` has no `id`, so we do not even send a request to fetch its `id`. Without ever "writing the viewer" into the Relay store, it is never even assigned a client-generated `id`. This means when `RelayContainer` tries to render, it can only populate `this.props.viewer` with `null`.

@mrogg Does this sound familiar? Is your `props.X` also `null`?

Assuming this is the problem, I think we need to do something better than merely vending `null`. One possible solution would be to ensure that a record always exists for each query, even if we do not end up sending a query to the server.

**Comment by mrogg** [comment]
@yungsters Yes, that's correct. It's null and there's no way for the setVariables path to recover.

I've been attempting to understand how an empty record could be dropped in instead since I assume there'd be some sort of response like that if the @include made it to the server with it's condition false and the server returned an empty response.

Thanks for your help.

**Comment by legomind** [comment]
any progress on this?

**Comment by brad-decker** [comment]
Just ran into this issue myself. Anyone have any work arounds?

**Comment by josephsavona** [comment]
One workaround is to include a dummy field - `__typename` for example - to ensure that there is a record supplied for a fragment prop.

**Comment by wincent** [comment]
Going to close this due to inactivity. We have a workaround (mentioned above), and in the new Relay core, `setVariables` as we know it is replaced with refetch containers (documentation and examples will be published in the near future as we continue to land the new code to the master branch). Thanks for the discussion!
