### ISSUE TITLE
Rename Relay.Mutation#getVariables?

### ISSUE THREAD

**Issue by clayallsopp** [facebook/relay#711]
Should Relay.Mutation#getVariables be named something like `getInput`? Or something else that explicitly ties it to constructing the input argument?

My understanding and reading [the docs](http://facebook.github.io/relay/docs/api-reference-relay-mutation.html#getvariables-abstract-method) suggests that the method is only ever used to in context with the input - in fact there's even a warning in the docs that tries to mitigate naming confusion.

**Comment by clayallsopp** [comment]
`getFatQuery` might also be a candidate for renaming? i.e. `getPayloadFragment` / `getPayloadQuery`? (I believe it can only be a fragment on the payload type?)

**Comment by wincent** [comment]
Thanks for filing this issue @clayallsopp!

There is some reasoning behind this: mostly, consistency with the "variables" terminology used in the `RelayDefaultNetworkLayer` for other kinds of queries (and you can think of mutations are just special kinds of queries). Nevertheless, there is definitely scope for improving the names here.

This is important, so I'm going to fold it into #538, which is about overhauling the mutations API. (It will be easier to manage with the various interrelated mutations issues in a single place.) Lots of details in the API are expected to change, so that is probably the best place to consider this.
