### ISSUE TITLE
import from "react-relay" and webpack bundle doesn't work

### ISSUE THREAD

**Issue by davide-ganito** [facebook/relay#72]
Hi,
I was trying to include Relay in my webpack bundle but when I render it throw a "setState on unmounted component" warning and crash.
If I include React and Relay from a script tag everything works fine. Can you tell me why?

The Relay object accessed by import have not the DefaultNetworkLayer property too. 
I have to require and inject it by myself.

Have a great day!
Davide

**Comment by fson** [comment]
Hi @davide-ganito! The `DefaultNetworkLayer` missing from the `Relay` object was fixed in version 0.1.1 of the `react-relay` package, so if you install the latest version that should help.

With regards to the other issue ("setState on unmounted component"), could you please provide the code that throws this error for you? Thanks!

**Comment by fortruce** [comment]
I ran into the exact same error `setState on unmounted component` when trying to `import Relay from 'react-relay'`, but it was fixed by updating to v0.1.1. Unfortunately, I don't have the code around anymore to trigger the error.

**Comment by josephsavona** [comment]
@davide-ganito can you confirm that this is fixed after upgrading to 0.1.1? If not, please feel free to reopen.

**Comment by davide-ganito** [comment]
Solved, yes. Thank you.
