### ISSUE TITLE
Relay is sending n requests when there is a difference in requested fields

### ISSUE THREAD

**Issue by mailaneel** [facebook/relay#724]
On Page1 I have below query

```js
	fragments: {
		viewer: () => Relay.QL`
		  fragment on Viewer{
			  races{
				  isAcceptingBets,
				  isResulted,
				  status,
				  dateString,
				  outcomeDateString,
				  hasFixedPrices,
				  hasTips,
				  hasPromo,
				  result
			  }
		  }`
	}

```

On Page 2 i have below query

```js
  fragments: {
    viewer: () => Relay.QL `
		  fragment on Viewer{
			  races{
                origId,
                name,
                countryCode,
                countryName,
                meetingName,
                distance,
                number,
                outcomeDateString,
                status,
                isAcceptingBets,
                isResulted,
                type,
                hasFixedPrices
			  }
		  }
		`
  }
```

User lands on ```page2``` to start with and when user navigate from ```page2``` to ```page1``` relay sends approx 300 requests to ```node(id:)``` endpoint

300 is number of races returned from ```races query```

one of 300 requests shown below

```js
query FKViewerQueries{
  node(id:"UmFjZToxMzg4MTIx")
  {
    id,
    __typename,
    ...__RelayQueryFragment7mm1m927
  }
} 
  
  fragment __RelayQueryFragment7mm1m927 on Race{
    origId,
    name,
    countryCode,
    countryName,
    meetingName,
    distance,
    number,
    type,
    id
  }
```

if you closely see the above request is a diff of page1 -> page2 query but instead of sending it to races endpoint it is send to node endpoint

response for node request

```js
{
  "data": {
    "node": {
      "id": "UmFjZToxMzg4MTIx",
      "__typename": "Race",
      "origId": "1388121",
      "name": "Bonneuil",
      "countryCode": null,
      "countryName": null,
      "meetingName": "Vincennes (FRA)",
      "distance": "2175m",
      "number": 5,
      "type": "h"
    }
  }
}
```

Interestingly if i add query params on page 2 query ex: ```races(limit: 500){}``` There is only one request

Note: I am not using node->edges in query request(see page 1 or page 2 request) Not sure if this is causing the above issue

also see https://github.com/facebook/relay/issues/691

**Comment by josephsavona** [comment]
Thanks for asking about this. Relay creates a new `node` query intentionally - it saves the server the work of fetching the list itself. The whole lieu is fetched again if use some arbitrary param (such as `limit`) because Relay hasn't fetched that combination of calls yet and doesn't know whether the data could be different. 

For all of these reasons, we recommend using a connection instead of a list.

**Comment by mailaneel** [comment]
Thanks @josephsavona 

As per your comment event implementing ```Connection Interface``` will not solve issue of sending n requests.

I agree with you on the edge cases, but sending 300 requests(in my case) instead of sending one request for list does not make sense(especially if this is on mobile), Temporary solution on my for now is to use arbitrary param(ex: limit as per your suggestion with different values), this way relay will treat them as different queries.

How does FB/Instagram/AdsManager get around this problem(if you guys hit the same)?

**Comment by josephsavona** [comment]
There are a few strategies for handling this case. The first is to use a connection and fetch only the data that is needed for the initial screen - load the first 5 or 10 items and paginate to load more only as necessary. 

At Faceboo, we also have a custom "batch" network layer that can send multiple queries in a single HTTP request and receive responses as they're evaluated by the server (note that the network layer interface is `sendQueries` - plural - which makes it easy to batch requests). If your app is making enough individual queries to be a performance problem, you might try implementing a simple version of a batched network layer. What's required is an endpoint that can accept a list of queries - `{id, query, variables}` - and return a list of `{id, response, error}` responses. Note that `RelayQueryRequest` provides access to a unique id for each query, which can be used to associate queries with their results.

**Comment by mailaneel** [comment]
Thanks for your help.

The problem for us is we display all races(times) for that day, I am using arbitrary param ```_``` on every endpoint to solve this for now. 

I will also try and see if creating custom batch network layer works for us.

**Comment by vladar** [comment]
Also faced this. The problem is that it is so unexpected and it is so easy to get this behavor unintentionally and trash the server.

Batching requests will probably help though.

**Comment by josephsavona** [comment]
@vladar Yeah, it's relatively easy to get into this state, hopefully also reasonably obvious when it happens (lots of network requests by default). Ultimately, though, Relay is just doing what you might otherwise code manually: check each item and fetch any missing information. If you're trying to optimize a specific transition between two views (`a` to `b`), one option is to prefetch `b`'s fragment on page `a`:

```javascript
// A container:
Relay.createContainer(A, {
  fragments: {
    foo: () => Relay.QL`
      fragment on Foo {
        ${B.getFragment('foo') # <- prefetch B's data
```

Again, there are tradeoffs with this approach (the user may never view page b), but it's an option to consider in addition to batching queries at the network layer.

**Comment by nickretallack** [comment]
Do you really have to do batching outside of Relay here?

I don't see this in the spec now, but I thought there was a way to fetch multiple nodes by id in one request from a Relay-GraphQL server by sending the list of IDs up, like this:

```
nodes(ids: ["1","2","3"]) {
  fields
}
```

**Comment by josephsavona** [comment]
@nickretallack it is possible to fetch data for multiple ids via `nodes`. However, different ids may be missing different sets of fields; given the complexity of diffing queries against the cache generally, we've chosen a balance of generating one `node` per id that is missing data. Network-level batching is a pretty big win here.

I'm going to close this since Relay is working as designed and there isn't any actionable next steps. If you have more questions about the batching approach please feel to comment here or start a new issue, or ask on Stack Overflow. Thanks!

**Comment by nodkz** [comment]
Publish custom RelayNetworkLayer with batching queries and middlewares 
https://github.com/nodkz/react-relay-network-layer

**Comment by skosch** [comment]
I'm curious whether it's possible to tweak the query diffing mechanism and (maybe globally) define that in the case that more than *n* queries would have to be sent, screw it and just force-refetch the whole thing. Does Relay allow for this in any way?

**Comment by wincent** [comment]
The new Relay core doesn't do diffing, so such a tweak wouldn't apply (users explicitly specify the query they wish to fetch, so total control is in the hands of the user).

**Comment by skosch** [comment]
> The new Relay core 

... isn't quite available yet though, is it? :cry: I ask because my backend (Elixir Absinthe) has dropped support for batching for now, and I'm grasping at straws now

**Comment by wincent** [comment]
Nope, not quite. If you're curious, progress is being made on the `experimental` branch towards getting it shipped.

**Comment by bochen2014** [comment]
I think implementing a custom batch network layer is the right decision. 
@skosch  Even in the cases where there are `n` nodes to fetch and `n` is big enough, Relay shouldn't do a  `connection`/`nodes` fetch to re-get all. e.g. Let's say a fruitStore endpoint returns 100 fruit on site's home page, and you are navigating to 'price' page to see detailed prices. 
```
fruitStore{
   fruit{
      id,
     name,
     picture, 
     price ---  only required on 'price' page
   }
}
```
in this case, just because there are 100 (n=100, seems big enough) fruits to fetch, doesn't mean we should fetch the entire fruitStore, because that means we are going to fetch pictures again which is the biggest overhead. 
So generating 100 node queries only for price makes more sense in this case

**Comment by bochen2014** [comment]
an arbitrary `_`  would always cause relay to re-fetch everything, which could be a very expensive operation

**Comment by skosch** [comment]
That's a great example for sure. I'm only dealing with lots of little text fields so that scenario never crossed my mind.
