### ISSUE TITLE
Query arguments being stripped out

### ISSUE THREAD

**Issue by dhoward** [facebook/relay#727]
Hi, I have an extremely simple query/route that just needs to query a particular team object and return it. But when the query is sent, it looks like it has the argument stripped out. I'm new to Relay so it may just be something I'm missing, but I believe I've set up everything according to the guides:

```
class TeamRoute extends Relay.Route {
    static queries = {
        team: (Component) => Relay.QL'
            query {
                team(uuid: $uuid) {
                    ${Component.getFragment("team")}
                }
            }
        ',
    };

    static paramDefinitions = {
        uuid: {required: true}
    };

    static routeName = "TeamRoute";
}

class Team extends React.Component {
    static propTypes = {
        team: React.PropTypes.object
    }

    render() {
        ...render the fields
    }
}

Team = Relay.createContainer(Team, {
    fragments: {
        team: () => Relay.QL`
            fragment on Team {
                id
                name
            }
        `,
    },
});

class ContainerComponent extends React.Component {
    render() {
        return(
            <div>
                <Relay.RootContainer Component={Team} route={new TeamRoute({uuid: "uuid-team-1"})} />
            </div>
        );
    }
}
```

When I render the ContainerComponent, I expect this to fetch the Team with a `uuid` of `uuid-team-1`, but the query that gets created looks like this:
```
{"query":"
    query Team{team{id,...__RelayQueryFragment1lntfd0}} 
    fragment __RelayQueryFragment1lntfd0 on Team{uuid,name,id}",
 "variables":{}
}
```

I would expect that the query would include the argument, something like `query Team{team(uuid:"uuid-team-1")...`

Is there something I'm missing? Any help would be great. Relay looks awesome I just want to get it working!

**Comment by devknoll** [comment]
Thanks for your question! We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

Questions like yours deserve a purpose-built Q&A forum. Would you like to post this question to Stack Overflow with the tag #relayjs? We'll be happy to answer there. Post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs

**Comment by dhoward** [comment]
Sorry for the slow reply. After messing around with it more, I think the issue lay elsewhere in my dev setup, with React loading multiple versions due to Relay requiring a different version than the one I was initially using.  When I tried running my code on a blank react starter project, it worked fine. I can still post the issue if you want but I don't want to send anyone on a wild goose chase tracking it down, since it looks like it may have been specific to my setup. Thanks!

**Comment by josephsavona** [comment]
@dhoward thanks for following up on this. We have tests to confirm that queries are printed with the expected arguments, and since this worked correctly on a clean setup it definitely sounds like this was a configuration issue.

If you do see the issue again, don't hesitate to comment here so we can reopen and investigate further. Thanks!
