### ISSUE TITLE
Q/D: Why are cursors strings?

### ISSUE THREAD

**Issue by devknoll** [facebook/relay#73]
...as opposed to opaque IDs?

https://facebook.github.io/relay/graphql/connections.htm

**Comment by devknoll** [comment]
One reasonable explanation: ID coercion might have particular semantics incompatible with cursors, and the Relay team didn't want to force folks to build their own scalar type for cursors.

**Comment by wincent** [comment]
The connection pattern, if you want to call it that, that Relay uses has its roots in the years-old GraphQL used internally at Facebook. That GraphQL is much less formally specified than the new-and-shiny GraphQL technical preview that we've released to the world.

Effectively, both cursors and ids were/are opaque and arbitrary (really, implementation-specific), and strings, because of the use of JSON as a serialization format.

We wanted to keep the open source GraphQL spec small and precisely-but-minimally specified, so it doesn't have a lot to say about connections.

**Comment by devknoll** [comment]
Thanks!
