### ISSUE TITLE
Why required getVariables on Mutation?

### ISSUE THREAD

**Issue by ryancole** [facebook/relay#734]
A mutation doesn't require variables necessarily, but the class wants that function defined. Of course, can easily create the function and return an empty object, but why?

**Comment by josephsavona** [comment]
In general we've found that explicit APIs lead to more consistent code and fewer unintended program behaviors. In this case, it's best to be explicit that there are no variables for a given mutation, as opposed to accidentally forgetting to specify them or specifying them incorrectly. As a counter example, if `getVariables` were optional then you could accidentally misspell the method name and wonder why no variables were being sent to the server. 

I'm going to close this since it isn't an issue per se, but feel free to ask follow-up questions and we'll try to answer.
