### ISSUE TITLE
Document that variables for routes are passed into query methods

### ISSUE THREAD

**Issue by RavenHursT** [facebook/relay#737]
So, I spent a couple days attempting to find a way to pass variables through as query argument values in underlying fragments in a `Relay.Route`

A co-worker pointed out to me this comment: https://github.com/facebook/relay/issues/309#issuecomment-167403119

Apparently, `variables` is passed in, along w/ the Component into the method callbacks for defining the `static queries` on a `React.Relay` object...

Unfortunately, this functionality isn't documented as far as I can see: https://facebook.github.io/relay/docs/api-reference-relay-route.html

Maybe I'm missing it?

If not, it would probably save others a lot of time to have this mentioned somewhere along w/ maybe some explanation as to how `variables` can be used w/ `Component.getFragment()`?

**Comment by edvinerikson** [comment]
@josephsavona, any input on this?

**Comment by josephsavona** [comment]
We should definitely update the docs with the API for passing variables from route/parents to child containers. The linked comment has most of the details, PRs welcome!

**Comment by wincent** [comment]
Going to close this as we're working on preparing for the release of [Relay 2](https://speakerdeck.com/wincent/relay-2-simpler-faster-more-predictable), so it is very unlikely that we'll be allocating resources to documenting the old APIs at this time. Like @josephsavona said, however, and we'd be happy to merge in a PR addressing this issue, but I'm still going to close this for now in order to clean out the issue tracker a bit.
