### ISSUE TITLE
Relay fetch for recursive data without `id`s returns null

### ISSUE THREAD

**Issue by shahankit** [facebook/relay#742]
I have a recursive data structure to be fetched and displayed. I have a graph ql type as follow:

```
human {
  name,
  children: [human]
}
```

Now I wanted to incrementally fetch data and hence used to react classes HumanList and HumanItem, where I've used relay to fetch children only when a item is clicked. In my actual code relay gives children a null on very click i.e. on rendering very first set of children. I tried test code on relay playground and found similar issue. [Here](https://gist.github.com/shahankit/409c8640b01f1d910fb0) is the link to gist. Playground.js contains the code part and Playground.gql.js contains schema part.

I've already checked #246 and #536 but none of them helped.

**Comment by josephsavona** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

Questions like yours deserve a purpose-built Q&A forum. Would you like to post this question to Stack Overflow with the tag #relayjs? We'll be happy to answer there. Post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs

**Comment by shahankit** [comment]
I created a stackoverflow for same [here](https://stackoverflow.com/questions/34882707/relay-fetch-for-recursive-data-returns-null). Any insights to issue are greatly welcome or temporary work around for issue if possible.

**Comment by josephsavona** [comment]
Thanks! Let's move discussion to the SO question.

**Comment by shahankit** [comment]
@josephsavona This is actually a bug, so can you please reopen the issue.

**Comment by josephsavona** [comment]
@shahankit just saw your SO comment - yeah this looks like a bug. I suspect this has to do with the fact that the schema doesn't use the `Node` interface, which means calls to fetch recursive data can't use `node(id: $id)` calls. We'll keep this open to track work on a fix, but as a workaround I would suggest implementing `Node` and see if that helps.

**Comment by steveluscher** [comment]
You were right all along. This was a bug. Fixed in https://github.com/facebook/relay/issues/1243

**Comment by shahankit** [comment]
@steveluscher thanks.
