### ISSUE TITLE
Docs - Relay's relationship to Flux

### ISSUE THREAD

**Issue by chrisbolin** [facebook/relay#747]
Currently Flux is only mentioned once in the Relay docs (deep in the API reference for [Relay.Store](https://facebook.github.io/relay/docs/api-reference-relay-store.html#commitupdate-static-method)). I was initially very confused about the relationship between the Relay and Flux, and I don't think I'm alone.

I would be more than happy to help with the documentation here - I'd just like to hear what you'd like the official word on Flux w/r/t Relay to be.

For example, @josephsavona summed this up succinctly in #168 -

> Relay is an implementation of the Flux pattern

There is probably more to say, e.g. on the use of Flux alongside Relay for ephemeral client state (before #114 is closed).

**Comment by josephsavona** [comment]
Thanks for your question! I have an answer for you but we want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

Questions like yours deserve a purpose-built Q&A forum. Would you like to post this question to Stack Overflow with the tag #relayjs? We'll be happy to answer there. Post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs

**Comment by chrisbolin** [comment]
Sounds good! https://stackoverflow.com/questions/34958295/whats-relays-relationship-to-flux

**Comment by chrisbolin** [comment]
Again, if you'd like to incorporate your answer into the Relay docs I'd be happy to do it.
