### ISSUE TITLE
Relay isn't requesting deep fields from a graphql server after mutatiton

### ISSUE THREAD

**Issue by vslinko** [facebook/relay#751]
I have `User` that is implementing `Node` and have `id` field.
I have `Profile` that isn't implementing `Node` but have `id` field.
Also, `User` has `profile` field.

Here is a component decorator that requesting data:

```js
  relay({
    initialVariables: {
      nickname: null,
    },
    fragments: {
      viewer: () => Relay.QL`
        fragment on Viewer {
          profileByNickname(nickname: $nickname) {
            firstName
            age
          }
        }
      `,
    },
  }),
```

Here is a mutation that updates data that used by the component.

```js
import Relay from 'react-relay';

export default class EditProfileMutation extends Relay.Mutation {
  getMutation() {
    return Relay.QL`mutation {editUserProfile}`;
  }

  getVariables() {
    return {
      userId: this.props.userId,
      firstName: this.props.firstName,
      birthday: this.props.birthday,
    };
  }

  getFatQuery() {
    return Relay.QL`
      fragment on EditUserProfilePayload {
        user {
          profile {
            firstName # those fields...
            age       # aren't requested
          }
        }
      }
    `;
  }

  getConfigs() {
    return [
      {
        type: 'FIELDS_CHANGE',
        fieldIDs: { user: this.props.userId },
      },
    ];
  }

  getCollisionKey() {
    return `editUserProfile`;
  }
}
```

Is it possible to use `FIELDS_CHANGE` like this?

**Comment by NevilleS** [comment]
Are you expecting this mutation to update the `profileByNickname` field?

**Comment by vslinko** [comment]
Yes

**Comment by NevilleS** [comment]
The fields in the fat query need to match the fields in the local graph then. Since your `profileByNickname` field takes arguments I'm not 100% sure how to guarantee that, but if definitely will need to match. `profile` and `profileByNickname` won't match.

If you made your `profile` type into a node as well, you could just update the profile and match based off of ID. You'd want to make a `user { profiles }` connection in that case, though, to represent the relationship between the two types

**Comment by josephsavona** [comment]
The field name `profileByNickname` suggests that the component is querying the `profile` record directly, and not the user. However, the mutation `FIELDS_CHANGE` configuration is rooted at the user, which isn't queried by the component. Because the component queries the profile directly (not through the user), the mutation doesn't find any fields that need updating. If the mutation affects the profile directly and note the fields of the `user`, you might consider changing the mutation accordingly.

**Comment by vslinko** [comment]
Thank you for your comments. Solved by adding `profile` to `FIELDS_CHANGE`

**Comment by josephsavona** [comment]
@vslinko Glad that helped!
