### ISSUE TITLE
Relay can create invalid queries when fields with arguments overlap

### ISSUE THREAD

**Issue by leebyron** [facebook/relay#784]
Please see the issue originally filed by @fson at https://github.com/graphql/graphql-js/issues/263 where Relay could generate an invalid query:

```
query ($orderBy: _GroupOrdering, $orderBy2: _GroupOrdering) {
  viewer {
    allGroups(orderBy: $orderBy) { count }
    allGroups(orderBy: $orderBy2) { count }
  }
}
```

**Comment by ryancole** [comment]
I've actually been encountering this issue over the past few days. In my particular case, a relay mutation's payload query seems to be where I'm seeing an invalid query format, resulting in the `"Fields \"_scrimInvitesBKmb7\" conflict because they have differing arguments."` error.

In my particular case, it only happens some times and not others. It also only seems to happen when I'm using `this.props.relay.forceFetch`, as well. if I follow a longer user navigation flow, and sign in, navigate to my react view that has the mutation and then execute the mutation, I will see the error. If I perform a hard refresh (clearing the relay store) and run the mutation, then it works every time without the duplicate field in the query.

I'm not sure if `forceFetch` or having data in the relay store already determines the query that gets built by relay, but I wanted to mention these two components of the issue, from my project. For now, just disabling `forceFetch` seems to fix it.

**Comment by josephsavona** [comment]
@ryancole thanks for the extra info, this is super helpful for debugging!

**Comment by josephsavona** [comment]
There are two basic approaches here:
- Flatten the query prior to printing it.
- Print duplicated fields, but in a way that passes validation.

Flattening the query requires a full extra traversal (O(n) operation), so this isn't tenable from a performance perspective. The simpler solution would be to avoid creating new variables when the values are actually the same. This could be achieved by keeping a map in `printRelayQuery` of serialized value -> variable name, and only generating new variables if the current value is not already a key in the map. This logic would go in [`createVariable`](https://github.com/facebook/relay/blob/master/src/traversal/printRelayOSSQuery.js#L298-L310)

@ryancole any interest in submitting a PR for this? ;-)

**Comment by ryancole** [comment]
I'll take a look right now. Ideally I could first come up with some test case that reproduces the issue, so I may focus on that first before focusing on the proposed fix.

**Comment by josephsavona** [comment]
@ryancole Great, thanks! For a test case, take a look at the [test schema](https://github.com/facebook/relay/blob/master/scripts/jest/testschema.graphql) for fields to use in constructing a repro case - something like

```
  query {
    defaultSettings {
      web: notifications(environment: WEB)
      foo: notifications(environment: $foo) # where $foo = 'WEB'
    }
  }
````

*should* probably be sufficient (or pretty close).

**Comment by ryancole** [comment]
off topic question, but is there a build step to these test files, or something? fresh out of master, if i run the tests they work fine. if add a new test case, it fails with a run time error of ...

```
ryan@ryan-ubuntu:~/repos/relay$ ./node_modules/.bin/jest ./src/traversal/__tests__/printRelayOSSQuery-test.js 
Using Jest CLI v0.8.2, jasmine2
 FAIL  src/traversal/__tests__/printRelayOSSQuery-test.js 
● Runtime Error
Error: Cannot find module './configureForRelayOSS' from '/home/ryan/repos/relay/src/traversal/__tests__/printRelayOSSQuery-test.js'
```

**Comment by josephsavona** [comment]
if you manually run jest, be sure to prefix the command with `NODE_ENV=test ./node_modules/.bin/jest ...`

**Comment by ryancole** [comment]
@josephsavona I managed to get the tests running. Not sure why they won't run on my other PC. I have a feeling it has something to do with me downgrading to node 4 / npm 2. Something might be cached in the npm 3 format, or something, idk.

Anyways, there's my first stab at the second approach you mentioned yesterday. There already exists a map of created variables, so I'm just checking that and returning the already-created id for it if the `name` and `value` match up.

**Comment by josephsavona** [comment]
@ryancole thanks again for working on this, let's keep discussion of the implementation on the PR.

> I don't fully understand all of the possible ramifications of this change, technically

This is a very localized change, and the file has good test coverage. If you're curious to learn more about the implementation and ramifications of a change, I'd encourage you to experiment with changing things in the file and seeing which tests break and why :-)
