### ISSUE TITLE
Subclasses of RelayRoute must define a `routeName`

### ISSUE THREAD

**Issue by devknoll** [facebook/relay#8]
This seems like a very mechanical requirement. Is there any chance this could be pulled into the babel plugin, similar to how JSX automatically defines a `displayName`?

**Comment by yungsters** [comment]
This is a good idea.

I would have gone as far as suggesting we rename `routeName` to `displayName`, but the `routeName` is used for much more than just display purposes. (For example, it is used as a cache key in a couple parts of Relay.)

**Comment by devknoll** [comment]
I could probably get this in.

@yungsters do you have a good idea of what would make a good `routeName`? I assume `baseName` isn't enough if it's being relied on for cache keys. Maybe `baseName + hash(uri)`?

**Comment by yungsters** [comment]
As a first iteration, we could only auto-generate `routeName` if someone extends `Relay.Route` using the class syntax without defining a static `routeName`.

Maybe as an improvement, if the class is anonymous and the default export (e.g. `export default class extends Relay.Route { ... }` or `module.exports = class extends Relay.Route { ... }`), then we can use the `baseName` (by which I assume you are referring to the path basename?).

Otherwise, we can simply not auto-generate the `routeName` and let the runtime exception explain that their route is incomplete.

> Maybe `baseName + hash(uri)`?

I'm reluctant to include `uri` because I actually think we'll want to remove that from `RelayRoute` in the near future. Check out #27 for more context.

**Comment by devknoll** [comment]
By `uri` I meant of the .js file itself (in case an app uses some format like `pages/*/route.js`).

Everything else sounds good. I'll see what I can do :smile:

**Comment by yungsters** [comment]
@devknoll Ahh, makes sense.

**Comment by devknoll** [comment]
I closed this because:
* Having used routes more over the past 12 days, this issue hasn't bitten me again or been a big deal. The issue might be a knee jerk reaction.
* At least when bundled with react-router, Relay.Routes aren't being used at all, and so any integration with Babel would go unused there anyway.
