### ISSUE TITLE
Unable to pass Relay variables to a Container through another Container

### ISSUE THREAD

**Issue by denvned** [facebook/relay#816]
See a [demo](https://facebook.github.io/relay/prototyping/playground.html#source=class%20ChildComponent%20extends%20React.Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20const%20%7Bhello%7D%20%3D%20this.props.greetings%3B%0A%20%20%20%20return%20%3Ch1%3E%7Bhello%7D%3C%2Fh1%3E%3B%0A%20%20%7D%0A%7D%0A%0Aconst%20ChildContainer%20%3D%20Relay.createContainer(ChildComponent%2C%20%7B%0A%20%20initialVariables%3A%20%7B%0A%20%20%20%20name%3A%20'A'%2C%0A%20%20%7D%2C%0A%20%20fragments%3A%20%7B%0A%20%20%20%20greetings%3A%20()%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20fragment%20on%20Greetings%20%7B%0A%20%20%20%20%20%20%20%20hello(name%3A%20%24name)%2C%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%0A%7D)%3B%0A%0Aclass%20ParentComponent%20extends%20React.Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20return%20%3CChildContainer%20greetings%3D%7Bthis.props.greetings%7D%20%2F%3E%3B%0A%20%20%7D%0A%7D%0A%0Aconst%20ParentContainer%20%3D%20Relay.createContainer(ParentComponent%2C%20%7B%0A%20%20initialVariables%3A%20%7B%0A%20%20%20%20name%3A%20null%2C%0A%20%20%7D%2C%0A%20%20fragments%3A%20%7B%0A%20%20%20%20greetings%3A%20(%7Bname%7D)%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20fragment%20on%20Greetings%20%7B%0A%20%20%20%20%20%20%20%20%24%7BChildContainer.getFragment('greetings'%2C%20%7Bname%7D)%7D%2C%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%0A%7D)%3B%0A%0Aclass%20Route%20extends%20Relay.Route%20%7B%0A%20%20static%20routeName%20%3D%20'Hello'%3B%0A%20%20static%20queries%20%3D%20%7B%0A%20%20%20%20greetings%3A%20()%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20query%20GreetingsQuery%20%7B%0A%20%20%20%20%20%20%20%20greetings%2C%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%3B%0A%7D%0A%0AReactDOM.render(%0A%20%20%3CRelay.RootContainer%0A%20%20%20%20Component%3D%7BParentContainer%7D%0A%20%20%20%20route%3D%7Bnew%20Route(%7Bname%3A%20'B'%7D)%7D%0A%20%20%2F%3E%2C%0A%20%20mountNode%0A)%3B%0A&schema=import%20%7B%0A%20%20GraphQLObjectType%2C%0A%20%20GraphQLSchema%2C%0A%20%20GraphQLString%2C%0A%7D%20from%20'graphql'%3B%0A%0Avar%20GREETINGS%20%3D%20%7B%0A%20%20hello%3A%20'Hello%20world'%2C%0A%7D%3B%0A%0Avar%20GreetingsType%20%3D%20new%20GraphQLObjectType(%7B%0A%20%20name%3A%20'Greetings'%2C%0A%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20hello%3A%20%7B%0A%20%20%20%20%20%20type%3A%20GraphQLString%2C%0A%20%20%20%20%20%20args%3A%20%7B%0A%20%20%20%20%20%20%20%20name%3A%20%7B%20type%3A%20GraphQLString%20%7D%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20resolve%3A%20(%7B%7D%2C%20%7Bname%7D)%20%3D%3E%20%60Hello%20%24%7Bname%7D!%60%2C%0A%20%20%20%20%7D%2C%0A%20%20%7D)%2C%0A%7D)%3B%0A%0Aexport%20default%20new%20GraphQLSchema(%7B%0A%20%20query%3A%20new%20GraphQLObjectType(%7B%0A%20%20%20%20name%3A%20'Query'%2C%0A%20%20%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20%20%20greetings%3A%20%7B%0A%20%20%20%20%20%20%20%20type%3A%20GreetingsType%2C%0A%20%20%20%20%20%20%20%20resolve%3A%20()%20%3D%3E%20GREETINGS%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D)%2C%0A%20%20%7D)%2C%0A%7D)%3B%0A). I expect "Hello B!" on the page, but got `TypeError: Cannot read property 'hello' of undefined` instead.

If I change `'A'` to `'B'` on line 10, or `'B'` to `'A'` on line 54, then the error disappears...

**Comment by josephsavona** [comment]
When parent components override variables in child components using the second param to `getFragment` they must *also* pass the same variables in props. This is required because the same child fragment may be included more than once, and the child container needs a way to distinguish which data to use. This is something we'd like to address and simplify, but the fix is simple: pass `name`:

[here's a working version of the demo](https://facebook.github.io/relay/prototyping/playground.html#source=class%20ChildComponent%20extends%20React.Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20const%20%7Bhello%7D%20%3D%20this.props.greetings%3B%0A%20%20%20%20return%20%3Ch1%3E%7Bhello%7D%3C%2Fh1%3E%3B%0A%20%20%7D%0A%7D%0A%0Aconst%20ChildContainer%20%3D%20Relay.createContainer(ChildComponent%2C%20%7B%0A%20%20initialVariables%3A%20%7B%0A%20%20%20%20name%3A%20'A'%2C%0A%20%20%7D%2C%0A%20%20fragments%3A%20%7B%0A%20%20%20%20greetings%3A%20()%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20fragment%20on%20Greetings%20%7B%0A%20%20%20%20%20%20%20%20hello(name%3A%20%24name)%2C%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%0A%7D)%3B%0A%0Aclass%20ParentComponent%20extends%20React.Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20%2F%2F%20***%20have%20to%20pass%20%60name%60%20prop%20here%20***%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3CChildContainer%20%0A%20%20%20%20%20%20%20%20greetings%3D%7Bthis.props.greetings%7D%20%0A%20%20%20%20%20%20%20%20name%3D%7Bthis.props.relay.variables.name%7D%20%0A%20%20%20%20%20%20%2F%3E%0A%20%20%20%20)%3B%0A%20%20%7D%0A%7D%0A%0Aconst%20ParentContainer%20%3D%20Relay.createContainer(ParentComponent%2C%20%7B%0A%20%20initialVariables%3A%20%7B%0A%20%20%20%20name%3A%20null%2C%0A%20%20%7D%2C%0A%20%20fragments%3A%20%7B%0A%20%20%20%20greetings%3A%20(%7Bname%7D)%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20fragment%20on%20Greetings%20%7B%0A%20%20%20%20%20%20%20%20%24%7BChildContainer.getFragment('greetings'%2C%20%7Bname%7D)%7D%2C%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%0A%7D)%3B%0A%0Aclass%20Route%20extends%20Relay.Route%20%7B%0A%20%20static%20routeName%20%3D%20'Hello'%3B%0A%20%20static%20queries%20%3D%20%7B%0A%20%20%20%20greetings%3A%20()%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20query%20GreetingsQuery%20%7B%0A%20%20%20%20%20%20%20%20greetings%2C%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%3B%0A%7D%0A%0AReactDOM.render(%0A%20%20%3CRelay.RootContainer%0A%20%20%20%20Component%3D%7BParentContainer%7D%0A%20%20%20%20route%3D%7Bnew%20Route(%7Bname%3A%20'B'%7D)%7D%0A%20%20%2F%3E%2C%0A%20%20mountNode%0A)%3B%0A&schema=import%20%7B%0A%20%20GraphQLObjectType%2C%0A%20%20GraphQLSchema%2C%0A%20%20GraphQLString%2C%0A%7D%20from%20'graphql'%3B%0A%0Avar%20GREETINGS%20%3D%20%7B%0A%20%20hello%3A%20'Hello%20world'%2C%0A%7D%3B%0A%0Avar%20GreetingsType%20%3D%20new%20GraphQLObjectType(%7B%0A%20%20name%3A%20'Greetings'%2C%0A%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20hello%3A%20%7B%0A%20%20%20%20%20%20type%3A%20GraphQLString%2C%0A%20%20%20%20%20%20args%3A%20%7B%0A%20%20%20%20%20%20%20%20name%3A%20%7B%20type%3A%20GraphQLString%20%7D%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20resolve%3A%20(%7B%7D%2C%20%7Bname%7D)%20%3D%3E%20%60Hello%20%24%7Bname%7D!%60%2C%0A%20%20%20%20%7D%2C%0A%20%20%7D)%2C%0A%7D)%3B%0A%0Aexport%20default%20new%20GraphQLSchema(%7B%0A%20%20query%3A%20new%20GraphQLObjectType(%7B%0A%20%20%20%20name%3A%20'Query'%2C%0A%20%20%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20%20%20greetings%3A%20%7B%0A%20%20%20%20%20%20%20%20type%3A%20GreetingsType%2C%0A%20%20%20%20%20%20%20%20resolve%3A%20()%20%3D%3E%20GREETINGS%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D)%2C%0A%20%20%7D)%2C%0A%7D)%3B%0A)

**Comment by denvned** [comment]
> This is required because the same child fragment may be included more than once, and the child container needs a way to distinguish which data to use.

Oh, sorry, I forgot I already seen it here: https://github.com/facebook/relay/issues/309#issuecomment-140485321

Probably some more illuminating error message than `TypeError: Cannot read property 'x' of undefined` would be more helpful here.

Also, isn't inclusion of the same fragment in the same place multiple times pretty rare? Maybe it makes sense to at least make the case with single inclusion more clean?

**Comment by josephsavona** [comment]
@denvned We agree on all counts. One option is to extend GraphQL to allow named fragment references:

```
// BEFORE:
// container:
foo: () => Relay.QL`fragment on Foo {
  id
  name
  ${Photo.getFragment('foo', {size: 32)}
}`
// render
<Photo photo={props.foo} size={32} /> 

// AFTER:
// container:
foo: () => Relay.QL`fragment on Foo {
  id
  name
  photo: ${Photo.getFragment('foo', {size: 32)}
}`
// render
// The fragment alias allows Relay to pass down the variables within an opaque `foo.photo` object:
<Photo photo={props.foo.photo} /> 
```

This is great for Relay, but could mean that GraphQL response payloads are inflated, as data that would otherwise be available under the same key is now duplicated under each alias:


```
foo {
  id
  name
  photo: {
    id  // <-- in current GraphQL these fields are merged with the outer object
    name
  }
}
```

**Comment by bsr203** [comment]
@josephsavona I have [one more nesting.](https://facebook.github.io/relay/prototyping/playground.html#source=class%20ChildComponent%20extends%20React.Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20const%20%7Bhello%7D%20%3D%20this.props.greetings%3B%0A%20%20%20%20return%20%3Ch1%3E%7Bhello%7D%3C%2Fh1%3E%3B%0A%20%20%7D%0A%7D%0A%0Aconst%20ChildContainer%20%3D%20Relay.createContainer(ChildComponent%2C%20%7B%0A%20%20initialVariables%3A%20%7B%0A%20%20%20%20name%3A%20'A'%2C%0A%20%20%7D%2C%0A%20%20fragments%3A%20%7B%0A%20%20%20%20greetings%3A%20()%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20fragment%20on%20Greetings%20%7B%0A%20%20%20%20%20%20%20%20hello(name%3A%20%24name)%2C%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%0A%7D)%3B%0A%20%20%0A%20%20class%20TeenComponent%20extends%20React.Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3CChildContainer%20%7B...this.props%7D%20%2F%3E%0A%20%20%20%20)%3B%0A%20%20%7D%0A%7D%0A%0Aconst%20TeenContainer%20%3D%20Relay.createContainer(TeenComponent%2C%20%7B%0A%20%20initialVariables%3A%20%7B%0A%20%20%20%20name%3A%20null%2C%0A%20%20%7D%2C%0A%20%20fragments%3A%20%7B%0A%20%20%20%20greetings%3A%20(%7Bname%7D)%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20fragment%20on%20Greetings%20%7B%0A%20%20%20%20%20%20%20%20%24%7BChildContainer.getFragment('greetings'%2C%20%7Bname%7D)%7D%2C%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%0A%7D)%3B%0A%0Aclass%20ParentComponent%20extends%20React.Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20%2F%2F%20***%20have%20to%20pass%20%60name%60%20prop%20here%20***%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3CTeenContainer%20%7B...this.props%7D%20%2F%3E%0A%20%20%20%20)%3B%0A%20%20%7D%0A%7D%0A%0Aconst%20ParentContainer%20%3D%20Relay.createContainer(ParentComponent%2C%20%7B%0A%20%20initialVariables%3A%20%7B%0A%20%20%20%20name%3A%20null%2C%0A%20%20%7D%2C%0A%20%20fragments%3A%20%7B%0A%20%20%20%20greetings%3A%20(%7Bname%7D)%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20fragment%20on%20Greetings%20%7B%0A%20%20%20%20%20%20%20%20%24%7BChildContainer.getFragment('greetings'%2C%20%7Bname%7D)%7D%2C%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%0A%7D)%3B%0A%0Aclass%20Route%20extends%20Relay.Route%20%7B%0A%20%20static%20routeName%20%3D%20'Hello'%3B%0A%20%20static%20queries%20%3D%20%7B%0A%20%20%20%20greetings%3A%20()%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20query%20GreetingsQuery%20%7B%0A%20%20%20%20%20%20%20%20greetings%2C%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%3B%0A%7D%0A%0AReactDOM.render(%0A%20%20%3CRelay.RootContainer%0A%20%20%20%20Component%3D%7BParentContainer%7D%0A%20%20%20%20route%3D%7Bnew%20Route(%7Bname%3A%20'B'%7D)%7D%0A%20%20%2F%3E%2C%0A%20%20mountNode%0A)%3B%0A&schema=import%20%7B%0A%20%20GraphQLObjectType%2C%0A%20%20GraphQLSchema%2C%0A%20%20GraphQLString%2C%0A%7D%20from%20'graphql'%3B%0A%0Avar%20GREETINGS%20%3D%20%7B%0A%20%20hello%3A%20'Hello%20world'%2C%0A%7D%3B%0A%0Avar%20GreetingsType%20%3D%20new%20GraphQLObjectType(%7B%0A%20%20name%3A%20'Greetings'%2C%0A%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20hello%3A%20%7B%0A%20%20%20%20%20%20type%3A%20GraphQLString%2C%0A%20%20%20%20%20%20args%3A%20%7B%0A%20%20%20%20%20%20%20%20name%3A%20%7B%20type%3A%20GraphQLString%20%7D%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20resolve%3A%20(%7B%7D%2C%20%7Bname%7D)%20%3D%3E%20%60Hello%20%24%7Bname%7D!%60%2C%0A%20%20%20%20%7D%2C%0A%20%20%7D)%2C%0A%7D)%3B%0A%0Aexport%20default%20new%20GraphQLSchema(%7B%0A%20%20query%3A%20new%20GraphQLObjectType(%7B%0A%20%20%20%20name%3A%20'Query'%2C%0A%20%20%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20%20%20greetings%3A%20%7B%0A%20%20%20%20%20%20%20%20type%3A%20GreetingsType%2C%0A%20%20%20%20%20%20%20%20resolve%3A%20()%20%3D%3E%20GREETINGS%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D)%2C%0A%20%20%7D)%2C%0A%7D)%3B%0A) why error in this case. thanks.
