### ISSUE TITLE
Idea: Remove `viewer` confusion?

### ISSUE THREAD

**Issue by ianstormtaylor** [facebook/relay#820]
In the docs, I saw the term `viewer` used a lot, and was never really sure of what it was referring to. I assumed it was just a random name for a piece of the data model, but I couldn’t shake the feeling that it was some special constant I wasn’t familiar with. Made worse by things like `relay-todomvc` example using the same `viewer` term, even though it seems to be meaningless there?

If this is just a random name, it would be a lot clearer as `user` or `person` or something that doesn’t feel like the name of some generic constructor/class that might be Relay-specific.

(Little thing, but I think it might help in people being onboarded!)

Edit: After stumbling on https://github.com/facebook/relay/issues/112, it seems like `viewer` actually *is* some sort of Relay-specific convention, but what it actually does isn't clear.

**Comment by wincent** [comment]
You describe well the confusion that all this `viewer` stuff produces, but I don't think we want to give more prominence to it in the docs by explaining it; the most desirable solution is actually just to fix #112, and we have a pretty clear idea of the steps that would need to be taken in order to do so. At that point we should revisit the docs and the sample code to ensure that it makes sense and there are no (now unnecessary) `viewer` fields in it.

So I am going to close this for now. Please comment again if you think there's something else we could be doing. Thanks for your input!

**Comment by schickling** [comment]
Great question @ianstormtaylor and thanks for the clarification @wincent.

But am I right with the assumption that as of now (currently version `0.7`) you **have to** use the `viewer` property?

**Comment by wincent** [comment]
@schickling: Yeah as of the current version you have to use `viewer` (or some other root field like it) to work around the limitations described in #112. See also [Dan's comment](https://github.com/facebook/relay/issues/112#issuecomment-170648934) on that issue and its predecessors for some caveats about working with `viewer`.

**Comment by schickling** [comment]
Thanks @wincent. I guess it would make sense to make this more clear in the docs, at least for now to avoid some confusion for new users :-)

**Comment by wincent** [comment]
We're [pretty close now](https://github.com/facebook/relay/issues/112#issuecomment-191912269), so I don't know if we'll get to the docs before it becomes a non-issue. We'd welcome a PR though if you want to take a stab at updating things to make them clearer.
