### ISSUE TITLE
Configure Relay to use GET instead of POST...?

### ISSUE THREAD

**Issue by zth** [facebook/relay#838]
Hi!

A quick question from a Relay beginner: Would it be possible to configure Relay to use GET instead of POST for its' requests...? How would one go about doing that if it's possible?

Thanks in advance!

**Comment by jurassix** [comment]
This should be easy for you, and well documented too. [Start reading the documentation on Relay Network Layer](html). [Then have a look at the current _default_ implementation, it simply uses `fetch`](https://github.com/facebook/relay/blob/master/src/network-layer/default/RelayDefaultNetworkLayer.js#L138). 

With the above information you should be able to create a custom Network Layer, inject it into Relay, and send via requests with any method you would like.

**Comment by josephsavona** [comment]
Thanks for the question! I'm going to close this since there is nothing actionable to do here, but please feel to continue to use this space for discussion. 

Also note that for "how-to" questions we recommend asking on [Stack Overflow](http://stackoverflow.com/questions/ask?tags=relayjs), which is a custom built support forum.
