### ISSUE TITLE
babel relay plugin configuration for es6

### ISSUE THREAD

**Issue by rarutu** [facebook/relay#841]
Hi

I am doing a test app that is all es6 ... and i hit a bump when using this plugin ... the docs say to use this to configure the plugin and it works:

```javascript
var getBabelRelayPlugin = require('babel-relay-plugin');
var schemaData = require('../data/schema.json').data;
module.exports = getBabelRelayPlugin(schemaData, {
  abortOnError: true
});
```

can anyone tell me why this syntax does not work?
```javascript
"use strict";

import getBabelRelayPlugin from 'babel-relay-plugin';
import schemaData from '../data/schema.json';

export default getBabelRelayPlugin(schemaData.data, {
  abortOnError: true
});
```

thanks,
rarutu

**Comment by josephsavona** [comment]
Thanks for your question! We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

Questions like yours deserve a purpose-built Q&A forum. Would you like to post this question to Stack Overflow with the tag #relayjs? We'll be happy to answer there. Post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs

**Comment by rarutu** [comment]
http://stackoverflow.com/questions/35419322/babel-relay-plugin-es6-configuration

thanks

**Comment by rarutu** [comment]
can u please confirm the answer on the stackoverflow question ... is the answer from there correct?

**Comment by josephsavona** [comment]
@rarutu I commented at Stack Overflow, let's move discussion there.
