### ISSUE TITLE
Accessing data of sibling component

### ISSUE THREAD

**Issue by Efimster** [facebook/relay#847]
Playing with Relay I got problems with accessing data. I was trying to reproduce the issues with official Todo example of the Relay project. Please consider gist in order to change Todo example. 
[here](https://gist.github.com/Efimster/886650d04f141e50c08d)

Here are the questions:
1. Why Summary component cant get access to sibling (viewer) component data?
2. What the reason for "queries must have exactly one field"? GraphQL doesn't have such limitations I believe.
3.Why I got Invariant Violation: Relay(TodoApp).getFragment(): `summary` is not a valid fragment name ?

Thanks in advance!

**Comment by steveluscher** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

Questions like yours deserve a purpose-built Q&A forum. Would you like to post this question to Stack Overflow with the tag #relayjs? We (or another member of the Relay community) will be happy to answer there. Post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs
