### ISSUE TITLE
Conflict of argument variables in 7.1

### ISSUE THREAD

**Issue by vladar** [facebook/relay#855]
Got this error after upgrading to Relay 7.1: 

```
Variable $size_0 of type PhotoSizeEnum used in position expecting type PhotoSizeEnum!
```

Here is a query generated by Relay (stripped unrelated parts as it is long):

```
query Routes($size_0: PhotoSizeEnum) {
  app {
    ...FG
  }
}

fragment F2 on User {
  id
  _photo21tsFy: photo(size: $size_0)
}

fragment F6 on File {
  id
  _photo21tsFy: photo(size: $size_0)
}

fragment FG on App {
  entries {
    author {
      ...F2
    }
    attachments {
      ...F6
    }
  }
}
```

The problem is that type `User` defines `size` argument as `PhotoSizeEnum` and type `File` defines `size` argument as `PhotoSizeEnum!` but Relay uses same variable for both.

Relay 6.x uses different variables in this case.

As a workaround made both definitions same, but this looks like a bug for me.

**Comment by josephsavona** [comment]
Thanks for reporting this, this is a bug. This is a side-effect of https://github.com/facebook/relay/commit/bf7ba6a31f9cc937141c73e55f6a37e46bcc85ce which fixed #784. To resolve both issues, we'll have to change the way the query variables are printed - since the variables are known to be non-null (else we wouldn't print them), we can print e.g. `query Routes($size_0: PhotoSizeEnum!)` (non-nullable). Non-null variables are a subset of of nullable variables, so this would allow `$size_0` to be used in both fields.

The variables are printed here: 
https://github.com/facebook/relay/blob/master/src/traversal/printRelayOSSQuery.js#L139-L149. Any interest in helping us fix? ;-)

**Comment by vladar** [comment]
I'd be happy to help, but have zero time now and also don't know Relay internals to the extent when I could contribute. Otherwise I would send pull request for this right away %)

**Comment by josephsavona** [comment]
Fix has landed. Thanks again for reporting this, @vladar!
