### ISSUE TITLE
How many RootContainers do you have in a single application?

### ISSUE THREAD

**Issue by bigblind** [facebook/relay#859]
It seems like you could get away with a single RootContainer, if you give it all the queries your server supports in a single route, but from the documentation, it seems like this means that your entire application will either load or fail to load, entirely removing the possibility of degrading gracefully.

**Comment by kassens** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

Questions like yours deserve a purpose-built Q&A forum. Would you like to post this question to Stack Overflow with the tag #relayjs? We (or another member of the Relay community) will be happy to answer there. Post a link to your Stack Overflow question here, to so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs

**Comment by bigblind** [comment]
Hi Jan,

Thank you for your reply. I've asked [this question on Stack Overflow](
http://stackoverflow.com/questions/35518074/how-many-relay-rootcontainers-should-my-app-have),
but it got put on-hold, because it was somehow deemed primarily opinion
based. I'm not sure how I could edit my question to be more objective, so I
 gave Relay's issue tracker a try.
