### ISSUE TITLE
Invalid query generated on mutation

### ISSUE THREAD

**Issue by vladar** [facebook/relay#884]
Given following set of types:

```
type Text {
  body: String
  isTruncated: Boolean
  length: Int
}

type SomeEntity {
  id: ID!
  text: Text
}
```

and following fatQuery definition:
```
fragment on SaveSomeEntityPayload {
  entity {
    text
  }
}
```

Relay would ignore `text` field in final mutation query. If I change fatQuery to:
```
  entity {
    text {
      body
    }
  }
```
then Relay would generate query as expected. But I had an impression that you don't need to descend to leaf nodes in fatQuery?

**Comment by josephsavona** [comment]
cc @wincent

**Comment by wincent** [comment]
Correct, you shouldn't have to go to the leaf nodes, @vladar. There are instances where fields might be queried for, such as when the mutation affects a record ID that we have't fetched data for before, so we end up not querying for the fields in question. The fix for that case is to use a `REQUIRED_CHILDREN` config, but that doesn't seem to be the case here, given that specifying the leaf field fixes the issue for you.

Can you provide a little more context on the mutation you're trying to perform and how you're rendering the entity? Then I'll be able to look into it.

**Comment by vladar** [comment]
Tried to quickly reproduce in Relay playground, but simplest case seems to be working as expected. So this is some edge situation. Will debug further as soon as I get to real code that causes this.

**Comment by steveluscher** [comment]
Fixing this, starting with #922. In the meantime, if you want to unbreak and future-proof your code, change your fat query to:

```
fragment on SaveSomeEntityPayload @relay(pattern: true) {
  entity {
    text
  }
}
```
