### ISSUE TITLE
componentWillMount not called for newly added item to list

### ISSUE THREAD

**Issue by BerndWessels** [facebook/relay#886]
Hi

Having this render function:

      render() {
        return (
          <div>
            {this.state.charts.map((chart, i) =>
              <Chart key={i} ref={i} chart={chart}/>
            )}
          </div>
        );
      }

and a `console.log` in the `Chart` component's `componentWillMount` and `componentWillReceiveProps` reveals that `componentWillMount` is not called when there is a new `chart` item added to the `charts` list by an `addChartMutation`. Instead only `componentWillReceiveProps` is called for newly added `Charts` from the mutation.

I wonder if that is a bug or intentionally. It seems like a bug to me.

Cheers
Bernd

**Comment by josephsavona** [comment]
This is likely because you're using the index `i` as the React key.  When a new item is added to the list React will attempt to map the new set of n+1 items onto the existing n components; you will get a `componentWillMount` somewhere, but it may not match up with the new chart. In general, using the list iterator as a React `key` is not recommended for this very reason: it's best to use some value that identifies the object itself. If the chart item has an `id`, that would be best.

**Comment by josephsavona** [comment]
I'm going to close this since it doesn't appear to be a Relay issue. For more information I'd recommend reading the [docs about keys](https://facebook.github.io/react/docs/reconciliation.html#keys) or asking on Stack Overflow.
