### ISSUE TITLE
Non-string cursors

### ISSUE THREAD

**Issue by freiksenet** [facebook/relay#89]
We'd like to use a custom scalar type for cursors, but a spec says that it should be a String. I wonder if spec can be changed so that any scalar can be used as cursor.

**Comment by josephsavona** [comment]
cc @dschafer

**Comment by dschafer** [comment]
What custom scalar type would you want to use? There's no conceptual reason why it has to be a String; we just picked that because it's kind of the "superset" of all scalars (i.e. if your cursors are ints, you can always treat them as strings by `toString`'ing them), so I'm curious what you had in mind; definitely open to changes to make things easier here.

I sort of wonder if we should have made a custom scalar type called `Cursor` that serializes as a String, is the result of `Edge.cursor`, and is the input to `after:` and `before:`, to clarify that these aren't just any strings.

**Comment by freiksenet** [comment]
We handle opaque strings like ID and Cursor as scalars that serialize to strings and deserialize to objects with appropriate data in them.

**Comment by devknoll** [comment]
Also #73

**Comment by freiksenet** [comment]
@dschafer: Good idea! Just naming a scalar type Cursor and having to work similar to ID (so implementation details up to server) would be enough for us.

**Comment by yungsters** [comment]
Looks like serializing cursors to strings behind a facade is the answer. Closing this out, but feel free to re-open if I' mistaken.

**Comment by fson** [comment]
@yungsters Currently the spec says you must return either a String or a Non‐Null wrapper around a String, so a scalar `Cursor` type is not allowed. I think changing the type from `String` to `Cursor` as @dschafer hinted would also make sense from the user point of view, as it would make it clear that a valid cursor is expected and not just any string.

**Comment by dschafer** [comment]
I just put up a PR with a proposed spec fix for this; let me know what you think!

**Comment by freiksenet** [comment]
Looks good to me! 


Thanks!
