### ISSUE TITLE
Can't access arrays of arrays

### ISSUE THREAD

**Issue by robrichard** [facebook/relay#931]
I have a GraphQL type like this

``` javascript
module.exports = new graphql.GraphQLObjectType({
    name: 'ItemClassification',
    fields: {
        inflatedCategories: {type: new graphql.GraphQLList(new graphql.GraphQLList(ItemCategoryType))}
    }
});
```

I can query directly with GraphQL:

```
inflatedCategories {
  name
}
```

returns

``` json
"inflatedCategories": [
  [
    {
      "name": "Furniture"
    },
    {
      "name": "Tables"
    },
    {
      "name": "Dining Room Sets"
    }
  ]
]
```

but when I make the same query from Relay, I end up with an object that looks like this (no way to access the name property).

``` javascript
{
  "__dataID__": "client:204522018612",
  "inflatedCategories": [
    {
      "__dataID__": "client:204522018613",
      "__status__": 4
    }
  ],
  "__status__": 4
}
```

Unfortunately I can't easily change the data's schema. Is there any way to support this in Relay?

**Comment by josephsavona** [comment]
Thanks for opening an issue. This isn't currently supported in Relay - we haven't yet come across a use case for lists of lists. In general we've found that plain lists aren't very flexible - we'd recommend at least using a list of objects with ids in order to normalize the data. 

I don't see any reason we can't support lists of lists in Relay, but we're unlikely to prioritize this soon. We're happy to support you in implementing this in a PR though!

**Comment by josephsavona** [comment]
Closing as won't fix. Arrays of arrays by nature don't have identities and are less amenable to consistent caching.

**Comment by chollier** [comment]
@josephsavona is this still the case with Relay Modern?

**Comment by josephsavona** [comment]
@chollier This hasn't changed, Relay Modern doesn't support lists of lists. It may be possible to work around this to some extent with a custom type, using something like https://github.com/taion/graphql-type-json.
