### ISSUE TITLE
Share code between the React and React Native versions of the todo example

### ISSUE THREAD

**Issue by steveluscher** [facebook/relay#937]
In making the React Native TodoMVC example app, a lot of code was copied without modifications. Fundamentally, the mutations, schema, and routes/queries are identical between the two projects.

It would be nice if the common parts were extracted into `examples/todo_common/` in such a way that they could be used to build both apps.

**Comment by vjefri** [comment]
I would love to take this on.

**Comment by vjefri** [comment]
I am going to work on this and get back to you if I have any questions. Should be fun first bug.

**Comment by NevilleS** [comment]
I would love to see how people approach this, I've done similar things in my projects but haven't found a "nice" way to do it yet...

**Comment by yodacom** [comment]
I would like to see this too

**Comment by esutton** [comment]
+1

**Comment by nikhildaga** [comment]
Yes. I was wondering what are the steps to make a relay app compatible with react-native

**Comment by wincent** [comment]
(Spring cleaning.) This issue will soon be a year old so I am closing this one due to inactivity. In any case, we no longer host the examples in this repo.

We would be happy to entertain PRs over in the [relay-examples repo](https://github.com/relayjs/relay-examples).

Thanks to everybody who participated in this discussion!
