### ISSUE TITLE
Fat query should come from the server

### ISSUE THREAD

**Issue by gilesbradshaw** [facebook/relay#947]
When making a mutation should the 'fat query' not come from the server as it's the server that knows what might change?

**Comment by wincent** [comment]
Ideally, yes. When we first introduced fat queries (pre open source) we
felt that there would be advantages to doing it that way. The client still
needs to know the query, however, because only the client can do anything
useful with the fat query (like intersect it with the tracked query), so it
would need to download it anyway. As such, we haven't given priority to
moving this server-side, as there are other more useful and urgent things
that we can do to improve mutations (for example, right now I am working or
synthesizing tracked queries lazily rather than building them up ahead of
time; this will save us a bunch of memory and make other operations which
previously had to update the tracked queries faster and simpler too, at the
cost of some complexity in the synthesis).

**Comment by gilesbradshaw** [comment]
Thanks a lot for this answer :)
