### ISSUE TITLE
Synthesize tracked queries lazily

### ISSUE THREAD

**Issue by wincent** [facebook/relay#973]
(We already have an internal task for this — t10388334 for anybody watching along at home — but creating this issue to give it some external visibility, seeing as it was asked about [here](https://github.com/facebook/relay/issues/967#issuecomment-199382654)).

As part of #538, we want to change the way we do tracked queries, which currently result in substantial amounts of memory use over time. The basic idea is to do this in two steps at mutation time:

1.Figure out what records in the store could be affected by a mutation by intersecting the fat query and the mutation config with what we have in the store. Mark those records as stale by moving them from `nodeData` to `cachedData`.
2. (Possibly asynchronously/incrementally, after applying the optimistic update) find all query resolvers observing affected IDs and do a traversal of the resolver fragments to reconstruct what would have been in the tracked query.

There are a few potential "gotchas" that we will want to handle here, but that's the basic overview.

**Comment by eyston** [comment]
First off, thanks!  Second off, feel free to ignore any / all of this -- I am just curious :).

I'm not sure I follow why two steps.  If in (1) you are intersecting the fat query I'm not sure what (2) does (I'm assuming query resolvers are components subscribed to the store?).

As for gotcha's with (1) I'm aware of an issue currently handled by Relay where the store has a `null` value but the tracking query might be:

```
selectedTodo { text completed }
```

Looking at the store data only you wouldn't know `text` and `completed` were being tracked since `selectedTodo` was currently `null` (or at least that is my understanding).  Any other major gotcha's for intersecting the fat query with the store data itself?

I previously had asked @josephsavona about the tracked queries and he mentioned performance was a big benefit.  I might not be fully understanding this, but are connections the performance driver here?  e.g. I have 100 edges in a connection, in order to intersect I don't want to have to traverse all 100 edges?  Or is that not how to handle the connection case anyways?

Do abstract types pose a problem for intersecting or in all cases does Relay have the type information required stored in the store?

**Comment by NevilleS** [comment]
@eyston if I follow this correctly, @wincent is saying that the query resolvers (basically Relay Containers, and Relay Routes, I think?) would take over from what the current query tracker does. This wouldn't change the behaviour of intersection since the query tracker essentially just stores the fragments registered by those containers/routes. So even in the case of a `null` record, those resolvers are still observing that node, so when asked to do so they could return the same fragments a query tracker would have.

My main question about the implications of this would be related to the "query resolver" lifecycle. As I understand it, those observers register/deregister when the containers mount/unmount. Therefore, it's quite likely that a container would mount, fetch a node, then unmount. The node remains in the store, and then is mutated later. In this scenario, this mutation wouldn't have access to the container's query, right? So in theory the node might not be refetched; how does the store "remember" that the node data might be stale and should be refetched before another container attempts to render it?

**Comment by eyston** [comment]
Hi @NevilleS ... I didn't want to tag you because I'm unsure if that is rude or not (I felt bad tagging en_js for example) but clearly I should have :)

And yah, your second paragraph is exactly my question.

**Comment by josephsavona** [comment]
Phenomenal questions! 

>  If in (1) you are intersecting the fat query I'm not sure what (2) does 

@eyston Step 1 ensures that records in the store that *could* be affected by the mutation are marked as stale (regardless of whether they will be refetched in step 2). Step 2 ensures that records affected by the mutation that are *actively being viewed* are refetched immediately. 

> So in theory the node might not be refetched; how does the store "remember" that the node data might be stale and should be refetched before another container attempts to render it?

@NevilleS This gets at the same thing @eyston is wondering about with step 1 - how do we *know* to mark something as stale without a query resolver? There are a few options that we're still exploring: changing the diff algorithm to be more conservative (perhaps diffing at a more coarse-grained level) or requiring that fat queries be specific enough that intersecting the fat query with the store would invalidate all possibly-changed records.

**Comment by NevilleS** [comment]
What does being "marked as stale" mean, in practice? Does this cause a refetch before another container attempts to query that data?

**Comment by josephsavona** [comment]
"Marked as stale" is updating the cache such that future queries won't be diffed against those fields and they will be refetched in full. The simplest implementation today is to move records/fields from `nodeData` (diffed against) to `cachedData` (not diffed against). By keeping the fields in the cache somewhere (instead of immediately removing them) Relay can serve stale data while fresh data is being fetched.

**Comment by NevilleS** [comment]
OK, got it - but existing containers that have already rendered won't necessarily refetch that data, and will continue to render stale info until a new container mounts that refetches any shared fields...?

**Comment by eyston** [comment]
not 100% sure I'm following :)

- the current behavior is able to send a single query for everything tracked in the store
- an alternative behavior is to send a single query for everything actively being viewed, and refetch stale records as they become active

**Comment by josephsavona** [comment]
> existing containers that have already rendered won't necessarily refetch that data, and will continue to render stale info

Data for actively mounted components that could be affected by the mutation is queried immediately as part of the mutation query - this is step 2. Stale data would only be encountered if a *new* component was mounted - it would see stale data while refetching fresh data.

Note that the mutation would still essentially construct a mutation query as it does today; the main difference is that tracked queries are determined lazily.

**Comment by NevilleS** [comment]
OK, got it - marking data as "stale" alone isn't a solution; the mutation query still needs to correctly refetch anything that is currently being rendered in order to avoid rendering incorrect data.

The reason I ask about the behaviour of "stale data" (since I didn't realize the Store had such a distinction) was more about #978

**Comment by eyston** [comment]
> Note that the mutation would still essentially construct a mutation query as it does today; the main difference is that tracked queries are determined lazily.

The same algorithm, but with the 'tracked queries' being via the active 'query resolvers' vs a history?

**Comment by josephsavona** [comment]
> The same algorithm, but with the 'tracked queries' being via the active 'query resolvers' vs a history?

@eyston exactly

**Comment by taion** [comment]
@xuorig pointed me here.

If I'm reading this issue correctly, this seems like it'd be a significant improvement in behavior as well.

If I have queried a connection with a bunch of arguments (say corresponding to querying with different names), and I need to refetch those connections, this would mean that I have an easy way to avoid refetching that connection with arguments corresponding to components that are no longer mounted.

Is that correct? Or e.g. am I misunderstanding something about the current behavior?

**Comment by wincent** [comment]
Tracked queries (and fat queries, and diff queries) aren't going to be a thing in [Relay 2](https://speakerdeck.com/wincent/relay-2-simpler-faster-more-predictable), so we don't have any plans to work on this issue. Closing it to de-cruft the issue tracker a little bit. Thanks for everybody's input!
